// 楼中楼「回复 @谁」由模型写 to、代码只认这层里真有的人；正文里 @ 了不存在的人，显示时摘掉（她 2026-09-24）。
const assert = require("assert");
const fs = require("fs");
const vm = require("vm");
const app = fs.readFileSync(__dirname + "/../js/app.js", "utf8");
const sc = fs.readFileSync(__dirname + "/../js/screens.js", "utf8");
const i = app.indexOf("const forumValidTo = ");
const ctx = {}; vm.createContext(ctx);
vm.runInContext("var forumValidTo = " + app.slice(i + "const forumValidTo = ".length, app.indexOf("};", i) + 2), ctx);
assert.strictEqual(ctx.forumValidTo("蓝笔批注", ["蓝笔批注", "路过拔刀"]), "蓝笔批注");
assert.strictEqual(ctx.forumValidTo("@蓝笔批注", ["蓝笔批注"]), "蓝笔批注");
assert.strictEqual(ctx.forumValidTo("sweeper_chen", ["蓝笔批注"]), "", "楼里没有的人不显示");
assert(/是在回【这层楼里的某个人】，就填 to/.test(app), "提示词让它写 to");
assert(/_to: r\.to \}/.test(app) && /const toName = forumValidTo\(_to, seen\)/.test(app), "首刷楼中楼接上");
assert(/const r = buildForumReplyObjBase\(x, post, floor\)/.test(app), "插楼那条接上");
assert(/const toName = forumValidTo\(x\.to, \[meNow\]/.test(app), "回我那条接上");
const a = sc.indexOf("const atClean = ");
const re = eval(sc.slice(sc.indexOf("replace(", a) + 8, sc.indexOf(", (all, name)", a)));
const known = new Set(["阿满"]);
const clean = t => t.replace(re, (all, name) => known.has(name) ? all : "");
assert.strictEqual(clean("@sweeper_chen 阁下道破天机"), "阁下道破天机");
assert.strictEqual(clean("@阿满 你说呢"), "@阿满 你说呢");
assert(/atClean\(r\.content\)/.test(sc) && /atClean\(cm\.content\)/.test(sc));
console.log("forum-reply-to-and-at ok");
// v74.011：atClean 必须在组件这一层——楼层/楼中楼在 detail() 外面的函数里画，放进 detail() 就整页崩（Can't find variable: atClean）
const d0 = sc.indexOf("  function detail() {");
const a0 = sc.indexOf("  const atClean = txt =>");
assert(a0 > 0 && a0 < d0, "atClean 定义在组件层、detail() 之前");
assert(!/^    const atClean/m.test(sc), "detail() 里不许再有一份");
assert(sc.indexOf("bodyEl = detail()") > a0, "detail() 被调用时 atClean 已经定义好");
console.log("atClean scope ok");
