const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
test('town scene controls use one local layout and keep the host shared Head',()=>{const html=fs.readFileSync('apps/pets/index.html','utf8'),css=fs.readFileSync('apps/pets/scene-controls.css','utf8'),host=fs.readFileSync('js/fairy-garden.js','utf8');assert.match(html,/scene-controls\.css\?v=/);assert.doesNotMatch(html,/<style>/);assert.match(css,/\.pet-game \.scene-head/);assert.doesNotMatch(css,/safe-area-inset-top/);assert.match(host,/h\(Head,\{zh:panel/);});
test('pet control dock follows the composer safe area and has accessible targets',()=>{const css=fs.readFileSync('apps/pets/scene-controls.css','utf8');assert.match(css,/--town-dock:calc\(env\(safe-area-inset-bottom\) \* \.4\)/);assert.doesNotMatch(css,/env\(safe-area-inset-bottom\)\s*\+/);assert.match(css,/min-height:44px/);assert.match(css,/min-height:48px/);assert.match(css,/\.pet-game\.customizing \.scene-head/);});
test('original game actions are retained and dynamic labels preserve their SVG',()=>{const html=fs.readFileSync('apps/pets/index.html','utf8'),code=fs.readFileSync('apps/pets/scene-controls.mjs','utf8'),game=fs.readFileSync('art/pet-career/preview.mjs','utf8');for(const id of['selected-pet','pet-talk','pet-work','pet-status','watch-view','reset','scene-camera','back'])assert.equal((html.match(new RegExp('id="'+id+'"','g'))||[]).length,1,id);assert.equal((html.match(/data-care=/g)||[]).length,6);assert.match(code,/aria-hidden="true"/);assert.match(code,/\(label\|\|button\)\.textContent=text/);assert.match(game,/document\.body\.dataset\.place=room\|\|'outside'/);assert.match(game,/setSceneControlLabel\(bar\.querySelector/);});

test('long scene notices share the same flow as care and camera controls',()=>{const html=fs.readFileSync('apps/pets/index.html','utf8'),css=fs.readFileSync('apps/pets/scene-controls.css','utf8'),game=fs.readFileSync('art/pet-career/preview.mjs','utf8');assert.match(html,/<div class="pet-scene-dock">/);assert.match(css,/\.pet-scene-dock\{[^}]*display:flex;flex-direction:column/);assert.match(css,/\.pet-game \.scene-foot\{position:static/);assert.match(game,/enterButton\.parentElement\.hidden=!entryVisible/);assert.match(game,/getElementById\('station-open'\)\?\.hidden===false/);assert.match(game,/function refreshBack\(/);});
test('first saved pet walks home with a hint; follow label uses the pet name; town menu has one name',()=>{const s=fs.readFileSync('art/pet-career/preview.mjs','utf8'),host=fs.readFileSync('js/fairy-garden.js','utf8');const i=s.indexOf('function commitProfile('),j=s.indexOf('function commitAddition(');assert.ok(i>0&&j>0,'抠不出 commitProfile');assert.match(s.slice(i,i+800),/first=!previous\.configured/);assert.match(s.slice(i,i+800),/if\(first&&host\)welcomeHome=true/);const c=s.indexOf('function customize(');assert.match(s.slice(c,i),/goTo\(world\.building\('home'\)\.approach,'home'\)/);assert.doesNotMatch(s,/'跟着猫'|'跟着狗'/);assert.match(host,/'小镇菜单'/);assert.doesNotMatch(host,/'去别处'|'职业与小金库'/);});
test('off-screen home, alley and station signs wait at the edge; care bar names the pet and grays fixed refusals',()=>{const s=fs.readFileSync('art/pet-career/preview.mjs','utf8'),css=fs.readFileSync('art/pet-career/preview.css','utf8'),bar=fs.readFileSync('apps/pets/scene-controls.css','utf8');const i=s.indexOf('function placeSign('),j=s.indexOf('function stationLabel(');assert.ok(i>0&&j>i,'抠不出 placeSign');assert.match(s,/EDGE_SIGNS=new Set\(\['home','alley','railway'\]\)/);assert.match(s.slice(j,j+300),/placeSign\(button,'railway'/);assert.match(s,/placeSign\(button,b\.id,v,room!==null\)/);assert.match(css,/\.door-label\.is-edge::after\{content:attr\(data-dir\)/);assert.match(s,/function markCareBlocks\(bar\)/);assert.match(s,/careBlock\(care\.state,action\)/);assert.match(bar,/\.home-actions::before\{content:attr\(data-who\)/);assert.match(bar,/button\.is-blocked\{opacity:/);});
test('care page shows skills and chores right after the meters',()=>{const s=fs.readFileSync('js/fairy-garden.js','utf8'),m=s.indexOf("className:'pet-care-meters'"),k=s.indexOf("title:'一起学的小技能'"),c=s.indexOf("title:'家里谁来做'"),t=s.indexOf("title:'一点点长出来的脾气'");assert.ok(m>0&&k>m&&c>k&&t>c,'技能和家务要排在饱腹精力之后、脾气之前');});
