const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const hostSource=fs.readFileSync('js/fairy-garden.js','utf8'),sceneSource=fs.readFileSync('art/pet-career/preview.mjs','utf8');
function slice(s,a,b){const x=s.indexOf(a),y=s.indexOf(b,x);assert.ok(x>=0&&y>x);return s.slice(x,y);}
test('town wardrobe commits through the original archive writer and changes only the companion look',async()=>{
 const wardrobe=await import('../apps/fairy-garden/wardrobe.mjs'),state=await import('../apps/pets/state.mjs'),worldModule=await import('../art/pet-career/world-navigation.mjs');
 const world=worldModule.createPetWorld(JSON.parse(fs.readFileSync('art/pet-career/outside.json'))),pets=state.restorePetState({configured:true,career:{balance:42},resident:{id:'ta'},profile:{name:'团子'}},world);
 let saved={id:'wardrobe-test',partnerId:'ta',journey:{keep:123},worlds:{pets:state.snapshotPetState(pets,{position:pets.position,room:pets.room,outdoor:pets.outdoor,evening:false}),garden:{day:23,herbs:17}},world:{day:23,herbs:17}},look={hair:'bob',dims:{height:1.1},wardrobe:{academy:{cloth:'#abcdef'}}},fail=false,applied=0;
 const ctx={...wardrobe,structuredClone,console,ready:true,busy:false,customizing:false,saveFailed:false,petState:pets,position:pets.position,room:'home',outdoor:null,evening:false,career:null,care:null,observation:{mode:'pet'},captureObservation(){},syncHousehold(){},snapshotPetState:state.snapshotPetState,draw(){},note(){},WORLDS:[{id:'pets'}],host:{companion:()=>({id:'ta'}),save:(s,id,j)=>{ctx.saveWorld('archive',()=>saved,s,id,j);return true;}},write:(key,next)=>{if(fail)throw Error('disk full');saved=structuredClone(next);return saved;},housemate:{person:{id:'ta'},snapshot:()=>({look}),setLook:n=>{look=structuredClone(n);applied++;},doll:{ready:()=>Promise.resolve()}}};
 vm.createContext(ctx);vm.runInContext(slice(hostSource,'function saveWorld(','function WorldSession('),ctx);vm.runInContext(slice(sceneSource,'function save(','function applyProfile('),ctx);
 const patch={eye:'#123456',outfit:'suit',outfitColors:{cloth:'#654321'},dims:{head:1.03}};
 assert.equal(ctx.setCompanionLook('companion',patch),true);assert.equal(applied,1);assert.equal(saved.journey.keep,123);assert.deepEqual(saved.journey.companionLook,look);assert.deepEqual(look.dims,{height:1.1,head:1.03});assert.equal(look.wardrobe.academy.cloth,'#abcdef');assert.equal(look.wardrobe.suit.cloth,'#654321');assert.deepEqual(saved.worlds.garden,{day:23,herbs:17});assert.equal(saved.worlds.pets.career.balance,42);
 const before=structuredClone(saved),oldLook=structuredClone(look);fail=true;assert.equal(ctx.setCompanionLook('companion',{skin:'#777777'}),false);assert.deepEqual(saved,before);assert.deepEqual(look,oldLook);assert.equal(applied,1);assert.equal(ctx.saveFailed,true);
 fail=false;assert.equal(ctx.setCompanionLook('companion',{skin:'#777777'}),true);assert.equal(ctx.saveFailed,false);assert.equal(look.skin,'#777777');ctx.host.companion=()=>({id:'other'});assert.throws(()=>ctx.setCompanionLook('companion',{face:'happy'}),/同行者已切换/);assert.equal(applied,2);assert.equal(ctx.setCompanionLook('me',{}),false);
});
test('town appearance reuses full pages, shared wardrobe controls and the existing native avatar preview',()=>{
 const session=slice(hostSource,'function PetSession(','function PetCompanionDress('),dress=slice(hostSource,'function PetCompanionDress(','function TrainSession(');
 assert.match(session,/panel==='companion-dress'\?'TA的外貌'/);assert.match(session,/save:\(state,id,journey\)=>frame.current===node&&!!saveWorld\(key,current,state,id,journey\)/);assert.match(session,/rememberScroll\(\);dressReturn.current=panel/);assert.match(session,/setPanel\(dressReturn.current\)/);assert.match(session,/onClick:editCompanion/);assert.match(dress,/h\(PetPanel,\{page:'companion-dress',scrollRef,onScroll/);assert.match(dress,/h\(DressControls,\{who:'companion'/);assert.match(dress,/h\(root.CompanionPreview/);assert.doesNotMatch(dress,/h\(Sheet|localStorage|callAI/);
 assert.match(fs.readFileSync('js/companion.js','utf8'),/window.CompanionPreview = PetFrame/);
});
