const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),s=fs.readFileSync('js/fairy-garden.js','utf8');
test('town neighbors use the shared full paper page, Head and body scroll restoration for list/detail',()=>{const start=s.indexOf('function PetSession'),end=s.indexOf('function PetCompanionDress',start),session=s.slice(start,end);assert.match(session,/h\(Head,\{zh:[^}]+panel==='neighbors'/);assert.match(session,/panel==='neighbors'&&neighborView&&h\(PetPanel,\{page:'neighbors',scrollRef:panelScroll,onScroll:rememberScroll/);assert.match(session,/panel==='neighbors'\?'neighbors:'\+neighborId/);assert.match(session,/rememberScroll\(\);setNeighborId\(n.id\)/);assert.match(session,/setNeighborId\(''\);setNeighborNotice\(''\)/);assert.match(session,/街坊与小约定/);assert.match(session,/openNeighbors:id=>\{if\(frame.current===node\)/);});
test('neighbors reuse the original scene actors, route executor, entrusted parcel and one original archive writer',()=>{const view=fs.readFileSync('apps/pets/neighborhood-view.mjs','utf8'),engine=fs.readFileSync('apps/pets/neighborhood.mjs','utf8'),state=fs.readFileSync('apps/pets/state.mjs','utf8'),preview=fs.readFileSync('art/pet-career/preview.mjs','utf8');assert.match(view,/createTraveler\(source,true,n.look\)/);assert.match(view,/createParcelProp\(T/);assert.match(engine,/createTownLife\(state.neighbors/);assert.match(state,/neighborhood:restoreNeighborhood\(raw\?\.neighborhood,pets.map\(p=>p.id\),pets\)/);assert.match(preview,/chatContext:\(\)=>\(\{[^}]*neighborhood:neighborhood.summary/);for(const code of[engine,view])assert.doesNotMatch(code,/callAI|runProbe|localStorage|sessionStorage/);});

test('pet friends join the existing neighborhood detail page and preserve original shared controls',()=>{assert.match(s,/if\(n\?\.pet\)return h\(React.Fragment/);assert.match(s,/去'\+n.placeName\+'找/);assert.match(s,/pet-play/);assert.match(s,/pet-together/);assert.match(s,/neighborAct\('pet-stop'/);const view=fs.readFileSync('apps/pets/neighborhood-view.mjs','utf8');assert.match(view,/if\(n.pet\)/);assert.match(view,/await loadPet\(\)/);assert.match(view,/createPetToy\(T,'ball'\)/);assert.doesNotMatch(s,/data-pet-neighbor=/);});
test('the original neighbor paper shows real whereabouts and daily hours, and a greeting returns to the scene to show its shared wave',()=>{
 const session=s.slice(s.indexOf('function PetSession'),s.indexOf('function PetCompanionDress'));
 assert.match(session,/日常见面 '\+n.hours/);assert.match(session,/已经收工休息，白天再见/);assert.match(session,/neighborAct=/);
 const preview=fs.readFileSync('art/pet-career/preview.mjs','utf8');assert.match(preview,/neighborhood.request\('find',id,petState.activePetId\)/);
});

test('accepted greetings and visitor choices return to the real scene, while rejection keeps the paper open',()=>{const vm=require('node:vm'),a=s.indexOf('const neighborAct='),b=s.indexOf('const neighborGo=',a);assert.ok(a>0&&b>a);let accepted=true,panel='neighbors';const ctx={current(){},game:()=>({neighborAction:()=>({accepted,text:'约好了'}),neighborhood:()=>({}),goGathering(){}}),setNeighborView(){},setNeighborNotice(){},setPanel:v=>panel=v};vm.createContext(ctx);vm.runInContext(s.slice(a,b)+'globalThis.act=neighborAct;',ctx);for(const action of['greet','deliver','join','invite','end-visit','leave-event','pet-greet','pet-play','pet-together','guest-invite','guest-play','guest-quiet','guest-guard','guest-end']){panel='neighbors';ctx.act(action,'bakery-dog');assert.equal(panel,'',action);}accepted=false;panel='neighbors';ctx.act('guest-invite','bakery-dog');assert.equal(panel,'neighbors');});
