const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const eng=fs.readFileSync(require('node:path').join(__dirname,'../js/engine.js'),'utf8');
const cut=(a,b)=>eng.slice(eng.indexOf(a),eng.indexOf(b));
function load(store={},fetchT=()=>{}){return new Function('localStorage','cleanBaseUrl','fetchT','Blob','location',[
cut('function loadTtsApi(', 'function loadVoiceEars('),cut('function ttsReady(', 'const TTS_VOICES'),
'const TTS_MARK_PAUSE=/<#\\s*\\d+(?:\\.\\d+)?\\s*#>/g;',cut('async function ttsSynthOther(', 'async function ttsCloneVoice('),
'return {loadTtsApi,saveTtsApi,ttsReady,ttsDefaultVoice,voiceStudioVoices,ttsSynthOther};'
].join('\n'))({getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},u=>String(u||'').trim().replace(/\/+$/,''),fetchT,Blob,{protocol:'https:'});}
const a={provider:'voicestudio',enabled:true,vsBase:'https://computer.example/studio',vsPin:'123456',vsKey:'fixture',vsModel:'tts-1'};
test('每个浏览器自己的配置；可无密钥使用本机；地址尾部v1归一化',()=>{const store={x_ttsApi:JSON.stringify({...a,vsBase:a.vsBase+'/v1/audio/speech'})};const e=load(store);assert.equal(e.loadTtsApi().vsBase,a.vsBase);assert.equal(e.ttsDefaultVoice(),'default');assert.equal(e.ttsReady({...a,vsKey:'',vsPin:''}),true);e.saveTtsApi({vsVoice:'profile-2'});assert.equal(e.loadTtsApi().vsVoice,'profile-2');assert.equal(load().loadTtsApi().vsBase,'');});
test('按上游实际voices结构读取，标准别名不伪装成不同音色',async()=>{let req;const e=load({},async(url,o)=>{req={url,o};return{ok:true,json:async()=>({voices:[{voice_id:'alloy',type:'openai_alias'},{voice_id:'profile-1',name:'我的声音',type:'profile'}],engines:[]})};});assert.deepEqual(await e.voiceStudioVoices(a),[{id:'profile-1',name:'我的声音'}]);assert.equal(req.url,a.vsBase+'/v1/audio/voices');assert.equal(req.o.headers.Authorization,'Bearer fixture');assert.equal(req.o.headers['X-OmniVoice-Pin'],'123456');});
test('语音走自己的电脑、角色音色、语速和WAV；保留已有API参数契约',async()=>{let req;const e=load({},async(url,o,timeout)=>{req={url,o,timeout};return{ok:true,blob:async()=>new Blob([new Uint8Array(80)])};});const b=await e.ttsSynthOther(a,'回来啦<#0.5#>好','profile-9',.85);assert.equal(b.type,'audio/wav');assert.equal(req.timeout,180000);assert.equal(req.url,a.vsBase+'/v1/audio/speech');assert.deepEqual(JSON.parse(req.o.body),{model:'tts-1',input:'回来啦…好',voice:'profile-9',response_format:'wav',speed:.85});});
test('错误地址/混合内容/不正确的PIN不伪装成成功',async()=>{const e=load({},async()=>({ok:false,status:401,json:async()=>({detail:'PIN required'})}));await assert.rejects(e.voiceStudioVoices({...a,vsBase:'https://computer.example/mcp'}),/去掉末尾/);await assert.rejects(e.voiceStudioVoices({...a,vsBase:'http://192.168.1.2:3900'}),/HTTPS/);await assert.rejects(e.voiceStudioVoices(a),/PIN/);await assert.rejects(load({},async()=>{throw Error('network')}).voiceStudioVoices(a),/跨域/);});
test('网页或JSON不能当声音播放',async()=>{await assert.rejects(load({},async()=>({ok:true,blob:async()=>new Blob(['x'.repeat(200)],{type:'text/html'})})).ttsSynthOther(a,'hi','default',1),/可播放/);await assert.rejects(load({},async()=>({ok:true,json:async()=>({foo:[]})})).voiceStudioVoices(a),/不是 VoiceStudio/);});
