import * as T from 'three';
import {createBrewSequence} from './brewing.mjs?v=fg-d8bdabe9d782b029';
// One close-up for both cauldron entrances. The existing world and dolls stay on screen.
// 小灶（v70.74）：同一套近景搬到自家灶台上——site.y 是台面高度（锅坐在台面上），pot 画一口小锅（庭院那口大锅是地图自带的）
export function makeBrewingView({scene,camera,site,onClose,id='brewing-dialog',pot=false}){const base=site.y||0;
 const dialog=document.createElement('dialog');dialog.id=id;dialog.className='brewing-dialog scene-activity';dialog.setAttribute('aria-labelledby','brewing-title');
 dialog.innerHTML='<div class="dialog-title"><button id="brewing-close" class="activity-close" aria-label="返回庭院">‹</button><h2 id="brewing-title">锅边的魔法</h2><span class="title-spacer"></span></div><div class="brew-body"><div class="brew-caption"><p id="brew-step"></p><p id="brew-instruction" aria-live="polite"></p></div><div id="brew-target" role="button" tabindex="0" aria-label="炼药锅：选好材料后点这里放入；搅拌时可以绕圈拖动"><span></span></div><div class="brew-controls"><div id="brew-ingredients"></div><p id="brew-result" aria-live="polite"></p><button id="brew-assist" hidden>按住慢慢搅拌</button><button id="brew-finish" hidden>收火，装瓶</button><small id="brew-footnote">完成时才使用材料 · 随时可以退出</small></div></div>';
 document.body.append(dialog);const $=id=>dialog.querySelector('#'+id),root=new T.Group();root.position.set(site.x,base,site.z);root.visible=false;scene.add(root);
 const mat=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:.55,...extra});
 const mesh=(geo,material,x=0,y=0,z=0,parent=root)=>{const m=new T.Mesh(geo,material);m.position.set(x,y,z);parent.add(m);return m;};
 if(pot){mesh(new T.CylinderGeometry(.3,.24,.42,24),mat('#5f6663',{roughness:.7,metalness:.25}),0,.49);mesh(new T.TorusGeometry(.3,.028,8,32),mat('#7c8480',{metalness:.3}),0,.7).rotation.x=Math.PI/2;for(const sx of [-1,1]){const h=mesh(new T.TorusGeometry(.05,.012,6,12),mat('#7c8480'),sx*.33,.62,0);h.rotation.y=Math.PI/2;}}
 const liquid=mesh(new T.CircleGeometry(.279,48),new T.MeshBasicMaterial({color:'#72bba6',side:T.DoubleSide,toneMapped:false}),0,.705);liquid.rotation.x=-Math.PI/2;
 const swirl=mesh(new T.TorusGeometry(.21,.012,6,48),mat('#eff6c2',{emissive:'#d8e9aa',emissiveIntensity:.6}),0,.716);swirl.rotation.x=-Math.PI/2;
 const spoon=new T.Group();root.add(spoon);const shaft=mesh(new T.CylinderGeometry(.018,.025,.8,8),mat('#b89661'),0,.4,0,spoon);shaft.rotation.z=.25;mesh(new T.SphereGeometry(.07,10,8),mat('#b89661'),.1,0,0,spoon).scale.set(1,.4,1.4);
 const bottle=new T.Group();root.add(bottle);const glass=mat('#d9eee0',{transparent:true,opacity:.52,metalness:.1});mesh(new T.SphereGeometry(.135,16,12),glass,0,.16,0,bottle).scale.set(1,1.3,1);mesh(new T.CylinderGeometry(.052,.052,.13,12),glass,0,.36,0,bottle);const fill=mesh(new T.SphereGeometry(.112,12,10),mat('#94d9be',{emissive:'#9cf4d0',emissiveIntensity:.5}),0,.16,0,bottle);const cork=mesh(new T.CylinderGeometry(.05,.045,.07,10),mat('#ae8556'),0,.43,0,bottle);
 const ribbon=mesh(new T.TorusGeometry(.057,.015,5,18),mat('#d7b472'),0,.32,0,bottle);ribbon.rotation.x=Math.PI/2;
 const stream=mesh(new T.CylinderGeometry(.017,.023,.6,8),mat('#a9ead1',{emissive:'#78c6aa',emissiveIntensity:.4}));
 const bubbles=Array.from({length:12},(_,i)=>mesh(new T.SphereGeometry(.015+i%3*.008,8,6),mat('#eaf4d4',{transparent:true,opacity:.6}),0,0,0));
 const drops=[];let session=null,config=null,chosen=null,drag=null,stirPointer=null,assist=false,assistPointer=null,savedCamera=null,phase='',heading=0;
 const projection=new T.Vector3();
 function project(x,y,z){projection.set(x,y,z).project(camera);return {x:(projection.x+1)*innerWidth/2,y:(1-projection.y)*innerHeight/2};}
 function target(){return project(site.x,.71+base,site.z);}
 function radius(){const a=target(),b=project(site.x+.55,.78+base,site.z);return Math.max(36,Math.hypot(a.x-b.x,a.y-b.y));}
 function hit(x,y){const p=target();return Math.hypot(x-p.x,y-p.y)<radius()*1.35;}
 function add(i){if(!session?.add(i))return;const item=config.items[i];const drop=mesh(item.key==='herbs'?new T.SphereGeometry(.07,8,6):new T.OctahedronGeometry(.085),mat(item.color),0,1.8,0);if(item.key==='herbs')drop.scale.set(.5,1.5,1);const from=config.helper?root.worldToLocal(config.helperHand()):new T.Vector3(0,1.8,0);drops.push({mesh:drop,age:0,from:from.clone()});chosen=null;sync();}
 function sync(){if(!session)return;const s=session.stage;dialog.dataset.stage=s;
 const names={ingredients:'一 · 放入材料',stir:'二 · 搅出微光',ready:'三 · 收火',pour:'四 · 留住这一炉',done:'这一炉做好了'};
 $('brew-step').textContent=names[s];$('brew-instruction').textContent={ingredients:'把材料拖到锅里，也可以先选材料，再点锅口。',stir:'沿锅口绕两圈，顺时针、逆时针都可以。',ready:'锅里的微光聚起来了，可以收火。',pour:'舀起微光，慢慢装进容器里……',done:'已经收进背包，带着它继续逛吧。'}[s];
 $('brew-assist').hidden=s!=='stir';$('brew-finish').hidden=!['ready','done'].includes(s);$('brew-finish').textContent=s==='done'?'收好，回庭院':config.finishLabel||'收火，装瓶';$('brew-ingredients').hidden=s!=='ingredients';$('brew-footnote').textContent=s==='done'?'这一炉已保存':(config.helper?'同行者在旁递材料 · 完成时才使用材料':'完成时才使用材料 · 随时可以退出');
 for(const b of $('brew-ingredients').children){b.disabled=session.snapshot().added.includes(Number(b.dataset.ingredient));b.setAttribute('aria-pressed',String(chosen===Number(b.dataset.ingredient)));}
 }
 function resetPointer(){assist=false;assistPointer=null;stirPointer=null;session?.release();if(drag){drag.el.classList.remove('dragging');drag.el.style.transform='';drag=null;}}
 function close(){if(!dialog.open)return;resetPointer();dialog.close();root.visible=false;document.body.classList.remove('brewing');for(const d of drops){root.remove(d.mesh);d.mesh.geometry.dispose();d.mesh.material.dispose();}drops.length=0;session=null;config=null;onClose(savedCamera);}
 $('brewing-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 $('brew-finish').onclick=()=>{if(session?.stage==='done'){close();return;}session?.finish();sync();};
 $('brew-assist').addEventListener('pointerdown',e=>{assist=true;assistPointer=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);});
 $('brew-assist').addEventListener('pointerup',resetPointer);$('brew-assist').addEventListener('pointercancel',resetPointer);$('brew-assist').addEventListener('lostpointercapture',()=>{assist=false;});
 $('brew-assist').onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();assist=true;}};$('brew-assist').onkeyup=()=>assist=false;$('brew-assist').onblur=()=>assist=false;
 $('brew-target').onclick=()=>{if(chosen!==null)add(chosen);};$('brew-target').onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();if(chosen!==null)add(chosen);}};
 dialog.addEventListener('pointerdown',e=>{if(!session)return;const b=e.target.closest('[data-ingredient]');if(b&&!b.disabled){drag={i:Number(b.dataset.ingredient),el:b,x:e.clientX,y:e.clientY,moved:false,pointer:e.pointerId};b.setPointerCapture(e.pointerId);}else if(session.stage==='stir'&&hit(e.clientX,e.clientY)){stirPointer=e.pointerId;dialog.setPointerCapture(e.pointerId);session.release();const p=target();session.stir(Math.atan2(e.clientY-p.y,e.clientX-p.x));}});
 dialog.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.pointer){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved||=Math.hypot(dx,dy)>8;if(drag.moved){drag.el.classList.add('dragging');drag.el.style.transform=`translate(${dx}px,${dy}px)`;}}if(stirPointer===e.pointerId){const p=target(),r=radius(),dist=Math.hypot(e.clientY-p.y,e.clientX-p.x);if(dist<r*.25||dist>r*1.8){session.release();return;}heading=Math.atan2(e.clientY-p.y,e.clientX-p.x);session.stir(heading);sync();}});
 dialog.addEventListener('pointerup',e=>{if(drag&&drag.pointer===e.pointerId){const d=drag;drag=null;d.el.classList.remove('dragging');d.el.style.transform='';if(d.moved&&hit(e.clientX,e.clientY))add(d.i);else if(!d.moved){chosen=d.i;sync();}}if(stirPointer===e.pointerId){stirPointer=null;session?.release();}});
 dialog.addEventListener('pointercancel',resetPointer);window.addEventListener('blur',resetPointer);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetPointer();});
 return {get helping(){return !!session&&config.helper;},get active(){return !!session;},get stage(){return session?.stage;},inspect:()=>session?.snapshot()||null,
  open(options,view){if(session)return false;config=options;savedCamera=view;session=createBrewSequence(options.items);phase='';chosen=null;heading=0;$('brewing-title').textContent=options.title;$('brew-result').textContent='';const list=$('brew-ingredients');list.replaceChildren();options.items.forEach((item,i)=>{const b=document.createElement('button');b.dataset.ingredient=i;b.style.setProperty('--ingredient',item.color);const icon=document.createElement('i');icon.className='ingredient-icon '+item.key;b.append(icon,document.createTextNode(item.label+' ×'+item.count));b.onclick=e=>{if(e.detail===0){chosen=i;sync();}};list.append(b);});root.visible=true;document.body.classList.add('brewing');dialog.showModal();sync();return true;},
  camera(){if(!session)return;const aspect=innerWidth/innerHeight,span=Math.max(3.4,4.8*aspect);camera.zoom=1;camera.left=-span/2;camera.right=span/2;camera.top=span/aspect/2;camera.bottom=-span/aspect/2;camera.position.set(site.x+6,4.9+base,site.z+3);camera.lookAt(site.x,.62+base,site.z+.25);camera.far=100;camera.updateProjectionMatrix();camera.updateMatrixWorld();},
  update(dt,time){if(!session)return;this.camera();if(assist){session.assist(dt);heading+=dt*2.5;}const result=session.tick(dt,config.commit);if(result!==undefined)$('brew-result').textContent=result;if(phase!==session.stage){phase=session.stage;sync();}const p=target(),r=radius();const t=$('brew-target');t.style.left=p.x+'px';t.style.top=p.y+'px';t.style.width=r*2+'px';t.style.height=r*2+'px';t.style.setProperty('--turn',Math.min(1,session.turn/(Math.PI*4)));t.firstElementChild.textContent=session.stage==='ingredients'?(chosen!==null?'放入':'锅口'):session.stage==='stir'?Math.min(100,Math.floor(session.turn/(Math.PI*4)*100))+'%':'';
 const stage=session.stage,done=stage==='done',pour=stage==='pour',stir=['stir','ready'].includes(stage);liquid.material.color.set(stage==='ingredients'?'#7fb291':'#60c6b0');liquid.scale.setScalar(.96+Math.sin(time*3)*.02);swirl.rotation.z=heading;swirl.visible=stir;spoon.visible=stir||pour;spoon.position.set(stir?Math.cos(heading)*.2:session.pour*.55,.72+(pour?Math.sin(session.pour*Math.PI)*.5:0),stir?Math.sin(heading)*.2:0);spoon.rotation.z=pour?-session.pour*.8:.2;
 bottle.visible=pour||done;bottle.position.set(.65,.38,.22);if(done&&config.hand){root.updateMatrixWorld(true);bottle.position.copy(root.worldToLocal(config.hand()));bottle.position.y-=.34;}fill.scale.y=pour?Math.max(.01,session.pour):1;cork.visible=done;stream.visible=pour&&session.pour>.35&&session.pour<.8;if(stream.visible){const from=new T.Vector3(spoon.position.x+.1,spoon.position.y,spoon.position.z),to=new T.Vector3(.65,.74,.22),delta=from.clone().sub(to);stream.position.copy(from).add(to).multiplyScalar(.5);stream.scale.y=delta.length()/.6;stream.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());}
 bubbles.forEach((b,i)=>{const a=i*2.4+time*.5;b.visible=session.count>0&&!done;b.position.set(Math.cos(a)*.28,.71+((time*.25+i/12)%1)*.6,Math.sin(a)*.28);b.material.opacity=(1-((time*.25+i/12)%1))*.5;});for(const d of drops){d.age+=dt;d.mesh.position.lerpVectors(d.from,new T.Vector3(0,.71,0),Math.min(1,d.age/.52));d.mesh.position.y+=Math.sin(Math.min(1,d.age/.52)*Math.PI)*.28;d.mesh.rotation.z+=dt*2;d.mesh.visible=d.age<.52;}
 },close};
}
