import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL(p,import.meta.url));
const bytes=read('./doll.glb'),glb=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());
const catalog=JSON.parse(read('./doll.json'));const nodes=glb.nodes.filter(n=>n.mesh!=null);
// v2 娃娃（她 2026-09-25 选了直接替换）：Hunyuan 底模 + 骨架蒙皮，发型是挂在 HeadAnchor 上的帽子，衣服蒙在同一副骨架上。
// 由 art/fairy-garden/doll/assemble_v2.py 组装、compress_asset.py 压缩；不许手改 doll.glb / doll.json / outfits.mjs。
test('v2 asset: every catalogued hairstyle hangs on HeadAnchor and every outfit is skinned to the doll rig',()=>{
 assert.equal(catalog.style,'hunyuan-v2-2026-09');
 const anchor=glb.nodes.find(n=>n.name==='HeadAnchor');assert.ok(anchor,'HeadAnchor');
 for(const id of Object.keys(catalog.hair)){const i=glb.nodes.findIndex(n=>n.name==='hair_'+id);assert.ok(i>=0,id);assert.ok(anchor.children.includes(i),id+' not on HeadAnchor');}
 for(const id of Object.keys(catalog.outfits)){const parts=nodes.filter(n=>n.extras?.outfit===id);assert.ok(parts.length>=1,id);for(const n of parts)assert.ok(n.skin!=null,id+' must be skinned');}
 assert.ok(bytes.length<4*1024*1024,'mobile asset budget');
});
test('v2 rig: bones carry the runtime pivot names and the pivots ride along in extras',()=>{
 const rig=glb.nodes.find(n=>n.extras?.dollRig)?.extras.dollRig;assert.ok(rig);
 for(const label of ['leftArm','rightArm','leftLeg','rightLeg']){assert.equal(rig[label].length,3);assert.ok(glb.skins.every(sk=>sk.joints.some(j=>glb.nodes[j].name===label)),label);}
 for(const m of glb.meshes)assert.ok((m.weights||[]).every(v=>v===0),m.name+' must not spawn deformed');
 const body=nodes.find(n=>n.name==='DollBody');assert.ok(body&&body.skin!=null,'body is skinned');
});
test('runtime rebinds cloned skins and drives bones from the pivot groups',()=>{
 const trav=read('./traveler.mjs').toString();
 assert.match(trav,/o\.bind\(new T\.Skeleton\(o\.skeleton\.bones\.map\(b=>model\.getObjectByName\(b\.name\)\)/);
 assert.match(trav,/const syncBones=\(\)=>/);assert.match(trav,/life\.update\([^)]*\);syncBones\(\);/);
});
test('shape controls expose names, live values and reset without altering page layout',()=>{
 const host=read('../../js/fairy-garden.js').toString();assert.match(host,/"aria-label": d.label/);assert.match(host,/Math.round\(value \* 100\)/);assert.match(host,/d.low \|\|/);assert.match(host,/pushLook\(\{ dims: \{ \[d.key\]: 1 \} \}\)/);
});
test('the app catalogues are generated by the v2 assembler, not hand-written',()=>{
 const asm=read('../../art/fairy-garden/doll/assemble_v2.py').toString();
 assert.match(asm,/hairstyles\.json/);assert.match(read('./outfits.mjs').toString(),/Generated by art\/fairy-garden\/doll\/assemble_v2\.py/);
});
