import * as T from 'three';
import {createExcavation,DUST_PATCHES} from './excavating.mjs?v=fg-90623cddf5e68c9b';
export function makeExcavatingView({scene,camera,onClose}){
 const root=new T.Group();root.visible=false;scene.add(root);let config=null,session=null,view=null,pointer=null,assisting=false,phase='',savedVeinY=0;
 const earth=new T.MeshStandardMaterial({color:'#82918a',roughness:1}),stone=new T.IcosahedronGeometry(.14,1);
 const patches=DUST_PATCHES.map((p,i)=>{const m=new T.Mesh(stone,earth.clone());m.position.set(p.x,.54+.2*(1-Math.hypot(p.x,p.z)),p.z);m.scale.set(1.05,1.1+(i%3)*.15,1.05);m.rotation.set(i*.7,i*1.3,i*.4);m.castShadow=true;m.userData.base=m.position.clone();m.userData.age=0;root.add(m);return m;});
 const brush=new T.Group();root.add(brush);const wood=new T.MeshStandardMaterial({color:'#b58b5e',roughness:.8}),bristles=new T.MeshStandardMaterial({color:'#e7d7b6',roughness:1});const block=new T.Mesh(new T.BoxGeometry(.27,.09,.14),wood);brush.add(block);
 for(let i=0;i<5;i++){const row=new T.Mesh(new T.BoxGeometry(.035,.11,.14),bristles);row.position.set((i-2)*.05,-.09,0);brush.add(row);}
 const handle=new T.Mesh(new T.CylinderGeometry(.023,.033,1,8),wood);root.add(handle);
 const lamp=new T.PointLight('#ffe3ad',0,3,2);root.add(lamp);
 const dialog=document.createElement('dialog');dialog.id='excavating-dialog';dialog.className='scene-activity brewing-dialog';dialog.setAttribute('aria-labelledby','excavating-title');dialog.innerHTML='<div class="dialog-title"><button class="activity-close" aria-label="返回星井">‹</button><h2 id="excavating-title">星井 · 拂去浮土</h2><span class="title-spacer"></span></div><div class="brew-body"><div class="brew-caption"><p id="excavate-instruction" aria-live="polite"></p><p id="excavate-progress"></p></div><div id="excavate-surface" aria-label="拖动刷子扫开奇物上的浮土"></div><div class="brew-controls"><p id="excavate-result" aria-live="polite"></p><button id="excavate-help">按住慢慢扫开</button><button id="excavate-finish" hidden>轻轻取出</button><small id="excavate-footnote">没有时限 · 取出时才收进背包</small></div></div>';
 document.body.append(dialog);const $=s=>dialog.querySelector(s),ray=new T.Raycaster(),plane=new T.Plane(),point=new T.Vector3();
 function reset(){pointer=null;assisting=false;}
 function close(){if(!session)return;config.vein.position.y=savedVeinY;config.onClose?.();session=null;reset();root.visible=false;dialog.close();document.body.classList.remove('brewing');onClose(view);}
 function sync(){if(!session)return;const stage=session.stage,repair=config.mode==='repair';$('#excavating-title').textContent=repair?'工坊 · 修复旧物':'星井 · 拂去浮土';dialog.dataset.stage=stage;$('#excavate-instruction').textContent={brush:'拖着刷子扫开浮土，看看光藏在哪里。',ready:'奇物露出来了，可以轻轻取出。',lift:'慢慢松开石缝，把这点光托起来……',done:'已经收进背包，带回去慢慢看。'}[stage];if(repair)$('#excavate-instruction').textContent={brush:'拖动软刷，扫去匣盖上的浮屑。',ready:'裂缝露出来了，可以扣合匣盖。',lift:'匣盖慢慢归位，金线沿着裂缝合拢……',done:'旧物修好了，原来的片段还在里面。'}[stage];$('#excavate-help').hidden=stage!=='brush';$('#excavate-finish').hidden=!['ready','done'].includes(stage);$('#excavate-finish').textContent=stage==='done'?'收好':repair?'扣合修复':'轻轻取出';$('#excavate-progress').textContent=stage==='brush'?(repair?'浮屑扫开了 ':'浮土扫开了 ')+Math.round(session.progress*100)+'%':'';$('#excavate-footnote').textContent=stage==='done'?'这一处已保存':(repair?'没有时限 · 完成后才消耗旧物':'没有时限 · 取出时才收进背包');}
 function move(e){if(pointer!==e.pointerId||session?.stage!=='brush')return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);if(ray.ray.intersectPlane(plane,point)){brush.position.set(Math.max(-.85,Math.min(.85,point.x-config.site.x)),.94,Math.max(-.85,Math.min(.85,point.z-config.site.z)));session.brush(brush.position.x,brush.position.z);sync();}}
 const surface=$('#excavate-surface');surface.onpointerdown=e=>{if(session?.stage!=='brush')return;pointer=e.pointerId;surface.setPointerCapture(pointer);move(e);};surface.onpointermove=move;surface.onpointerup=reset;surface.onpointercancel=reset;surface.onlostpointercapture=reset;
 const help=$('#excavate-help');help.onpointerdown=e=>{assisting=true;help.setPointerCapture(e.pointerId);};help.onpointerup=reset;help.onpointercancel=reset;help.onlostpointercapture=reset;help.onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();assisting=true;}};help.onkeyup=reset;help.onblur=reset;window.addEventListener('blur',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden)reset();});
 $('.activity-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});$('#excavate-finish').onclick=()=>{if(session?.stage==='done')close();else {session?.finish();reset();sync();}};
 const screen=p=>{const v=p.clone().project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};};
 return {get active(){return !!session;},get helping(){return !!session&&config.helper;},
 open(options,saved){if(session)return;config=options;view=saved;$('.activity-close').setAttribute('aria-label',options.mode==='repair'?'返回工坊':'返回星井');session=createExcavation();savedVeinY=options.vein.position.y;phase='';root.position.set(options.site.x,options.height??.08,options.site.z);root.visible=true;brush.position.set(.5,.94,.4);patches.forEach(m=>{m.visible=true;m.position.copy(m.userData.base);m.userData.age=0;m.material.transparent=true;m.material.opacity=1;});plane.set(new T.Vector3(0,1,0),-(root.position.y+.94));$('#excavate-result').textContent=options.helper?'同行者在一旁替你照亮手边。':'';document.body.classList.add('brewing');dialog.showModal();sync();},
 camera(){if(!session)return;const site=config.site,aspect=innerWidth/innerHeight,span=Math.max(3.4,4.7*aspect);camera.zoom=1;camera.userData.fogOffset=0;camera.left=-span/2;camera.right=span/2;camera.top=span/aspect/2;camera.bottom=-span/aspect/2;camera.position.set(site.x+1.8,8,site.z-2.5);camera.lookAt(site.x,root.position.y+.52,site.z+.25);camera.updateProjectionMatrix();camera.updateMatrixWorld();},
 update(dt,time){if(!session)return;this.camera();if(assisting){const cleared=session.snapshot().cleared,p=DUST_PATCHES.find((_,i)=>!cleared.includes(i));if(p)brush.position.set(p.x,.94,p.z);session.help(dt);}const snap=session.snapshot();patches.forEach((m,i)=>{const cleared=snap.cleared.includes(i)||session.stage!=='brush';if(cleared)m.userData.age+=dt;const t=Math.min(1,m.userData.age/.45),base=m.userData.base;m.position.copy(base);m.position.x+=base.x*t*.7;m.position.z+=base.z*t*.7;m.position.y-=t*.25;m.material.opacity=1-t;m.visible=t<1;});brush.visible=handle.visible=session.stage==='brush';brush.rotation.y=Math.sin(time*5)*.15;
 if(config.hand){root.updateMatrixWorld(true);const hand=root.worldToLocal(config.hand()),end=brush.position.clone(),delta=hand.clone().sub(end);handle.position.copy(hand).add(end).multiplyScalar(.5);handle.scale.y=delta.length();handle.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());}
 lamp.intensity=config.helper?1.6:0;lamp.position.set(-.45,1.3,.4);if(config.animate)config.animate(session.stage,session.lift);else if(session.stage==='lift')config.vein.position.y=savedVeinY+session.lift*.65;
 if(phase!==session.stage){phase=session.stage;sync();}const result=session.tick(dt,config.commit);if(result!==undefined){phase=session.stage;sync();$('#excavate-result').textContent=result.text;if(!result.ok){$('#excavate-instruction').textContent=config.mode==='repair'?'这次没有修好，旧物还在背包里。':'这次没有取出，矿点还留着。';$('#excavate-footnote').textContent=config.mode==='repair'?'回到工坊可以再试。':'回到井里可以再试。';}}},
 inspect:()=>session?{...session.snapshot(),id:config.site.id,helper:config.helper,points:DUST_PATCHES.map(p=>screen(new T.Vector3(config.site.x+p.x,root.position.y+.94,config.site.z+p.z)))}:null,close};
}
