import {isKeepsake,makeKeepsake} from './keepsake-view.mjs?v=fg-ea5123e06bd52651';
import {makeCurio} from './curio-view.mjs?v=fg-ea5123e06bd52651';
import * as T from 'three';import {MAPS,centralLit} from './world.mjs?v=fg-ea5123e06bd52651';import {museumCollection} from './museum.mjs?v=fg-ea5123e06bd52651';
export function makeMuseum(){const root=new T.Group(),groups={};let previous=null;
 const paper=new T.MeshStandardMaterial({color:'#e4d5b1',roughness:1}),green=new T.MeshStandardMaterial({color:'#a5bf93',roughness:.9}),amber=new T.MeshStandardMaterial({color:'#c6a362',roughness:.5}),crystal=new T.MeshStandardMaterial({color:'#b2c4cb',roughness:.45,metalness:.15});
 const card=new T.BoxGeometry(.56,.66,.025),leaf=new T.SphereGeometry(1,8,6),bottle=new T.SphereGeometry(.17,12,8),neck=new T.CylinderGeometry(.055,.07,.17,8),stone=new T.IcosahedronGeometry(.18,0);
 function add(g,geo,mat,x,y,z){const o=new T.Mesh(geo,mat);o.position.set(x,y,z);g.add(o);return o;}
 for(const [id,d]of Object.entries(MAPS.museum.displays)){groups[id]=d.slots.map(p=>{const g=new T.Group();g.position.set(p.x,p.y,p.z);g.visible=false;root.add(g);if(id==='flowers'){add(g,card,paper,0,0,0);const stem=add(g,neck,green,0,-.05,.025);stem.scale.set(.16,1.5,.16);for(const sign of [-1,1]){const l=add(g,leaf,green,sign*.09,-.04,.035);l.scale.set(.11,.045,.018);l.rotation.z=sign*.5;}const f=add(g,leaf,amber,0,.15,.04);f.scale.set(.08,.08,.025);}else if(id==='alchemy'){add(g,bottle,green,0,.18,0);add(g,neck,amber,0,.37,0);}else {const o=add(g,stone,crystal,0,.18,0);o.scale.y=1.45;o.rotation.z=.25;add(g,stone,amber,.18,.11,.04).scale.setScalar(.5);}return g;});}
 // 中央那座一直空着的展台：炼金笔记三十种写满了才亮（world.centralLit 一处说了算）
 const central=new T.Group();central.position.set(0,.14,-.1);central.visible=false;root.add(central);
 const core=new T.Mesh(new T.IcosahedronGeometry(.22,1),new T.MeshStandardMaterial({color:'#f2e6b8',emissive:'#e2c76a',emissiveIntensity:1.2,roughness:.3}));core.position.y=1.05;central.add(core);
 const glow=new T.PointLight('#f0d98a',1.6,4.5);glow.position.y=1.2;central.add(glow);
 for(let i=0;i<5;i++){const ring=new T.Mesh(new T.TorusGeometry(.32+i*.06,.012,6,32),new T.MeshStandardMaterial({color:'#e9d7a0',emissive:'#d9bd72',emissiveIntensity:.7}));ring.rotation.x=Math.PI/2;ring.position.y=.9+i*.05;central.add(ring);}
 return {root,update(s,time){central.visible=centralLit(s);if(central.visible){core.rotation.y=(time||0)*.4;core.position.y=1.05+Math.sin((time||0)*1.3)*.04;}
  if(previous&&previous.notes===s.notes&&previous.things===s.things&&previous.shards===s.shards&&previous.day===s.day)return;previous={notes:s.notes,things:s.things,shards:s.shards,day:s.day};const rows=museumCollection(s);for(const [id,list]of Object.entries(groups))list.forEach((g,i)=>{g.visible=i<rows[id].length;g.userData.collectionId=rows[id][i]?.id||null;if(id==='fragments'||id==='alchemy'){const form=id==='alchemy'?(isKeepsake(rows[id][i])?rows[id][i].recipe:null):(rows[id][i]?.curio||null);if(g.userData.form!==form){if(!g.userData.legacy)g.userData.legacy=[...g.children];g.clear();if(form){const model=isKeepsake(rows[id][i])?makeKeepsake(rows[id][i]):makeCurio(form);model.scale.setScalar(.7);g.add(model);}else g.add(...g.userData.legacy);g.userData.form=form;}}});},inspect(){return Object.fromEntries(Object.entries(groups).map(([id,list])=>[id,list.filter(g=>g.visible).map(g=>g.userData.collectionId)]));}};
}
