// Generated by art/fairy-garden/doll/assemble_v2.py.
export const OUTFITS = {"academy": {"label": "学院背心", "colors": {"cloth": "#e1d6cd", "trim": "#f5efea", "bottom": "#988d87", "accent": "#ae8f7f", "boots": "#4a3a32"}}, "garden": {"label": "背带连衣裙", "colors": {"cloth": "#b09b8e", "trim": "#c3b4aa", "boots": "#3b2b25"}}};
