// Generated by art/fairy-garden/doll/assemble_v2.py.
export const OUTFITS = {"academy": {"label": "学院背心", "colors": {"cloth": "#e1d6cd", "trim": "#f5efea", "bottom": "#988d87", "accent": "#ae8f7f", "boots": "#4a3a32"}}};
