import * as T from 'three';
import {createRitual} from './ritual.mjs?v=fg-3495a25de4ed3f21';
import {SPELLS,SPELL_PLACES} from './world.mjs?v=fg-3495a25de4ed3f21';
export function makeRitualView({scene,camera,onClose}){
 const root=new T.Group();root.visible=false;scene.add(root);const glyph=new T.Group();root.add(glyph);
 const material=new T.LineBasicMaterial({color:'#cfb9fa',transparent:true,opacity:.85,depthTest:false,depthWrite:false});
 const guideMaterial=material.clone();guideMaterial.opacity=.18;
 const geometry=new T.BufferGeometry(),guideGeometry=new T.BufferGeometry();const line=new T.Line(geometry,material),guide=new T.Line(guideGeometry,guideMaterial);glyph.add(guide,line);line.renderOrder=101;guide.renderOrder=100;
 const ring=new T.Mesh(new T.TorusGeometry(1,.012,6,80),new T.MeshBasicMaterial({color:'#cfb9fa',transparent:true,opacity:.4,depthTest:false,depthWrite:false}));ring.renderOrder=99;glyph.add(ring);

 const strokes=Array.from({length:6},()=>{const g=new T.Group();for(const [radius,opacity]of [[.037,.17],[.009,.95]]){const m=new T.Mesh(new T.CylinderGeometry(radius,radius,1,8),new T.MeshBasicMaterial({color:'#cfb9fa',transparent:true,opacity,depthTest:false,depthWrite:false,toneMapped:false}));m.renderOrder=101;g.add(m);}glyph.add(g);return g;});
 const dots=Array.from({length:7},()=>{const m=new T.Mesh(new T.SphereGeometry(.045,10,8),new T.MeshBasicMaterial({color:'#cfb9fa',depthTest:false,depthWrite:false,transparent:true}));m.renderOrder=102;glyph.add(m);return m;});
 const sparks=Array.from({length:28},()=>{const m=new T.Mesh(new T.OctahedronGeometry(.022),new T.MeshBasicMaterial({color:'#cfb9fa',transparent:true,depthTest:false,depthWrite:false}));m.renderOrder=103;root.add(m);return m;});
 const dialog=document.createElement('dialog');dialog.id='ritual-dialog';dialog.className='scene-activity brewing-dialog';dialog.setAttribute('aria-labelledby','ritual-title');dialog.innerHTML='<div class="dialog-title"><button class="activity-close" aria-label="返回许愿树">‹</button><h2 id="ritual-title">树下施法</h2><span class="title-spacer"></span></div><div class="brew-body"><div class="brew-caption"><p id="ritual-instruction" aria-live="polite"></p><p id="ritual-destination"></p></div><div id="ritual-surface" aria-label="依次连接法阵上的亮点"></div><div class="brew-controls"><p id="ritual-message" aria-live="polite"></p><button id="ritual-help">按住，让微光带着画</button><button id="ritual-send" hidden>将咒送出去</button><small id="ritual-footnote">没有时限 · 描到一半松手也没关系</small></div></div>';
 document.body.append(dialog);const $=s=>dialog.querySelector(s);let session=null,config=null,view=null,pointer=null,helping=false,helpPointer=null,phase='',center=new T.Vector3();
 const screen=p=>{const v=p.clone().project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};};
 function localScreen(p){glyph.updateMatrixWorld(true);return screen(glyph.localToWorld(new T.Vector3(p.x,p.y,0)));}
 function sync(){if(!session)return;const stage=session.stage;dialog.dataset.stage=stage;$('#ritual-instruction').textContent=stage==='trace'?'沿着亮点连成法阵，可以松手再接着画。':stage==='ready'?'法阵亮起来了，准备好就把咒送出去。':stage==='send'?'微光正带着这片碎片，去你选的地方……':'这一道咒已经送到了。';$('#ritual-help').hidden=stage!=='trace';$('#ritual-send').hidden=!['ready','done'].includes(stage);$('#ritual-send').textContent=stage==='done'?'收好，回到树下':'将咒送出去';$('#ritual-footnote').textContent=stage==='done'?'碎片留在那个地方，走近还能读到原文':'完成时才封存碎片 · 随时可以返回';}
 function reset(){pointer=null;helping=false;helpPointer=null;}
 function close(){if(!session)return;session=null;reset();root.visible=false;dialog.close();document.body.classList.remove('brewing');onClose(view);}
 $('.activity-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 const surface=$('#ritual-surface');function trace(e){if(pointer!==e.pointerId||session?.stage!=='trace')return;const p=localScreen({x:0,y:0}),a=localScreen({x:1,y:0}),b=localScreen({x:0,y:1}),scaleX=a.x-p.x,scaleY=b.y-p.y;session.touch((e.clientX-p.x)/scaleX,(e.clientY-p.y)/scaleY);sync();}
 surface.onpointerdown=e=>{pointer=e.pointerId;surface.setPointerCapture(pointer);trace(e);};surface.onpointermove=trace;surface.onpointerup=reset;surface.onpointercancel=reset;surface.onlostpointercapture=reset;
 const help=$('#ritual-help');help.onpointerdown=e=>{helping=true;helpPointer=e.pointerId;help.setPointerCapture(helpPointer);};help.onpointerup=reset;help.onpointercancel=reset;help.onlostpointercapture=reset;help.onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();helping=true;}};help.onkeyup=reset;help.onblur=reset;window.addEventListener('blur',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden)reset();});
 $('#ritual-send').onclick=()=>{if(session?.stage==='done')close();else {session?.send();reset();sync();}};
 return {get active(){return !!session;},get helping(){return !!session&&config.helper;},
 open(options,saved){if(session)return;config=options;view=saved;center.set(options.position.x,options.height+.9,options.position.z);session=createRitual(options.spell);phase='';root.visible=true;glyph.scale.setScalar(1);glyph.visible=true;$('#ritual-title').textContent=SPELLS[options.spell].name;$('#ritual-destination').textContent='封往 · '+SPELL_PLACES[options.place];$('#ritual-message').textContent=options.helper?'同行者在你身边，陪你托住这道光。':'';const pts=session.glyph.points.map(p=>new T.Vector3(p.x,p.y,0));geometry.setFromPoints(pts);guideGeometry.setFromPoints(pts);material.color.set(session.glyph.color);guideMaterial.color.copy(material.color);ring.material.color.copy(material.color);dots.forEach((d,i)=>{d.visible=i<pts.length;if(pts[i])d.position.copy(pts[i]);});strokes.forEach((g,i)=>{g.visible=false;if(!pts[i+1])return;const delta=pts[i+1].clone().sub(pts[i]);g.position.copy(pts[i]).add(pts[i+1]).multiplyScalar(.5);g.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.clone().normalize());g.scale.y=delta.length();g.children.forEach(m=>m.material.color.copy(material.color));});document.body.classList.add('brewing');dialog.showModal();sync();},
 camera(){if(!session)return;const aspect=innerWidth/innerHeight,span=Math.max(3.3,4.4*aspect);camera.zoom=1;camera.userData.fogOffset=0;camera.left=-span/2;camera.right=span/2;camera.top=span/aspect/2;camera.bottom=-span/aspect/2;camera.position.set(center.x+4,center.y+3.5,center.z+6);camera.lookAt(center);camera.updateProjectionMatrix();camera.updateMatrixWorld();glyph.position.copy(center);glyph.position.y+=innerHeight<550?0:.7;glyph.quaternion.copy(camera.quaternion);},
 update(dt,time){if(!session)return;this.camera();if(helping)session.help(dt);if(phase!==session.stage){phase=session.stage;sync();}const n=session.count;geometry.setDrawRange(0,n);strokes.forEach((g,i)=>g.visible=i<n-1);ring.material.opacity=.25+Math.sin(time*2)*.1;dots.forEach((d,i)=>{d.material.color.set(i===n?'#fff7d4':session.glyph.color);d.material.opacity=i<=n?1:.3;d.scale.setScalar(i===n?1.8+Math.sin(time*5)*.35:1);});
 const sending=session.stage==='send',p=session.progress;glyph.scale.setScalar(sending?1-p*.85:1);glyph.position.y+=sending?p*1.2:0;glyph.visible=session.stage!=='done';sparks.forEach((s,i)=>{s.visible=sending;if(!sending)return;const a=i*2.4+time*1.5,r=(1-p)*(.3+(i%5)*.15);s.position.set(center.x+Math.cos(a)*r,center.y+.7+p*2+(i/28)*.4,center.z+Math.sin(a)*r);s.material.color.copy(material.color);s.material.opacity=1-p*.5;});
 const result=session.tick(dt,config.commit);if(result!==undefined){phase=session.stage;$('#ritual-message').textContent=result.text;sync();if(!result.ok){$('#ritual-instruction').textContent='这一次没能封进去，碎片还留在背包。';$('#ritual-footnote').textContent='返回后可以重新选择。';}}},
 inspect:()=>session?{...session.snapshot(),spell:config.spell,place:config.place,helper:config.helper,points:session.glyph.points.map(localScreen)}:null,close};
}
