// Shared by the phone host, game simulation and renderer. Model output names existing activities.
(function(root){
 const START={x:-.15,z:2.35},TREES=[[-3.9,-1.5],[-3,-3.6],[-.5,-4.2],[2,-3.6],[3.8,-2.2],[4.15,.8],[-4.2,1.2]];
 const NODES=[{id:'herb-a',map:'forest',kind:'herb',x:-2.8,z:.2},{id:'herb-b',map:'forest',kind:'herb',x:.1,z:2},{id:'herb-c',map:'forest',kind:'herb',x:2.5,z:-2.1},{id:'mushroom-a',map:'forest',kind:'mushroom',x:2.6,z:.5},{id:'mushroom-b',map:'forest',kind:'mushroom',x:-1.8,z:-3.1}];
 const MAPS={
 garden:{name:'微光庭院',decor:{lamps:Array.from({length:4},(_,i)=>({x:-2.2+i*.52,z:1.2}))},asset:'./garden.glb?v=fg-ef749ce728ca49b7',renderer:'glb',background:'#dfe5d5',light:3.5,radius:5.12,spawn:START,exits:{travel:{to:'forest'}},stations:{well:{x:-3,z:3.1},garden:{x:2.35,z:2.85},brew:{x:3.5,z:-.45},travel:{x:.1,z:4.45},rest:{x:-1,z:1.35},star:{x:.8,z:3.15},lamp:{x:-1.6,z:1.25}},interactions:[{kind:'well',x:-3,z:2,r:.85},{kind:'garden',x:2.35,z:1.3,w:1.9,d:2.4},{kind:'brew',x:2.7,z:-.65,r:.65},{kind:'travel',x:.1,z:4.45,r:.4},{kind:'star',x:.8,z:2.65,r:.4}],obstacles:[{x:-1,z:-1,w:3.65,d:3.12},{x:2.35,z:.65,w:1.95,d:1.18},{x:2.35,z:1.9,w:1.95,d:1.18},{x:1.65,z:-1.4,w:1.6,d:1},{x:2.7,z:-.65,r:.57},{x:-3,z:2,r:.87},...[[-3.6,-1.4],[-3,-3.2],[0,-3.8],[3.8,-2.5],[-4,1]].map(([x,z])=>({x,z,r:.4}))]},
 forest:{name:'萤光林地',renderer:'forest',background:'#dbe5d6',light:2.4,radius:5.12,spawn:{x:-2.7,z:3.05},exits:{travel:{to:'garden'}},stations:{travel:{x:-2.7,z:3.05},seed:{x:1.7,z:3}},interactions:[{kind:'travel',x:-3.1,z:2.55,r:.55},{kind:'seed',x:1.7,z:2.5,r:.45}],obstacles:[{x:-.7,z:-1.1,r:1.28},...TREES.map(([x,z])=>({x,z,r:.44}))]}
 };
 const ACTIVITIES={
 flowers:{map:'garden',target:MAPS.garden.stations.garden,label:'照料月光花',gesture:'water'},herbs:{map:'forest',target:{x:.1,z:2.48},label:'观察铃叶草',gesture:'gather'},mushrooms:{map:'forest',target:{x:2.6,z:.98},label:'寻找会发光的蘑菇',gesture:'gather'},pond:{map:'forest',target:{x:-.7,z:.6},label:'在池边观察水纹',gesture:'read'},study:{map:'garden',target:{x:1.5,z:-2.25},label:'翻看魔法笔记',gesture:'read'},potion:{map:'garden',target:MAPS.garden.stations.brew,label:'研究炼药锅里的微光',gesture:'read'},glow:{map:'forest',target:{x:1.7,z:3},label:'等草丛里的萤光亮起来',gesture:'rest'},home:{map:'garden',target:{x:-2,z:1.15},label:'在屋前歇脚',gesture:'rest'},rain:{map:'garden',target:{x:-1,z:1.35},label:'在屋檐下听雨',gesture:'read'},star:{map:'garden',target:MAPS.garden.stations.star,label:'看看星铃花的新芽',gesture:'read'}
 };
 const SEASONS=[{name:'春',tint:'#eef5dd',dusk:1080,weather:['晴日','细雨','薄雾','晴日','细雨','晴日','晴日']},{name:'夏',tint:'#e7f5ce',dusk:1140,weather:['晴日','晴日','细雨','晴日','薄雾','晴日','细雨']},{name:'秋',tint:'#efd2a9',dusk:1020,weather:['薄雾','晴日','晴日','细雨','晴日','薄雾','晴日']},{name:'冬',tint:'#dce7ee',dusk:960,weather:['细雪','晴日','薄雾','晴日','细雪','晴日','晴日']}];
 const seasonOf=day=>{const d=Math.max(1,Math.floor(Number(day)||1)),index=Math.floor((d-1)/14);return {...SEASONS[index%4],index,key:String(index),year:Math.floor(index/4)+1,day:(d-1)%14+1,start:index*14+1,end:index*14+14};};
 const weather=day=>{const s=seasonOf(day);return s.weather[(s.day-1+Math.floor((s.day-1)/7)*2+Math.floor(s.index/4))%s.weather.length];};
 function normalizePlan(raw,day){const season=seasonOf(day);if(!raw||!Array.isArray(raw.days)||raw.days.length!==14)throw Error('这一季需要完整的 14 天安排，可以重试。');const seen=new Set();const days=raw.days.map(d=>{if(!Number.isInteger(d.day)||d.day<1||d.day>14||seen.has(d.day)||!Array.isArray(d.activities)||d.activities.length!==3)throw Error('日期或活动数量没有对上，请重试这一季。');seen.add(d.day);return {day:d.day,note:String(d.note||'').slice(0,180),activities:d.activities.map(a=>{if(!a||!Object.hasOwn(ACTIVITIES,a.id))throw Error('有一项活动还不在这个世界里，请重试这一季。');return {id:a.id,note:String(a.note||'').slice(0,120)};})};}).sort((a,b)=>a.day-b.day);return {season:season.index,title:String(raw.title||'一起度过这一季').slice(0,60),days};}
 function hitInteraction(map,p){const m=MAPS[map];if(!m)return null;const n=NODES.find(n=>n.map===map&&Math.hypot(n.x-p.x,n.z-p.z)<.48);if(n)return {kind:'gather',id:n.id};return m.interactions.find(o=>o.r?Math.hypot(p.x-o.x,p.z-o.z)<o.r:Math.abs(p.x-o.x)<o.w/2&&Math.abs(p.z-o.z)<o.d/2)||null;}
 root.FairyGardenRules={START,TREES,NODES,MAPS,ACTIVITIES,SEASONS,seasonOf,weather,normalizePlan,hitInteraction};
})(globalThis);
