import {landingOf,villagePoint} from './world.mjs';
import {rainyEpoch} from '../../test/_fairy-weather.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {seasonOf,weather,freshState,restoreState,perform,targetFor,normalizePlan,MAPS,hitInteraction,nextDay,journalText,actionError} from './world.mjs';
import {dailySchedule,makeCompanionController} from './companion.mjs';
const act=(s,k)=>perform({...s,position:targetFor(s,k)},k);
const makePlan=(day=1)=>normalizePlan({title:'这一季',days:Array.from({length:14},(_,i)=>({day:i+1,note:'安排',activities:[{id:'pond',note:'看水'},{id:'study',note:'读书'},{id:'home',note:'休息'}]}))},day);
test('four fourteen-day seasons roll into another year and weather is stable after reload',()=>{assert.equal(seasonOf(14).name,'春');assert.equal(seasonOf(15).name,'夏');assert.equal(seasonOf(56).name,'冬');assert.deepEqual([seasonOf(57).year,seasonOf(57).day],[2,1]);for(let day=1;day<=112;day++)assert.equal(weather(day),weather(restoreState({...freshState(),day}).day));assert.notEqual(seasonOf(15).dusk,seasonOf(43).dusk);});
test('map interaction coordinates and exits come from the same registry',()=>{assert.equal(hitInteraction('garden',villagePoint({x:-3,z:2},'home')).kind,'well');assert.equal(hitInteraction('forest',{x:1.7,z:2.5}).kind,'seed');for(const [id,m]of Object.entries(MAPS))for(const [action,exit]of Object.entries(m.exits)){const kind=exit.action||action,raw={...freshState(),map:id},s=perform({...raw,position:targetFor(raw,kind,action)},kind,action);assert.equal(s.map,exit.to);assert.deepEqual(s.position,landingOf(exit,kind),'穿过一道口子该落在说好的那一点上');}});
test('season plans require all fourteen distinct days and existing activities',()=>{const p=makePlan();assert.equal(p.days.length,14);assert.throws(()=>normalizePlan({days:p.days.slice(1)},1));const duplicate=structuredClone(p);duplicate.days[1].day=1;assert.throws(()=>normalizePlan(duplicate,1));const invented=structuredClone(p);invented.days[2].activities[0].id='spawnGold';assert.throws(()=>normalizePlan(invented,1));});
test('saved seasonal schedule drives movement; rain adapts locally and a new season drops the old plan',()=>{let s={...freshState(),epoch:rainyEpoch,seasonPlan:makePlan()};assert.equal(dailySchedule(s).find(p=>p.start===480).id,'pond');const ctrl=makeCompanionController();for(let i=0;i<800;i++)s=ctrl.tick(s,.1).state;assert.equal(s.companion.map,'forest');assert.equal(s.herbs,0);assert.equal(dailySchedule({...s,day:2}).find(p=>p.start===480).id,'rain');let dry=1;for(let d=1;d<60;d++)if(!['细雨','细雪'].includes(weather(d,'initial'))){dry=d;break;}
 const next=dailySchedule({...s,day:15});assert.ok(!next.some(p=>['看水','读书','休息'].includes(p.note)),'旧计划的备注还挂在上面＝没真丢掉');assert.ok(next.some(p=>p.id==='flowers'),'哪天都得有那件杂活');for(const p of next)assert.ok(p.id==='home'||p.id==='flowers'||p.id==='rain'||MAPS[p.map].interior,'雨天还有一格露天站着：'+p.id);(()=>{const floor=dailySchedule({...s,epoch:'initial',day:dry,seasonPlan:null}).map(p=>p.id);assert.equal(floor[0],'home');assert.equal(floor[1],'flowers');assert.ok(floor.length>=5,'不下雨那天该是满满一天，不是四格');assert.ok(!floor.includes('rain'),'不下雨就不该有檐下那一格');})();});
test('cooperative seed requires actual presence, cannot be duplicated within a season, and returns next season',()=>{let s={...freshState(),map:'forest',position:MAPS.forest.stations.seed};assert.equal(perform(s,'seed'),s);s.companion={...s.companion,map:'forest',position:{x:2.4,z:3}};s=perform(s,'seed');assert.equal(s.magic.seeds,1);assert.equal(perform(s,'seed'),s);s={...s,day:15};s=perform(s,'seed');assert.equal(s.magic.seeds,2);});
test('planting and two distinct watering days lead to one flower, one persistent lamp and honest journal facts',()=>{let s=freshState();s.magic.seeds=1;s=act(s,'star');assert.equal(s.magic.seeds,0);s=act(s,'well');s=act(s,'star');assert.equal(s.magic.growth,1);const water=s.water;s=act(s,'star');assert.equal(s.water,water);assert.equal(s.magic.growth,1);s=nextDay(s);assert.match(journalText(s.journal[0]),/照料或采收星铃花/);s=act(s,'star');assert.equal(s.magic.growth,2);s=act(s,'star');assert.equal(s.magic.flowers,1);assert.equal(s.magic.discovered,true);s.harvest=3;s=act(s,'lamp');assert.deepEqual([s.magic.flowers,s.harvest,s.magic.lamps],[0,0,1]);assert.equal(actionError(s,'lamp'),'星铃灯需要星铃花 ×1、月光花 ×3。');assert.deepEqual(restoreState(JSON.parse(JSON.stringify(s))),s);});
test('v3 migrates dates and inventory and preserves actual world state without inventing seasonal records',()=>{const s=restoreState({version:3,day:30,minute:1120,map:'forest',water:2,herbs:7,potions:3,harvest:9});assert.deepEqual([s.day,s.minute,s.water,s.herbs,s.potions,s.harvest],[30,1120,2,7,3,9]);assert.equal(s.magic.lamps,0);assert.deepEqual(s.journal,[]);});
