import test from 'node:test';import assert from 'node:assert/strict';
import {SEASONS,MAPS,weather,seasonOf,freshState,restoreState,perform,targetFor,findPath,nextDay,actionError} from './world.mjs';
import {makeCompanionController} from './companion.mjs';
test('daily weather is seeded by save, stable through reload and weighted per season',()=>{
 for(let season=0;season<4;season++){const totals={};for(let i=0;i<10000;i++){const epoch='save-'+i,day=season*14+1,kind=weather(day,epoch);totals[kind]=(totals[kind]||0)+1;const s=restoreState({...freshState(),epoch,day});assert.equal(weather(s.day,s.epoch),kind);}for(const [kind,weight]of Object.entries(SEASONS[season].weather))assert.ok(Math.abs(totals[kind]/100-weight)<2,JSON.stringify(totals));assert.equal(Object.values(SEASONS[season].weather).reduce((a,b)=>a+b),100);}
 assert.ok(new Set(Array.from({length:56},(_,i)=>weather(i+1,'one-save'))).size===4);
 assert.notDeepEqual(Array.from({length:56},(_,i)=>weather(i+1,'a')),Array.from({length:56},(_,i)=>weather(i+1,'b')));
});
test('journal preserves actual old weather and rain watering uses the same daily draw',()=>{for(let day=1;day<56;day++){const s={...freshState(),day,epoch:'rain-test'},n=nextDay(s);assert.equal(n.journal[0].weather,weather(day,s.epoch));assert.equal(n.blooms,weather(day+1,s.epoch)==='细雨'?1:0);assert.equal(restoreState(n).journal[0].weather,n.journal[0].weather);}const s=restoreState({...freshState(),journal:[{day:2,weather:'细雪',actions:{},partner:'旧同行者'}]});assert.equal(s.journal[0].weather,'细雪');});
test('both outdoor ponds have reachable seats, persist sitting only at the actual location',()=>{for(const map of ['garden','forest']){let s={...freshState(),map,position:{...MAPS[map].spawn}};const target=targetFor(s,'sit');assert.ok(findPath(s.position,target,map)?.length);assert.equal(perform(s,'sit'),s);s=perform({...s,position:target},'sit');assert.equal(s.seat,'pond');assert.equal(restoreState(s).seat,'pond');assert.equal(restoreState({...s,map:'depths'}).seat,null);assert.equal(restoreState({...s,position:MAPS[map].spawn}).seat,null);}assert.ok(actionError({...freshState(),map:'depths'},'sit'));});
test('following companion reaches adjacent seat and faces the water without overlapping',()=>{for(const map of ['garden','forest']){let s={...freshState(),map,position:targetFor({map},'sit'),seat:'pond'};s.companion={...s.companion,map,mode:'follow',position:{...MAPS[map].spawn}};const c=makeCompanionController();for(let i=0;i<1200;i++)s=c.tick(s,.05).state;assert.equal(c.view().gesture,'sit');assert.equal(c.view().heading,MAPS[map].seats.pond.heading);assert.ok(Math.hypot(s.position.x-s.companion.position.x,s.position.z-s.companion.position.z)>.65);s={...s,seat:null};for(let i=0;i<100;i++)s=c.tick(s,.05).state;assert.notEqual(c.view().gesture,'sit');}});
