const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{createHash}=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.TRAIN_JOURNEY_SHOTS||'/Users/lisa/.codex/visualizations/2026/09/24/train-journey';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'}),errors=[],failed=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
 await p.goto((process.env.TRAIN_URL||'http://127.0.0.1:18924')+'/art/train-carriage/preview.html');await p.waitForFunction(()=>window.carriageReview?.scenery.nextStop);await p.locator('[data-view=window]').click();
 const cases=await p.evaluate(async()=>{
  const {JOURNEYS}=await import(new URL('./journey.mjs',location.href).href),r=carriageReview,s=r.scenery;const records=[],initialObjects=r.scene.children.length;
  for(const [route,entries] of Object.entries(JOURNEYS))for(const [id,label,start,duration] of entries){s.seekJourney(start+duration*.5);r.setEnvironment({route,hour:12,weather:'clear',season:'spring',playing:false});const data=s.canvas.getContext('2d').getImageData(0,0,s.canvas.width,s.canvas.height).data;let hash=0;for(let i=0;i<data.length;i+=124)hash=Math.imul(hash^data[i],16777619);records.push({route,id,label,actual:s.journey.id,hash:hash>>>0});}
  s.seekJourney(0);r.setEnvironment({route:'forest',hour:12,playing:false});const daylight=s.lighting();s.seekJourney(81);r.setEnvironment({});const tunnel=s.lighting();s.seekJourney(88);r.setEnvironment({});const exit=s.lighting();
  const speeds=[];for(const speed of [.5,1,2]){s.seekJourney(0);s.set({speed,playing:true});s.step(.1);speeds.push(s.state.distance);s.set({playing:false});}
  s.seekJourney(113);r.setEnvironment({playing:false,speed:1});const saved={...s.state};s.step(.1);const frozen=JSON.stringify(saved)===JSON.stringify(s.state);
  return {records,initialObjects,finalObjects:r.scene.children.length,daylight,tunnel,exit,speeds,frozen,nearSpeed:s.layers.at(-1).speed};
 });
 assert.equal(cases.records.length,21);for(const e of cases.records)assert.equal(e.actual,e.id);assert.ok(new Set(cases.records.map(r=>r.hash)).size>=17);assert.equal(cases.initialObjects,cases.finalObjects);assert.ok(cases.nearSpeed>=300);assert.ok(cases.tunnel.sun<cases.daylight.sun*.2);assert.ok(cases.tunnel.lamps>cases.daylight.lamps);assert.equal(cases.exit.sun,cases.daylight.sun);assert.ok(cases.frozen);assert.ok(Math.abs(cases.speeds[2]/cases.speeds[0]-4)<1e-6);
 for(const [name,route,distance] of [['crossing','country',7.5],['village','forest',25],['bridge','forest',42],['station','forest',62],['tunnel','forest',81],['harbor','coast',10],['windmill','country',24],['train','country',113]]){await p.evaluate(({route,distance})=>{const r=carriageReview;r.scenery.seekJourney(distance);r.setEnvironment({route,playing:false,hour:12});},{route,distance});await p.screenshot({path:path.join(out,name+'.png')});}
 // Pause remains respected by both the skip control and a speed change.
 await p.evaluate(()=>{carriageReview.scenery.seekJourney(0);carriageReview.setEnvironment({route:'forest',playing:false});});await p.locator('#next-stop').click();assert.equal(await p.evaluate(()=>carriageReview.scenery.journey.id),'crossing');assert.equal(await p.evaluate(()=>carriageReview.scenery.state.playing),false);
 await p.locator('#speed').evaluate(el=>{el.value=2;el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await p.evaluate(()=>carriageReview.scenery.state.speed),2);await p.locator('#play').click();const before=await p.evaluate(()=>carriageReview.scenery.state.distance);await p.waitForTimeout(350);assert.ok(await p.evaluate(()=>carriageReview.scenery.state.distance)>before);await p.locator('#play').click();
 await p.setViewportSize({width:390,height:844});await p.locator('#next-stop').scrollIntoViewIfNeeded();await p.locator('#next-stop').click();assert.equal(await p.evaluate(()=>carriageReview.scenery.journey.id),'village');const layout=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,stage:document.querySelector('#stage').getBoundingClientRect().height}));assert.equal(layout.overflow,false);assert.ok(layout.stage>300);await p.screenshot({path:path.join(out,'mobile.png')});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 const sourceHashes=Object.fromEntries(['destinations.mjs','journey.mjs','scenery.mjs','preview.mjs','preview.html'].map(f=>[f,createHash('sha256').update(fs.readFileSync(path.join(__dirname,f))).digest('hex')]));
 fs.writeFileSync(path.join(__dirname,'journey-validation.json'),JSON.stringify({sourceHashes,encounters:21,distinctFrames:new Set(cases.records.map(r=>r.hash)).size,nearSpeed:cases.nearSpeed,stableSceneObjects:true,tunnelLighting:true,speedRatio:4,pausedSkip:true,mobile:layout,errors,failed},null,2)+'\n');console.log(JSON.stringify({encounters:21,distinctFrames:new Set(cases.records.map(r=>r.hash)).size,layout,errors,failed}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
