// Generated by scripts/build-char-day-catalog.mjs from the actual scene maps.
(function(root){root.CharDayCatalog=[
  {
    "id": "dayHome",
    "label": "你们的小家",
    "spots": [
      {
        "id": "sleep",
        "action": "sleep"
      },
      {
        "id": "meal",
        "action": "meal"
      },
      {
        "id": "tea",
        "action": "tea"
      },
      {
        "id": "rest",
        "action": "rest"
      },
      {
        "id": "read",
        "action": "read"
      },
      {
        "id": "cook",
        "label": "厨房料理",
        "action": "cook"
      }
    ]
  },
  {
    "id": "dayWork",
    "label": "工作与学习空间",
    "spots": [
      {
        "id": "work",
        "action": "work"
      },
      {
        "id": "read",
        "action": "read"
      },
      {
        "id": "rest",
        "action": "rest"
      }
    ]
  },
  {
    "id": "dayCafe",
    "label": "街角餐饮小店",
    "spots": [
      {
        "id": "meal",
        "action": "meal"
      },
      {
        "id": "tea",
        "action": "tea"
      },
      {
        "id": "rest",
        "action": "rest"
      },
      {
        "id": "read",
        "action": "read"
      }
    ]
  },
  {
    "id": "dayStreet",
    "label": "小街与散步处",
    "spots": [
      {
        "id": "walk",
        "action": "walk"
      },
      {
        "id": "rest",
        "action": "rest"
      }
    ]
  },
  {
    "id": "dayLaboratory",
    "label": "实验室",
    "spots": [
      {
        "id": "entrance",
        "label": "入口",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "bench",
        "label": "实验台前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "observation",
        "label": "观察台前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "computer",
        "label": "电脑工位",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "records",
        "label": "记录工位",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "archive",
        "label": "资料柜前",
        "action": "read",
        "gesture": "rest"
      },
      {
        "id": "materials",
        "label": "材料架前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "break",
        "label": "休息座位",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayLibrary",
    "label": "图书馆／阅览室",
    "spots": [
      {
        "id": "choose-book",
        "label": "书架前挑书",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "desk-reading",
        "label": "桌前坐着阅读",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "study-notes",
        "label": "自习与备考",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "window-reading",
        "label": "窗边独自阅读",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "return-book",
        "label": "借阅台归还",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "exit",
        "label": "入口与离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayClinic",
    "label": "诊室／值班室",
    "spots": [
      {
        "id": "entrance",
        "label": "入口与离开",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "casework",
        "label": "桌前整理病历",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "bedside",
        "label": "诊查床旁",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "equipment",
        "label": "器材柜前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "casefiles",
        "label": "病历柜前",
        "action": "read",
        "gesture": "rest"
      },
      {
        "id": "handoff",
        "label": "交班资料台",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "preparation",
        "label": "器材车前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "duty",
        "label": "值班阅读座",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "rest",
        "label": "小休息角",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayStudio",
    "label": "创作工作室",
    "spots": [
      {
        "id": "entrance",
        "label": "工作室入口",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "easel",
        "label": "画架前站位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "drawing",
        "label": "画桌坐位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "handcraft",
        "label": "手作坐位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "materials",
        "label": "材料架前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "storage",
        "label": "收纳柜前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "gallery",
        "label": "站着看作品",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "drying",
        "label": "整理与晾放作品",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "rest",
        "label": "创作间隙休息",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "整理后离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayRehearsal",
    "label": "排练室",
    "spots": [
      {
        "id": "entrance",
        "label": "进入排练室",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "practice",
        "label": "开阔练习区",
        "action": "practice",
        "gesture": "rest"
      },
      {
        "id": "mirror",
        "label": "镜墙前站位",
        "action": "practice",
        "gesture": "rest"
      },
      {
        "id": "score",
        "label": "乐谱架前",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "piano",
        "label": "乐器前坐位",
        "action": "practice",
        "gesture": "rest"
      },
      {
        "id": "instruments",
        "label": "乐器架前",
        "action": "practice",
        "gesture": "rest"
      },
      {
        "id": "rest",
        "label": "排练间隙休息",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "准备结束后离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayStation",
    "label": "车站／候车区",
    "spots": [
      {
        "id": "entrance",
        "label": "进入候车厅",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "information",
        "label": "站牌前看信息",
        "action": "wait",
        "gesture": "rest"
      },
      {
        "id": "service",
        "label": "服务台前",
        "action": "wait",
        "gesture": "rest"
      },
      {
        "id": "luggage",
        "label": "行李放置处",
        "action": "wait",
        "gesture": "rest"
      },
      {
        "id": "waiting",
        "label": "坐着候车",
        "action": "wait",
        "gesture": "rest"
      },
      {
        "id": "reading",
        "label": "候车时阅读",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "platform",
        "label": "站台内侧等候",
        "action": "wait",
        "gesture": "rest"
      },
      {
        "id": "departure",
        "label": "出发准备位置",
        "action": "wait",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "起身离开候车区",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayGym",
    "label": "健身房",
    "spots": [
      {
        "id": "entrance",
        "label": "走进健身房",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "storage",
        "label": "柜前整理随身物品",
        "action": "prepare",
        "gesture": "rest"
      },
      {
        "id": "treadmill",
        "label": "跑步机上慢跑",
        "action": "exercise",
        "gesture": "rest"
      },
      {
        "id": "take-weights",
        "label": "哑铃架前取放",
        "action": "prepare",
        "gesture": "rest"
      },
      {
        "id": "weights",
        "label": "哑铃区练习",
        "action": "exercise",
        "gesture": "rest"
      },
      {
        "id": "stretch",
        "label": "软垫上拉伸",
        "action": "exercise",
        "gesture": "rest"
      },
      {
        "id": "water",
        "label": "补水位置",
        "action": "tea",
        "gesture": "tea"
      },
      {
        "id": "rest",
        "label": "长椅上休息",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "结束运动离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayMarket",
    "label": "超市",
    "spots": [
      {
        "id": "entrance",
        "label": "走进超市",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "basket",
        "label": "拿取购物篮",
        "action": "shop",
        "gesture": "rest"
      },
      {
        "id": "produce",
        "label": "蔬果台前挑选",
        "action": "shop",
        "gesture": "rest"
      },
      {
        "id": "groceries",
        "label": "货架旁挑日用品",
        "action": "shop",
        "gesture": "rest"
      },
      {
        "id": "cold",
        "label": "冷柜前挑选",
        "action": "shop",
        "gesture": "rest"
      },
      {
        "id": "checkout",
        "label": "收银台前结账",
        "action": "shop",
        "gesture": "rest"
      },
      {
        "id": "cashier",
        "label": "收银工位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "packing",
        "label": "整理购物袋",
        "action": "shop",
        "gesture": "rest"
      },
      {
        "id": "rest",
        "label": "入口长椅歇脚",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "提袋离开超市",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayOffice",
    "label": "办公室／会议室",
    "spots": [
      {
        "id": "entrance",
        "label": "办公区入口",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "computer",
        "label": "窗边电脑工位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "notes",
        "label": "整理文件与写记录",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "meeting",
        "label": "会议席听讨论",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "meeting-notes",
        "label": "会议记录席",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "presentation",
        "label": "投影前汇报",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "files",
        "label": "资料柜取文件",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "print",
        "label": "打印与收文件",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "tea",
        "label": "茶水角喝口水",
        "action": "tea",
        "gesture": "tea"
      },
      {
        "id": "rest",
        "label": "入口休息长椅",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "收工离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayCampus",
    "label": "教室／校园",
    "spots": [
      {
        "id": "entrance",
        "label": "校园入口",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "listen",
        "label": "课桌前听课",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "notes",
        "label": "听课记笔记",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "study",
        "label": "课后自习与做题",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "blackboard",
        "label": "黑板前板书",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "teach",
        "label": "讲台旁授课",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "prepare",
        "label": "讲台整理教案",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "lockers",
        "label": "走廊整理书包",
        "action": "read",
        "gesture": "rest"
      },
      {
        "id": "corridor",
        "label": "走廊课间停步",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "rest",
        "label": "庭院课间长椅",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "meal",
        "label": "校园午餐桌",
        "action": "meal",
        "gesture": "eat"
      },
      {
        "id": "exit",
        "label": "下课离开校园",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  }
];})(globalThis);
