// Generated by scripts/build-char-day-catalog.mjs from the actual scene maps.
(function(root){root.CharDayCatalog=[
  {
    "id": "dayHome",
    "label": "你们的小家",
    "spots": [
      {
        "id": "sleep",
        "action": "sleep"
      },
      {
        "id": "meal",
        "action": "meal"
      },
      {
        "id": "tea",
        "action": "tea"
      },
      {
        "id": "rest",
        "action": "rest"
      },
      {
        "id": "read",
        "action": "read"
      }
    ]
  },
  {
    "id": "dayWork",
    "label": "工作与学习空间",
    "spots": [
      {
        "id": "work",
        "action": "work"
      },
      {
        "id": "read",
        "action": "read"
      },
      {
        "id": "rest",
        "action": "rest"
      }
    ]
  },
  {
    "id": "dayCafe",
    "label": "街角餐饮小店",
    "spots": [
      {
        "id": "meal",
        "action": "meal"
      },
      {
        "id": "tea",
        "action": "tea"
      },
      {
        "id": "rest",
        "action": "rest"
      },
      {
        "id": "read",
        "action": "read"
      }
    ]
  },
  {
    "id": "dayStreet",
    "label": "小街与散步处",
    "spots": [
      {
        "id": "walk",
        "action": "walk"
      },
      {
        "id": "rest",
        "action": "rest"
      }
    ]
  },
  {
    "id": "dayLaboratory",
    "label": "实验室",
    "spots": [
      {
        "id": "entrance",
        "label": "入口",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "bench",
        "label": "实验台前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "observation",
        "label": "观察台前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "computer",
        "label": "电脑工位",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "records",
        "label": "记录工位",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "archive",
        "label": "资料柜前",
        "action": "read",
        "gesture": "rest"
      },
      {
        "id": "materials",
        "label": "材料架前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "break",
        "label": "休息座位",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayLibrary",
    "label": "图书馆／阅览室",
    "spots": [
      {
        "id": "choose-book",
        "label": "书架前挑书",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "desk-reading",
        "label": "桌前坐着阅读",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "study-notes",
        "label": "自习与备考",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "window-reading",
        "label": "窗边独自阅读",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "return-book",
        "label": "借阅台归还",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "exit",
        "label": "入口与离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayClinic",
    "label": "诊室／值班室",
    "spots": [
      {
        "id": "entrance",
        "label": "入口与离开",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "casework",
        "label": "桌前整理病历",
        "action": "work",
        "gesture": "read"
      },
      {
        "id": "bedside",
        "label": "诊查床旁",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "equipment",
        "label": "器材柜前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "casefiles",
        "label": "病历柜前",
        "action": "read",
        "gesture": "rest"
      },
      {
        "id": "handoff",
        "label": "交班资料台",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "preparation",
        "label": "器材车前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "duty",
        "label": "值班阅读座",
        "action": "read",
        "gesture": "read"
      },
      {
        "id": "rest",
        "label": "小休息角",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  },
  {
    "id": "dayStudio",
    "label": "创作工作室",
    "spots": [
      {
        "id": "entrance",
        "label": "工作室入口",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "easel",
        "label": "画架前站位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "drawing",
        "label": "画桌坐位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "handcraft",
        "label": "手作坐位",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "materials",
        "label": "材料架前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "storage",
        "label": "收纳柜前",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "gallery",
        "label": "站着看作品",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "drying",
        "label": "整理与晾放作品",
        "action": "work",
        "gesture": "rest"
      },
      {
        "id": "rest",
        "label": "创作间隙休息",
        "action": "rest",
        "gesture": "rest"
      },
      {
        "id": "exit",
        "label": "整理后离开",
        "action": "rest",
        "gesture": "rest"
      }
    ]
  }
];})(globalThis);
