"""Build the app's doll.glb from the v2 pieces (option B: the v2 doll replaces the old one).
One skinned body (bones leftArm/rightArm/leftLeg/rightLeg, pivots in extras dollRig), the hair
hats parented to HeadAnchor and named hair_<id>, the outfits skinned to the same armature and
tagged extras outfit=<id>. Hair base-colour textures are neutralised to grey so the runtime
tint (hairColor) is the actual colour. Writes a raw GLB; run compress_asset.py on it after.
Hair / outfit IDs reuse old save IDs (world.mjs only accepts [a-z]{2,16}); the aliases for the
retired old IDs live in apps/fairy-garden/wardrobe.mjs.
Usage: python3 assemble_v2.py out_raw.glb"""
import bpy,sys,os,numpy as np
out=sys.argv[-1];V2=os.path.join(os.path.dirname(os.path.abspath(__file__)),'v2')
import json
LABELS=json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','hairstyles.json')))  # the one hair list (tests pin runtime to it)
OUTFIT_LABELS={'academy':'学院背心'}
HAIRS={'korean':'hats/hair_m03.glb','curtains':'hats/hair_m02.glb','airbang':'hats/hair_f01.glb','bob':'hats/hair_f02.glb'}
OUTFITS={'academy':'outfits/outfit_c01.glb'}
for o in list(bpy.data.objects):bpy.data.objects.remove(o)
def imp(p):
    before=set(bpy.data.objects);bpy.ops.import_scene.gltf(filepath=os.path.join(V2,p));return [o for o in bpy.data.objects if o not in before]
new=imp('doll-rigged.glb')
A=next(o for o in new if o.type=='ARMATURE');HA=bpy.data.objects['HeadAnchor']
for o in new:
    if o.type=='MESH' and o.name.startswith('Icosphere'):bpy.data.objects.remove(o)
def grey(mat):
    for n in mat.node_tree.nodes:
        if n.type=='BSDF_PRINCIPLED':
            l=n.inputs['Base Color'].links
            if not l:return
            im=l[0].from_node.image;px=np.array(im.pixels[:]).reshape(-1,4);y=px[:,:3]@[.2126,.7152,.0722]
            y=np.clip(y/np.percentile(y,92),0,1);px[:,:3]=y[:,None];im.pixels[:]=px.ravel();im.pack();return
for hid,f in HAIRS.items():
    objs=imp(f);m=next(o for o in objs if o.type=='MESH');mw=m.matrix_world.copy()
    m.parent=HA;m.matrix_parent_inverse.identity();m.matrix_basis=mw;m.name='hair_'+hid;m['hair']=hid
    for s in m.material_slots:
        s.material=s.material.copy();s.material.name='hair_'+hid;grey(s.material)
    for o in objs:
        if o!=m:bpy.data.objects.remove(o)
for oid,f in OUTFITS.items():
    objs=imp(f);m=next(o for o in objs if o.type=='MESH' and o.name.startswith('Outfit'))
    m.parent=A;m.matrix_parent_inverse.identity()
    for md in m.modifiers:
        if md.type=='ARMATURE':md.object=A
    m.name='outfit_'+oid;m['outfit']=oid
    for o in objs:
        if o!=m:bpy.data.objects.remove(o)
bpy.ops.object.select_all(action='SELECT')
bpy.ops.export_scene.gltf(filepath=out,export_format='GLB',use_selection=True,export_extras=True,export_skins=True,export_animations=False)
print('assembled',[o.name for o in bpy.data.objects])
# The catalogues the app reads: doll.json (hair names; dims kept as they are) and outfits.mjs.
import json
APP=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','..','..','apps','fairy-garden')
dj=os.path.join(APP,'doll.json');d=json.load(open(dj))
d['hair']=LABELS;cat={k:{'label':v,'colors':{}} for k,v in OUTFIT_LABELS.items()};d['outfits']=cat;d['style']='hunyuan-v2-2026-09'
with open(dj,'w') as f:json.dump(d,f,ensure_ascii=False,indent=1);f.write('\n')
with open(os.path.join(APP,'outfits.mjs'),'w') as f:f.write('// Generated by art/fairy-garden/doll/assemble_v2.py.\nexport const OUTFITS = '+json.dumps(cat,ensure_ascii=False)+';\n')
