"""Keep authored dye controls in both catalogues and future doll builds."""
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
APP = HERE.parents[2] / 'apps/fairy-garden'

def apply_regions(outfits):
    for key, region in json.loads((HERE / 'dye_regions.json').read_text()).items():
        if key in outfits:
            for slot, value in region['add'].items():
                outfits[key]['colors'].setdefault(slot, value)
            outfits[key]['colorLabels'] = region['labels']
            if 'coveredLegsBelow' in region:outfits[key]['coveredLegsBelow']=region['coveredLegsBelow']
    return outfits

if __name__ == '__main__':
    path = APP / 'doll.json'
    catalog = json.loads(path.read_text())
    apply_regions(catalog['outfits'])
    path.write_text(json.dumps(catalog, ensure_ascii=False, indent=1) + '\n')
    (APP / 'outfits.mjs').write_text('// Generated by art/fairy-garden/doll/assemble_v2.py.\nexport const OUTFITS = ' + json.dumps(catalog['outfits'], ensure_ascii=False) + ';\n')
