import {panelHeader} from './panel-header.mjs?v=fg-b6dcbc456b2edf7e';
import {PHOTO_THEMES,currentPromise,photoTheme,promiseSummaries} from './photo-promise.mjs?v=fg-b6dcbc456b2edf7e';
import {cropRect} from './album.mjs?v=fg-b6dcbc456b2edf7e';
export function createTravelCamera({host,source,shoot,onOpen,onClose=()=>{},onMode=()=>{},hasCompanion=()=>false,state,onPromise}){
 const el=document.createElement('section');el.id='travel-camera';el.hidden=true;el.innerHTML='<header><button id="camera-back">收起</button><strong>旅途取景器</strong><button id="camera-shoot">拍下来</button></header><div class="camera-body"><label>拍什么 <select id="camera-subject" aria-label="拍摄对象"><option value="window">窗外风景</option><option value="companion">拍 TA</option><option value="together">两人合照</option></select></label><p>拖动画面取景，列车会继续前进。</p><section id="photo-promise"><label>这趟想拍 <select id="photo-theme" aria-label="拍照约定主题"></select></label><p id="photo-theme-hint"></p><button id="photo-promise-start">约好，就拍这个</button><p id="photo-promise-status" role="status"></p></section><canvas id="camera-canvas" aria-label="拖动调整取景位置"></canvas><label>焦距 <input id="camera-zoom" aria-label="取景放大倍数" type="range" min="1" max="3" step=".05" value="1"><span id="camera-scale">1.0×</span></label><button id="camera-reset">复位取景</button><p id="camera-status" role="status"></p></div>';document.body.append(el);
 const toolbar=panelHeader(host,el);const $=s=>el.querySelector(s),c=$('#camera-canvas'),ctx=c.getContext('2d');let mode='window',promiseKey='',zoom=1,pan={x:.5,y:.5},drag=null,raf=0,last=0;
 for(const theme of PHOTO_THEMES){const o=document.createElement('option');o.value=theme.id;o.textContent=theme.name;$('#photo-theme').append(o);}
 function refreshPromise(){const p=currentPromise(state()),summary=promiseSummaries(state()).find(x=>x.id===p?.id);const key=JSON.stringify([summary,$('#photo-theme').value]);if(key===promiseKey)return;promiseKey=key;if(p)$('#photo-theme').value=p.you.theme;$('#photo-theme').disabled=!!p;$('#photo-promise-start').disabled=!!p;$('#photo-promise-start').textContent=p?'这一趟已约好':'约好，就拍这个';$('#photo-theme-hint').textContent=photoTheme($('#photo-theme').value)?.hint||'';$('#photo-promise-status').textContent=summary?'你：'+summary.you.theme+' · '+summary.you.status+(summary.companion?'；'+summary.companion.name+'想拍：'+summary.companion.theme+' · '+summary.companion.status:''):'选好后从下一张开始算，旧照片不补算；这一趟各拍到一张就好。';}
 $('#photo-theme').onchange=refreshPromise;$('#photo-promise-start').onclick=()=>{try{onPromise($('#photo-theme').value);$('#camera-status').textContent='约好了，沿途留心窗外吧。';refreshPromise();}catch(e){$('#camera-status').textContent=e.message;}};
 const promiseSection=$('#photo-promise');$('.camera-body').append(promiseSection);
 function rect(){const src=source(mode);return cropRect(src.width,src.height,zoom,pan);}
 function draw(now){raf=requestAnimationFrame(draw);if(el.hidden||document.hidden||now-last<50)return;last=now;refreshPromise();const r=rect();c.width=900;c.height=600;ctx.drawImage(source(mode),r.x,r.y,r.w,r.h,0,0,900,600);ctx.strokeStyle='#ffffff75';ctx.lineWidth=1.2;for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(i*300,0);ctx.lineTo(i*300,600);ctx.moveTo(0,i*200);ctx.lineTo(900,i*200);ctx.stroke();}}
 c.onpointerdown=e=>{c.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,pan:{...pan}};};c.onpointermove=e=>{if(!drag)return;const box=c.getBoundingClientRect(),r=rect(),src=source(mode);pan={x:Math.max(0,Math.min(1,drag.pan.x-(e.clientX-drag.x)/box.width*r.w/Math.max(1,src.width-r.w))),y:Math.max(0,Math.min(1,drag.pan.y-(e.clientY-drag.y)/box.height*r.h/Math.max(1,src.height-r.h)))};};c.onpointerup=c.onpointercancel=()=>{drag=null;};
 $('#camera-zoom').oninput=e=>{zoom=Number(e.target.value);$('#camera-scale').textContent=zoom.toFixed(1)+'×';};$('#camera-reset').onclick=()=>{zoom=1;pan={x:.5,y:.5};$('#camera-zoom').value='1';$('#camera-scale').textContent='1.0×';};$('#camera-subject').onchange=e=>{mode=e.target.value;onMode(mode);$('#camera-reset').click();$('#photo-promise').hidden=mode!=='window';$('#camera-status').textContent='';};$('#camera-back').onclick=()=>{el.hidden=true;toolbar.close();onClose();};$('#camera-shoot').onclick=()=>{const photo=shoot(rect(),mode);$('#camera-status').textContent=photo?(photo.promise?'拍到了「'+photo.promise.name+'」，约定完成！照片已存进相册。':'拍好了，已放进这档的旅行相册。'):'没有保存成功，请重试。';};raf=requestAnimationFrame(draw);
 return{open(){onOpen();for(const o of $('#camera-subject').options)o.disabled=o.value!=='window'&&!hasCompanion();if(!hasCompanion())mode='window';$('#camera-subject').value=mode;onMode(mode);$('#photo-promise').hidden=mode!=='window';el.hidden=false;refreshPromise();toolbar.show();},get isOpen(){return !el.hidden;},dispose(){cancelAnimationFrame(raf);el.remove();}};
}
