import {cropRect} from './album.mjs?v=fg-aa26ce08d191440c';
export function createTravelCamera({source,shoot,onOpen}){
 const el=document.createElement('section');el.id='travel-camera';el.hidden=true;el.innerHTML='<header><button id="camera-back">收起</button><strong>窗景取景器</strong><button id="camera-shoot">拍下来</button></header><div class="camera-body"><p>拖动画面取景，风景会继续前进。</p><canvas id="camera-canvas" aria-label="拖动调整取景位置"></canvas><label>焦距 <input id="camera-zoom" aria-label="取景放大倍数" type="range" min="1" max="3" step=".05" value="1"><span id="camera-scale">1.0×</span></label><button id="camera-reset">复位取景</button><p id="camera-status" role="status"></p></div>';document.body.append(el);
 const $=s=>el.querySelector(s),c=$('#camera-canvas'),ctx=c.getContext('2d');let zoom=1,pan={x:.5,y:.5},drag=null,raf=0,last=0;
 function rect(){const src=source();return cropRect(src.width,src.height,zoom,pan);}
 function draw(now){raf=requestAnimationFrame(draw);if(el.hidden||document.hidden||now-last<50)return;last=now;const r=rect();c.width=900;c.height=600;ctx.drawImage(source(),r.x,r.y,r.w,r.h,0,0,900,600);ctx.strokeStyle='#ffffff75';ctx.lineWidth=1.2;for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(i*300,0);ctx.lineTo(i*300,600);ctx.moveTo(0,i*200);ctx.lineTo(900,i*200);ctx.stroke();}}
 c.onpointerdown=e=>{c.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,pan:{...pan}};};c.onpointermove=e=>{if(!drag)return;const box=c.getBoundingClientRect(),r=rect(),src=source();pan={x:Math.max(0,Math.min(1,drag.pan.x-(e.clientX-drag.x)/box.width*r.w/Math.max(1,src.width-r.w))),y:Math.max(0,Math.min(1,drag.pan.y-(e.clientY-drag.y)/box.height*r.h/Math.max(1,src.height-r.h)))};};c.onpointerup=c.onpointercancel=()=>{drag=null;};
 $('#camera-zoom').oninput=e=>{zoom=Number(e.target.value);$('#camera-scale').textContent=zoom.toFixed(1)+'×';};$('#camera-reset').onclick=()=>{zoom=1;pan={x:.5,y:.5};$('#camera-zoom').value='1';$('#camera-scale').textContent='1.0×';};$('#camera-back').onclick=()=>{el.hidden=true;};$('#camera-shoot').onclick=()=>{const photo=shoot(rect());$('#camera-status').textContent=photo?'拍好了，已放进这档的旅行相册。':'没有保存成功，请重试。';};raf=requestAnimationFrame(draw);
 return{open(){onOpen();el.hidden=false;},get isOpen(){return !el.hidden;},dispose(){cancelAnimationFrame(raf);el.remove();}};
}
