import test from 'node:test';import assert from 'node:assert/strict';
import {createPuzzle,drop,target} from './puzzle.mjs';
import {HANDOFF,inHandoff,cooperate,pendingPiece,cooperationMove,finishCooperation,cooperationContext} from './cooperation.mjs';
const desk=()=>({...createPuzzle('photo',12,3),mode:'together'});
test('递片只能一片一片接，保留同行者失误概率，真实落位后才记贡献',()=>{const p=desk();assert.ok(cooperate(p,'solve',7));assert.equal(cooperate(p,'solve',4),false);const m=cooperationMove(p,.25,()=>.99);assert.equal(m.id,7);assert.equal(m.correct,false);const ok=drop(p,m.id,m.x,m.y,'companion');finishCooperation(p,m.id,false,ok,'companion');assert.equal(pendingPiece(p),null);assert.equal(cooperationContext(p).companion,0);assert.equal(cooperationContext(p).last.matched,false);});
test('找片沿真实拖动递回，不代拼、不增加落手，等待用户接过',()=>{const p=desk();assert.ok(cooperate(p,'fetch',3));const m=cooperationMove(p,.9),q=p.pieces[3],t=target(p,3);assert.ok(m.delivery);Object.assign(q,{x:m.x,y:m.y});assert.ok(inHandoff(q.x+t.w/2,q.y+t.h/2));finishCooperation(p,3,true,false,'companion');assert.equal(p.moves,0);assert.equal(q.locked,false);assert.equal(cooperationMove(p,.9),null);const ok=drop(p,3,t.x,t.y);finishCooperation(p,3,false,ok,'you');assert.equal(cooperationContext(p).you,1);assert.equal(pendingPiece(p),null);assert.match(cooperationContext(p).last.kind,/接过/);});
test('最后一片留给你，明确递过去或看TA拼才由TA落手',()=>{const p=desk();for(let id=0;id<11;id++){const t=target(p,id);drop(p,id,t.x,t.y,'companion');}assert.equal(cooperationMove(p,.9),null);assert.equal(cooperationContext(p).lastPieceForYou,true);assert.ok(cooperate(p,'solve',11));assert.equal(cooperationMove(p,.9,()=>0).id,11);p.mode='watch';assert.equal(cooperationMove(p,.9,()=>0).id,11);});
test('新旧档及跨旅程恢复，已拼/错误碎片不可递，自己拼不接任务',()=>{const p=desk();assert.equal(cooperationContext(p).pending,null);assert.ok(cooperate(p,'fetch',2));const copy=JSON.parse(JSON.stringify(p));assert.deepEqual(cooperationMove(copy,.5),cooperationMove(p,.5));p.mode='self';assert.equal(cooperate(p,'solve',1),false);p.mode='together';p.cooperation=null;const t=target(p,2);drop(p,2,t.x,t.y);assert.equal(cooperate(p,'solve',2),false);assert.equal(cooperate(p,'solve',99),false);assert.equal(inHandoff(HANDOFF.x-1,HANDOFF.y),false);});

test('两次实际失败才递回求助，重进不中断、手动落片解除求助',()=>{const p=desk();for(let n=1;n<=2;n++){const m=cooperationMove(p,.25,()=>.99);const ok=drop(p,m.id,m.x,m.y,'companion');finishCooperation(p,m.id,false,ok,'companion');assert.equal(ok,false);if(n===1){assert.equal(pendingPiece(p),null);assert.equal(p.cooperation.failures[m.id],1);}else assert.equal(pendingPiece(p).kind,'help');}const copy=JSON.parse(JSON.stringify(p)),m=cooperationMove(copy,.25);assert.ok(m.delivery);finishCooperation(copy,m.id,true,false,'companion');assert.match(cooperationContext(copy).pending.action,/请你帮忙/);assert.equal(copy.moves,2);assert.equal(copy.pieces[m.id].locked,false);const t=target(copy,m.id),ok=drop(copy,m.id,t.x,t.y);finishCooperation(copy,m.id,false,ok,'you');assert.equal(pendingPiece(copy),null);assert.equal(cooperationContext(copy).you,1);});

test('分工限定同行者选片、找片送给用户一侧，完成自己的部分后等待，显式递片优先',async()=>{const {setDivision,assignedPieces,fetchPiece}=await import('./cooperation.mjs'),{isEdgePiece}=await import('./puzzle.mjs');const p=desk();setDivision(p,'you-edge');for(let i=0;i<10;i++){const m=cooperationMove(p,.9,()=>i/10);assert.equal(isEdgePiece(p,m.id),false);assert.equal(isEdgePiece(p,fetchPiece(p,.9,()=>i/10).id),true);}for(const id of assignedPieces(p,'companion')){const t=target(p,id);drop(p,id,t.x,t.y,'companion');}assert.equal(cooperationMove(p,.9),null);assert.ok(cooperate(p,'solve',0));assert.equal(cooperationMove(p,.9,()=>0).id,0);p.cooperation.pending=null;setDivision(p,'you-center');assert.equal(isEdgePiece(p,cooperationMove(p,.9,()=>0).id),true);assert.equal(fetchPiece(p,.9),null);assert.equal(setDivision(p,'bad'),false);});

test('成功不会触发求助、观看模式继续自行试；求助开口先记账且遵守45秒间隔',async()=>{const {claimHelpAnnouncement}=await import('./cooperation.mjs');const p=desk();const t=target(p,1);drop(p,1,t.x,t.y,'companion');finishCooperation(p,1,false,true,'companion');assert.equal(pendingPiece(p),null);p.mode='watch';for(let n=0;n<2;n++)finishCooperation(p,2,false,false,'companion');assert.equal(pendingPiece(p),null);p.mode='together';for(let n=0;n<2;n++)finishCooperation(p,2,false,false,'companion');assert.equal(claimHelpAnnouncement(p,100000,0),false);finishCooperation(p,2,true,false,'companion');assert.equal(claimHelpAnnouncement(p,100000,90000),false);assert.equal(claimHelpAnnouncement(p,150000,90000),true);const loaded=JSON.parse(JSON.stringify(p));assert.equal(claimHelpAnnouncement(loaded,250000,90000),false);});

test('明确递来的另一侧碎片优先，失败后也会再试一次再求助',async()=>{const {setDivision}=await import('./cooperation.mjs');const p=desk();setDivision(p,'you-edge');cooperate(p,'solve',0);for(let i=0;i<2;i++){const m=cooperationMove(p,.25,()=>.99);assert.equal(m.id,0);const ok=drop(p,0,m.x,m.y,'companion');finishCooperation(p,0,false,ok,'companion');}assert.equal(pendingPiece(p).kind,'help');});
