import {restState,isResting,changeRest,restContext} from './rest.mjs?v=fg-426a48697f4c439b';
import {makePromise,creditPhoto,promiseSummaries} from './photo-promise.mjs?v=fg-426a48697f4c439b';
import {createPassengers} from './passengers.mjs?v=fg-426a48697f4c439b';
import {photoPlan,photoLabel,exchangePhotos} from './photography.mjs?v=fg-426a48697f4c439b';
import {createTravelCamera} from './camera-view.mjs?v=fg-426a48697f4c439b';
import {removeAlbumItem} from './album.mjs?v=fg-426a48697f4c439b';
import {createPuzzleDesk} from './puzzle-view.mjs?v=fg-426a48697f4c439b';
import {createCarriageView} from '../../art/train-carriage/view.mjs?v=fg-426a48697f4c439b';
import {restoreTrip,travelEnvironment,travelContext,advanceTrip} from './travel.mjs?v=fg-426a48697f4c439b';
import {ROUTES,SEASONS,WEATHERS} from '../../art/train-carriage/scenery.mjs?v=fg-426a48697f4c439b';
const host=window.parent!==window&&window.parent.FairyGardenHostFor?.(window),status=document.querySelector('#status');
let cameraSubject='window',companionCamera=()=>{},passengers,cameraUI,desk,view,state,frame=0,last=0,saveAt=0,closed=false,saveFailed=false;
function flush(){if(!view||!state)return false;try{if(!host.save({...state},'train'))throw Error('没有保存成功');saveFailed=false;status.textContent='';return true;}catch(e){saveFailed=true;status.textContent='进度没有保存成功，请留在车上重试。';return false;}}
function sync(){const r=restState(state),has=!!host.companion?.()?.id;document.querySelector('#rest-controls').hidden=view.currentView!=='berths'||cameraUI?.isOpen||desk?.isOpen;document.querySelector('#rest-you').textContent=r.you?'我回桌边':'我躺下';document.querySelector('#rest-companion').textContent=r.companion?'TA回桌边':'TA休息';document.querySelector('#rest-companion').disabled=!has;document.querySelector('#rest-together').disabled=!has;document.querySelector('#rest-info').textContent=(r.you?'你在下铺休息':'你在桌边')+(has?(r.companion?' · TA在上铺休息':' · TA在桌边'):'');document.querySelector('#take-photo').textContent=isResting(state)?'起身拍照':'拍照';document.querySelector('#open-puzzle').textContent=isResting(state)?'起身拼图':'拼图';const pending=(state.companionPhotos||[]).length;document.querySelector('#open-album').textContent=pending?'相册 · '+pending:'相册';const env=travelEnvironment(state);view.scenery.set({...env,distance:state.distance,playing:false});view.syncLighting();if(!cameraUI?.isOpen||cameraSubject!=='window')view.render();const minute=Math.floor(state.minute),clock=String(Math.floor(minute/60)).padStart(2,'0')+':'+String(minute%60).padStart(2,'0');document.querySelector('#scene-info').textContent=`${SEASONS[env.season]} · ${WEATHERS[env.weather]} · ${clock}　${env.routeBlend>0?ROUTES[env.route]+' → '+ROUTES[env.nextRoute]:ROUTES[env.route]}`;}
function animate(now){frame=requestAnimationFrame(animate);if(closed||document.hidden){last=0;return;}if(last&&now-last<1000/30)return;const dt=last?Math.min(.1,(now-last)/1000):0;last=now;
 if(!saveFailed){state=advanceTrip(state,dt,view.scenery.destination.speedFactor);view.scenery.state.weatherTime+=dt;sync();passengers?.tick(now,dt,!cameraUI?.isOpen);companionCamera();saveAt+=dt;if(saveAt>=3){saveAt=0;flush();}}
}
try{if(!host)throw Error('请从小世界的列车入口进入。');state=restoreTrip(host.load().worlds?.train);view=await createCarriageView(document.querySelector('#stage'),{immersive:true});passengers=await createPassengers(view,host,document.querySelector('#stage'),()=>state);view.setView(isResting(state)?'berths':'table');view.setZoom(.72);sync();
 for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{try{if(b.dataset.view==='table')rise();view.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}catch(e){status.textContent=e.message;}};document.querySelector('[data-view='+view.currentView+']').setAttribute('aria-pressed','true');
 function setRest(who,lying){const before=state;state=changeRest(state,who,lying,!!host.companion?.()?.id);if(!flush()){state=before;throw Error('休息状态没有保存成功，请重试。');}passengers.tick(performance.now(),0,true);sync();}
 function rise(){if(isResting(state)){setRest('both',false);view.setView('table');}}
 for(const [id,who] of [['rest-you','you'],['rest-companion','companion']])document.querySelector('#'+id).onclick=()=>{try{setRest(who,!restState(state)[who]);}catch(e){status.textContent=e.message;}};document.querySelector('#rest-together').onclick=()=>{try{setRest('both',true);}catch(e){status.textContent=e.message;}};
 function capture(crop,plan=null,subject='window'){if(!plan&&isResting(state)){try{rise();}catch(e){status.textContent=e.message;return null;}}if(subject!=='window')view.render();const src=subject==='window'?view.scenery.canvas:view.renderer.domElement,c=document.createElement('canvas');c.width=900;c.height=600;const ctx=c.getContext('2d'),sw=Math.min(src.width,src.height*1.5),sh=sw/1.5,r=crop||{x:(src.width-sw)/2,y:(src.height-sh)/2,w:sw,h:sh};ctx.drawImage(src,r.x,r.y,r.w,r.h,0,0,900,600);const companion=host.companion?.(),environment=plan?.environment||travelContext(state),photo={id:'photo-'+crypto.randomUUID(),src:c.toDataURL('image/jpeg',.84),crop:r,environment,subject,label:photoLabel(environment,subject==='window'?plan?.subject:subject==='companion'?'车厢里的'+(companion?.name||'同行者'):'车厢合照'),photographer:plan?{role:'companion',id:companion.id,name:companion.name}:{role:'you'}};
 const before=state,credited=creditPhoto(state,photo,r,src.width,src.height);state=credited.s;Object.assign(photo,credited.photo);state=plan?{...state,companionPhotos:[...(state.companionPhotos||[]),photo],cameraLog:{key:plan.key,trip:plan.trip,count:plan.count,distance:plan.distance}}:{...state,photos:[...(state.photos||[]),photo]};if(!flush()){state=before;return null;}return photo;}
 companionCamera=()=>{const src=view.scenery.canvas,plan=photoPlan(state,host.companion?.(),src.width,src.height);if(plan)capture(plan.crop,plan);};

 cameraUI=createTravelCamera({host,source:mode=>mode==='window'?view.scenery.canvas:view.renderer.domElement,shoot:(crop,mode)=>capture(crop,null,mode),hasCompanion:()=>!!host.companion?.()?.id,onMode:mode=>{cameraSubject=mode;view.setPhotoView(mode);},onClose:()=>{cameraSubject='window';view.setPhotoView(null);},state:()=>state,onPromise:theme=>{const before=state;state=makePromise(state,theme,host.companion?.());if(!flush()){state=before;throw Error('约定没有存好，请重试。');}},onOpen:()=>{rise();view.setView('table');}});
 desk=createPuzzleDesk({state:()=>state,save:flush,capture,host,environment:()=>travelContext(state),onOpen:mode=>{if(mode!=='travel')rise();view.setView(isResting(state)?'berths':'table');},stage:document.querySelector('#stage')});
 document.querySelector('#open-chat').onclick=()=>desk.open('travel').catch(e=>{status.textContent=e.message;});
 document.querySelector('#open-puzzle').onclick=()=>desk.open().catch(e=>{status.textContent=e.message;});
 document.querySelector('#take-photo').onclick=()=>{try{cameraUI.open();}catch(e){status.textContent=e.message;}};
 document.querySelector('#open-album').onclick=()=>{if(flush())host.openAlbum?.();};
 window.TrainGame={desk,flush,speak:(lines,who)=>passengers?.speak(lines,who),passengers,chatContext:()=>({map:"carriage",activity:cameraUI?.isOpen?(cameraSubject==='window'?'拍摄窗景':cameraSubject==='companion'?'给同行者拍照':'拍两人合照'):desk?.isOpen&&desk?.activity==='travel'?(isResting(state)?'在卧铺边休息聊天':'看窗外聊天'):desk?.isOpen?'拼图桌边':'乘车看风景',rest:restContext(state,!!host.companion?.()?.id),environment:travelContext(state),photography:{promises:promiseSummaries(state,true).slice(-3),unopenedCount:(state.companionPhotos||[]).length,recentPhotos:[...(state.photos||[]),...(state.companionPhotos||[])].slice(-4).map(p=>({label:p.label,photographer:p.photographer?.role==='companion'?p.photographer.name:'对方',shared:!(state.companionPhotos||[]).some(x=>x.id===p.id)}))}}),editAlbum:action=>{const before=state;try{if(action.kind==='exchange')state=exchangePhotos(state);else if(action.kind==='delete')state=removeAlbumItem(state,action.id);else throw Error('未知操作');if(!flush())throw Error('相册没有保存成功');desk.refresh().catch(e=>{status.textContent=e.message;});return true;}catch(e){state=before;throw e;}},snapshot:()=>({...state}),get ready(){return !!view;}};host.ready?.();if(!flush())throw Error('进度没有保存成功，请返回重试。');frame=requestAnimationFrame(animate);
}catch(e){status.textContent=e.message;}
window.addEventListener('visibilitychange',()=>{last=0;if(document.hidden)flush();});
window.addEventListener('pagehide',()=>{closed=true;cancelAnimationFrame(frame);flush();cameraUI?.dispose();desk?.dispose();passengers?.dispose();view?.dispose();});
