import {makePuzzleMemory} from './puzzle-memory.mjs?v=fg-62c9f6e29466f4a7';
import {HANDOFF,inHandoff,pendingPiece,cooperate,cooperationMove,finishCooperation,cooperationContext,DIVISIONS,divisionOf,setDivision,assignedPieces,fetchPiece,claimHelpAnnouncement} from './cooperation.mjs?v=fg-62c9f6e29466f4a7';
import {panelHeader} from './panel-header.mjs?v=fg-62c9f6e29466f4a7';
import {photographerLabel,addArtwork} from './album.mjs?v=fg-62c9f6e29466f4a7';
import {LEVELS,BOARD,createPuzzle,validPuzzle,outlines,target,drop,skillOf} from './puzzle.mjs?v=fg-62c9f6e29466f4a7';
export function createPuzzleDesk({state,save,capture,host,onOpen,environment,stage}){
 const panel=document.createElement('section');panel.id='puzzle-desk';panel.hidden=true;panel.innerHTML=`<header><button id="desk-back">收起</button><strong id="desk-title">旅行拼图</strong><button id="desk-album">相册</button><button id="desk-camera">拍窗景</button></header><div class="desk-body"><figure id="travel-window" hidden><figcaption id="travel-window-caption"></figcaption></figure><details id="desk-setup"><summary><span id="desk-setup-label">选照片和片数</span><span class="setup-hint">改</span></summary><div class="desk-controls"><label>照片 <select id="desk-photo" aria-label="选择照片"></select></label><label>片数 <select id="desk-count" aria-label="拼图片数">${LEVELS.map(x=>`<option value="${x.count}">${x.count} 片</option>`).join('')}</select></label><button id="desk-new">开始拼图</button></div><div class="desk-controls"><button data-mode="self">自己拼</button><button data-mode="together">一起拼</button><button data-mode="watch">看 TA 拼</button></div></details><p id="desk-progress" role="status"></p><p id="desk-error" role="alert"></p><div id="desk-cooperation" class="desk-controls" hidden><button id="desk-fetch">请 TA 递一片</button><span id="desk-cooperation-status" role="status"></span></div><details id="desk-division" hidden><summary>分工 · <span id="desk-division-label"></span></summary><div class="desk-controls"><label>分工 <select id="desk-division-select" aria-label="拼图分工">${DIVISIONS.map(d=>`<option value="${d.id}">${d.label}</option>`).join('')}</select></label><button id="desk-swap">交换分工</button></div></details><button id="desk-keep" hidden>装框收藏</button><div class="puzzle-viewport"><canvas id="puzzle-canvas" aria-label="拖动拼图碎片，双指缩放，拖动空白移动桌面"></canvas><div class="zoom-controls"><button id="desk-reference" aria-pressed="false">原图</button><button id="zoom-out" aria-label="缩小拼图">−</button><button id="zoom-fit">全桌</button><button id="zoom-in" aria-label="放大拼图">＋</button></div><img id="puzzle-reference" alt="这次拼图的原照片" hidden></div><button id="desk-peer" type="button" aria-label="打开聊天"><span id="desk-peer-say"></span><span id="desk-peer-face"></span></button></div><div id="desk-dock"><div class="dock-head"><strong id="dock-name">聊天</strong><button id="dock-close" type="button">收起</button></div><div id="desk-chat" aria-live="polite"></div><div class="desk-footer"><form id="desk-form"><input id="desk-message" aria-label="对同行者说话" placeholder="边拼边聊…" maxlength="4000"><button id="desk-send">发送</button></form></div></div>`;document.body.append(panel);
 const toolbar=panelHeader(host,panel);const $=s=>panel.querySelector(s),canvas=$('#puzzle-canvas'),ctx=canvas.getContext('2d'),photoSelect=$('#desk-photo'),countSelect=$('#desk-count'),progress=$('#desk-progress'),error=$('#desk-error'),reference=$('#puzzle-reference'),chat=$('#desk-chat');
 let puzzle=null,image=null,paths=[],z=[],drag=null,bot=null,wait=2,zoom=1,pan={x:0,y:0},scale=1,last=0,raf=0,showReference=false,speaking=false,lastTalk=0,opened=false,pointers=new Map(),pinch=null,skill=skillOf(host.companion?.()?.id||'solo'),restart=false,activity='puzzle',scrollPositions={},helpRetryAfter=0;
 const data=()=>state();
 // 聊天收成右上角一个头像+最后一句（她 2026-09-25：「拼图直接全屏，角色头像和气泡在右上角，点开可以开个聊天框」
 //   「普通聊天现在点开也没有地方折叠」）。拼图和旅途聊天共用这一个坞：拼图默认收着，聊天默认开着，两边都能收能开。
 function setDock(open){panel.dataset.dock=open?'open':'closed';if(open){$('#desk-peer').classList.remove('unread');chat.scrollTop=chat.scrollHeight;}}
 function peerFace(){const c=host.companion?.()||null,face=$('#desk-peer-face');face.replaceChildren();$('#desk-peer').hidden=!c;if(!c)return;$('#dock-name').textContent=c.name||'聊天';if(c.avatar){const img=document.createElement('img');img.src=c.avatar;img.alt='';face.append(img);}else face.textContent=String(c.name||'TA').slice(0,1);}
 $('#desk-peer').onclick=()=>setDock(true);$('#dock-close').onclick=()=>setDock(false);const currentPhoto=()=>data().photos?.find(p=>p.id===puzzle?.photoId);const hasCompanion=()=>!!host.companion?.()?.id;
 function persist(){if(puzzle)data().puzzle=puzzle;const ok=save();if(!ok)error.textContent='这次进度还没存好，请留在车上重试。';return ok;}
 function resetCamera(){zoom=1;pan={x:0,y:0};}
 function photos(){const selected=photoSelect.value||data().puzzle?.photoId;photoSelect.replaceChildren();for(const p of data().photos||[]){const o=document.createElement('option');o.value=p.id;o.textContent=photographerLabel(p)+' · '+p.label;photoSelect.append(o);}if(selected&&[...photoSelect.options].some(x=>x.value===selected))photoSelect.value=selected;$('#desk-new').disabled=!photoSelect.value;}
 async function loadPuzzle(){puzzle=validPuzzle(data().puzzle)?data().puzzle:null;bot=null;drag=null;wait=2;paths=puzzle?outlines(puzzle).map(s=>new Path2D(s)):[];z=puzzle?puzzle.pieces.map(x=>x.id):[];image=null;resetCamera();if(!puzzle){$('#desk-cooperation').hidden=true;$('#desk-division').hidden=true;$('#desk-keep').hidden=true;reference.removeAttribute('src');reference.hidden=true;showReference=false;$('#desk-reference').setAttribute('aria-pressed','false');progress.textContent='选一张旅途照片和片数，就能开始。';$('#desk-setup').open=true;$('#desk-setup-label').textContent='选照片和片数';return;}countSelect.value=puzzle.count;photoSelect.value=puzzle.photoId;const photo=currentPhoto();if(photo){const img=new Image();img.src=photo.src;await img.decode();if(puzzle?.photoId===photo.id){image=img;reference.src=photo.src;}}update();}
 function update(){if(!puzzle){$('#desk-cooperation').hidden=true;$('#desk-division').hidden=true;return;}$('#desk-setup-label').textContent=puzzle.count+' 片 · '+({self:'自己拼',together:'一起拼',watch:'看 TA 拼'}[puzzle.mode]||'自己拼')+(showReference?' · 原图':'');const coop=cooperationContext(puzzle);$('#desk-cooperation').hidden=puzzle.mode!=='together'||!hasCompanion();$('#desk-division').hidden=$('#desk-cooperation').hidden;$('#desk-division-label').textContent=divisionOf(puzzle).label;$('#desk-division-select').value=divisionOf(puzzle).id;$('#desk-swap').disabled=divisionOf(puzzle).id==='free'||!!puzzle.completed;$('#desk-division-select').disabled=!!puzzle.completed;$('#desk-fetch').disabled=!!coop.pending||!!puzzle.completed||!assignedPieces(puzzle,'you').length;$('#desk-cooperation-status').textContent=coop.pending?('第 '+coop.pending.piece+' 片 · '+coop.pending.action):coop.lastPieceForYou?'最后一片留给你':puzzle.completed?'你们拼好了':!coop.companionRemaining?'TA 的部分已拼完，等你或交换分工':'把碎片拖到下方递给 TA';$('#desk-keep').hidden=!puzzle.completed;$('#desk-keep').textContent=(data().artworks||[]).some(a=>a.puzzleKey===puzzle.photoId+':'+puzzle.seed)?'已装框 · 打开相册':'装框收藏';const n=puzzle.pieces.filter(x=>x.locked).length;progress.textContent=puzzle.completed?'拼好了 · '+puzzle.count+' 片 · '+puzzle.moves+' 次落手':`${n} / ${puzzle.count} 片　${puzzle.mode==='watch'?'正在看 '+(host.companion?.()?.name||'TA')+' 拼':puzzle.mode==='together'?'你们一起拼':'拖动碎片 · 双指放大'}`;
 progress.textContent+='　你 '+coop.you+' · TA '+coop.companion;
 for(const b of panel.querySelectorAll('[data-mode]')){b.setAttribute('aria-pressed',String(b.dataset.mode===puzzle.mode));b.disabled=!hasCompanion()&&b.dataset.mode!=='self';}}
 function bubble(text,who){const el=document.createElement('p');el.className=who==='you'?'you':'companion';el.textContent=text;chat.append(el);chat.scrollTop=chat.scrollHeight;if(who!=='you'){$('#desk-peer-say').textContent=text;if(panel.dataset.dock!=='open')$('#desk-peer').classList.add('unread');}}
 async function talk(text,auto=false){if(speaking)return;/* 列车设置里「拼图时 TA 自己开口」关了，就只在她说话时回 */if(auto){try{if(localStorage.getItem('x_trainAutoTalk')==='0')return;}catch(e){}}if(!hasCompanion()){error.textContent='这一档还没有同行者，可以从列车设置选同行者开房间。';return;}speaking=true;lastTalk=Date.now();$('#desk-send').disabled=true;$('#desk-send').textContent='回复中';error.textContent='';try{const result=await host.chat(text,activity==='travel'?null:{count:puzzle?.count||0,placed:puzzle?.pieces.filter(x=>x.locked).length||0,mode:puzzle?.mode||'self',complete:!!puzzle?.completed,skill,photo:currentPhoto()?.label||'',lastMove:data().puzzleLastMove||null,cooperation:puzzle?cooperationContext(puzzle):null},auto);if(!auto)bubble(text,'you');for(const s of result.parts||[result.reply])bubble(s,'companion');return true;}catch(e){error.textContent=e.message||'这句没有发出去，可以再试一次。';}finally{speaking=false;$('#desk-send').disabled=false;$('#desk-send').textContent='发送';}}
 $('#desk-album').onclick=()=>{if(persist())host.openAlbum?.();};
 $('#desk-keep').onclick=()=>{if(!puzzle?.completed||!image)return;const puzzleKey=puzzle.photoId+':'+puzzle.seed;if((data().artworks||[]).some(a=>a.puzzleKey===puzzleKey)){host.openAlbum?.();return;}
 const c=document.createElement('canvas');c.width=960;c.height=690;const x=c.getContext('2d');x.fillStyle='#765b3e';x.fillRect(0,0,960,690);x.fillStyle='#f3ecd9';x.fillRect(10,10,940,670);x.drawImage(image,30,30,900,600);x.save();const s=900/BOARD.w;x.translate(30-BOARD.x*s,30-BOARD.y*s);x.scale(s,s);x.strokeStyle='rgba(255,255,255,.38)';x.lineWidth=.8;paths.forEach(p=>x.stroke(p));x.restore();x.fillStyle='#665b46';x.font='16px system-ui';x.fillText(puzzle.count+' 片 · '+(currentPhoto()?.label||'旅行拼图'),30,658);
 const art={id:'art-'+crypto.randomUUID(),at:Date.now(),puzzleKey,photoId:puzzle.photoId,src:c.toDataURL('image/jpeg',.9),label:puzzle.count+'片拼图 · '+(currentPhoto()?.label||'窗景'),count:puzzle.count,moves:puzzle.moves,seed:puzzle.seed,day:data().day,kind:'puzzle',memory:makePuzzleMemory(puzzle,currentPhoto(),host.companion?.(),data().day)};
 const previous=data().artworks;data().artworks=addArtwork(data(),art).artworks;if(save()){error.textContent='已装框。在相册里点开这一幅，可以在背面各留一句话，也可以带回庭院。';update();}else{data().artworks=previous;error.textContent='成品没有保存成功，请重试。';}};
 $('#desk-form').onsubmit=e=>{e.preventDefault();const input=$('#desk-message'),text=input.value.trim();if(text&&!speaking)talk(text).then(ok=>{if(ok&&input.value.trim()===text)input.value='';});};
 $('#desk-back').onclick=()=>{if(persist()){scrollPositions[activity]=chat.scrollTop;opened=false;panel.hidden=true;toolbar.close();if(stage)document.body.prepend(stage);bot=null;drag=null;pointers.clear();}};
 $('#desk-camera').onclick=()=>{if(!persist())return;const p=capture();if(p){photos();photoSelect.value=p.id;$('#desk-new').disabled=false;error.textContent='拍好了，选片数后开始。';}};
 $('#desk-new').onclick=async()=>{if(!photoSelect.value)return;if(puzzle&&!puzzle.completed&&!restart){restart=true;$('#desk-new').textContent='确认重开';error.textContent='重开会替换这桌未完成的进度，原照片保留。再点一次确认。';return;}restart=false;$('#desk-new').textContent='开始拼图';error.textContent='';data().puzzle=createPuzzle(photoSelect.value,Number(countSelect.value));if(persistNew()){$('#desk-setup').open=false;await loadPuzzle();}};
 function persistNew(){const next=data().puzzle;if(save())return true;data().puzzle=puzzle;error.textContent='新拼图没有存好，请重试。';return false;}
 for(const b of panel.querySelectorAll('[data-mode]'))b.onclick=()=>{if(!puzzle){error.textContent='先选一张照片，开始一桌拼图。';return;}if(b.dataset.mode!=='self'&&!hasCompanion()){error.textContent='这一档还没有同行者。';return;}if(puzzle.mode===b.dataset.mode)return;if(!saveInteraction(()=>{puzzle.mode=b.dataset.mode;if(puzzle.cooperation)puzzle.cooperation={...puzzle.cooperation,pending:null,retry:null,retryGiven:false};}))return;bot=null;drag=null;wait=1;if(puzzle.mode!=='self'&&!puzzle.completed)talk('对方选择了'+(puzzle.mode==='watch'?'看你拼这桌拼图':'和你一起拼这桌拼图')+'。',true);};
 function saveInteraction(change){const before=structuredClone(puzzle);change();if(!persist()){puzzle=before;data().puzzle=puzzle;update();return false;}update();return true;}
 $('#desk-fetch').onclick=()=>{if(!puzzle||!hasCompanion()||pendingPiece(puzzle))return;const move=fetchPiece(puzzle,skill);if(!move)return;if(saveInteraction(()=>cooperate(puzzle,'fetch',move.id))){bot=null;wait=0;}};
 function changeDivision(id){if(!puzzle||!hasCompanion())return;if(saveInteraction(()=>setDivision(puzzle,id))){bot=null;wait=1;}}
 $('#desk-division-select').onchange=e=>changeDivision(e.target.value);
 $('#desk-swap').onclick=()=>changeDivision(divisionOf(puzzle).id==='you-edge'?'you-center':'you-edge');
 function announceHelp(){const pending=pendingPiece(puzzle),now=Date.now();if(speaking||now<helpRetryAfter||now-lastTalk<45000||pending?.kind!=='ready'||pending.reason!=='help'||pending.announced)return;helpRetryAfter=now+45000;let claimed=false;if(saveInteraction(()=>{claimed=claimHelpAnnouncement(puzzle,now,lastTalk);})&&claimed)talk('你刚把连续两次未拼上的碎片递到对方手边，请对方帮忙。按你的性格自然开口。',true);}
 $('#desk-reference').onclick=()=>{showReference=!showReference;reference.hidden=!showReference;$('#desk-reference').setAttribute('aria-pressed',String(showReference));};
 $('#zoom-in').onclick=()=>{zoom=Math.min(3.5,zoom*1.3);};$('#zoom-out').onclick=()=>{zoom=Math.max(1,zoom/1.3);};$('#zoom-fit').onclick=resetCamera;
 function point(e){const rect=canvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};}
 function transform(){const rect=canvas.getBoundingClientRect();scale=Math.min(rect.width/1000,rect.height/1320);return{s:scale*zoom,x:(rect.width-1000*scale*zoom)/2+pan.x,y:(rect.height-1320*scale*zoom)/2+pan.y};}
 function world(pt){const t=transform();return{x:(pt.x-t.x)/t.s,y:(pt.y-t.y)/t.s};}
 function hit(pt){if(!puzzle)return null;for(const id of [...z].reverse()){const q=puzzle.pieces[id],t=target(puzzle,id);if(!q.locked&&ctx.isPointInPath(paths[id],pt.x-q.x+t.x,pt.y-q.y+t.y))return q;}return null;}
 canvas.onpointerdown=e=>{if(!puzzle)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const pt=point(e);pointers.set(e.pointerId,pt);if(pointers.size===2){const a=[...pointers.values()];pinch={distance:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom};drag=null;return;}const p=world(pt),q=puzzle.mode==='watch'?null:hit(p);if(q){if(bot?.id===q.id)bot=null;drag={id:q.id,dx:p.x-q.x,dy:p.y-q.y};z=z.filter(id=>id!==q.id).concat(q.id);}else drag={pan:true,start:pt,x:pan.x,y:pan.y};};
 canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const pt=point(e);pointers.set(e.pointerId,pt);if(pinch&&pointers.size>=2){const a=[...pointers.values()];zoom=Math.max(1,Math.min(3.5,pinch.zoom*Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)/Math.max(1,pinch.distance)));return;}if(!drag)return;if(drag.pan){pan.x=drag.x+pt.x-drag.start.x;pan.y=drag.y+pt.y-drag.start.y;}else{const q=puzzle.pieces[drag.id],p=world(pt);q.x=p.x-drag.dx;q.y=p.y-drag.dy;}};
 function release(e){pointers.delete(e.pointerId);if(drag&&!drag.pan&&puzzle){const q=puzzle.pieces[drag.id],t=target(puzzle,q.id);if(e.type!=='pointercancel'&&puzzle.mode==='together'&&hasCompanion()&&inHandoff(q.x+t.w/2,q.y+t.h/2)&&!pendingPiece(puzzle)){if(saveInteraction(()=>cooperate(puzzle,'solve',q.id))){bot=null;wait=0;}}else settle(q.id,q.x,q.y,'you');}drag=null;pinch=null;}
 canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(1,Math.min(3.5,zoom*(e.deltaY<0?1.1:.9)));};
 function settle(id,x,y,who){const was=puzzle.completed,before=structuredClone(puzzle),previous=data().puzzleLastMove,ok=drop(puzzle,id,x,y,who);finishCooperation(puzzle,id,false,ok,who);data().puzzleLastMove={by:who,piece:id+1,matched:ok};if(!persist()){puzzle=before;data().puzzle=puzzle;data().puzzleLastMove=previous;update();return;}update();if(hasCompanion()&&puzzle.mode!=='self'){if(!was&&puzzle.completed)talk('这桌拼图刚刚拼好了。',true);else if(ok&&Date.now()-lastTalk>45000&&puzzle.pieces.filter(q=>q.locked).length%Math.ceil(puzzle.count/4)===0)talk('你们继续拼了一会儿，看看实际进度，按你的性格自然接一句。',true);}}
 function paint(now){raf=requestAnimationFrame(paint);if(!opened||document.hidden){last=0;return;}if(last&&now-last<1000/30)return;const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(activity==='travel'){const env=environment();$('#travel-window-caption').textContent=`${env.season} · ${env.weather} · ${env.time}　${env.transition?env.transition.from+' → '+env.transition.to:env.scenery} · ${env.passing}`;return;}const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const t=transform();ctx.translate(t.x,t.y);ctx.scale(t.s,t.s);ctx.fillStyle='#e9e2cf';ctx.fillRect(BOARD.x-9,BOARD.y-9,BOARD.w+18,BOARD.h+18);ctx.fillStyle='#c7c4b2';ctx.fillRect(BOARD.x,BOARD.y,BOARD.w,BOARD.h);ctx.fillStyle='#7b715e';ctx.font='23px system-ui';ctx.fillText('散片区',100,665);
 if(!puzzle||!image){ctx.setTransform(1,0,0,1,0,0);return;}
 if(puzzle.mode!=='self'&&!puzzle.completed&&hasCompanion()&&(!drag||drag.pan||bot&&drag.id!==bot.id)){if(bot&&!bot.delivery&&cooperationContext(puzzle).lastPieceForYou){const q=puzzle.pieces[bot.id];q.x=bot.fromX;q.y=bot.fromY;bot=null;update();}if(bot){bot.elapsed+=dt;const q=puzzle.pieces[bot.id],u=Math.min(1,bot.elapsed/bot.duration),ease=u*u*(3-2*u);q.x=bot.fromX+(bot.x-bot.fromX)*ease;q.y=bot.fromY+(bot.y-bot.fromY)*ease-Math.sin(u*Math.PI)*20;if(u===1){const move=bot;bot=null;if(move.delivery){saveInteraction(()=>finishCooperation(puzzle,move.id,true,false,'companion'));}else settle(move.id,move.x,move.y,'companion');wait=move.wait;}}else{wait-=dt;if(wait<=0){const m=cooperationMove(puzzle,skill);if(m){const q=puzzle.pieces[m.id];bot={...m,elapsed:0,fromX:q.x,fromY:q.y};z=z.filter(id=>id!==m.id).concat(m.id);}}}}
 if(puzzle.mode==='together'&&hasCompanion()){ctx.fillStyle='#e8eddbc9';ctx.fillRect(HANDOFF.x,HANDOFF.y,HANDOFF.w,HANDOFF.h);ctx.fillStyle='#344936';ctx.font='22px system-ui';ctx.fillText(pendingPiece(puzzle)?.kind==='ready'?'TA 递来的一片 · 拖走试试':'递给 TA · 把碎片拖到这里',HANDOFF.x+18,HANDOFF.y+57);}
 if(puzzle.mode==='together'&&hasCompanion())announceHelp();
 const ordered=[...z.filter(id=>puzzle.pieces[id].locked),...z.filter(id=>!puzzle.pieces[id].locked)];for(const id of ordered){const q=puzzle.pieces[id],targetAt=target(puzzle,id);ctx.save();ctx.translate(q.x-targetAt.x,q.y-targetAt.y);ctx.save();ctx.clip(paths[id]);ctx.drawImage(image,BOARD.x,BOARD.y,BOARD.w,BOARD.h);ctx.restore();ctx.strokeStyle=q.locked?'rgba(255,255,255,.22)':'#fff5df';ctx.lineWidth=q.locked?1.2:2.5;ctx.stroke(paths[id]);ctx.restore();}
 if(bot){const q=puzzle.pieces[bot.id],targetAt=target(puzzle,q.id);ctx.beginPath();ctx.arc(q.x+targetAt.w*.55,q.y+targetAt.h*.55,13,0,Math.PI*2);ctx.fillStyle='#516b59';ctx.fill();ctx.fillStyle='#263d2c';ctx.font='bold 22px system-ui';ctx.fillText(host.companion?.()?.name||'TA',q.x+targetAt.w*.55+20,q.y+targetAt.h*.55);}
 ctx.setTransform(1,0,0,1,0,0);
 }
 raf=requestAnimationFrame(paint);
 return{async refresh(){photos();await loadPuzzle();},async open(mode='puzzle'){if(opened)scrollPositions[activity]=chat.scrollTop;activity=mode==='travel'?'travel':'puzzle';onOpen(activity);opened=true;panel.hidden=false;panel.dataset.activity=activity;$('#desk-title').textContent=activity==='travel'?'旅途聊天':'旅行拼图';toolbar.show();$('#travel-window').hidden=activity!=='travel';if(stage){if(activity==='travel')$('#travel-window').prepend(stage);else if(stage.parentNode!==document.body)document.body.prepend(stage);}$('#desk-message').placeholder=activity==='travel'?'一起看风景，聊点什么…':'边拼边聊…';photos();chat.replaceChildren();for(const m of host.history?.()||[])bubble(m.content,m.role==='user'?'you':'companion');($('#travel-window')&&activity==='travel'?$('#travel-window'):$('.puzzle-viewport')).append($('#desk-peer'));peerFace();setDock(activity==='travel');$('#desk-peer').classList.remove('unread');chat.scrollTop=scrollPositions[activity]??chat.scrollHeight;await loadPuzzle();},flush(){return !puzzle||persist();},get isOpen(){return opened;},get activity(){return activity;},dispose(){cancelAnimationFrame(raf);panel.remove();},debug(){return{puzzle,camera:transform(),companionMove:bot?{id:bot.id,delivery:!!bot.delivery}:null};}};
}
