import {photographerLabel,addArtwork} from './album.mjs?v=fg-dc9ff4745fd4acb8';
import {LEVELS,BOARD,createPuzzle,validPuzzle,outlines,target,drop,nextCompanionMove,skillOf} from './puzzle.mjs?v=fg-dc9ff4745fd4acb8';
export function createPuzzleDesk({state,save,capture,host,onOpen,environment,stage}){
 const panel=document.createElement('section');panel.id='puzzle-desk';panel.hidden=true;panel.innerHTML=`<header><button id="desk-back">收起</button><strong id="desk-title">旅行拼图</strong><button id="desk-album">相册</button><button id="desk-camera">拍窗景</button></header><div class="desk-body"><figure id="travel-window" hidden><figcaption id="travel-window-caption"></figcaption></figure><div class="desk-controls"><label>照片 <select id="desk-photo" aria-label="选择照片"></select></label><label>片数 <select id="desk-count" aria-label="拼图片数">${LEVELS.map(x=>`<option value="${x.count}">${x.count} 片</option>`).join('')}</select></label><button id="desk-new">开始拼图</button></div><div class="desk-controls"><button data-mode="self">自己拼</button><button data-mode="together">一起拼</button><button data-mode="watch">看 TA 拼</button><button id="desk-reference" aria-pressed="false">原图</button></div><p id="desk-progress" role="status"></p><button id="desk-keep" hidden>装框收藏</button><div class="puzzle-viewport"><canvas id="puzzle-canvas" aria-label="拖动拼图碎片，双指缩放，拖动空白移动桌面"></canvas><div class="zoom-controls"><button id="zoom-out" aria-label="缩小拼图">−</button><button id="zoom-fit">全桌</button><button id="zoom-in" aria-label="放大拼图">＋</button></div><img id="puzzle-reference" alt="这次拼图的原照片" hidden></div><div id="desk-chat" aria-live="polite"></div><form id="desk-form"><input id="desk-message" aria-label="对同行者说话" placeholder="边拼边聊…" maxlength="4000"><button id="desk-send">发送</button></form><p id="desk-error" role="alert"></p></div>`;document.body.append(panel);
 const $=s=>panel.querySelector(s),canvas=$('#puzzle-canvas'),ctx=canvas.getContext('2d'),photoSelect=$('#desk-photo'),countSelect=$('#desk-count'),progress=$('#desk-progress'),error=$('#desk-error'),reference=$('#puzzle-reference'),chat=$('#desk-chat');
 let puzzle=null,image=null,paths=[],z=[],drag=null,bot=null,wait=2,zoom=1,pan={x:0,y:0},scale=1,last=0,raf=0,showReference=false,speaking=false,lastTalk=0,opened=false,pointers=new Map(),pinch=null,skill=skillOf(host.companion?.()?.id||'solo'),restart=false,activity='puzzle',scrollPositions={};
 const data=()=>state();const currentPhoto=()=>data().photos?.find(p=>p.id===puzzle?.photoId);const hasCompanion=()=>!!host.companion?.()?.id;
 function persist(){if(puzzle)data().puzzle=puzzle;const ok=save();if(!ok)error.textContent='这次进度还没存好，请留在车上重试。';return ok;}
 function resetCamera(){zoom=1;pan={x:0,y:0};}
 function photos(){const selected=photoSelect.value||data().puzzle?.photoId;photoSelect.replaceChildren();for(const p of data().photos||[]){const o=document.createElement('option');o.value=p.id;o.textContent=photographerLabel(p)+' · '+p.label;photoSelect.append(o);}if(selected&&[...photoSelect.options].some(x=>x.value===selected))photoSelect.value=selected;$('#desk-new').disabled=!photoSelect.value;}
 async function loadPuzzle(){puzzle=validPuzzle(data().puzzle)?data().puzzle:null;bot=null;drag=null;wait=2;paths=puzzle?outlines(puzzle).map(s=>new Path2D(s)):[];z=puzzle?puzzle.pieces.map(x=>x.id):[];image=null;resetCamera();if(!puzzle){$('#desk-keep').hidden=true;reference.removeAttribute('src');reference.hidden=true;showReference=false;$('#desk-reference').setAttribute('aria-pressed','false');progress.textContent='选一张旅途照片和片数，就能开始。';return;}countSelect.value=puzzle.count;photoSelect.value=puzzle.photoId;const photo=currentPhoto();if(photo){const img=new Image();img.src=photo.src;await img.decode();if(puzzle?.photoId===photo.id){image=img;reference.src=photo.src;}}update();}
 function update(){if(!puzzle)return;$('#desk-keep').hidden=!puzzle.completed;$('#desk-keep').textContent=(data().artworks||[]).some(a=>a.puzzleKey===puzzle.photoId+':'+puzzle.seed)?'已装框 · 打开相册':'装框收藏';const n=puzzle.pieces.filter(x=>x.locked).length;progress.textContent=puzzle.completed?'拼好了 · '+puzzle.count+' 片 · '+puzzle.moves+' 次落手':`${n} / ${puzzle.count} 片　${puzzle.mode==='watch'?'正在看 '+(host.companion?.()?.name||'TA')+' 拼':puzzle.mode==='together'?'你们一起拼':'拖动碎片 · 双指放大'}`;
 for(const b of panel.querySelectorAll('[data-mode]')){b.setAttribute('aria-pressed',String(b.dataset.mode===puzzle.mode));b.disabled=!hasCompanion()&&b.dataset.mode!=='self';}}
 function bubble(text,who){const el=document.createElement('p');el.className=who==='you'?'you':'companion';el.textContent=text;chat.append(el);chat.scrollTop=chat.scrollHeight;}
 async function talk(text,auto=false){if(speaking)return;if(!hasCompanion()){error.textContent='这一档还没有同行者，可以从列车设置选同行者开房间。';return;}speaking=true;lastTalk=Date.now();$('#desk-send').disabled=true;$('#desk-send').textContent='回复中';error.textContent='';try{const result=await host.chat(text,activity==='travel'?null:{count:puzzle?.count||0,placed:puzzle?.pieces.filter(x=>x.locked).length||0,mode:puzzle?.mode||'self',complete:!!puzzle?.completed,skill,photo:currentPhoto()?.label||'',lastMove:data().puzzleLastMove||null},auto);if(!auto)bubble(text,'you');for(const s of result.parts||[result.reply])bubble(s,'companion');return true;}catch(e){error.textContent=e.message||'这句没有发出去，可以再试一次。';}finally{speaking=false;$('#desk-send').disabled=false;$('#desk-send').textContent='发送';}}
 $('#desk-album').onclick=()=>{if(persist())host.openAlbum?.();};
 $('#desk-keep').onclick=()=>{if(!puzzle?.completed||!image)return;const puzzleKey=puzzle.photoId+':'+puzzle.seed;if((data().artworks||[]).some(a=>a.puzzleKey===puzzleKey)){host.openAlbum?.();return;}
 const c=document.createElement('canvas');c.width=960;c.height=690;const x=c.getContext('2d');x.fillStyle='#765b3e';x.fillRect(0,0,960,690);x.fillStyle='#f3ecd9';x.fillRect(10,10,940,670);x.drawImage(image,30,30,900,600);x.save();const s=900/BOARD.w;x.translate(30-BOARD.x*s,30-BOARD.y*s);x.scale(s,s);x.strokeStyle='rgba(255,255,255,.38)';x.lineWidth=.8;paths.forEach(p=>x.stroke(p));x.restore();x.fillStyle='#665b46';x.font='16px system-ui';x.fillText(puzzle.count+' 片 · '+(currentPhoto()?.label||'旅行拼图'),30,658);
 const art={id:'art-'+crypto.randomUUID(),puzzleKey,photoId:puzzle.photoId,src:c.toDataURL('image/jpeg',.9),label:puzzle.count+'片拼图 · '+(currentPhoto()?.label||'窗景'),count:puzzle.count,moves:puzzle.moves,seed:puzzle.seed,day:data().day,kind:'puzzle'};
 const previous=data().artworks;data().artworks=addArtwork(data(),art).artworks;if(save()){error.textContent='已装框。相册里可以导出，也可以带回庭院。';update();}else{data().artworks=previous;error.textContent='成品没有保存成功，请重试。';}};
 $('#desk-form').onsubmit=e=>{e.preventDefault();const input=$('#desk-message'),text=input.value.trim();if(text&&!speaking)talk(text).then(ok=>{if(ok&&input.value.trim()===text)input.value='';});};
 $('#desk-back').onclick=()=>{if(persist()){scrollPositions[activity]=chat.scrollTop;opened=false;panel.hidden=true;if(stage)document.body.prepend(stage);bot=null;drag=null;pointers.clear();}};
 $('#desk-camera').onclick=()=>{if(!persist())return;const p=capture();if(p){photos();photoSelect.value=p.id;$('#desk-new').disabled=false;error.textContent='拍好了，选片数后开始。';}};
 $('#desk-new').onclick=async()=>{if(!photoSelect.value)return;if(puzzle&&!puzzle.completed&&!restart){restart=true;$('#desk-new').textContent='确认重开';error.textContent='重开会替换这桌未完成的进度，原照片保留。再点一次确认。';return;}restart=false;$('#desk-new').textContent='开始拼图';error.textContent='';data().puzzle=createPuzzle(photoSelect.value,Number(countSelect.value));if(persistNew())await loadPuzzle();};
 function persistNew(){const next=data().puzzle;if(save())return true;data().puzzle=puzzle;error.textContent='新拼图没有存好，请重试。';return false;}
 for(const b of panel.querySelectorAll('[data-mode]'))b.onclick=()=>{if(!puzzle){error.textContent='先选一张照片，开始一桌拼图。';return;}if(b.dataset.mode!=='self'&&!hasCompanion()){error.textContent='这一档还没有同行者。';return;}if(puzzle.mode===b.dataset.mode)return;puzzle.mode=b.dataset.mode;bot=null;drag=null;wait=1;persist();update();if(puzzle.mode!=='self'&&!puzzle.completed)talk('对方选择了'+(puzzle.mode==='watch'?'看你拼这桌拼图':'和你一起拼这桌拼图')+'。',true);};
 $('#desk-reference').onclick=()=>{showReference=!showReference;reference.hidden=!showReference;$('#desk-reference').setAttribute('aria-pressed',String(showReference));};
 $('#zoom-in').onclick=()=>{zoom=Math.min(3.5,zoom*1.3);};$('#zoom-out').onclick=()=>{zoom=Math.max(1,zoom/1.3);};$('#zoom-fit').onclick=resetCamera;
 function point(e){const rect=canvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};}
 function transform(){const rect=canvas.getBoundingClientRect();scale=Math.min(rect.width/1000,rect.height/1320);return{s:scale*zoom,x:(rect.width-1000*scale*zoom)/2+pan.x,y:(rect.height-1320*scale*zoom)/2+pan.y};}
 function world(pt){const t=transform();return{x:(pt.x-t.x)/t.s,y:(pt.y-t.y)/t.s};}
 function hit(pt){if(!puzzle)return null;for(const id of [...z].reverse()){const q=puzzle.pieces[id],t=target(puzzle,id);if(!q.locked&&ctx.isPointInPath(paths[id],pt.x-q.x+t.x,pt.y-q.y+t.y))return q;}return null;}
 canvas.onpointerdown=e=>{if(!puzzle)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const pt=point(e);pointers.set(e.pointerId,pt);if(pointers.size===2){const a=[...pointers.values()];pinch={distance:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom};drag=null;return;}const p=world(pt),q=puzzle.mode==='watch'?null:hit(p);if(q){if(bot?.id===q.id)bot=null;drag={id:q.id,dx:p.x-q.x,dy:p.y-q.y};z=z.filter(id=>id!==q.id).concat(q.id);}else drag={pan:true,start:pt,x:pan.x,y:pan.y};};
 canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const pt=point(e);pointers.set(e.pointerId,pt);if(pinch&&pointers.size>=2){const a=[...pointers.values()];zoom=Math.max(1,Math.min(3.5,pinch.zoom*Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)/Math.max(1,pinch.distance)));return;}if(!drag)return;if(drag.pan){pan.x=drag.x+pt.x-drag.start.x;pan.y=drag.y+pt.y-drag.start.y;}else{const q=puzzle.pieces[drag.id],p=world(pt);q.x=p.x-drag.dx;q.y=p.y-drag.dy;}};
 function release(e){pointers.delete(e.pointerId);if(drag&&!drag.pan&&puzzle){const q=puzzle.pieces[drag.id];settle(q.id,q.x,q.y,'you');}drag=null;pinch=null;}
 canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(1,Math.min(3.5,zoom*(e.deltaY<0?1.1:.9)));};
 function settle(id,x,y,who){const was=puzzle.completed,ok=drop(puzzle,id,x,y,who);data().puzzleLastMove={by:who,piece:id+1,matched:ok};persist();update();if(hasCompanion()&&puzzle.mode!=='self'){if(!was&&puzzle.completed)talk('这桌拼图刚刚拼好了。',true);else if(ok&&Date.now()-lastTalk>45000&&puzzle.pieces.filter(q=>q.locked).length%Math.ceil(puzzle.count/4)===0)talk('你们继续拼了一会儿，看看实际进度，按你的性格自然接一句。',true);}}
 function paint(now){raf=requestAnimationFrame(paint);if(!opened||document.hidden){last=0;return;}if(last&&now-last<1000/30)return;const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(activity==='travel'){const env=environment();$('#travel-window-caption').textContent=`${env.season} · ${env.weather} · ${env.time}　${env.transition?env.transition.from+' → '+env.transition.to:env.scenery} · ${env.passing}`;return;}const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const t=transform();ctx.translate(t.x,t.y);ctx.scale(t.s,t.s);ctx.fillStyle='#e9e2cf';ctx.fillRect(BOARD.x-9,BOARD.y-9,BOARD.w+18,BOARD.h+18);ctx.fillStyle='#c7c4b2';ctx.fillRect(BOARD.x,BOARD.y,BOARD.w,BOARD.h);ctx.fillStyle='#7b715e';ctx.font='23px system-ui';ctx.fillText('散片区',100,665);
 if(!puzzle||!image){ctx.setTransform(1,0,0,1,0,0);return;}
 if(puzzle.mode!=='self'&&!puzzle.completed&&hasCompanion()&&!drag){if(bot){bot.elapsed+=dt;const q=puzzle.pieces[bot.id],u=Math.min(1,bot.elapsed/bot.duration),ease=u*u*(3-2*u);q.x=bot.fromX+(bot.x-bot.fromX)*ease;q.y=bot.fromY+(bot.y-bot.fromY)*ease-Math.sin(u*Math.PI)*20;if(u===1){const move=bot;bot=null;settle(move.id,move.x,move.y,'companion');wait=move.wait;}}else{wait-=dt;if(wait<=0){const m=nextCompanionMove(puzzle,skill);if(m){const q=puzzle.pieces[m.id];bot={...m,elapsed:0,fromX:q.x,fromY:q.y};z=z.filter(id=>id!==m.id).concat(m.id);}}}}
 const ordered=[...z.filter(id=>puzzle.pieces[id].locked),...z.filter(id=>!puzzle.pieces[id].locked)];for(const id of ordered){const q=puzzle.pieces[id],targetAt=target(puzzle,id);ctx.save();ctx.translate(q.x-targetAt.x,q.y-targetAt.y);ctx.save();ctx.clip(paths[id]);ctx.drawImage(image,BOARD.x,BOARD.y,BOARD.w,BOARD.h);ctx.restore();ctx.strokeStyle=q.locked?'rgba(255,255,255,.22)':'#fff5df';ctx.lineWidth=q.locked?1.2:2.5;ctx.stroke(paths[id]);ctx.restore();}
 if(bot){const q=puzzle.pieces[bot.id],targetAt=target(puzzle,q.id);ctx.beginPath();ctx.arc(q.x+targetAt.w*.55,q.y+targetAt.h*.55,13,0,Math.PI*2);ctx.fillStyle='#516b59';ctx.fill();ctx.fillStyle='#263d2c';ctx.font='bold 22px system-ui';ctx.fillText(host.companion?.()?.name||'TA',q.x+targetAt.w*.55+20,q.y+targetAt.h*.55);}
 ctx.setTransform(1,0,0,1,0,0);
 }
 raf=requestAnimationFrame(paint);
 return{async refresh(){photos();await loadPuzzle();},async open(mode='puzzle'){if(opened)scrollPositions[activity]=chat.scrollTop;activity=mode==='travel'?'travel':'puzzle';onOpen(activity);opened=true;panel.hidden=false;panel.dataset.activity=activity;$('#desk-title').textContent=activity==='travel'?'旅途聊天':'旅行拼图';$('#travel-window').hidden=false;if(stage)$('#travel-window').prepend(stage);$('#desk-message').placeholder=activity==='travel'?'一起看风景，聊点什么…':'边拼边聊…';photos();chat.replaceChildren();for(const m of host.history?.()||[])bubble(m.content,m.role==='user'?'you':'companion');chat.scrollTop=scrollPositions[activity]??chat.scrollHeight;await loadPuzzle();},flush(){return !puzzle||persist();},get isOpen(){return opened;},get activity(){return activity;},dispose(){cancelAnimationFrame(raf);panel.remove();},debug(){return{puzzle,camera:transform()};}};
}
