// Gameplay only. Scene/motion owners consume these facts through PetGame.career().
export const PET_DAY_SECONDS=300;
export const WORK_EVENTS=[
 {id:'flour',title:'柜台旁落了一点面粉',text:'它凑近闻了闻，鼻尖差点碰到白白的一小堆。现在怎么安排？',options:[{id:'watch',label:'留在柜台等客人',note:'守住了自己的位置，来买面包的人多看了它几眼。',tip:4,bread:0,like:.04,trait:'social'},{id:'explore',label:'让它在安全的角落看看',note:'绕着面粉观察了一圈，发现柜台下面还有小纸袋。',tip:1,bread:1,like:.07,trait:'bold'},{id:'break',label:'陪它歇一小会儿',note:'休息以后又愿意回到柜台边，今天没那么累。',tip:0,bread:0,like:.08,energy:5}]},
 {id:'visitor',title:'门边来了一个小客人',text:'隔壁的小宠物停在店门口。它一边看着新朋友，一边听店里打包面包的声音。',options:[{id:'greet',label:'让它慢慢认识新朋友',note:'互相闻了闻，认识了附近的新朋友。',tip:2,bread:0,like:.08,trait:'social'},{id:'stay',label:'一起留在熟悉的柜台边',note:'没有勉强打招呼，它安安稳稳陪完了这一段。',tip:3,bread:0,like:.04},{id:'pause',label:'先给它一点独处时间',note:'在安静的角落缓了缓，没被店里的热闹吓着。',tip:0,bread:0,like:.06,energy:4}]},
 {id:'bag',title:'一个空纸袋滚到了脚边',text:'它盯着纸袋，明显比盯着招牌还认真。顾客的面包已经打包好，纸袋是多出来的。',options:[{id:'keep',label:'收好纸袋，等下班再玩',note:'把纸袋留到了下班，多站了一会儿柜台。',tip:4,bread:0,like:.03},{id:'play',label:'给它一小段纸袋游戏时间',note:'玩过纸袋以后，今天对店里的印象更好了。',tip:0,bread:0,like:.09,energy:-2,trait:'active'},{id:'swap',label:'把纸袋送回打包台',note:'送回了多余的纸袋，下班时多带回一个小面包。',tip:2,bread:1,like:.05}]},
 {id:'closing',title:'柜台上还剩几个小面包',text:'这一段快结束了。它看了看面包，又看了看门口的阳光。',options:[{id:'pose',label:'再陪最后一位客人',note:'耐心陪完最后一位客人，得到了一点额外酬谢。',tip:5,bread:0,like:.03,trait:'social'},{id:'pack',label:'把留给它的小面包装好',note:'收好了属于它的小面包，可以带回家留着。',tip:1,bread:1,like:.07},{id:'easy',label:'让它安安静静结束这段',note:'按自己的节奏收尾，没有被催着营业。',tip:0,bread:0,like:.08,energy:3}]}
];
export const PET_SHOP=[{id:'snack',name:'小零食包',cost:8,count:2,text:'两份零食，可以分给它，也能在拒工后再邀请一次。'},{id:'toy',name:'它自己的小球',cost:22,count:1,text:'把小球记在它的名下；可以带回家，用原来的玩球玩法陪它玩。'}];
const n=(v,min=0,max=1e7,f=0)=>Number.isFinite(v)?Math.max(min,Math.min(max,v)):f;
const str=(v,max=160)=>typeof v==='string'?v.slice(0,max):'';
const validEvent=id=>WORK_EVENTS.some(e=>e.id===id);
export function restoreTrialMemory(raw){if(!raw||typeof raw.id!=='string'||!Number.isFinite(raw.day)||!Array.isArray(raw.choices))return null;return {id:str(raw.id,80),day:Math.floor(n(raw.day,1,1e7,1)),name:str(raw.name,24),wage:Math.floor(n(raw.wage)),bread:Math.floor(n(raw.bread,0,5)),choices:raw.choices.filter(x=>typeof x?.text==='string').slice(0,3).map(x=>({text:str(x.text),by:str(x.by,24)}))};}
export function restoreCareer(raw){const r=raw&&typeof raw==='object'?raw:{},d=r.daily||{},j=r.job;
 return {version:1,day:Math.floor(n(r.day,1,1e7,1)),seq:Math.floor(n(r.seq,0,1e7)),rng:n(r.rng,1,4294967295,19102026),trialDone:!!r.trialDone,firstTrial:restoreTrialMemory(r.firstTrial),preference:n(r.preference,-1,1),balance:Math.floor(n(r.balance)),inventory:{snack:Math.floor(n(r.inventory?.snack,0,10000,2)),bread:Math.floor(n(r.inventory?.bread,0,10000)),toy:Math.floor(n(r.inventory?.toy,0,1))},daily:{invited:!!d.invited,declined:!!d.declined,bribed:!!d.bribed,closed:!!d.closed,rest:!!d.rest},job:j&&typeof j.id==='string'&&['working','choice','ready','tired'].includes(j.phase)&&Array.isArray(j.events)&&j.events.length===3&&j.events.every(validEvent)&&((j.phase==='ready'&&j.index===3)||(j.phase!=='ready'&&Number.isInteger(j.index)&&j.index>=0&&j.index<3))?{id:str(j.id,80),day:Math.floor(n(j.day,1,1e7,1)),type:j.type==='shift'?'shift':'trial',phase:j.phase,index:Math.floor(n(j.index,0,3)),time:n(j.time,0,18),elapsed:n(j.elapsed,0,1000),events:j.events.slice(),tips:Math.floor(n(j.tips,0,30)),bread:Math.floor(n(j.bread,0,5)),choices:Array.isArray(j.choices)?j.choices.filter(x=>typeof x?.text==='string').slice(-3).map(x=>({text:str(x.text),by:str(x.by,24)})):[]}:null,ledger:Array.isArray(r.ledger)?r.ledger.filter(x=>typeof x?.id==='string'&&Number.isFinite(x.amount)).slice(-80).map(x=>({id:str(x.id,80),day:Math.floor(n(x.day,1,1e7,1)),amount:Math.trunc(n(x.amount,-1e7,1e7)),text:str(x.text)})):[],history:Array.isArray(r.history)?r.history.filter(x=>['bakery','rest'].includes(x?.kind)).slice(-60).map(x=>({kind:x.kind,day:Math.floor(n(x.day,1,1e7,1)),days:Math.floor(n(x.days,1,1e7,1)),wage:Math.floor(n(x.wage)),text:str(x.text),mood:n(x.mood,0,100,70)})):[],recent:Array.isArray(r.recent)?r.recent.filter(x=>typeof x?.text==='string').slice(-12).map(x=>({day:Math.floor(n(x.day,1,1e7,1)),text:str(x.text)})):[],receipt:r.receipt&&typeof r.receipt.text==='string'?{text:str(r.receipt.text),day:Math.floor(n(r.receipt.day,1,1e7,1)),wage:Math.floor(n(r.receipt.wage)),bread:Math.floor(n(r.receipt.bread,0,5))}:null};
}
export function createPetCareer(raw){const s=restoreCareer(raw),record=text=>{s.recent.push({day:s.day,text});s.recent=s.recent.slice(-12);};
 const random=()=>{s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296;};
 function restHistory(day,days,mood){const last=s.history.at(-1);if(last?.kind==='rest'&&last.day+last.days===day){last.days+=days;last.mood=(last.mood+mood)/2;}else s.history.push({kind:'rest',day,days,wage:0,text:'没有上班，按自己的节奏过日子。',mood});s.history=s.history.slice(-60);}
 function syncDay(care){const day=Math.floor(n(care.elapsed)/PET_DAY_SECONDS)+1;if(day<=s.day)return false;if(!s.job&&!s.history.some(x=>x.kind==='bakery'&&x.day===s.day))restHistory(s.day,day-s.day,care.mood);else if(!s.job&&day-s.day>1)restHistory(s.day+1,day-s.day-1,care.mood);s.day=day;s.daily={invited:false,declined:false,bribed:false,closed:false,rest:false};return true;}
 function event(){const j=s.job;if(j?.phase!=='choice')return null;const e=WORK_EVENTS.find(e=>e.id===j.events[j.index]);return e?{id:j.id+':'+j.index,title:e.title,text:e.text,options:e.options.map(o=>({id:o.id,label:o.label}))}:null;}
 const result=(accepted,text)=>({accepted,text});
 function request(action,options={},ctx={}){const care=ctx.care;if(!care)return result(false,'宠物还没准备好。');syncDay(care);const j=s.job;
  if(action==='invite'||action==='bribe'){
   if(ctx.room!=='bakery')return result(false,'先走进面包店，再问它愿不愿意试工。');
   if(j)return result(false,'这份试工还没结束，先看看眼前这一段。');if(s.daily.closed||s.daily.rest)return result(false,'今天已经收工了，下一天再来吧。');
   if(care.task||care.helper)return result(false,'它还有正在做的事，等忙完再问问。');
   if(care.energy<25||care.satiety<20){record('今天先休息，精神和肚子舒服些再谈工作。');return result(false,care.energy<25?'它有点累，先回家休息吧。':'它肚子有点空，先吃点东西吧。');}
   const bribe=action==='bribe';if(bribe){if(!s.daily.declined||s.daily.bribed)return result(false,'拒绝以后最多用零食再邀请一次。');if(!s.inventory.snack)return result(false,'小金库里没有零食了。');if(care.satiety>90)return result(false,'已经很饱啦，零食留到下次。');s.inventory.snack--;s.daily.bribed=true;care.satiety=n(care.satiety+4,0,100);record('拿一份自己的小零食，再问了它一次。');}
   else if(s.daily.invited)return result(false,s.daily.declined?'今天已经问过了；可以让它休息，或用一份零食再邀请一次。':'今天已经邀请过了。');
   s.daily.invited=true;const chance=n(.25+care.mood*.003+care.traits.social*.15+s.preference*.22+(bribe?.18:0)-(care.energy<40?.12:0),.12,.94);
   if(random()>chance){s.daily.declined=true;care.mood=n(care.mood+1,0,100);record('今天不想在面包店营业，把这次邀请留在了门边。');return result(false,'看了看柜台，今天这会儿不想营业。');}
   s.daily.declined=false;const offset=Math.floor(random()*WORK_EVENTS.length);s.job={id:'bakery:'+s.day+':'+(++s.seq),day:s.day,type:s.trialDone?'shift':'trial',phase:'working',index:0,time:0,elapsed:0,events:[0,1,2].map(i=>WORK_EVENTS[(offset+i)%WORK_EVENTS.length].id),tips:0,bread:0,choices:[]};record(s.trialDone?'愿意再来陪一班面包店。':'愿意试一小段面包店的工作。');return result(true,'它愿意啦。回到店里，先一起陪完第一段。');
  }
  if(action==='choose'){
   const e=event();if(!e||options.eventId!==e.id)return result(false,'这件小事已经变了，先看看最新进度。');const def=WORK_EVENTS.find(e=>e.id===j.events[j.index]),choice=def.options.find(o=>o.id===options.choice);if(!choice)return result(false,'选一个当前的小主意吧。');
   const by=str(options.by||'你',24);j.choices.push({by,text:choice.note});j.tips+=choice.tip;j.bread+=choice.bread;s.preference=n(s.preference+choice.like,-1,1);care.energy=n(care.energy+(choice.energy||0),0,100);care.mood=n(care.mood+2,0,100);if(choice.trait)care.traits[choice.trait]=n(care.traits[choice.trait]+.008,0,1);record(by+'拿了主意：'+choice.note);j.index++;j.time=0;j.phase=j.index>=3?'ready':'working';return result(true,j.phase==='ready'?'这一班的小事都处理好了，可以收工了。':'这件小事记下了，回到店里继续下一段。');
  }
  if(action==='finish'){
   if(!j||j.phase!=='ready')return result(false,'先把这一班的三件小事陪完。');const id='income:'+j.id;if(s.ledger.some(x=>x.id===id))return result(false,'这一班已经结过工资了。');const wage=(j.type==='trial'?24:30)+j.tips,bread=1+j.bread;s.balance+=wage;s.inventory.bread+=bread;s.ledger.push({id,day:s.day,amount:wage,text:j.type==='trial'?'面包店试工':'面包店看板宠物'});s.ledger=s.ledger.slice(-80);if(j.type==='trial'&&!s.firstTrial)s.firstTrial=restoreTrialMemory({id:j.id,day:s.day,name:ctx.name||'',wage,bread,choices:j.choices});s.trialDone=true;s.daily.closed=true;s.preference=n(s.preference+.04,-1,1);s.history.push({kind:'bakery',day:s.day,days:1,wage,text:j.type==='trial'?'完成了第一次面包店试工。':'在面包店陪完了一班。',mood:care.mood});s.history=s.history.slice(-60);s.receipt={day:s.day,wage,bread,text:'这一班赚了 ￥'+wage+'，带回 '+bread+' 个小面包。'};record(s.receipt.text);s.job=null;return result(true,s.receipt.text);
  }
  if(action==='cancel'){if(!j)return result(false,'现在没有正在上的班。');record('提前离开面包店，今天先休息；这次没有结工资。');s.daily.closed=true;s.job=null;return result(true,'这次先停下，回家休息吧。');}
  if(action==='resume'){if(!j||j.phase!=='tired')return result(false,'现在不用恢复试工。');if(care.energy<30)return result(false,'还想歇一会儿，精神恢复些再来。');j.phase='working';return result(true,'恢复精神了，回店里继续这一段。');}
  if(action==='rest'){if(j)return result(false,'先结束眼前这份试工，再安排休息。');if(s.daily.rest||s.daily.closed)return result(false,'今天已经留给它自己了。');s.daily.rest=true;record('今天不上班，让它按自己的心情过日子。');return result(true,'今天就开开心心休息。');}
  if(action==='buy'){const item=PET_SHOP.find(x=>x.id===options.item);if(!item)return result(false,'这里暂时没有这个东西。');if(item.id==='toy'&&s.inventory.toy)return result(false,'自己的小球已经有啦。');if(s.balance<item.cost)return result(false,'它的小金库还不够，先留着这笔钱。');s.balance-=item.cost;s.inventory[item.id]+=item.count;s.ledger.push({id:'buy:'+(++s.seq),day:s.day,amount:-item.cost,text:item.name});s.ledger=s.ledger.slice(-80);record('用自己的小金库买了'+item.name+'。');return result(true,'已经放进它自己的小东西里了。');}
  if(action==='use'){const item=['snack','bread'].includes(options.item)?options.item:null;if(!item||!s.inventory[item])return result(false,'这份已经用完了。');if(ctx.room!=='home'||typeof ctx.startTreat!=='function')return result(false,'带回家以后，再从面包篮或零钱袋里分给它。');if(j||care.task||care.helper)return result(false,'先等它忙完这一件事，再分给它。');const started=ctx.startTreat(item);if(!started.accepted)return started;s.inventory[item]--;record(item==='bread'?'从面包篮里分出一个自己带回的小面包。':'从袋子里分出一份自己的小零食。');return result(true,'给它留好这一份，回到屋里等它走过来慢慢吃。');}
  return result(false,'先看看今天想怎么过吧。');
 }
 function tick(dt,{care,room,paused=false}={}){if(paused||!care||!Number.isFinite(dt)||dt<=0)return null;syncDay(care);const j=s.job;if(!j||j.phase!=='working'||room!=='bakery')return null;dt=Math.min(dt,1);j.elapsed+=dt;j.time+=dt;care.energy=n(care.energy-dt*.18,0,100);if(care.energy<18){j.phase='tired';record('它有点累了，停下来等你安排休息。');return {event:true,text:'它有点累了，先歇歇吧。'};}if(j.time>=(j.type==='trial'?12:18)){j.phase='choice';return {event:true,text:event().title};}return null;}
 function summary(){const j=s.job;return {...structuredClone(s),event:event(),shop:PET_SHOP,daySeconds:PET_DAY_SECONDS,activity:j?(j.phase==='choice'?'有一件小事等你拿主意':j.phase==='ready'?'这一班做完了，等你一起收工':j.phase==='tired'?'暂停试工，想先恢复精神':'面包店第 '+(j.index+1)+' 段 · '+(j.type==='trial'?'试工':'上班')):s.daily.rest?'今天开心休息':s.daily.closed?'今天已经收工':s.daily.declined?'今天这会儿不想营业':'今天还没上班',opinion:s.preference>.3?'越来越喜欢面包店':s.preference<-.2?'对面包店还有点犹豫':'还在认识这份工作',resume:{bakery:s.history.filter(x=>x.kind==='bakery').reduce((a,x)=>a+x.days,0),rest:s.history.filter(x=>x.kind==='rest').reduce((a,x)=>a+x.days,0)}};}
 return {state:s,request,tick,summary,syncDay,snapshot:()=>structuredClone(s),restore:raw=>{const next=restoreCareer(raw);for(const key of Object.keys(s))delete s[key];Object.assign(s,next);}};
}
