// Gameplay only. Scene/motion owners consume these facts through PetGame.career().
export const PET_DAY_SECONDS=300;
import {BAKERY_EVENTS,PET_WORKPLACES,petWorkplace,workplaceInfo} from './workplaces.mjs?v=fg-1c2b9317458d023e';
export const WORK_EVENTS=BAKERY_EVENTS;
import {PET_SHOP,SHOPPING_CAPS,restoreShopping,shoppingItem,canPurchase,chooseShopping} from './shopping.mjs?v=fg-1c2b9317458d023e';
export {PET_SHOP};
const n=(v,min=0,max=1e7,f=0)=>Number.isFinite(v)?Math.max(min,Math.min(max,v)):f;
const str=(v,max=160)=>typeof v==='string'?v.slice(0,max):'';
const validEvent=(id,profession)=>petWorkplace(profession).events.some(e=>e.id===id);
export function restoreTrialMemory(raw){if(!raw||typeof raw.id!=='string'||!Number.isFinite(raw.day)||!Array.isArray(raw.choices))return null;return {id:str(raw.id,80),profession:petWorkplace(raw.profession).id,flower:Number.isFinite(raw.flower)?Math.floor(n(raw.flower,0,5)):null,petals:Number.isFinite(raw.petals)?Math.floor(n(raw.petals,0,10)):null,day:Math.floor(n(raw.day,1,1e7,1)),name:str(raw.name,24),wage:Math.floor(n(raw.wage)),bread:Number.isFinite(raw.bread)?Math.floor(n(raw.bread,0,5)):null,choices:raw.choices.filter(x=>typeof x?.text==='string').slice(0,3).map(x=>({text:str(x.text),by:str(x.by,24)}))};}
function legacyTrialMemory(raw){if(!raw?.trialDone||!Array.isArray(raw.history))return null;const first=raw.history.find(x=>x?.kind==='bakery'&&x.text==='完成了第一次面包店试工。'&&Number.isFinite(x.day)&&Number.isFinite(x.wage));return first?restoreTrialMemory({id:'legacy-trial:'+first.day,day:first.day,wage:first.wage,choices:[]}):null;}
export function restoreCareer(raw){const r=raw&&typeof raw==='object'?raw:{},d=r.daily||{},j=r.job;
 return {version:3,shopping:restoreShopping(r.shopping,(n(r.rng,1,4294967295,19102026)^0x71e5ab35)>>>0||1),selected:petWorkplace(j?.profession||r.selected).id,florist:{trialDone:!!r.florist?.trialDone,preference:n(r.florist?.preference,-1,1),friend:r.florist?.friend&&Number.isFinite(r.florist.friend.day)?{day:Math.floor(n(r.florist.friend.day,1,1e7,1)),visits:Math.floor(n(r.florist.friend.visits,1,1e7,1)),name:'花店门口的小邻居'}:null},vase:{flowers:Math.floor(n(r.vase?.flowers,0,3)),day:Math.floor(n(r.vase?.day,1,1e7,1)),by:str(r.vase?.by,24)},day:Math.floor(n(r.day,1,1e7,1)),seq:Math.floor(n(r.seq,0,1e7)),rng:n(r.rng,1,4294967295,19102026),trialDone:!!r.trialDone,firstTrial:restoreTrialMemory(r.firstTrial)||legacyTrialMemory(r),preference:n(r.preference,-1,1),balance:Math.floor(n(r.balance)),inventory:{box:Math.floor(n(r.inventory?.box,0,1)),snack:Math.floor(n(r.inventory?.snack,0,10000,2)),bread:Math.floor(n(r.inventory?.bread,0,10000)),toy:Math.floor(n(r.inventory?.toy,0,1)),flower:Math.floor(n(r.inventory?.flower,0,10000)),petals:Math.floor(n(r.inventory?.petals,0,10000))},daily:{invited:!!d.invited,declined:!!d.declined,bribed:!!d.bribed,closed:!!d.closed,rest:!!d.rest},job:j&&typeof j.id==='string'&&['working','choice','ready','tired'].includes(j.phase)&&Array.isArray(j.events)&&j.events.length===3&&j.events.every(id=>validEvent(id,j.profession))&&((j.phase==='ready'&&j.index===3)||(j.phase!=='ready'&&Number.isInteger(j.index)&&j.index>=0&&j.index<3))?{id:str(j.id,80),profession:petWorkplace(j.profession).id,flower:Math.floor(n(j.flower,0,5)),petals:Math.floor(n(j.petals,0,10)),day:Math.floor(n(j.day,1,1e7,1)),type:j.type==='shift'?'shift':'trial',phase:j.phase,index:Math.floor(n(j.index,0,3)),time:n(j.time,0,18),elapsed:n(j.elapsed,0,1000),events:j.events.slice(),tips:Math.floor(n(j.tips,0,30)),bread:Math.floor(n(j.bread,0,5)),choices:Array.isArray(j.choices)?j.choices.filter(x=>typeof x?.text==='string').slice(-3).map(x=>({text:str(x.text),by:str(x.by,24)})):[]}:null,ledger:Array.isArray(r.ledger)?r.ledger.filter(x=>typeof x?.id==='string'&&Number.isFinite(x.amount)).slice(-80).map(x=>({id:str(x.id,80),day:Math.floor(n(x.day,1,1e7,1)),amount:Math.trunc(n(x.amount,-1e7,1e7)),text:str(x.text)})):[],history:Array.isArray(r.history)?r.history.filter(x=>['bakery','florist','rest'].includes(x?.kind)).slice(-60).map(x=>({kind:x.kind,day:Math.floor(n(x.day,1,1e7,1)),days:Math.floor(n(x.days,1,1e7,1)),wage:Math.floor(n(x.wage)),text:str(x.text),mood:n(x.mood,0,100,70)})):[],recent:Array.isArray(r.recent)?r.recent.filter(x=>typeof x?.text==='string').slice(-12).map(x=>({day:Math.floor(n(x.day,1,1e7,1)),text:str(x.text)})):[],receipt:r.receipt&&typeof r.receipt.text==='string'?{text:str(r.receipt.text),day:Math.floor(n(r.receipt.day,1,1e7,1)),wage:Math.floor(n(r.receipt.wage)),bread:Math.floor(n(r.receipt.bread,0,5)),flower:Math.floor(n(r.receipt.flower,0,5)),petals:Math.floor(n(r.receipt.petals,0,10))}:null};
}
export function createPetCareer(raw){const s=restoreCareer(raw),record=text=>{s.recent.push({day:s.day,text});s.recent=s.recent.slice(-12);};
 const progress=id=>id==='florist'?s.florist:s;
 const current=()=>petWorkplace(s.job?.profession||s.selected);
 const random=()=>{s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296;};
 function restHistory(day,days,mood){const last=s.history.at(-1);if(last?.kind==='rest'&&last.day+last.days===day){last.days+=days;last.mood=(last.mood+mood)/2;}else s.history.push({kind:'rest',day,days,wage:0,text:'没有上班，按自己的节奏过日子。',mood});s.history=s.history.slice(-60);}
 function syncDay(care){const day=Math.floor(n(care.elapsed)/PET_DAY_SECONDS)+1;if(day<=s.day)return false;if(!s.job&&!s.history.some(x=>['bakery','florist'].includes(x.kind)&&x.day===s.day))restHistory(s.day,day-s.day,care.mood);else if(!s.job&&day-s.day>1)restHistory(s.day+1,day-s.day-1,care.mood);s.day=day;s.daily={invited:false,declined:false,bribed:false,closed:false,rest:false};return true;}
 function event(){const j=s.job;if(j?.phase!=='choice')return null;const e=petWorkplace(j.profession).events.find(e=>e.id===j.events[j.index]);return e?{id:j.id+':'+j.index,title:e.title,text:e.text,options:e.options.map(o=>({id:o.id,label:o.label}))}:null;}
 const result=(accepted,text)=>({accepted,text});
 function purchase(item,{self=false,id='',reason=''}={}){if(!canPurchase(s,item))return result(false,item?.max&&s.inventory[item.id]?'自己的'+item.name+'已经有啦。':'它的小金库还不够，先留着这笔钱。');s.balance-=item.cost;const purchaseId=id||'buy:'+(++s.seq);if(self)s.shopping.trip={...s.shopping.trip,phase:'packed',item:item.id,amount:item.cost};else s.inventory[item.id]+=item.count;s.ledger.push({id:purchaseId,day:s.day,amount:-item.cost,text:(self?'它自己买了':'')+(self?item.selfName:item.name)});s.ledger=s.ledger.slice(-80);record(self?reason+' 花了 ￥'+item.cost+'，收进小袋子，等带回家。':'用自己的小金库买了'+item.name+'。');return result(true,self?'它自己挑了'+item.selfName+'，花了 ￥'+item.cost+'。带回家再拆小袋子吧。':'已经放进它自己的小东西里了。');}
 function request(action,options={},ctx={}){const care=ctx.care;if(!care)return result(false,'宠物还没准备好。');syncDay(care);const j=s.job,place=current(),p=progress(place.id);
  if(action==='shopping-settings'){if(options.enabled!==undefined&&typeof options.enabled!=='boolean'||options.cap!==undefined&&!SHOPPING_CAPS.includes(options.cap))return result(false,'选一个小票上写好的额度吧。');if(typeof options.enabled==='boolean')s.shopping.enabled=options.enabled;if(options.cap!==undefined)s.shopping.cap=options.cap;if(!s.shopping.enabled&&s.shopping.trip?.phase==='browsing')s.shopping.trip=null;return result(true,s.shopping.enabled?'逛便利店时，可以让它自己挑一点喜欢的。':'先替它收好零钱，已经买好的东西仍可以带回家。');}
  if(action==='checkout'){const q=s.shopping,t=q.trip;if(ctx.room!=='store'||!q.enabled||!t||t.phase!=='browsing'||t.time<12||q.lastDay>=s.day||j||care.task||care.helper)return result(false,'先让它在便利店慢慢看看。');const chosen=chooseShopping(s,care,()=>{q.rng=(Math.imul(q.rng,1664525)+1013904223)>>>0;return q.rng/4294967296;});q.lastDay=s.day;const log={id:t.id,day:s.day,item:chosen.item?.id||'',amount:chosen.item?.cost||0,reason:chosen.reason,text:chosen.item?'它自己买了'+chosen.item.selfName+' · ￥'+chosen.item.cost:chosen.reason,delivered:!chosen.item,served:false};q.log.push(log);q.log=q.log.slice(-8);if(chosen.item)return purchase(chosen.item,{self:true,id:t.id,reason:chosen.reason});q.trip=null;record(chosen.reason);return result(true,chosen.reason);}
  if(action==='unpack'){const t=s.shopping.trip;if(ctx.room!=='home'||t?.phase!=='packed')return result(false,'等带着小袋子回家，再拆开看看。');const item=shoppingItem(t.item);s.inventory[item.id]+=item.count;if(item.id==='toy')s.shopping.toyStyle='wonky';const log=s.shopping.log.find(x=>x.id===t.id);if(log)log.delivered=true;s.shopping.trip=null;record('把它自己挑的'+item.selfName+'带回了家。');let line='小袋子拆开了，'+item.selfName+'已经放进它自己的小东西里。';if(item.id==='snack'&&!care.task&&!care.helper&&typeof ctx.startSelfTreat==='function'){const started=ctx.startSelfTreat();if(started.accepted){s.inventory.snack--;if(log)log.served=true;record('它拆出一份自己买的小零食，准备慢慢吃。');line+=' 它先拆了一份准备吃，袋子里留着另一份。';}}return result(true,line);}
  if(action==='box-rest'){if(ctx.room!=='home'||!s.inventory.box||typeof ctx.startRest!=='function')return result(false,'先把自己的小纸箱带回家。');return ctx.startRest('box');}
  if(action==='select'){if(!PET_WORKPLACES.some(x=>x.id===options.profession))return result(false,'先挑一个已经开放的小店。');if(options.profession===place.id)return result(true,'今天先看看'+place.title+'。');if(j||s.daily.invited||s.daily.closed||s.daily.rest)return result(false,'今天已经拿过主意了，下一天再换一家小店吧。');s.selected=options.profession;return result(true,'今天先看看'+current().title+'。');}
  if(action==='arrange'){if(ctx.room!=='home')return result(false,'先把小花带回家，再插进花瓶。');if(!s.inventory.flower)return result(false,'袋子里暂时没有小花。');if(s.vase.flowers>=3)return result(false,'花瓶里已经有三枝小花，先看看这一束吧。');s.inventory.flower--;s.vase={flowers:s.vase.flowers+1,day:s.day,by:str(options.by||'你',24)};record(s.vase.by+'把它从花店带回的小花插进了家里的花瓶。');return result(true,'小花插好啦，家里多了一点花店的颜色。');}
  if(action==='invite'||action==='bribe'){
   if(ctx.room!==place.id)return result(false,'先走进'+place.title+'，再问它愿不愿意试工。');
   if(j)return result(false,'这份试工还没结束，先看看眼前这一段。');if(s.daily.closed||s.daily.rest)return result(false,'今天已经收工了，下一天再来吧。');
   if(care.task||care.helper)return result(false,'它还有正在做的事，等忙完再问问。');
   if(care.energy<25||care.satiety<20){record('今天先休息，精神和肚子舒服些再谈工作。');return result(false,care.energy<25?'它有点累，先回家休息吧。':'它肚子有点空，先吃点东西吧。');}
   const bribe=action==='bribe';if(bribe){if(!s.daily.declined||s.daily.bribed)return result(false,'拒绝以后最多用零食再邀请一次。');if(!s.inventory.snack)return result(false,'小金库里没有零食了。');if(care.satiety>90)return result(false,'已经很饱啦，零食留到下次。');s.inventory.snack--;s.daily.bribed=true;care.satiety=n(care.satiety+4,0,100);record('拿一份自己的小零食，再问了它一次。');}
   else if(s.daily.invited)return result(false,s.daily.declined?'今天已经问过了；可以让它休息，或用一份零食再邀请一次。':'今天已经邀请过了。');
   s.daily.invited=true;const chance=n(.25+care.mood*.003+care.traits.social*.15+p.preference*.22+(place.id==='florist'?care.traits.bold*.08:0)+(bribe?.18:0)-(care.energy<40?.12:0),.12,.94);
   if(random()>chance){s.daily.declined=true;care.mood=n(care.mood+1,0,100);record('今天不想在'+place.title+'营业，把这次邀请留在了门边。');return result(false,'看了看柜台，今天这会儿不想营业。');}
   s.daily.declined=false;const offset=Math.floor(random()*place.events.length);s.job={id:place.id+':'+s.day+':'+(++s.seq),profession:place.id,flower:0,petals:0,day:s.day,type:p.trialDone?'shift':'trial',phase:'working',index:0,time:0,elapsed:0,events:[0,1,2].map(i=>place.events[(offset+i)%place.events.length].id),tips:0,bread:0,choices:[]};record(p.trialDone?'愿意再来陪一班'+place.title+'。':'愿意试一小段'+place.title+'的工作。');return result(true,'它愿意啦。回到店里，先一起陪完第一段。');
  }
  if(action==='choose'){
   const e=event();if(!e||options.eventId!==e.id)return result(false,'这件小事已经变了，先看看最新进度。');const def=petWorkplace(j.profession).events.find(e=>e.id===j.events[j.index]),choice=def.options.find(o=>o.id===options.choice);if(!choice)return result(false,'选一个当前的小主意吧。');
   const by=str(options.by||'你',24);j.choices.push({by,text:choice.note});j.tips+=choice.tip;j.bread+=choice.bread||0;j.flower+=choice.flower||0;j.petals+=choice.petals||0;p.preference=n(p.preference+choice.like,-1,1);if(choice.friend){s.florist.friend=s.florist.friend?{...s.florist.friend,visits:s.florist.friend.visits+1}:{name:'花店门口的小邻居',day:s.day,visits:1};}care.energy=n(care.energy+(choice.energy||0),0,100);care.mood=n(care.mood+2,0,100);if(choice.trait)care.traits[choice.trait]=n(care.traits[choice.trait]+.008,0,1);record(by+'拿了主意：'+choice.note);j.index++;j.time=0;j.phase=j.index>=3?'ready':'working';return result(true,j.phase==='ready'?'这一班的小事都处理好了，可以收工了。':'这件小事记下了，回到店里继续下一段。');
  }
  if(action==='finish'){
   if(!j||j.phase!=='ready')return result(false,'先把这一班的三件小事陪完。');const id='income:'+j.id;if(s.ledger.some(x=>x.id===id))return result(false,'这一班已经结过工资了。');const wage=(j.type==='trial'?place.trialWage:place.wage)+j.tips,bread=place.id==='bakery'?1+j.bread:0,flower=place.id==='florist'?1+j.flower:0,petals=place.id==='florist'?1+j.petals:0;s.balance+=wage;s.inventory.bread+=bread;s.inventory.flower+=flower;s.inventory.petals+=petals;s.ledger.push({id,day:s.day,amount:wage,text:j.type==='trial'?place.title+'试工':place.role});s.ledger=s.ledger.slice(-80);if(j.type==='trial'&&!s.firstTrial)s.firstTrial=restoreTrialMemory({id:j.id,profession:place.id,day:s.day,name:ctx.name||'',wage,bread:place.id==='bakery'?bread:null,flower:place.id==='florist'?flower:null,petals:place.id==='florist'?petals:null,choices:j.choices});p.trialDone=true;s.daily.closed=true;p.preference=n(p.preference+.04,-1,1);s.history.push({kind:place.id,day:s.day,days:1,wage,text:j.type==='trial'?'完成了第一次'+place.title+'试工。':'在'+place.title+'陪完了一班。',mood:care.mood});s.history=s.history.slice(-60);s.receipt={day:s.day,wage,bread,flower,petals,text:'这一班赚了 ￥'+wage+(place.id==='bakery'?'，带回 '+bread+' 个小面包。':'，带回 '+flower+' 枝小花和 '+petals+' 片花瓣。')};record(s.receipt.text);s.job=null;return result(true,s.receipt.text);
  }
  if(action==='cancel'){if(!j)return result(false,'现在没有正在上的班。');record('提前离开'+place.title+'，今天先休息；这次没有结工资。');s.daily.closed=true;s.job=null;return result(true,'这次先停下，回家休息吧。');}
  if(action==='resume'){if(!j||j.phase!=='tired')return result(false,'现在不用恢复试工。');if(care.energy<30)return result(false,'还想歇一会儿，精神恢复些再来。');j.phase='working';return result(true,'恢复精神了，回店里继续这一段。');}
  if(action==='rest'){if(j)return result(false,'先结束眼前这份试工，再安排休息。');if(s.daily.rest||s.daily.closed)return result(false,'今天已经留给它自己了。');s.daily.rest=true;record('今天不上班，让它按自己的心情过日子。');return result(true,'今天就开开心心休息。');}
  if(action==='buy'){const item=shoppingItem(options.item);if(!item)return result(false,'这里暂时没有这个东西。');return purchase(item);}
  if(action==='use'){const item=['snack','bread'].includes(options.item)?options.item:null;if(!item||!s.inventory[item])return result(false,'这份已经用完了。');if(ctx.room!=='home'||typeof ctx.startTreat!=='function')return result(false,'带回家以后，再从面包篮或零钱袋里分给它。');if(j||care.task||care.helper)return result(false,'先等它忙完这一件事，再分给它。');const started=ctx.startTreat(item);if(!started.accepted)return started;s.inventory[item]--;record(item==='bread'?'从面包篮里分出一个自己带回的小面包。':'从袋子里分出一份自己的小零食。');return result(true,'给它留好这一份，回到屋里等它走过来慢慢吃。');}
  return result(false,'先看看今天想怎么过吧。');
 }
 function tick(dt,{care,room,paused=false}={}){if(paused||!care||!Number.isFinite(dt)||dt<=0)return null;syncDay(care);const j=s.job,q=s.shopping;if(room==='store'&&q.enabled&&!j&&!care.task&&!care.helper&&care.energy>=20&&q.lastDay<s.day&&q.trip?.phase!=='packed'){if(!q.trip||q.trip.day!==s.day)q.trip={id:'shopping:'+s.day+':'+(++s.seq),day:s.day,phase:'browsing',time:0,item:'',amount:0};q.trip.time=Math.min(12,q.trip.time+Math.min(dt,1));if(q.trip.time>=12)return {shopping:true,text:'它在货架前拿好了自己的主意。'};}if(!j||j.phase!=='working'||room!==petWorkplace(j.profession).id)return null;dt=Math.min(dt,1);j.elapsed+=dt;j.time+=dt;care.energy=n(care.energy-dt*petWorkplace(j.profession).energy,0,100);if(care.energy<18){j.phase='tired';record('它有点累了，停下来等你安排休息。');return {event:true,text:'它有点累了，先歇歇吧。'};}if(j.time>=(j.type==='trial'?12:18)){j.phase='choice';return {event:true,text:event().title};}return null;}
 function summary(){const j=s.job,place=current(),p=progress(place.id);return {...structuredClone(s),trialDone:p.trialDone,preference:p.preference,workplace:workplaceInfo(place.id),workplaces:PET_WORKPLACES.map(x=>workplaceInfo(x.id)),event:event(),shop:PET_SHOP,daySeconds:PET_DAY_SECONDS,activity:j?(j.phase==='choice'?'有一件小事等你拿主意':j.phase==='ready'?'这一班做完了，等你一起收工':j.phase==='tired'?'暂停试工，想先恢复精神':place.title+'第 '+(j.index+1)+' 段 · '+(j.type==='trial'?'试工':'上班')):s.daily.rest?'今天开心休息':s.daily.closed?'今天已经收工':s.daily.declined?'今天这会儿不想营业':'今天还没上班',opinion:p.preference>.3?'越来越喜欢'+place.title:p.preference<-.2?'对'+place.title+'还有点犹豫':'还在认识这份工作',resume:{florist:s.history.filter(x=>x.kind==='florist').reduce((a,x)=>a+x.days,0),bakery:s.history.filter(x=>x.kind==='bakery').reduce((a,x)=>a+x.days,0),rest:s.history.filter(x=>x.kind==='rest').reduce((a,x)=>a+x.days,0)}};}
 return {state:s,request,tick,summary,syncDay,snapshot:()=>structuredClone(s),restore:raw=>{const next=restoreCareer(raw);for(const key of Object.keys(s))delete s[key];Object.assign(s,next);}};
}
