import test from 'node:test';
import assert from 'node:assert/strict';
import {createPetCareer} from './career.mjs';
import {createPetCare} from './care.mjs';
import {createCareerCompany,careerSuggestion,restoreCareerCompany} from './career-company.mjs';
function setup(){const career=createPetCareer({rng:1}),care=createPetCare().state;Object.assign(care,{task:null,helper:null,energy:85,satiety:80,mood:100});let actor={id:'a',name:'小青',person:{id:'a',persona:'喜欢植物、自然和花。'},available:true,place:'home',position:{x:0,z:0},activity:null,company:false},ctx={date:'2026-10-05',petId:'one',name:'团子',place:'home',position:{x:0,z:0},free:true},fail=false;const notices=[];const controller=createCareerCompany({getCareer:()=>career.state,getActor:()=>actor,getContext:()=>ctx,save:()=>!fail,applyDecision:(action,options)=>career.request(action,options,{care,room:ctx.place}),capture:()=>career.snapshot(),restore:old=>career.restore(old),startCompany:()=>{actor.company=true;actor.activity={phase:'walking'};return {accepted:true};},cancelCompany:()=>{actor.company=false;actor.activity=null;},notify:x=>notices.push(x)});return {career,care,controller,ctx,actor,notices,setFail:x=>fail=x,setActor:x=>actor=x};}
function actualBag(f){const {career,care}=f;let ctx={care,room:'bakery',name:'团子'};assert.equal(career.request('invite',{},ctx).accepted,true);for(let i=0;i<3;i++){for(let j=0;j<20;j++)career.tick(1,ctx);const e=career.summary().event;assert.ok(e);assert.equal(career.request('choose',{eventId:e.id,choice:e.options[0].id},ctx).accepted,true);}assert.equal(career.request('finish',{},ctx).accepted,true);const bag=career.state.parcels.queue[0];const body=createPetCare(care),home={care:body.state,room:'home',startBag:(id,point)=>body.startBag(id,point),finishBag:()=>body.cancel()};assert.equal(career.request('carry-bag',{bagId:bag.id,position:{x:0,z:0}},home).accepted,true);body.arrive();body.tick(1,{home:true,idleAllowed:false});body.tick(.3,{home:true,idleAllowed:false});assert.equal(career.request('place-bag',{bagId:bag.id},home).accepted,true);assert.equal(career.request('unpack',{bagId:bag.id},home).accepted,true);return career.state.parcels.opened[0];}
test('TA proposals are local, once per real date, leave original job/income untouched',()=>{const f=setup();assert.equal(f.controller.request('suggest',{random:()=>.2}).accepted,true);const p=f.controller.facts().proposal;assert.ok(p.profession);assert.equal(f.career.state.job,null);assert.equal(f.career.state.balance,0);assert.equal(f.controller.request('suggest').accepted,false);const saved=createPetCareer(f.career.snapshot());assert.equal(saved.state.company.actors[0].proposal.profession,p.profession);assert.equal(saved.summary().company,undefined,'raw actor history never enters public career facts');});
test('agree and different opinion use original career select, rest uses original daily rest',()=>{for(const action of ['agree','change','rest']){const f=setup();f.controller.request('suggest',{random:()=>0});const chosen=f.controller.facts().proposal.profession;const r=f.controller.request(action,{profession:'florist'});assert.equal(r.accepted,true);assert.equal(f.career.state.job,null);assert.equal(f.controller.facts().proposal.status,action==='agree'?'agreed':action==='change'?'changed':'rest');assert.equal(f.career.state.selected,action==='agree'?chosen:action==='change'?'florist':'bakery');assert.equal(f.career.state.daily.rest,action==='rest');}});
test('failed decision restores proposal and original profession atomically',()=>{const f=setup();f.controller.request('suggest',{random:()=>0});const before=f.career.snapshot();f.setFail(true);assert.equal(f.controller.request('change',{profession:'alley'}).accepted,false);assert.deepEqual(f.career.snapshot(),before);});
test('agreed proposal still reaches original will/refusal and limited bribe algorithm',()=>{const f=setup();f.controller.request('suggest',{random:()=>0});f.controller.request('agree');f.career.state.rng=1000;f.care.mood=0;f.care.traits.social=0;const refused=f.career.request('invite',{}, {care:f.care,room:'bakery'});f.controller.observe('invite',refused);assert.equal(refused.accepted,false);assert.equal(f.controller.facts().proposal.outcome,'refused');assert.equal(f.career.state.job,null);assert.equal(f.career.state.balance,0);});
test('actor and pet archive boundaries: a different TA sees no old proposal or memory',()=>{const f=setup();f.controller.request('suggest',{random:()=>0});f.setActor({...f.actor,id:'other',person:{id:'other',persona:''}});assert.equal(f.controller.facts().proposal,null);assert.deepEqual(f.controller.facts().memories,[]);assert.equal(f.controller.request('suggest').accepted,true);assert.equal(f.career.state.company.actors.length,2);const second=setup();assert.deepEqual(second.controller.facts().memories,[]);assert.equal(second.controller.facts().proposal,null);});
test('only an actual opened work bag can be reviewed; arrival and eight actual seconds precede memory',()=>{const f=setup(),bag=actualBag(f),money=f.career.state.balance;assert.equal(f.controller.request('review',{bagId:'shopping:no'}).accepted,false);assert.equal(f.controller.request('review',{bagId:bag.id}).accepted,true);for(let i=0;i<100;i++)f.controller.tick(.05);assert.equal(f.controller.facts().memories.length,0);f.actor.activity.phase='doing';for(let i=0;i<161;i++)f.controller.tick(.05);const memories=f.controller.facts().memories;assert.equal(memories.length,1);assert.equal(memories[0].bagId,bag.id);assert.match(memories[0].text,/面包店.*小面包/);assert.equal(f.controller.reviewing,false);assert.equal(f.career.state.balance,money);assert.equal(f.controller.request('review',{bagId:bag.id}).accepted,false);assert.equal(createPetCareer(f.career.snapshot()).state.company.actors[0].memories.length,1);});
test('failed review start and completion do not count; retry completes once',()=>{const f=setup(),bag=actualBag(f);f.setFail(true);assert.equal(f.controller.request('review',{bagId:bag.id}).accepted,false);assert.equal(f.actor.company,false);f.setFail(false);f.controller.request('review',{bagId:bag.id});f.actor.activity.phase='doing';f.setFail(true);for(let i=0;i<161;i++)f.controller.tick(.05);assert.equal(f.controller.facts().memories.length,0);assert.equal(f.controller.reviewing,true);f.setFail(false);f.controller.tick(.05);assert.equal(f.controller.facts().memories.length,1);f.controller.tick(.05);assert.equal(f.controller.facts().memories.length,1);});
test('leaving, sleeping, cancel, swapped TA and refreshed manual review never manufacture completion',()=>{for(const reason of ['away','sleep','actor','cancel','reload']){const f=setup(),bag=actualBag(f);f.controller.request('review',{bagId:bag.id});f.actor.activity.phase='doing';f.controller.tick(3);if(reason==='away')f.ctx.place='outside';if(reason==='sleep')f.ctx.free=false;if(reason==='actor')f.setActor({...f.actor,id:'other'});if(reason==='cancel')f.controller.request('cancel-review');if(reason==='reload')f.controller.cancel();f.controller.tick(.05);assert.equal(f.controller.reviewing,false);assert.equal(f.controller.facts().memories.length,0);}});
test('automatic offer respects same place, real availability and original pet activity',()=>{const f=setup();f.ctx.free=false;for(let i=0;i<500;i++)f.controller.tick(.05);assert.equal(f.controller.facts().proposal,null);f.ctx.free=true;f.actor.available=false;f.controller.tick(30);assert.equal(f.controller.facts().proposal,null);f.actor.available=true;for(let i=0;i<361;i++)f.controller.tick(.05);assert.ok(f.controller.facts().proposal);assert.equal(f.career.state.job,null);});
test('invalid saves are bounded and interests are read through canonical persona parser',()=>{const f=setup(),different={id:'a',persona:'讨厌植物和花。喜欢侦探推理，读书和探索。'};assert.notDeepEqual(Array.from({length:10},(_,i)=>careerSuggestion(f.career.state,f.actor.person,()=>i/10).profession),Array.from({length:10},(_,i)=>careerSuggestion(f.career.state,different,()=>i/10).profession));assert.deepEqual(restoreCareerCompany({actors:[{id:'bad',proposal:{profession:'unknown',status:'offered'},memories:[{bagId:'x',source:'unknown',text:'fake',at:1}]}]}).actors[0].memories,[]);});
test('refusal is remembered after refresh and informs later suggestions without forcing a job',()=>{const f=setup();f.controller.request('suggest',{random:()=>0});f.controller.request('agree');f.career.state.rng=1000;f.care.mood=0;f.care.traits.social=0;f.controller.observe('invite',f.career.request('invite',{}, {care:f.care,room:'bakery'}));const saved=createPetCareer(f.career.snapshot());assert.equal(saved.state.company.actors[0].response.outcome,'refused');assert.match(careerSuggestion(saved.state,f.actor.person,()=>0).reason,/不想营业/);assert.equal(saved.state.job,null);});
test('career company cards reuse the original full-page shell and canonical actual facts',async()=>{const {readFile}=await import('node:fs/promises'),s=await readFile(new URL('../../js/fairy-garden.js',import.meta.url),'utf8'),runtime=await readFile(new URL('../../art/pet-career/preview.mjs',import.meta.url),'utf8');assert.ok(s.includes("h(PetNote,{title:'和TA商量今天',kind:'chat'}"));assert.ok(s.includes("h(PetNote,{title:'下班后，一起看看',kind:'chat'}"));assert.ok(s.includes("h(PetPanel,{page:'career'"));assert.match(s,/companyWork\('review',\{bagId:bag.id\}\)/);assert.match(runtime,/career:\{\.\.\.x.career.summary\(\),company:companyFor\(x\).facts\(\)\}/);assert.match(runtime,/career:\{\.\.\.career.summary\(\),company:companyFor\(household.get\(petState.activePetId\)\).facts\(\)\}/);const shell=s.slice(s.indexOf('function PetPanel('),s.indexOf('function PetNote('));assert.match(shell,/COMPOSER_PAD_BOTTOM/);assert.equal((shell.match(/overflow-y-auto/g)||[]).length,1);});
test('choosing the same shop records agreement rather than a fictional disagreement',()=>{const f=setup();f.controller.request('suggest',{random:()=>0});f.controller.request('change',{profession:f.controller.facts().proposal.profession});assert.equal(f.controller.facts().proposal.status,'agreed');});
