import {turnPet} from './movement.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {createPetCare,restoreCare,careSummary,careBlock} from './care.mjs';
import {createHomeNavigation,HOME_PLACES} from './home-navigation.mjs';
const run=(care,n,options={home:true})=>{for(let i=0;i<n;i++)care.tick(1,options);};
test('legacy and corrupt care saves recover to finite bounded values without inventing offline time',()=>{const s=restoreCare({satiety:Infinity,energy:-4,mood:300,task:{kind:'bogus'},recent:[null,{text:'饭'}]});assert.equal(s.satiety,65);assert.equal(s.energy,0);assert.equal(s.mood,100);assert.equal(s.task,null);assert.equal(s.elapsed,0);assert.equal(s.bowl,0);assert.equal(s.recent.length,1);});
test('serving food leaves a real bowl supply; walking never awards meal effects',()=>{const c=createPetCare({satiety:30});assert.equal(c.request('feed').accepted,true);const before=c.state.satiety;run(c,4);assert.ok(c.state.satiety<=before);assert.equal(c.state.bowl,100);c.arrive();run(c,10);assert.ok(c.state.satiety>before+20);assert.equal(c.state.bowl,60);const s=c.snapshot();s.bowl=0;assert.equal(c.state.bowl,60);});
test('sleep restores energy only while doing it; paused/background time has no effects',()=>{const c=createPetCare({energy:20});c.request('rest');c.arrive();const s=c.snapshot();run(c,30,{home:true,paused:true});assert.deepEqual(c.snapshot(),s);run(c,20);assert.ok(c.state.energy>34);const resumed=createPetCare(c.snapshot());assert.equal(resumed.state.task.kind,'sleep');assert.equal(resumed.state.task.time,20);assert.equal(resumed.state.energy,c.state.energy);});
test('tired pets and repeated petting refuse; successful play and affection grow preferences and temperament',()=>{const tired=createPetCare({energy:10});assert.equal(tired.request('play').accepted,false);assert.equal(tired.state.task,null);const c=createPetCare({rng:1});const social=c.state.traits.social;c.request('pet');c.arrive();run(c,5);assert.equal(c.request('pet').accepted,false);assert.ok(c.state.traits.social>social);run(c,21,{home:false});assert.equal(c.request('play',{toy:'mouse'}).accepted,true);c.arrive();run(c,16);assert.equal(c.state.toys.mouse,1);assert.equal(careSummary(c.state).favoriteToy,'小老鼠');assert.ok(c.state.energy<75);});
test('idle pets choose available food or rest without player dispatch',()=>{const hungry=createPetCare({satiety:35,bowl:60});run(hungry,12);assert.equal(hungry.state.task.kind,'eat');assert.equal(hungry.state.task.source,'self');const tired=createPetCare({energy:30});run(tired,12);assert.equal(tired.state.task.kind,'sleep');});
test('home paths reach every care approach at all supported sizes and avoid furniture at every segment',()=>{for(const size of[.7,1,1.3]){const n=createHomeNavigation(size),spawn=n.restore(null);for(const origin of[spawn,...Object.values(HOME_PLACES)])for(const [key,target]of Object.entries(HOME_PLACES)){assert.ok(n.walkable(target.x,target.z),key+' target');const route=n.path(origin,target);assert.ok(route,key+' route');let from=origin;for(const p of route){for(let i=0;i<=20;i++){const t=i/20;assert.ok(n.walkable(from.x+(p.x-from.x)*t,from.z+(p.z-from.z)*t),key+' segment');}from=p;}}}});

test('a small snack is eaten over time and a full pet refuses another',()=>{const c=createPetCare({satiety:50});assert.equal(c.request('snack').accepted,true);c.arrive();run(c,6);assert.ok(c.state.satiety>55);assert.equal(c.state.task,null);assert.equal(createPetCare({satiety:95}).request('snack').accepted,false);});

test('street and home pivots turn on the shortest arc and wait to move when facing away',()=>{const t=turnPet(0,Math.PI,.05);assert.ok(Math.abs(t.heading-.15)<1e-12);assert.equal(t.canMove,false);const wrap=turnPet(Math.PI-.01,-Math.PI+.01,.05);assert.ok(wrap.canMove);assert.ok(Math.abs(wrap.heading-(Math.PI+.01))<1e-8);});
test('care buttons gray out exactly when request would surely refuse, with the same words',()=>{const cases=[[{bowl:60},'feed'],[{satiety:95},'snack'],[{energy:10},'play'],[{satiety:5,energy:80},'play'],[{cooldown:5},'pet'],[{task:{kind:'sleep',phase:'doing',place:'bed',source:'self',time:3}},'snack']];for(const [raw,action] of cases){const care=createPetCare(raw),block=careBlock(care.state,action);assert.ok(block,action+' 应该预先灰掉');const r=care.request(action,{toy:'ball'});assert.equal(r.accepted,false);assert.equal(r.text,block.text);}const fresh=createPetCare({bowl:0,satiety:50,energy:80});for(const a of ['feed','snack','play','pet'])assert.equal(careBlock(fresh.state,a),null,a+' 不该灰');});
