import {PET_WORKPLACES,petWorkplace,availableWorkplaces} from './workplaces.mjs?v=fg-dcb7068d4ae7c310';
import {deriveResidentPreferences,weightedChoice} from './resident-choice.mjs?v=fg-dcb7068d4ae7c310';
import {parcelContents,parcelSourceTitle} from './parcels.mjs?v=fg-dcb7068d4ae7c310';
const text=(x,n=200)=>typeof x==='string'?x.slice(0,n):'';
const places=new Set(PET_WORKPLACES.map(x=>x.id));
const distance=(a,b)=>a&&b?Math.hypot(a.x-b.x,a.z-b.z):Infinity;
const axes={bakery:['social','attentive'],florist:['plants','nature'],store:['explore','social'],cafe:['coffee','tea','quiet'],courier:['active','attentive'],stall:['social','explore'],alley:['explore','reading'],model:['social'],actor:['social','explore'],wedding:['plants','social'],books:['reading','quiet'],scent:['nature','active']};
export function restoreCareerCompany(raw){const seen=new Set();return {version:1,actors:(Array.isArray(raw?.actors)?raw.actors:[]).slice(-8).filter(x=>text(x?.id,80)&&!seen.has(x.id)&&seen.add(x.id)).map(x=>({id:text(x.id,80),offeredDate:text(x.offeredDate,16),response:x.response&&places.has(x.response.profession)&&['willing','refused'].includes(x.response.outcome)?{date:text(x.response.date,16),profession:x.response.profession,outcome:x.response.outcome}:null,proposal:x.proposal&&places.has(x.proposal.profession)&&['offered','agreed','changed','rest'].includes(x.proposal.status)?{date:text(x.proposal.date,16),profession:x.proposal.profession,reason:text(x.proposal.reason),status:x.proposal.status,selected:places.has(x.proposal.selected)?x.proposal.selected:'',outcome:['willing','refused'].includes(x.proposal.outcome)?x.proposal.outcome:''}:null,memories:(Array.isArray(x.memories)?x.memories:[]).slice(-16).filter(m=>text(m?.bagId)&&places.has(m.source)&&Number.isFinite(m.at)&&typeof m.text==='string').map(m=>({bagId:text(m.bagId,100),source:m.source,at:m.at,day:Math.max(1,Math.floor(m.day)||1),preference:Math.max(-1,Math.min(1,Number(m.preference)||0)),text:text(m.text,500)}))}))};}
function actorRecord(state,id,create=false){let row=state.actors.find(x=>x.id===id);if(!row&&create){row={id,offeredDate:'',response:null,proposal:null,memories:[]};state.actors.push(row);state.actors=state.actors.slice(-8);}return row;}
export function careerSuggestion(career,person,random=Math.random,species='cat'){const scores=deriveResidentPreferences(person).scores,row=actorRecord(career.company,String(person.id)),memories=row?.memories||[];const candidates=availableWorkplaces(species).filter(x=>x.id!=='stall'||Object.values(career.inventory||{}).some(n=>n>0)).map(x=>{const known=memories.filter(m=>m.source===x.id).at(-1),interest=(axes[x.id]||[]).reduce((sum,k)=>sum+(scores[k]||0),0);return {id:x.id,weight:Math.max(.08,1+interest*.18+(known?.preference||0)*1.6-(row?.response?.profession===x.id&&row.response.outcome==='refused'?.7:0)),known,interest,refused:row?.response?.profession===x.id&&row.response.outcome==='refused'};});const id=weightedChoice(candidates,random),chosen=candidates.find(x=>x.id===id)||candidates[0];return {profession:chosen.id,reason:chosen.refused?'记得上次商量去这家后，它到店不想营业。这次先去看看，愿不愿意仍由它。':chosen.known?chosen.known.preference>.2?'上次一起看过它带回的东西，它对这份工作的印象越来越好了。':chosen.known.preference<-.2?'记得它对这份工作还有点犹豫，这次可以只去看看。':'你们一起看过这家店的下班小袋子，今天也可以再去看看。':chosen.interest>0?'这家店和TA平时的兴趣有些相近，想带它一起认识看看。':'想和你商量，带它去认识一家小店。'};}
export function createCareerCompany({getCareer,getActor,getContext,save,startCompany=()=>({accepted:false}),cancelCompany=()=>{},applyDecision=()=>({accepted:true}),capture=()=>null,restore=()=>{},notify=()=>{}}){let idle=0,review=null;
 const state=()=>getCareer().company;
 const current=()=>{const a=getActor();return a?.id?{...a,id:String(a.id)}:null;};
 const write=fn=>{const external=capture(),before=structuredClone(state()),oldReview=review&&{...review};const result=fn();if(!result.accepted)return result;if(save()===false){getCareer().company=before;if(!oldReview&&review)cancelCompany();review=oldReview;restore(external,!!oldReview);return {accepted:false,text:'这件事还没有保存成功，重试保存后再商量。'};}notify(result.text);return result;};
 function request(action,options={}){const actor=current(),ctx=getContext(),career=getCareer();if(!actor)return {accepted:false,text:'先和这一档的同行者一起进入小镇。'};if(action==='cancel-review'){if(!review)return {accepted:false,text:'现在没有正在看的袋子。'};return write(()=>{review=null;return {accepted:true,text:'这次先各自忙，没看完的袋子不记成共同经历。'};});}if(!actor.available||ctx.place!=='home'||ctx.youPlace&&ctx.youPlace!=='home'||!ctx.free)return {accepted:false,text:'先等TA和它在家空下来，再一起商量。'};
 if(action==='suggest'){if(career.job||career.daily.invited||career.daily.closed||career.daily.rest)return {accepted:false,text:'它今天已经有安排了，下次空下来再商量。'};const row=actorRecord(state(),actor.id);if(row?.offeredDate===ctx.date)return {accepted:false,text:'今天已经商量过啦，去看看、换一家或休息都可以。'};return write(()=>{const next=actorRecord(state(),actor.id,true),suggestion=careerSuggestion(career,actor.person,options.random||Math.random,ctx.species);next.offeredDate=ctx.date;next.proposal={date:ctx.date,...suggestion,status:'offered',selected:'',outcome:''};return {accepted:true,text:'TA有个想法：今天去'+petWorkplace(suggestion.profession).title+'看看。'};});}
 if(action==='agree'||action==='change'||action==='rest'){const row=actorRecord(state(),actor.id),p=row?.proposal;if(!p||p.date!==ctx.date||p.status!=='offered')return {accepted:false,text:'这份提议已经商量过了，按现在的安排慢慢来。'};const selected=action==='agree'?p.profession:options.profession;if(action!=='rest'&&!places.has(selected))return {accepted:false,text:'先选一家现有的小店。'};if(career.job||career.daily.invited||career.daily.closed||career.daily.rest)return {accepted:false,text:'它今天已经有安排了，先陪完眼前这一件。'};return write(()=>{const decision=applyDecision(action==='rest'?'rest':'select',action==='rest'?{}:{profession:selected});if(!decision.accepted)return decision;p.status=action==='rest'?'rest':selected===p.profession?'agreed':'changed';p.selected=action==='rest'?'':selected;return {accepted:true,text:action==='rest'?'你想让它先歇歇，TA的提议留在今天的商量里。':p.status==='changed'?'你选了'+petWorkplace(selected).title+'，和TA原先的想法不同。到了店里再问它愿不愿意。':'商量好先去'+petWorkplace(selected).title+'看看，到了店里再问它愿不愿意。',profession:p.selected,rest:action==='rest'};});}
 if(action==='review'){const bag=career.parcels.opened.find(b=>b.id===options.bagId&&b.id.startsWith('work:')&&b.position),row=actorRecord(state(),actor.id);if(!bag)return {accepted:false,text:'先把打工的小袋子带回家，拆开以后再一起看。'};if(row?.memories.some(m=>m.bagId===bag.id))return {accepted:false,text:'这份袋子已经一起看过了，记在你们的共同小事里。'};if(review)return {accepted:false,text:'正在等TA过来，先看完这一份。'};if(distance(ctx.position,bag.position)>2)return {accepted:false,text:'先带它到自己的小袋子旁，再约TA一起看。'};return write(()=>{const started=startCompany(ctx.petId,bag.position);if(!started.accepted)return started;review={actorId:actor.id,petId:ctx.petId,bagId:bag.id,time:0,elapsed:0};return {accepted:true,text:'TA准备走到小袋子旁，到了以后陪它一起看看。'};});}
 return {accepted:false,text:'先看看今天想商量哪件事。'};}
 function observe(action,result){const actor=current(),row=actor&&actorRecord(state(),actor.id),p=row?.proposal,ctx=getContext();if(!p||p.date!==ctx.date||!['agreed','changed'].includes(p.status)||!['invite','bribe'].includes(action)||p.selected!==getCareer().selected)return;if(result.accepted&&getCareer().job)p.outcome='willing';else if(getCareer().daily.declined)p.outcome='refused';if(p.outcome)row.response={date:ctx.date,profession:p.selected,outcome:p.outcome};}
 function cancel(){if(review){review=null;cancelCompany();}idle=0;}
 function tick(dt){const actor=current(),ctx=getContext();if(review){const career=getCareer(),bag=career.parcels.opened.find(x=>x.id===review.bagId);review.elapsed+=dt;if(!actor||actor.id!==review.actorId||ctx.petId!==review.petId||ctx.place!=='home'||ctx.youPlace&&ctx.youPlace!=='home'||!ctx.free||actor.place!=='home'||!bag||!actor.company||review.elapsed>75){cancel();notify('这次先各自忙，没看完的袋子还没有记成共同经历。');return;}const near=actor.activity?.phase==='doing'&&distance(actor.position,bag.position)<1.4&&distance(ctx.position,bag.position)<2;review.time=near?review.time+dt:0;if(review.time>=8){const completed=write(()=>{const row=actorRecord(state(),actor.id,true);if(!row.memories.some(m=>m.bagId===bag.id)){const contents=parcelContents(bag).map(x=>x.count+x.unit+x.name).join('、');row.memories.push({bagId:bag.id,source:bag.source,at:Date.now(),day:bag.day,preference:career[bag.source]?.preference??career.preference??0,text:actor.name+'和你陪'+ctx.name+'看过从'+parcelSourceTitle(bag.source)+'带回的小袋子：'+contents+'。'});row.memories=row.memories.slice(-16);}review=null;return {accepted:true,text:'你们一起看过小袋子了，这件小事记进职业生活册。'};});if(completed.accepted)cancelCompany();}return;}
 if(actor?.available&&ctx.place==='home'&&(!ctx.youPlace||ctx.youPlace==='home')&&ctx.free&&!getCareer().job&&!getCareer().daily.invited&&!getCareer().daily.closed&&!getCareer().daily.rest){idle+=dt;if(idle>=18){idle=0;request('suggest');}}else idle=0;}
 function facts(){const actor=current(),ctx=getContext(),row=actor&&actorRecord(state(),actor.id);return {actorId:actor?.id||'',name:actor?.name||'TA',available:!!actor?.available&&ctx.place==='home'&&(!ctx.youPlace||ctx.youPlace==='home')&&ctx.free,proposal:row?.proposal?.date===ctx.date?structuredClone(row.proposal):null,response:row?.response?structuredClone(row.response):null,review:review&&review.actorId===actor?.id?{...review,phase:getActor()?.activity?.phase==='doing'?'looking':'walking'}:null,memories:structuredClone(row?.memories||[]),bags:getCareer().parcels.opened.filter(b=>b.id.startsWith('work:')&&b.position&&!row?.memories.some(m=>m.bagId===b.id)).map(b=>({id:b.id,title:parcelSourceTitle(b.source)+'的小袋子'}))};}
 return {request,tick,observe,cancel,facts,get reviewing(){return !!review;}};
}
