import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {createPetCareer} from './career.mjs';import {createPetCare} from './care.mjs';import {caseForJob,PET_CASES,restoreCasebook} from './detective.mjs';import {LOCAL_CASES,SERIAL_CASES} from './detective-local.mjs';import {normalizeCase} from './case-schema.mjs';import {generateModelCase,parseModelCase,modelCaseContext} from './detective-model.mjs';import {placeParcel} from './parcel-test-helpers.mjs';import {restorePetState,snapshotPetState} from './state.mjs';
const response=await createRequire(import.meta.url)('../../scripts/checks/pet-case-fixture.cjs')();
const model=()=>parseModelCase(response,'model:test');
const fixture=()=>{const c=createPetCareer({rng:1,balance:40}),body=createPetCare({mood:100,energy:85,satiety:85,traits:{social:.6,bold:.6}}),ctx={care:body.state,room:'alley',name:'团子'};c.request('select',{profession:'alley'},ctx);return {c,body,ctx};};
function clues(c,ctx){for(let i=0;i<3;i++){for(let t=0;t<(c.state.job.type==='trial'?12:18);t++)c.tick(1,ctx);const e=c.summary().event;assert.ok(e);c.request('choose',{eventId:e.id,choice:'look'},ctx);}return c.summary().event;}
function finish(c,body,ctx,choice){const e=clues(c,ctx),id=c.state.job.investigation.caseId;c.request('choose',{eventId:e.id,choice:choice||caseForJob(c.state.job).answer},ctx);assert.equal(c.request('finish',{},ctx).accepted,true);const bag=c.state.parcels.queue.at(-1);c.request('unpack',{bagId:bag.id},placeParcel(c,body,ctx));return id;}
test('44 local combinations have four causal families, distinct clues and a valid immutable answer',()=>{assert.equal(LOCAL_CASES.length,44);assert.equal(new Set(LOCAL_CASES.map(x=>x.id)).size,44);assert.equal(new Set(LOCAL_CASES.map(x=>x.family)).size,4);for(const c of [...LOCAL_CASES,...SERIAL_CASES]){assert.ok(normalizeCase(c));assert.equal(new Set(c.clues).size,3);assert.ok(c.options.some(o=>o.id===c.answer));if(c.source==='local')assert.ok(!c.id.includes(c.answer));}});
test('60 actual shifts grow beyond tutorials and complete the ordered serial, writer reload retains novelty after the 30-case book limit',()=>{let {c,body,ctx}=fixture();const ids=[];for(let day=0;day<60;day++){body.state.elapsed=day*300;Object.assign(body.state,{energy:85,mood:100,satiety:85,task:null,helper:null});c.syncDay(body.state);c.state.rng=1;assert.equal(c.request('invite',{},ctx).accepted,true);const def=caseForJob(c.state.job);if(def.source==='local')assert.ok(!ids.slice(-12).includes(def.id));ids.push(finish(c,body,ctx));if(day===32)c=createPetCareer(c.snapshot());}assert.equal(new Set(ids.slice(0,50)).size,50);assert.equal(c.state.casebook.length,30);assert.equal(c.state.detective.memory.length,60);assert.equal(c.state.detective.count,60);assert.deepEqual(c.state.detective.solvedSerials,['gift-1','gift-2','gift-3']);assert.deepEqual(createPetCareer(c.snapshot()).state.detective,c.state.detective);assert.equal(c.state.inventory.caseCard,60);});
test('leaving a serial open does not invent later chapters; a cooled-off first chapter can be checked again',()=>{const {c,body,ctx}=fixture();let serial=[];for(let day=0;day<10;day++){body.state.elapsed=day*300;Object.assign(body.state,{energy:85,mood:100,task:null,helper:null});c.syncDay(body.state);c.state.rng=1;c.request('invite',{},ctx);const def=caseForJob(c.state.job);if(def.serial)serial.push(def.id);finish(c,body,ctx,def.serial?'leave':undefined);}assert.ok(serial.length>=2);assert.ok(serial.every(id=>id==='gift-1'));assert.deepEqual(c.state.detective.solvedSerials,[]);});
test('one explicit model invocation uses system facts and one trigger, with structural proof checks and an honest retained error',async()=>{let args,n=0;const context={day:5,completed:2,pet:{name:'团子',species:'cat'},avoid:['查过的题目']};const c=await generateModelCase({active:{id:'test'},context,id:'model:test',invoke:async(...a)=>{n++;args=a;return JSON.stringify(response);},parse:JSON.parse});assert.equal(n,1);assert.equal(c.source,'model');assert.match(args[1],/团子/);assert.match(args[1],/查过的题目/);assert.equal(args[2].length,1);assert.equal(args[2][0].content,'写这一封小巷消息。');assert.equal(args[3].maxTokens,65535);assert.equal(args[3].tag,'绒绒小镇侦探案');assert.equal(args[3].noNetRetry,true);await assert.rejects(()=>generateModelCase({context,id:'model:missing',invoke:()=>{n++;},parse:JSON.parse}),/配置创作线路/);assert.equal(n,1);const bad={...response,answer:'b'};await assert.rejects(()=>generateModelCase({active:{},context,id:'model:bad',invoke:async()=>JSON.stringify(bad),parse:JSON.parse}),e=>/没有通过检查/.test(e.message)&&e.detail.includes('花桶'));});
test('model contradictions, ambiguous answers, unknown evidence references, duplicated clues and executable rewards never enter a case',()=>{for(const mutate of [x=>x.clues[0].excludes.push('a'),x=>x.clues.forEach(c=>c.excludes=[]),x=>x.clues[0].supports.push('unknown'),x=>x.clues[1].text=x.clues[0].text,x=>x.options[1].id='a']){const x=structuredClone(response);mutate(x);assert.equal(parseModelCase(x,'model:bad'),null);}const c=parseModelCase({...response,wage:999999,actions:[{kind:'giveMoney'}]},'model:test');assert.ok(c);assert.equal(c.wage,undefined);assert.equal(c.actions,undefined);});
test('prepared model case is stored once and hidden from public facts, then one real accepted shift owns its exact definition',()=>{let {c,body,ctx}=fixture();const def=model();assert.equal(c.request('prepare-case',{day:2,definition:def},ctx).accepted,false);assert.equal(c.request('prepare-case',{day:1,definition:def},ctx).accepted,true);assert.equal(c.state.balance,40);const pub=JSON.stringify(c.summary());for(const text of [def.ending,def.clues[2],'"proof"','"answer"'])assert.ok(!pub.includes(text));assert.equal(c.summary().detective.prepared.title,def.title);assert.equal(c.request('prepare-case',{day:1,definition:def},ctx).accepted,false);c=createPetCareer(c.snapshot());assert.deepEqual(c.state.detective.next,def);c.state.rng=1;c.request('invite',{},ctx);assert.deepEqual(caseForJob(c.state.job),def);assert.equal(c.state.detective.next,null);assert.equal(c.summary().job.events,undefined);assert.ok(!JSON.stringify(c.summary()).includes(def.ending));c=createPetCareer(c.snapshot());finish(c,body,ctx);assert.equal(c.summary().casebook.at(-1).source,'model');assert.equal(c.summary().casebook.at(-1).conclusion,def.ending);assert.equal(c.state.balance,72);assert.equal(c.state.inventory.caseCard,1);assert.deepEqual(createPetCareer(c.snapshot()).state.casebook,c.state.casebook);});
test('case preparation cannot replace a running case or ignore refusal and daily boundaries; discarding a letter costs no money',()=>{const {c,ctx}=fixture();c.request('prepare-case',{day:1,definition:model()},ctx);assert.equal(c.request('discard-case',{day:1},ctx).accepted,true);assert.equal(c.state.balance,40);c.request('invite',{},ctx);const saved=c.snapshot().job;assert.equal(c.request('prepare-case',{day:1,definition:model()},ctx).accepted,false);assert.deepEqual(c.snapshot().job,saved);});
test('v7 writer job and casebook without definitions remain valid and do not acquire invented serial progress',()=>{const {c,body,ctx}=fixture();c.request('invite',{},ctx);const e=clues(c,ctx);c.request('choose',{eventId:e.id,choice:caseForJob(c.state.job).answer},ctx);const ready=c.snapshot();ready.version=7;delete ready.job.investigation.definition;delete ready.detective;let old=createPetCareer(ready);assert.equal(old.state.job.phase,'ready');old.request('finish',{},ctx);const book=old.snapshot();delete book.detective;for(const x of book.casebook)delete x.definition;old=createPetCareer(book);assert.equal(old.state.casebook.length,1);assert.ok(PET_CASES.some(x=>x.id===old.state.casebook[0].caseId));assert.deepEqual(old.state.detective.solvedSerials,[]);assert.deepEqual(restoreCasebook(old.snapshot().casebook),old.state.casebook);});
test('real four-pet snapshot writers keep prepared letters, solved serials and generated definitions with their owners',()=>{const {c,body,ctx}=fixture();c.request('prepare-case',{day:1,definition:model()},ctx);const world={restore:()=>({position:{x:0,z:0},room:'home'})};const s=restorePetState({pets:[{id:'writer',profile:{name:'团子'},career:c.snapshot(),care:body.snapshot()},...['a','b','c'].map(id=>({id,career:createPetCareer({balance:55}).snapshot()}))],activePetId:'writer'},world);const r=restorePetState(snapshotPetState(s,{position:s.position,room:'home'}),world);assert.equal(r.pets[0].career.detective.next.id,'model:test');for(const other of r.pets.slice(1)){assert.equal(other.career.detective.next,null);assert.deepEqual(other.career.detective.memory,[]);assert.equal(other.career.balance,55);}});

test('model author input uses only the active pet public facts and its remembered titles, with no other residents or mainline',()=>{const raw=modelCaseContext({pet:{name:'团子',species:'cat',traits:{social:.5},recent:[{text:'私下照料'}]},pets:[{name:'别人的宠物'}],mainline:'主线私事',dialogs:['角色私聊'],career:{day:4,detective:{completed:3,avoid:['查过的题目'],next:model()},workplaces:[{title:'花店'}]}});const text=JSON.stringify(raw);assert.ok(text.includes('团子')&&text.includes('查过的题目'));for(const secret of ['别人的宠物','主线私事','角色私聊','私下照料',response.ending])assert.ok(!text.includes(secret));});
