// Different causes carry their own observable evidence, rather than a name swap on one solution.
const shops=[['bakery','面包店','打包台'],['florist','花店','包花台'],['store','便利店','货架旁'],['cafe','咖啡店','窗边小桌']];
const paper=[['bag','空面包纸袋'],['card','空白留言卡'],['ribbon','薄纸丝带']];
const round=[['bell','圆滚滚的小铃铛'],['button','圆木扣'],['ball','小木球']];
const other=[['stamp','小爪印印章'],['mitten','小针织手套']];
export const LOCAL_CASES=shops.flatMap(([shop,name,table])=>[
 ...paper.map(([item,object],index)=>({id:`local:${shop}:0${index}`,title:name+'门外的'+object,intro:name+'的'+table+'少了一份'+object+'，小巷店员收到消息，请它帮忙看看东西去了哪里。',clues:[table+'的门朝街口开着；原来放东西的位置没有撕扯或啃咬痕迹。','门外落着一条干叶子，沿着墙角一直延到长凳边。','长凳边压着那份'+object+'，上面的店章与'+name+'的一样，叶子也一起停在这里。'],options:[{id:'wind',label:'被穿过门口的风卷到了长凳边'},{id:'trade',label:'小邻居叼去交换了玩具'},{id:'tidy',label:'店员收进了店内的抽屉'}],answer:'wind',ending:'那份'+object+'被穿堂风卷出'+name+'，与干叶子一起停在长凳边。店员把它带回'+table+'，这次给轻飘飘的东西压上了小木块。',hint:'沿着干叶子走过的方向，再核对店章和门口的位置。',source:'local',family:'wind'})),
 ...round.map(([item,object],index)=>({id:`local:${shop}:1${index}`,title:name+'长凳下的'+object,intro:name+'擦过'+table+'以后，'+object+'不见了。门窗一直关着，长凳那边偶尔传来轻轻一响。',clues:[table+'边到长凳之间，有一条细细的滚动痕迹。','长凳脚下留着圆形碰印，没有纸袋、叶子或叼咬的痕迹。','店员挪开长凳，从墙边取出了完好的'+object+'；它刚好能沿地板的浅坡滚过去。'],options:[{id:'trade',label:'小邻居从门外叼走了它'},{id:'roll',label:'擦桌时滑落，沿浅坡滚到长凳下'},{id:'wind',label:'从开着的窗户吹到了街上'}],answer:'roll',ending:'擦拭'+table+'时，'+object+'滑落后沿浅坡滚进长凳下。东西找到了，店员在台边加了一只浅浅的收纳盘。',hint:'把门窗状态、滚动痕迹和找到东西的位置对起来。',source:'local',family:'roll'})),
 ...other.map(([item,object],index)=>({id:`local:${shop}:2${index}`,title:name+'的'+object+'交换物',intro:name+'的'+object+'没在原处，柜台上却多了一件旧布玩具。小巷店员请它看看这两件事有没有关系。',clues:['旧布玩具旁留着几根毛，'+table+'到门边还有一串小爪印。','门外的小邻居嘴里叼着'+object+'；东西完整，没有被吃掉或吹散。','小邻居把'+object+'放到旧布玩具旁，又推了推玩具。店员认出玩具是它刚从自己窝里带来的。'],options:[{id:'tidy',label:'店员清台面时收进了抽屉'},{id:'wind',label:'两件东西一起被风卷到门口'},{id:'trade',label:'小邻居拿自己的旧玩具来交换'}],answer:'trade',ending:'小邻居想用自己的旧布玩具交换'+object+'。店员把交换物都摆好，告诉它先等主人拿主意；'+name+'的东西仍留在店里。',hint:'看看谁带来旧玩具，又是谁把两件东西摆到了一起。',source:'local',family:'trade'})),
 ...paper.map(([item,object],index)=>({id:`local:${shop}:3${index}`,title:name+'的'+object+'空位置',intro:name+'的'+table+'忽然变得整齐，原本留着的'+object+'找不到了。店员托小巷帮忙核对今天的整理记录。',clues:[table+'擦拭的痕迹一直延到桌角，原来放东西的位置没有散落碎屑。','收纳抽屉贴着一张新的整理清单，其中写了'+object+'，数量与原来一致。','店员打开抽屉，取出清单上那份完好的'+object+'，并找到自己刚写下的收纳时间。'],options:[{id:'tidy',label:'整理台面时收进了抽屉'},{id:'trade',label:'小邻居换走后带回了自己的窝'},{id:'wind',label:'被风吹散在店外的街道上'}],answer:'tidy',ending:object+'已经按清单收进'+name+'的抽屉，台面空下来是今天整理的结果。店员在'+table+'留了小字条，让接班的人也能找到它。',hint:'对照清单、数量和抽屉里实际取出的东西。',source:'local',family:'tidy'}))
]);
export const SERIAL_CASES=[
 {id:'gift-1',title:'悄悄留下的小纸片',intro:'花店的小邻居最近总把小纸片送到咖啡店。店员请小巷帮忙看看它在忙什么，这封消息是街角筹备的第一回。',clues:['纸片都剪成一样的长方形，背面有折线，边缘没有啃过的痕迹。','咖啡店空桌旁摆着几张折立起来的纸片，每张都留了写名字的位置。','小邻居把新送来的纸片折好，立到桌前，又量了量几张纸片之间的距离。'],options:[{id:'nest',label:'收集碎纸给自己的窝加垫子'},{id:'cards',label:'准备能立在桌上的小桌签'},{id:'clean',label:'拿纸片擦拭咖啡店的桌子'}],answer:'cards',ending:'纸片是在做小桌签。咖啡店先把空桌留好，小邻居还没说准备邀请谁；这条消息先收进卷宗，等街角送来下一封。',hint:'看看纸片的折线、站立方式和留空的位置。',source:'series',family:'gift'},
 {id:'gift-2',title:'桌签旁的小布包',intro:'上回查明小邻居在做桌签。过了几班，花店又送来消息：咖啡店那张桌上多了一个系丝带的小布包。',clues:['小布包已经缝好，丝带扎得整齐，附近没有拆开的包裹或寄件单。','一张桌签上画了圆耳朵和小爪子，布包也绣着同样的图案。','小邻居把布包放到那张桌签前，旁边的空卡写着「留给新朋友」。'],options:[{id:'gift',label:'把布包作为新朋友的见面礼'},{id:'parcel',label:'准备寄给街外商店的快递'},{id:'repair',label:'等着拆线重新修补旧布包'}],answer:'gift',ending:'布包是给新朋友准备的见面礼，图案和那张桌签相配。店员把它好好留在桌上，邀请卡还没送出，筹备仍在继续。',hint:'核对图案、桌签上的位置和卡片里留下的话。',source:'series',family:'gift'},
 {id:'gift-3',title:'终于坐满的小圆桌',intro:'桌签和见面礼都已查明。又过了几班，小巷收到最后一封消息：咖啡店那张留着的小圆桌终于来了客人。',clues:['桌上立着先前做好的桌签，绣着圆耳朵的小布包放在新来的小狗面前。','邻居们只带了自己的杯子和小点心，桌旁没有价签或收费箱。','新来的小狗翻开邀请卡，里面写着欢迎搬到这条街；它把小布包收到了自己的小篮子里。'],options:[{id:'sale',label:'邻居们临时摆了一场收费小集市'},{id:'welcome',label:'大家为刚搬来的小狗办欢迎小聚'},{id:'shift',label:'小狗第一次来咖啡店接班值班'}],answer:'welcome',ending:'小邻居一直在为新搬来的小狗准备欢迎小聚。桌签和布包都有了去处，大家慢慢坐下来吃点心，这条街角连载也完整留在它的卷宗里。',hint:'把桌签、见面礼和邀请卡上写的来意连起来。',source:'series',family:'gift'}
];
