import {normalizeCase,caseSourceLabel} from './case-schema.mjs?v=fg-837facea1cb3043b';
import {LOCAL_CASES,SERIAL_CASES} from './detective-local.mjs?v=fg-837facea1cb3043b';
// Local case definitions. Only collected clues and submitted conclusions enter game/chat facts.
export const PET_CASES=[
 {id:'bell',title:'不见的小铃铛',intro:'小巷门垫上的玩具铃铛不见了。门一直关着，店员请它看看铃铛去了哪里。',clues:['门垫到长凳之间，有一条细细的滚动痕迹。','长凳下面的缝隙很窄，小爪子伸不进去。','店员抬起长凳，里面露出和门垫上一样的蓝色绳结。'],options:[{id:'visitor',label:'被路过的客人带走了'},{id:'rolling',label:'滚进了长凳下面'},{id:'wind',label:'被风吹到了屋外'}],answer:'rolling',ending:'铃铛滚到了长凳下面，蓝色绳结和原来的一样。店员取出铃铛，重新放回门垫。',hint:'再对照滚动痕迹、长凳缝隙和蓝色绳结。'},
 {id:'paper-bag',title:'跑到花桶边的纸袋',intro:'一个空面包纸袋出现在小巷的花桶边。没有人来认领，店员想知道它怎么过来的。',clues:['纸袋里面是空的，袋口朝着街口。','纸袋旁有一路干叶子，从街口一直停到花桶边。','面包店说空纸袋刚从门口被一阵风卷走，袋角也画着同样的小麦。'],options:[{id:'wind',label:'空纸袋被风卷到了这里'},{id:'neighbor',label:'小邻居来这里吃过面包'},{id:'shopkeeper',label:'店员把花装进了面包袋'}],answer:'wind',ending:'空纸袋和干叶子被同一阵风卷到花桶边。店员把纸袋还给面包店，没有谁偷吃面包。',hint:'看看袋子有没有装过东西，以及干叶子走的方向。'},
 {id:'wet-paws',title:'门口的一串湿爪印',intro:'小巷门口留下几枚湿爪印，地上却没有下雨。它想知道小邻居刚才忙什么去了。',clues:['湿爪印从花桶边一直延到门垫，越往门垫越浅。','花桶旁的水壶倒着，旁边的小球是干的。','花店店员说小邻居来陪浇花，踩到了刚洒出的水。'],options:[{id:'rain',label:'小邻居刚从雨里跑回来'},{id:'ball',label:'小邻居追着小球撞倒了水壶'},{id:'watering',label:'小邻居陪浇花时踩到了水'}],answer:'watering',ending:'小邻居陪浇花时踩到了洒出的水，走到门垫前爪子已经快干了。水壶被扶好，这串脚印也慢慢干了。',hint:'把水壶、小球和花店店员的话放在一起看。'}
];
const choices=clue=>[{id:'look',label:'收好线索，继续看看',note:'收好一条线索：'+clue,tip:2,like:.06,trait:'bold'},{id:'ask',label:'陪它和店员一起核对',note:'和店员核对了线索：'+clue,tip:3,like:.05,trait:'social'},{id:'easy',label:'先歇歇，再记下这一条',note:'按它的节奏记下线索：'+clue,tip:0,like:.09,energy:4}];
export const caseEvents=c=>c.clues.map((clue,i)=>({id:c.id+':'+i,title:c.title+' · 线索 '+(i+1),text:clue,options:choices(clue)}));
export const DETECTIVE_EVENTS=PET_CASES.flatMap(caseEvents);
export const petCase=id=>[...PET_CASES,...LOCAL_CASES,...SERIAL_CASES].find(c=>c.id===id)||null;
export const caseEventIds=c=>c.clues.map((_,i)=>c.id+':'+i);
export function caseForJob(j){if(j?.profession!=='alley'||!Array.isArray(j.events)||j.events.length!==3)return null;const c=normalizeCase(j.investigation?.definition)||normalizeCase(petCase(j.investigation?.caseId))||PET_CASES.map(normalizeCase).find(c=>caseEventIds(c).every((id,i)=>j.events[i]===id));return c&&caseEventIds(c).every((id,i)=>j.events[i]===id)?c:null;}
export function restoreInvestigation(raw,j){const c=caseForJob(j);if(!c)return null;const conclusion=j.index===3&&[c.answer,'leave'].includes(raw?.conclusion)?raw.conclusion:'';return {caseId:c.id,definition:raw?.definition?c:null,conclusion,by:conclusion&&typeof raw.by==='string'?raw.by.slice(0,24):'',attempts:[...new Set((Array.isArray(raw?.attempts)?raw.attempts:[]).filter(id=>c.options.some(o=>o.id===id)&&id!==c.answer))]};}
export function investigationView(j){const c=caseForJob(j);if(!c)return null;const solved=j.investigation?.conclusion===c.answer,open=j.investigation?.conclusion==='leave';return {caseId:c.id,title:c.title,intro:c.intro,source:c.source,sourceLabel:caseSourceLabel(c),serial:c.serial||null,clues:c.clues.slice(0,j.index).map((text,i)=>({id:c.id+':'+i,text})),outcome:solved?'solved':open?'open':'pending',conclusion:solved?c.ending:open?'先把三条线索留下，这次还没有认定结论。':'',by:j.investigation?.by||''};}
export function deductionEvent(j){const c=caseForJob(j);if(!c||j.phase!=='ready'||j.investigation?.conclusion)return null;return {id:j.id+':deduction',title:'把三条线索拼起来',text:'这次发生了什么？可以再看一遍上面的线索，或先把悬案留下。',kind:'deduction',options:[...c.options,{id:'leave',label:'先留作悬案，不认定结论'}].map(o=>({...o}))};}
export function chooseDeduction(j,choice,by){const c=caseForJob(j),e=deductionEvent(j);if(!e||!e.options.some(o=>o.id===choice))return {accepted:false,text:'选一个当前卷宗里的结论吧。'};if(choice!=='leave'&&choice!==c.answer){if(!j.investigation.attempts.includes(choice))j.investigation.attempts.push(choice);return {accepted:false,text:'这个结论还对不上。'+c.hint};}j.investigation.conclusion=choice;j.investigation.by=by;return {accepted:true,keepPanel:true,solved:choice===c.answer,text:choice===c.answer?c.ending:'三条线索先收好了，这次作为悬案留下。'};}
export function restoreCasebook(raw){const seen=new Set(),out=[];for(const x of Array.isArray(raw)?raw:[]){const c=normalizeCase(x?.definition)||normalizeCase(petCase(x?.caseId));if(!c||typeof x.id!=='string'||!Number.isFinite(x.day)||![c.answer,'leave'].includes(x.conclusion)||seen.has(x.id))continue;seen.add(x.id);out.push({id:x.id.slice(0,80),day:Math.max(1,Math.floor(x.day)),wage:Math.max(0,Math.floor(Number.isFinite(x.wage)?x.wage:0)),...restoreInvestigation(x,{profession:'alley',events:caseEventIds(c),index:3,investigation:{definition:c}})});}return out.slice(-30);}
export const casebookView=book=>book.map(x=>({...investigationView({profession:'alley',events:caseEventIds(normalizeCase(x.definition)||petCase(x.caseId)),index:3,investigation:x}),id:x.id,day:x.day,wage:x.wage}));
export function restoreDetective(raw,book=[]){const memory=(Array.isArray(raw?.memory)?raw.memory:book.map(x=>({id:x.caseId,title:(normalizeCase(x.definition)||petCase(x.caseId))?.title,family:(normalizeCase(x.definition)||petCase(x.caseId))?.family||'classic'}))).filter(x=>typeof x?.id==='string'&&typeof x.title==='string').slice(-128).map(x=>({id:x.id.slice(0,80),title:x.title.slice(0,48),family:typeof x.family==='string'?x.family.slice(0,40):'classic'}));const solved=new Set((Array.isArray(raw?.solvedSerials)?raw.solvedSerials:book.filter(x=>x.conclusion!=='leave').map(x=>x.caseId)).filter(id=>SERIAL_CASES.some(c=>c.id===id)));const titles=[...new Set([...(Array.isArray(raw?.titles)?raw.titles:[]),...memory.map(x=>x.title)].filter(x=>typeof x==='string'&&x.length<=48))].slice(-1000);return {titles,next:normalizeCase(raw?.next)?.source==='model'?normalizeCase(raw.next):null,memory,solvedSerials:SERIAL_CASES.filter((c,i)=>solved.has(c.id)&&SERIAL_CASES.slice(0,i).every(p=>solved.has(p.id))).map(c=>c.id),count:Math.max(memory.length,Math.floor(Number.isFinite(raw?.count)?Math.max(0,raw.count):book.length))};}
export function chooseCase(book,random,progress=restoreDetective(null,book)){
 const seen=new Set(progress.memory.map(x=>x.id));const unseen=PET_CASES.filter(c=>!seen.has(c.id));if(unseen.length)return normalizeCase(unseen[Math.floor(random()*unseen.length)]);
 const serial=SERIAL_CASES[progress.solvedSerials.length],recent=progress.memory.slice(-12),lastFamilies=new Set(progress.memory.slice(-2).map(x=>x.family));
 if(serial&&progress.count%3===0&&!progress.memory.slice(-3).some(x=>x.id===serial.id))return normalizeCase(serial);
 const fresh=LOCAL_CASES.filter(c=>!seen.has(c.id)),pool=fresh.length?fresh:LOCAL_CASES.filter(c=>!recent.some(x=>x.id===c.id)),varied=pool.filter(c=>!lastFamilies.has(c.family));const pick=varied.length?varied:pool;return normalizeCase(pick[Math.floor(random()*pick.length)]);
}
export function rememberCase(progress,j){const c=caseForJob(j);if(!c)return;progress.memory.push({id:c.id,title:c.title,family:c.family});progress.memory=progress.memory.slice(-128);progress.count++;if(!progress.titles.includes(c.title))progress.titles.push(c.title);progress.titles=progress.titles.slice(-1000);if(c.serial&&j.investigation.conclusion===c.answer&&!progress.solvedSerials.includes(c.id))progress.solvedSerials.push(c.id);}
export function detectiveView(s){return {prepared:s.next?{title:s.next.title,intro:s.next.intro,sourceLabel:caseSourceLabel(s.next)}:null,avoid:s.titles.slice(),completed:s.count,serial:s.solvedSerials.length?{name:'街角的筹备',solved:s.solvedSerials.length,total:3}:null};}
