import {realTime} from '../fairy-garden/real-clock.mjs?v=fg-c27bf8a6a71ea07b';
import {restorePetBirth} from './birth.mjs?v=fg-c27bf8a6a71ea07b';
import {homeGood,furniturePoint,PET_HOME_GOODS} from './furnishings.mjs?v=fg-c27bf8a6a71ea07b';
export const PET_RECIPES=[
 {id:'crumb',name:'温水软粮小点',ingredients:{snack:1},detail:'把宠物自己的零食用温水泡软，捣成一口大的小点。',flavor:'soft'},
 {id:'crunch',name:'原味零食小粒',ingredients:{snack:2},detail:'只用它原有的宠物零食，分成方便慢慢嚼的小粒。',flavor:'crunch'}
];
const count=v=>Number.isFinite(v)?Math.max(0,Math.min(1e7,Math.floor(v))):0;
const text=(v,n=160)=>typeof v==='string'?v.slice(0,n):'';
const key=v=>text(v,80);
const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))?v:'';
const wishKinds=['bed','gift','friends','taste','corner'];
export function restoreDomesticPet(raw){return {wish:raw?.wish&&wishKinds.includes(raw.wish.kind)?{id:key(raw.wish.id),kind:raw.wish.kind,title:text(raw.wish.title),target:key(raw.wish.target),baseline:count(raw.wish.baseline),created:date(raw.wish.created),paused:!!raw.wish.paused}:null,wishDate:date(raw?.wishDate),seq:count(raw?.seq),memories:(Array.isArray(raw?.memories)?raw.memories:[]).filter(x=>key(x?.id)&&text(x.text)&&Number.isFinite(x.at)).map(x=>({id:key(x.id),at:x.at,text:text(x.text),kind:key(x.kind)})),tastes:Object.fromEntries(PET_RECIPES.map(r=>[r.id,{count:count(raw?.tastes?.[r.id]?.count),liked:count(raw?.tastes?.[r.id]?.liked),makers:Object.fromEntries(Object.entries(raw?.tastes?.[r.id]?.makers||{}).filter(([k,v])=>key(k)&&typeof v?.name==='string').map(([k,v])=>[key(k),{name:text(v.name,24),count:count(v.count)}]))}])),celebrated:(Array.isArray(raw?.celebrated)?raw.celebrated:[]).filter(x=>typeof x==='string'),gifts:(Array.isArray(raw?.gifts)?raw.gifts:[]).filter(x=>typeof x?.peer==='string'&&Number.isFinite(x.at)).map(x=>({peer:key(x.peer),item:key(x.item),at:x.at}))};}
export function restoreDomestic(raw,ids=[]){const valid=new Set(ids),t=raw?.task,task=t&&valid.has(t.petId)&&['cook','celebrate'].includes(t.kind)&&key(t.id)&&['walking','mix','portion','ready','gather'].includes(t.phase)&&(t.kind!=='cook'||PET_RECIPES.some(r=>r.id===t.recipe))?{id:key(t.id),petId:key(t.petId),kind:t.kind,phase:t.phase,recipe:key(t.recipe),actor:key(t.actor),name:text(t.name,24)||'你',time:Number.isFinite(t.time)?Math.max(0,Math.min(30,t.time)):0,at:Number.isFinite(t.at)?t.at:0,date:date(t.date),occasion:key(t.occasion),gift:key(t.gift),consumed:!!t.consumed,point:t.point&&Number.isFinite(t.point.x)&&Number.isFinite(t.point.z)?{x:t.point.x,z:t.point.z}:null}:null;return {version:1,seq:count(raw?.seq),task,batches:(Array.isArray(raw?.batches)?raw.batches:[]).filter(x=>key(x?.id)&&valid.has(x.petId)&&PET_RECIPES.some(r=>r.id===x.recipe)&&count(x.remaining)>0).map(x=>({id:key(x.id),petId:key(x.petId),recipe:key(x.recipe),actor:key(x.actor),name:text(x.name,24),at:Number.isFinite(x.at)?x.at:0,remaining:Math.min(3,count(x.remaining))})),serving:raw?.serving&&valid.has(raw.serving.petId)&&PET_RECIPES.some(r=>r.id===raw.serving.recipe)&&key(raw.serving.id)?{id:key(raw.serving.id),petId:key(raw.serving.petId),recipe:key(raw.serving.recipe),actor:key(raw.serving.actor),name:text(raw.serving.name,24),after:Number.isFinite(raw.serving.after)?raw.serving.after:0,at:Number.isFinite(raw.serving.at)?raw.serving.at:0}:null};}
export function occasions(entry,at=Date.now()){const b=restorePetBirth(entry.birth);if(!b)return [];const now=realTime(null,at),y=Number(now.date.slice(0,4));return [['birthday','生日',b.birthday],['adopted','领养纪念日',b.adoptedOn]].filter(([, ,d])=>d).map(([kind,name,d])=>{const annual=year=>{const target=year+d.slice(4);return d.endsWith('-02-29')&&new Date(target+'T12:00:00Z').getUTCMonth()!==1?year+'-02-28':target;};const thisYear=annual(y),target=thisYear<now.date?annual(y+1):thisYear;return {kind,name,date:target,id:kind+':'+target,today:now.date>d&&target===now.date,done:entry.domestic.celebrated.includes(kind+':'+target),origin:d};});}
function memory(entry,id,message,kind,at){if(entry.domestic.memories.some(x=>x.id===id))return false;entry.domestic.memories.push({id,at,text:message,kind});return true;}
function tasteTotal(d,target){return Object.values(d.tastes).reduce((sum,t)=>sum+Object.entries(t.makers).filter(([actor])=>target==='companion'?actor!=='you':actor==='you').reduce((n,[,m])=>n+m.count,0),0);}
function friendTotal(social,id){return Object.entries(social?.pairs||{}).filter(([k])=>k.split('|').includes(id)).reduce((sum,[,v])=>sum+(v.window||0)+(v.ball||0)+(v.reconcile||0),0);}
export function choosePetWish(entry,{date:today,neighbors=[],social,hasCompanion=false}={}){const d=entry.domestic;if(d.wish||d.wishDate===today||!entry.configured)return false;const c=entry.career,b=entry.care,recent=d.memories.filter(x=>x.kind==='wish').slice(-2).map(x=>x.text),choices=[];
 if(!c.furnishings.sleep)choices.push({kind:'bed',target:'cloudBed',title:'想攒钱买一个自己的软窝',baseline:b.rests.own||0});
 if(c.furnishings.sleep)choices.push({kind:'corner',target:c.furnishings.sleep,title:'想在自己挑的小窝里好好睡一觉',baseline:b.rests.own||0});
 const friend=neighbors.find(x=>x.familiar);if(friend&&['flower','sticker','bookmark','coaster'].some(id=>c.inventory[id]>0))choices.push({kind:'gift',target:friend.id,title:'想给'+friend.name+'送一份自己的小礼物',baseline:d.gifts.filter(x=>x.peer===friend.id).length});
 if(social&&Object.keys(social.pairs).some(k=>k.split('|').includes(entry.id)))choices.push({kind:'friends',target:'',title:'想和家里的伙伴一起待一会儿',baseline:friendTotal(social,entry.id)});
 choices.push({kind:'taste',target:hasCompanion?'companion':'you',title:hasCompanion?'想尝尝你和TA一起做的小点心':'想尝尝你亲手做的小点心',baseline:tasteTotal(d,hasCompanion?'companion':'you')});
 const scores=choices.map(w=>({w,score:(w.kind==='bed'?2:w.kind==='corner'&&b.energy<55?3:w.kind==='gift'?b.traits.social*3:w.kind==='friends'?b.traits.social*2:w.kind==='taste'&&hasCompanion?1.6:1.4)-(recent.some(t=>t.includes(w.title))?4:0)})).sort((a,b)=>b.score-a.score);
 d.seq++;d.wish={...scores[0].w,id:'wish-'+entry.id+'-'+d.seq,created:today,paused:false};d.wishDate=today;return true;
}
export function settlePetWish(entry,{social,at=Date.now()}={}){const d=entry.domestic,w=d.wish;if(!w||w.paused)return false;const done=(w.kind==='bed'||w.kind==='corner')?!!entry.career.furnishings.sleep&&(entry.care.rests.own||0)>w.baseline:w.kind==='gift'?d.gifts.filter(x=>x.peer===w.target).length>w.baseline:w.kind==='friends'?friendTotal(social,entry.id)>w.baseline:tasteTotal(d,w.target)>w.baseline;if(!done)return false;memory(entry,w.id,'小心愿实现了：'+w.title+'。','wish',at);d.wish=null;d.wishDate=realTime(null,at).date;return true;}
export function domesticView(state,petId,at=Date.now()){const p=state.pets.find(x=>x.id===petId);if(!p)return null;return {name:p.profile.name,petId,wish:structuredClone(p.domestic.wish),memories:structuredClone(p.domestic.memories).reverse(),occasions:occasions(p,at),task:state.domestic.task?{...structuredClone(state.domestic.task),petName:state.pets.find(p=>p.id===state.domestic.task.petId)?.profile.name||'小伙伴'}:null,serving:state.domestic.serving?structuredClone(state.domestic.serving):null,batches:state.domestic.batches.filter(x=>x.petId===petId).map(x=>({...x,title:PET_RECIPES.find(r=>r.id===x.recipe).name})),recipes:PET_RECIPES.map(r=>({...r,available:Object.entries(r.ingredients).every(([k,n])=>p.career.inventory[k]>=n),taste:structuredClone(p.domestic.tastes[r.id])})),gifts:['flower','sticker','bookmark','coaster'].filter(id=>p.career.inventory[id]>0),furniture:PET_HOME_GOODS.filter(x=>x.kind==='rest'&&p.career.inventory[x.id]>0).map(x=>({id:x.id,name:x.name,point:furniturePoint(p.career,state.pets.findIndex(x=>x.id===petId),x.id),selected:p.career.furnishings.sleep===x.id}))};}
export function domesticRequest(state,petId,action,options={},ctx={}){const p=state.pets.find(x=>x.id===petId),s=state.domestic;if(!p)return {accepted:false,text:'没有找到这只小伙伴。'};const yes=text=>({accepted:true,text}),no=text=>({accepted:false,text}),at=ctx.at||Date.now(),today=realTime(null,at).date;
 if(action==='wish-pause'||action==='wish-resume'){if(!p.domestic.wish)return no('它还没有新的小心愿。');p.domestic.wish.paused=action==='wish-pause';return yes(action==='wish-pause'?'先留着这个心愿，按自己的节奏来。':'这个小心愿又拿出来啦。');}
 if(action==='cancel'){if(!s.task)return no('现在没有正在做的小事。');ctx.stop?.(s.task);s.task=null;return yes('先把这次收好；已经做出的点心仍留着，没有完成的小事不记完成。');}
 if(action==='gift'){if(!ctx.home||!ctx.neighborReady?.(options.peer)||!['flower','sticker','bookmark','coaster'].includes(options.item)||p.career.inventory[options.item]<1)return no('先让熟悉的朋友实际来到家里，挑一件已经收好的小礼物。');p.career.inventory[options.item]--;p.domestic.gifts.push({peer:options.peer,item:options.item,at});memory(p,'gift-'+(++s.seq),'把自己带回的'+({flower:'小花',sticker:'贴纸',bookmark:'书签',coaster:'杯垫'}[options.item])+'送给了'+ctx.neighborName(options.peer)+'。','gift',at);ctx.friendGift?.(options.peer);return yes('它把自己的小礼物分给了朋友，这件事留在它们的记忆里。');}
 if(action==='serve'){if(s.serving||s.task)return no('先完成眼前这件小事。');const batch=s.batches.find(x=>x.id===options.id&&x.petId===petId&&x.remaining>0);if(!batch||!ctx.free)return no('先在家里等它空下来，再拿一口点心给它。');const result=ctx.serve?.(batch);if(!result?.accepted)return result||no('它这会儿还不想吃。');batch.remaining--;s.serving={...batch,id:'taste-'+(++s.seq),after:p.care.elapsed,at};s.batches=s.batches.filter(x=>x.remaining>0);return yes('端出一小口'+PET_RECIPES.find(r=>r.id===batch.recipe).name+'，等它实际吃完再记口味。');}
 if(s.task||s.serving)return no('先完成眼前这件小事，再准备下一份。');
 if(!ctx.home||!ctx.free)return no('先实际回家，等它把手头的事做完。');
 if(action==='cook'){const r=PET_RECIPES.find(x=>x.id===options.recipe);if(!r||!Object.entries(r.ingredients).every(([k,n])=>p.career.inventory[k]>=n))return no('先收好配方需要的宠物零食，材料还不够。');if(s.batches.filter(x=>x.petId===petId).length>=6)return no('先把留着的点心慢慢吃完。');const actor=options.actor==='companion'?ctx.person?.id:'you';if(!actor)return no('先等TA实际回到家里。');const task={id:'home-'+(++s.seq),kind:'cook',petId,recipe:r.id,actor,name:actor==='you'?'你':ctx.person.name,phase:'walking',time:0,at,date:today,point:ctx.point,consumed:false};const start=ctx.start?.(task);if(!start?.accepted)return start||no('这里暂时准备不过来。');s.task=task;return yes('准备和'+task.name+'一起做'+r.name+'，先走到小料理盘旁。');}
 if(action==='celebrate'){const event=occasions(p,at).find(x=>x.id===options.occasion&&x.today&&!x.done);if(!event)return no('生日和领养纪念日按真实日期来，到当天再一起庆祝。');if(!ctx.person)return no('等TA回家，再一起过这一天。');const gift=options.gift;if(gift&&!((p.career.inventory[gift]||0)>0))return no('先选一件它已经有的小礼物。');const task={id:'home-'+(++s.seq),kind:'celebrate',petId,actor:ctx.person.id,name:ctx.person.name,phase:'walking',time:0,at,date:today,occasion:event.id,gift:gift||'',point:ctx.point};const start=ctx.start?.(task);if(!start?.accepted)return start||no('等大家空下来，再围过来。');s.task=task;return yes('你和'+task.name+'准备陪'+p.profile.name+'过'+event.name+'，等它走过来。');}
 return no('没有找到这件小事。');
}
// Preparation time advances only while the original actors have actually arrived.
export function domesticTick(state,dt,ctx={}){if(!Number.isFinite(dt)||dt<=0||ctx.paused)return null;const s=state.domestic,at=ctx.at||Date.now(),now=realTime(null,at).date;let changed=false;
 for(const p of state.pets){changed=choosePetWish(p,{date:now,social:state.social,neighbors:ctx.neighbors?.(p.id)||[],hasCompanion:!!ctx.person})||changed;changed=settlePetWish(p,{social:state.social,at})||changed;}
 const serving=s.serving;if(serving){const p=state.pets.find(x=>x.id===serving.petId),done=p?.care.recent.some(x=>x.completed&&x.at>=serving.after&&x.wallAt>=serving.at&&x.text.includes('零食'));if(done){const r=p.domestic.tastes[serving.recipe],liked=(serving.recipe==='crunch'?p.care.traits.active:p.care.traits.social)>=.45;r.count++;if(liked)r.liked++;const maker=r.makers[serving.actor]||(r.makers[serving.actor]={name:serving.name,count:0});maker.count++;memory(p,serving.id,serving.name+'做的'+PET_RECIPES.find(r=>r.id===serving.recipe).name+'，它'+(liked?'认真吃完，喜欢这种口感。':'慢慢吃完，暂时没有特别偏爱这种口感。'),'taste',at);s.serving=null;changed=true;}else if(!p||!p.care.task){s.serving=null;changed=true;}}
 const t=s.task;if(!t)return changed?{changed:true}:null;const p=state.pets.find(x=>x.id===t.petId);
 if(!p||at-preparationLastSeen(state,t)>60000&&!ctx.online){ctx.stop?.(t);s.task=null;return {changed:true,cancelled:true};}
 if(!ctx.present?.(t)){ctx.stop?.(t);s.task=null;return {changed:true,cancelled:true};}
 if(!ctx.arrived?.(t))return changed?{changed:true}:null;
 if(t.phase==='walking'){t.phase=t.kind==='cook'?'mix':'gather';t.time=0;changed=true;}
 t.time+=Math.min(.1,dt);
 if(t.kind==='cook'&&t.phase==='mix'&&t.time>=4){const r=PET_RECIPES.find(r=>r.id===t.recipe);if(!Object.entries(r.ingredients).every(([k,n])=>p.career.inventory[k]>=n)){ctx.stop?.(t);s.task=null;return {changed:true,text:'材料已经用在别处，这份还没有做出来。'};}t.phase='portion';t.time=0;return {changed:true};}
 if(t.kind==='cook'&&t.phase==='portion'&&t.time>=4){const r=PET_RECIPES.find(r=>r.id===t.recipe);if(!Object.entries(r.ingredients).every(([k,n])=>p.career.inventory[k]>=n)){ctx.stop?.(t);s.task=null;return {changed:true,text:'材料已经用在别处，这份没有做出来。'};}for(const[k,n]of Object.entries(r.ingredients))p.career.inventory[k]-=n;s.batches.push({id:t.id,petId:t.petId,recipe:t.recipe,actor:t.actor,name:t.name,at,remaining:2});memory(p,t.id,t.name+'把'+p.profile.name+'自己的宠物零食做成了'+PET_RECIPES.find(r=>r.id===t.recipe).name+'，分好两小口留着。','cook',at);ctx.stop?.(t);s.task=null;return {changed:true,completed:true,text:'小点心做好了，留了两小口，愿意的时候再尝。'};}
 if(t.kind==='celebrate'&&t.phase==='gather'&&t.time>=8){if(!p.domestic.celebrated.includes(t.occasion)){p.domestic.celebrated.push(t.occasion);memory(p,t.id,'你和'+t.name+'陪它过了'+(t.occasion.startsWith('birthday')?'生日':'领养纪念日')+(t.gift?'，拿出给它选的'+(homeGood(t.gift)?.name||'小礼物')+'作纪念':'')+'。','celebrate',at);ctx.photo?.(t);}ctx.stop?.(t);s.task=null;return {changed:true,completed:true,text:'这一年的纪念留好了，照片成功拍下时会收进生活相册。'};}
 return changed?{changed:true}:null;
}
function preparationLastSeen(state,t){const seen=state.pets.find(p=>p.id===t.petId)?.life?.at;return Number.isFinite(seen)?Math.max(t.at,seen):t.at;}
export function recoverDomestic(state,at=Date.now()){const t=state.domestic.task;if(t&&at-preparationLastSeen(state,t)>60000){state.domestic.task=null;return t;}return null;}
