import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {restorePetState,snapshotPetState,petEntry} from './state.mjs';import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';import {domesticView,domesticRequest,domesticTick,occasions,recoverDomestic,choosePetWish,settlePetWish} from './domestic.mjs';import {createPetCare} from './care.mjs';import {createPetCareer} from './career.mjs';import {furniturePoint} from './furnishings.mjs';import {createPetSocial} from './social.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url)))),at=new Date('2026-10-05T15:00:00').getTime();
function fixture(){const state=restorePetState({configured:true,room:'home',profile:{name:'团子'},birth:{birthday:'2026-10-05',registeredOn:'2026-10-05',adoptedOn:'2026-10-05'},care:{energy:80,satiety:65,mood:90},career:{inventory:{snack:6,cloudBed:1,flower:1},balance:47}},world,{at});state.pets.push(petEntry({configured:true,profile:{name:'栗子',species:'dog'},career:{balance:73,inventory:{snack:5}}},'other',{at}));const pet=state.pets[0],ctx={at,online:true,home:true,free:true,person:{id:'ta',name:'沈屿白'},point:{x:0,z:1},start:()=>({accepted:true}),stop:()=>{},present:()=>true,arrived:()=>true,neighbors:()=>[]};return {state,pet,ctx};}
function run(f,seconds){for(let i=0;i<seconds*20;i++)domesticTick(f.state,.05,f.ctx);}
function write(f){return restorePetState(snapshotPetState(f.state,{position:f.state.position,room:'home',outdoor:null,evening:false}),world,{at});}
test('old archive upgrades without invented fulfilled wishes, parties or tastes; stable pet identity survives writer',()=>{const f=fixture(),s=write(f);assert.equal(s.pets[0].domestic.wish,null);assert.equal(s.pets[1].domestic.memories.length,0);assert.equal(s.domestic.task,null);assert.equal(s.pets[1].career.balance,73);});
test('persistent wish stays across dates/refresh and pause, requires actual completed owned-bed sleep',()=>{const f=fixture();choosePetWish(f.pet,{date:'2026-10-05'});const wish=structuredClone(f.pet.domestic.wish);choosePetWish(f.pet,{date:'2026-10-06'});assert.deepEqual(f.pet.domestic.wish,wish);assert.equal(settlePetWish(f.pet,{at}),false);f.pet.domestic.wish.paused=true;f.pet.care.rests.own++;assert.equal(settlePetWish(f.pet,{at}),false);f.pet.domestic.wish.paused=false;assert.equal(settlePetWish(f.pet,{at}),true);assert.equal(settlePetWish(f.pet,{at}),false);assert.equal(write(f).pets[0].domestic.memories.length,1);});
test('birthday and adoption use real anniversary, not game day, and leap birthday is February 28',()=>{const f=fixture();assert.equal(occasions(f.pet,at).some(x=>x.today),false);f.pet.birth={birthday:'2024-10-05',registeredOn:'2024-10-05',adoptedOn:'2024-10-05'};assert.equal(occasions(f.pet,at).filter(x=>x.today).length,2);f.pet.birth={birthday:'2024-02-29',registeredOn:'2024-03-01',adoptedOn:null};assert.equal(occasions(f.pet,new Date('2025-02-28T15:00:00').getTime())[0].today,true);});
test('celebration waits for both original actors; cancel and refresh cannot invent a party',()=>{const f=fixture();f.pet.birth={birthday:'2024-10-05',registeredOn:'2024-10-05',adoptedOn:'2024-10-05'};let arrived=false;f.ctx.arrived=()=>arrived;const o=occasions(f.pet,at)[0];assert.ok(domesticRequest(f.state,f.pet.id,'celebrate',{occasion:o.id,gift:'cloudBed'},f.ctx).accepted);run(f,20);assert.equal(f.pet.domestic.celebrated.length,0);assert.equal(f.state.domestic.task.time,0);arrived=true;run(f,8.2);assert.equal(f.pet.domestic.celebrated.length,1);assert.equal(domesticRequest(f.state,f.pet.id,'celebrate',{occasion:o.id},f.ctx).accepted,false);assert.equal(write(f).pets[0].domestic.celebrated.length,1);assert.equal(f.state.pets[1].domestic.celebrated.length,0);});
test('cooking consumes real owner ingredients exactly once after mixing/portioning, never while walking/cancelled',()=>{const f=fixture();const old=f.pet.career.inventory.snack;let arrived=false;f.ctx.arrived=()=>arrived;assert.ok(domesticRequest(f.state,f.pet.id,'cook',{recipe:'crumb',actor:'companion'},f.ctx).accepted);run(f,30);assert.equal(f.pet.career.inventory.snack,old);assert.equal(f.state.domestic.batches.length,0);arrived=true;run(f,4.2);assert.equal(f.state.domestic.task.phase,'portion');assert.equal(f.pet.career.inventory.snack,old);assert.ok(domesticRequest(f.state,f.pet.id,'cancel',{},f.ctx).accepted);assert.equal(f.pet.career.inventory.snack,old);domesticRequest(f.state,f.pet.id,'cook',{recipe:'crumb',actor:'you'},f.ctx);run(f,8.2);assert.equal(f.pet.career.inventory.snack,old-1);assert.equal(f.state.domestic.batches[0].remaining,2);const restored=write(f);domesticTick(restored,.05,f.ctx);assert.equal(restored.pets[0].career.inventory.snack,old-1);assert.equal(restored.pets[1].career.inventory.snack,5);});
test('actual original care writer completes taste and remembers real maker, failed/refused serving consumes nothing',()=>{const f=fixture();domesticRequest(f.state,f.pet.id,'cook',{recipe:'crunch',actor:'companion'},f.ctx);run(f,8.2);const batch=f.state.domestic.batches[0];f.ctx.serve=()=>({accepted:false,text:'吃饱了'});assert.equal(domesticRequest(f.state,f.pet.id,'serve',{id:batch.id},f.ctx).accepted,false);assert.equal(batch.remaining,2);const care=createPetCare(f.pet.care,{now:()=>at+100});f.pet.care=care.state;f.state.care=care.state;f.ctx.serve=()=>care.request('snack');assert.ok(domesticRequest(f.state,f.pet.id,'serve',{id:batch.id},f.ctx).accepted);assert.equal(f.pet.domestic.tastes.crunch.count,0);care.arrive();for(let i=0;i<125;i++)care.tick(.05,{home:true,idleAllowed:false});run(f,.2);assert.equal(f.pet.domestic.tastes.crunch.count,1);assert.equal(f.pet.domestic.tastes.crunch.makers.ta.name,'沈屿白');run(f,2);assert.equal(f.pet.domestic.tastes.crunch.count,1);assert.equal(write(f).pets[0].domestic.tastes.crunch.count,1);});
test('gifts require original guest physically at home, transfer one own object and no peer wallet',()=>{const f=fixture();f.ctx.neighborReady=()=>false;assert.equal(domesticRequest(f.state,f.pet.id,'gift',{peer:'florist-cat',item:'flower'},f.ctx).accepted,false);f.ctx.neighborReady=()=>true;f.ctx.neighborName=()=> '小茉';assert.ok(domesticRequest(f.state,f.pet.id,'gift',{peer:'florist-cat',item:'flower'},f.ctx).accepted);assert.equal(f.pet.career.inventory.flower,0);assert.equal(f.state.pets[1].career.balance,73);assert.equal(write(f).pets[0].domestic.gifts.length,1);});
test('free furniture points round trip through actual career/world writer, blocked move stays unchanged',()=>{const f=fixture(),c=createPetCareer(f.pet.career),ctx={care:f.pet.care,room:'home',canPlace:()=>true};assert.ok(c.request('move-furniture',{item:'cloudBed',point:{x:.25,z:1.25,yaw:Math.PI/4}},ctx).accepted);f.pet.career=c.state;f.state.career=c.state;const p=furniturePoint(write(f).pets[0].career);assert.deepEqual(p,{x:.25,z:1.25,yaw:Math.PI/4});const before=c.snapshot();assert.equal(c.request('move-furniture',{item:'cloudBed',point:{x:3,z:2}}, {...ctx,canPlace:()=>false}).accepted,false);assert.deepEqual(c.snapshot().furnishings,before.furnishings);});
test('long absence cancels preparation, retains already finished batches, no offline ceremony',()=>{const f=fixture();domesticRequest(f.state,f.pet.id,'cook',{recipe:'crumb'},f.ctx);assert.ok(recoverDomestic(f.state,at+60001));assert.equal(f.state.domestic.task,null);assert.equal(f.pet.career.inventory.snack,6);assert.equal(f.pet.domestic.memories.length,0);});
test('attention starts from original completed care counters; reconciliation requires both real arrivals',()=>{const f=fixture(),ids=f.state.pets.map(p=>p.id),rows=f.state.pets.map(entry=>{const care=createPetCare(entry.care);care.state.position={x:.2,z:.8};return {entry,care,career:createPetCareer(entry.career),pet:{root:{scale:{x:1}}},home:{socialSpot:()=>({x:0,z:1}),socialBeside:q=>({x:q.x+1,z:q.z}),cancelSocial:()=>care.cancel()}};}),pair=ids.sort().join('|'),social=createPetSocial({wait:180,pairs:{[pair]:{window:5,ball:2}}},ids);rows[1].care.state.traits.social=.8;social.tick(.05,rows);rows[0].care.state.relationships.you={pet:1,snack:0};social.tick(.05,rows);assert.equal(social.state.pairs[pair].tension,1);social.tick(.05,rows);assert.equal(social.state.pairs[pair].tension,1);const invited=social.request('reconcile',ids[0],ids[1],rows);assert.ok(invited.accepted,JSON.stringify(invited));for(let i=0;i<100;i++)social.tick(.05,rows);assert.equal(social.state.pairs[pair].reconcile,0);rows.forEach(r=>r.care.arrive());for(let i=0;i<170;i++){rows.forEach(r=>{if(r.care.state.task?.phase==='walking')r.care.arrive();r.care.tick(.05,{home:true,idleAllowed:false});});social.tick(.05,rows);}assert.equal(social.state.pairs[pair].tension,0);assert.equal(social.state.pairs[pair].reconcile,1);});

test('a wish for TA cooking requires actually eating TA food; future anniversaries show next civil year',()=>{const f=fixture();choosePetWish(f.pet,{date:'2026-10-05',hasCompanion:true});assert.equal(f.pet.domestic.wish.kind,'taste');f.pet.domestic.tastes.crumb.makers.you={name:'你',count:1};assert.equal(settlePetWish(f.pet,{at}),false);f.pet.domestic.tastes.crumb.makers.ta={name:'沈屿白',count:1};assert.equal(settlePetWish(f.pet,{at}),true);assert.equal(occasions(f.pet,new Date('2026-10-06T15:00:00').getTime())[0].date,'2027-10-05');});

test('preparation older than a minute survives a recent original life heartbeat and writer reload',()=>{const f=fixture();domesticRequest(f.state,f.pet.id,'cook',{recipe:'crumb'},f.ctx);f.pet.life.at=at+120000;const loaded=write(f);assert.equal(recoverDomestic(loaded,at+120500),null);assert.ok(loaded.domestic.task);assert.ok(recoverDomestic(loaded,at+181001));assert.equal(loaded.domestic.task,null);assert.equal(loaded.pets[0].career.inventory.snack,6);});
