import test from 'node:test';import assert from 'node:assert/strict';
import {createPetCareer} from './career.mjs';import {createPetCare,careSummary} from './care.mjs';
import {restoreFurnishings,furniturePoint} from './furnishings.mjs';import {createHomeNavigation} from './home-navigation.mjs';
import {choreNeeds} from './home-chores.mjs';import {restorePetState,snapshotPetState} from './state.mjs';
function setup(){const c=createPetCareer({balance:100,rng:1}),care=createPetCare({satiety:90,energy:45,mood:100}),ctx={care:care.state,room:'home',canPlace:()=>true,startRest:place=>care.request('rest',{place})};return {c,care,ctx};}
test('treasury purchases are real and unique; furniture cannot be changed while away/busy or at a blocked spot',()=>{const {c,care,ctx}=setup();assert.equal(c.request('buy',{item:'cloudBed'},ctx).accepted,true);assert.equal(c.state.balance,62);assert.equal(c.state.inventory.cloudBed,1);assert.equal(c.state.furnishings.sleep,'cloudBed');assert.equal(c.request('buy',{item:'cloudBed'},ctx).accepted,false);const before=c.snapshot();for(const x of[{...ctx,room:'cafe'},{...ctx,canPlace:()=>false},{...ctx,care:{...care.state,task:{kind:'sleep'}}}])assert.equal(c.request('furnish',{item:'cloudBed',slot:'rug'},x).accepted,false);assert.deepEqual(c.snapshot(),before);assert.equal(c.request('furnish',{item:'cloudBed',slot:'rug'},ctx).accepted,true);assert.equal(c.state.furnishings.placements.cloudBed,'rug');assert.equal(c.state.balance,62);assert.equal(createPetCareer(c.snapshot()).state.furnishings.sleep,'cloudBed');});
test('sleep uses the selected purchased spot and grows its own preference/cleaning need only after completion',()=>{const {c,care,ctx}=setup();c.request('buy',{item:'roundMat'},ctx);c.request('furnish',{item:'roundMat',slot:'rug'},ctx);assert.equal(c.request('own-rest',{item:'roundMat'},ctx).accepted,true);assert.equal(care.state.task.place,'own');assert.equal(care.state.rests.own,0);const resumed=createPetCare(care.snapshot());resumed.arrive();for(let i=0;i<45;i++)resumed.tick(1,{home:true,idleAllowed:false});assert.equal(resumed.state.rests.own,1);assert.equal(careSummary(resumed.state).favoriteRest,'自己摆好的小窝');assert.equal(choreNeeds({care:resumed,career:c,entry:{}},0).find(x=>x.kind==='bedding').place,'own');assert.equal(choreNeeds({care:resumed,career:c,entry:{}},0).find(x=>x.kind==='bedding').needed,true);});
test('owned toy/accessories share inventory, preserve individual arrangement and cannot invent job rewards',()=>{const {c,care,ctx}=setup();assert.equal(c.request('wear',{item:'wreath'},ctx).accepted,false);c.request('buy',{item:'bandana'},ctx);c.request('buy',{item:'bellBall'},ctx);assert.equal(c.request('wear',{item:'bandana'},ctx).accepted,true);assert.equal(c.request('furnish',{item:'bellBall'},ctx).accepted,true);assert.equal(c.summary().furnishings.wear,'雾蓝小方巾');assert.equal(c.request('undress',{},ctx).accepted,true);assert.equal(c.state.inventory.bandana,1);assert.equal(c.state.furnishings.wear,'');assert.deepEqual(restoreFurnishings({wear:'wreath',sleep:'cloudBed',placements:{cloudBed:'roof'},toy:'bellBall'},{}),{placements:{},positions:{},sleep:'',wear:'',toy:'',recent:[]});});
test('both placement options are reachable by all four size slots; per-pet objects survive the canonical archive writer',()=>{for(let i=0;i<4;i++)for(const size of[.7,1,1.3])for(const slot of['corner','rug']){const p=furniturePoint({furnishings:{placements:{cloudBed:slot}}},i,'cloudBed'),nav=createHomeNavigation(size);assert.ok(nav.walkable(p.x,p.z));assert.ok(nav.path({x:0,z:2.8},p));}const world={restore:()=>({position:{x:0,z:0},room:'home'})},s=restorePetState({pets:[{id:'a',career:{balance:62,inventory:{cloudBed:1},furnishings:{placements:{cloudBed:'rug'},sleep:'cloudBed'}}},{id:'b',career:{balance:80,inventory:{bandana:1},furnishings:{wear:'bandana'}}}],activePetId:'a'},world);const saved=snapshotPetState(s,{position:s.position,room:'home'}),loaded=restorePetState(saved,world);assert.equal(loaded.pets[0].career.furnishings.sleep,'cloudBed');assert.equal(loaded.pets[0].career.furnishings.placements.cloudBed,'rug');assert.equal(loaded.pets[1].career.furnishings.wear,'bandana');assert.equal(loaded.pets[1].career.balance,80);});

test('ordinary self wandering gives way to an owned rest request while social reservations stay busy',()=>{const {c,care,ctx}=setup();c.request('buy',{item:'cloudBed'},ctx);care.state.task={kind:'wander',phase:'walking',source:'self'};assert.equal(c.request('own-rest',{item:'cloudBed'},ctx).accepted,true);assert.equal(care.state.task.kind,'sleep');care.state.task={kind:'watch',source:'self',socialId:'pair'};assert.equal(c.request('wear',{item:'bandana'},ctx).accepted,false);});

test('re-laying a freely placed bed retains its original point and revalidates that point',()=>{const {c,care,ctx}=setup(),point={x:.5,z:1.8,yaw:.75};c.request('buy',{item:'cloudBed'},ctx);assert.ok(c.request('move-furniture',{item:'cloudBed',point},ctx).accepted);const loaded=createPetCareer(c.snapshot());assert.ok(loaded.request('furnish',{item:'cloudBed',slot:'free'},ctx).accepted);assert.deepEqual(furniturePoint(loaded.state),point);const before=loaded.snapshot();assert.equal(loaded.request('furnish',{item:'cloudBed',slot:'free'},{...ctx,canPlace:()=>false}).accepted,false);assert.deepEqual(loaded.snapshot(),before);assert.ok(loaded.request('furnish',{item:'cloudBed',slot:'rug'},ctx).accepted);assert.equal(loaded.state.furnishings.positions.cloudBed,undefined);});
