// Learned habits belong to this pet's existing care save. Toy/rest experience
// remains in the original counters; only actual comfortable floor spots are new.
const bound=(v,a,b,d=0)=>Number.isFinite(v)?Math.max(a,Math.min(b,v)):d;
import {homePoint as point} from './room-layout.mjs?v=fg-504734d19f7543b2';
const personKey=k=>k==='you'||typeof k==='string'&&/^companion:.{1,80}$/.test(k);
export function restoreHabitMemory(raw){return {version:1,spots:Array.isArray(raw?.spots)?raw.spots.filter(x=>point(x?.position)&&['window','quiet'].includes(x.kind)).slice(-6).map(x=>({kind:x.kind,position:point(x.position),visits:bound(x.visits,1,24,1)})):[],greetings:Object.fromEntries(Object.entries(raw?.greetings||{}).filter(([k,v])=>personKey(k)&&Number.isFinite(v)).slice(-40).map(([k,v])=>[k,bound(v,0,1e15)]))};}
function weighted(rows,random){let n=bound(random(),0,.999999,0)*rows.reduce((n,r)=>n+r.weight,0);for(const r of rows){n-=r.weight;if(n<0)return r.id;}return rows.at(-1)?.id;}
export function choosePetToy(state,random,attention=0){return weighted(['ball','mouse'].map(id=>({id,weight:1+Math.min(8,bound(state.toys?.[id],0,1e6))*(.55+Math.max(0,attention)*.2)})),random);}
export function choosePetRest(state,available,random){const places=['bed','sofa','box','own'].filter(id=>available.includes(id));return weighted(places.map(id=>({id,weight:1+Math.min(8,bound(state.rests?.[id],0,1e6))*.8})),random)||'bed';}
export function learnComfortSpot(state,task){if(!['watch','wander'].includes(task?.kind)||task.phase!=='doing'||task.time<6||task.target||task.socialId||state.mood<55)return false;const p=point(state.position);if(!p)return false;const memory=state.habits||(state.habits=restoreHabitMemory()),kind=task.kind==='watch'?'window':'quiet',old=memory.spots.find(x=>x.kind===kind&&Math.hypot(x.position.x-p.x,x.position.z-p.z)<.55);if(old)old.visits=Math.min(24,old.visits+1);else {memory.spots.push({kind,position:p,visits:1});memory.spots=memory.spots.slice(-6);}return true;}
export function chooseComfortSpot(state,random,available=()=>true){const spots=state.habits?.spots?.filter(x=>x.visits>=3&&available(x.position))||[];if(!spots.length||random()>.45)return null;const index=weighted(spots.map((s,i)=>({id:i,weight:s.visits})),random);return {...spots[index].position};}
export function familiarity(state,key){const r=state.relationships?.[key]||{};return ['play','pet','food','snack','rest'].reduce((n,k)=>n+bound(r[k],0,1e6),0);}
export function greetingFor(state,person,at,random){if(!personKey(person?.key)||person.available===false||!point(person.position)||familiarity(state,person.key)<3||state.energy<45||state.satiety<30||state.task||state.helper||state.cooldown>0)return null;const previous=state.habits?.greetings?.[person.key];if(previous!==undefined&&at-previous<30*60000)return null;const r=state.relationships[person.key],play=(r.play||0)>=3&&state.energy>55&&(state.traits.active>.5||random()<.35);return {kind:play?'invitePlay':'invitePet',place:play?'toy':'person',toy:choosePetToy(state,random),source:'self',target:person.key,actor:person.id||'',name:person.name||'你',stage:play?'fetch':'',greeting:true};}
export function petHabitFacts(state){const toy=['ball','mouse'].sort((a,b)=>(state.toys?.[b]||0)-(state.toys?.[a]||0))[0],rest=['bed','sofa','box','own'].sort((a,b)=>(state.rests?.[b]||0)-(state.rests?.[a]||0))[0],spots=(state.habits?.spots||[]).filter(x=>x.visits>=3);return {toy:{kind:toy,label:toy==='mouse'?'小老鼠':'小球',completed:state.toys?.[toy]||0,formed:(state.toys?.[toy]||0)>=3},rest:{kind:rest,label:{bed:'自己的窝',sofa:'沙发边',box:'自己的小纸箱',own:'自己布置的小窝'}[rest],completed:state.rests?.[rest]||0,formed:(state.rests?.[rest]||0)>=3},spots:spots.map(s=>({kind:s.kind,label:s.kind==='window'?'常去看窗外的位置':'常歇脚的角落',position:{...s.position},visits:s.visits})),greeting:'熟悉以后，会在你们实际回到家时靠近，或叼着熟悉的玩具来；睡觉和忙碌时继续自己的事。'};}
