import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createPetCare,careSummary} from './care.mjs';import {choosePetToy,choosePetRest,learnComfortSpot,chooseComfortSpot,petHabitFacts} from './habits.mjs';import {careManner,chooseCareOffer,companyPlan} from './resident-care.mjs';import {restoreResident} from './autonomy.mjs';import {syncResidentPreferences,deriveResidentPreferences} from './resident-choice.mjs';import {createHomeNavigation} from './home-navigation.mjs';import {restorePetState,snapshotPetState,projectActivePet} from './state.mjs';import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';import {recoverPetLife} from './routine.mjs';import {restoreClock} from '../fairy-garden/real-clock.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url)))),person=persona=>({id:'ta',persona}),resident=persona=>{const r=restoreResident({id:'ta'});syncResidentPreferences(r,person(persona));return r;};
const finish=(c,seconds=20)=>{c.arrive();for(let i=0;i<seconds&&c.state.task;i++)c.tick(1,{home:true});};
test('toy and sleeping habits derive from completed care, and walking or cancellation earns no habit',()=>{const c=createPetCare({mood:100,energy:90});c.request('play',{toy:'mouse'});c.tick(1,{home:true});assert.equal(petHabitFacts(c.state).toy.completed,0);c.cancel();for(let i=0;i<3;i++){c.request('play',{toy:'mouse'});finish(c);}assert.equal(petHabitFacts(c.state).toy.formed,true);assert.equal(petHabitFacts(c.state).toy.kind,'mouse');assert.equal(petHabitFacts(c.state).toy.completed,3);assert.equal(petHabitFacts(c.state).rest.formed,false);});
test('learned choices remain varied and never invent ownership of a box',()=>{const s=createPetCare({toys:{mouse:12},rests:{box:20,sofa:8}}).state;let mouse=0,ball=0,sofa=0;for(let i=0;i<1000;i++){const t=choosePetToy(s,()=>i/1000);mouse+=t==='mouse';ball+=t==='ball';const place=choosePetRest(s,['bed','sofa'],()=>i/1000);assert.notEqual(place,'box');sofa+=place==='sofa';}assert.ok(mouse>750&&ball>80);assert.ok(sofa>800);assert.equal(choosePetRest(s,['box'],()=>.2),'box');});
test('comfortable actual floor positions require repeated completed stays and respect current obstacles',()=>{const c=createPetCare({mood:100,position:{x:-.55,z:-1.9}});for(let i=0;i<3;i++){c.request('watch');finish(c);}assert.equal(petHabitFacts(c.state).spots.length,1);const remembered=chooseComfortSpot(c.state,()=>.1);assert.deepEqual(remembered,c.state.position);assert.equal(chooseComfortSpot(c.state,()=>.1,()=>false),null);assert.equal(learnComfortSpot(c.state,{kind:'wander',phase:'walking',time:100}),false);assert.equal(learnComfortSpot(c.state,{kind:'watch',phase:'doing',time:1}),false);});
test('homecoming is learned per person, uses an actual toy route and survives refresh without repetition',()=>{const c=createPetCare({energy:90,satiety:80,traits:{active:1},toys:{mouse:8},relationships:{you:{play:4},'companion:a':{pet:4}}}),you={key:'you',name:'你',position:{x:-.65,z:1.72}},at=1e12;assert.equal(c.greet(you,at).accepted,true);assert.equal(c.state.task.kind,'invitePlay');assert.equal(c.state.recent.length,0);c.arrive();for(let i=0;i<2;i++)c.tick(1,{home:true});assert.equal(c.pickupToy(),true);assert.equal(c.state.recent.length,0);c.arrive();for(let i=0;i<2;i++)c.tick(1,{home:true});assert.equal(c.deliverToy({x:-.7,z:1.3}),true);assert.match(c.state.recent.at(-1).text,/回家的动静/);c.cancel();const restored=createPetCare(c.snapshot());assert.equal(restored.greet(you,at+5000).accepted,false);assert.equal(restored.greet({key:'companion:b',id:'b',position:{x:0,z:0}},at+5000).accepted,false);assert.equal(restored.greet({key:'companion:a',id:'a',name:'甲',position:{x:0,z:0}},at+5000).accepted,true);});
test('homecoming does not wake a sleeper or interrupt work-like and user care tasks',()=>{const c=createPetCare({relationships:{you:{pet:8}},energy:90,satiety:80}),you={key:'you',position:{x:0,z:1}};c.request('rest');c.arrive();assert.equal(c.greet(you,1e12).accepted,false);c.cancel();c.request('pet');assert.equal(c.greet(you,1e12).accepted,false);c.cancel();c.state.energy=20;assert.equal(c.greet(you,1e12).accepted,false);});
test('care style uses independent persona cues and actual pet preferences, while offers still obey needs',()=>{const gentle=resident('性格温柔安静，耐心细心，谨慎。'),active=resident('喜欢运动，热爱散步，性格活泼。'),pet=createPetCare({toys:{mouse:8},energy:80,mood:75,satiety:60,bowl:100}).state,a=careManner(gentle,pet,'play',()=>.8),b=careManner(active,pet,'play',()=>.8);assert.ok(a.tempo<b.tempo);assert.ok(a.offerAfter>b.offerAfter);assert.ok(a.gentle);assert.equal(a.toy,'mouse');assert.match(a.detail,/熟悉的小老鼠/);pet.satiety=45;pet.bowl=0;assert.equal(chooseCareOffer(active,pet,()=>.9),'feed');pet.bowl=100;pet.energy=20;assert.equal(chooseCareOffer(active,pet,()=>.9),'company');assert.equal(careManner(resident(''),pet,'pet',()=>.1).tempo,1);});
test('quiet and active residents choose different kinds of care over repeated free choices',()=>{const q=resident('喜欢安静，热爱独处。性格耐心温柔。'),a=resident('喜欢运动，热爱散步，性格活泼。'),pet=createPetCare({energy:90,satiety:80,bowl:100}).state;const count=(r,id)=>{let n=0;for(let i=0;i<1000;i++)n+=chooseCareOffer(r,pet,()=>i/1000)===id;return n;};assert.ok(count(q,'company')>count(a,'company')*2);assert.ok(count(a,'play')>count(q,'play')*2);});
test('quiet company is a physical route beside the pet with no fabricated care or teleport',()=>{const nav=createHomeNavigation(1.4),from={x:-1.15,z:1.35},pet={id:'pet-1',position:{x:.3,z:.7}},plan=companyPlan(nav,from,pet,q=>Math.hypot(q.x-pet.position.x,q.z-pet.position.z)>.7,()=>.4);assert.ok(plan);assert.equal(plan.activity.petId,pet.id);assert.equal(plan.activity.kind,'pets');assert.equal(plan.activity.phase,'walking');assert.ok(Math.hypot(plan.activity.goal.x-pet.position.x,plan.activity.goal.z-pet.position.z)>.7);for(const p of plan.route)assert.ok(nav.walkable(p.x,p.z));assert.equal(companyPlan(nav,from,pet,()=>false,()=>.4),null);});
test('the real world writer preserves habits, pending greeting and caregiver manner independently for each pet',()=>{const s=restorePetState({configured:true,profile:{name:'团子'}},world),c=createPetCare({relationships:{you:{pet:4}},toys:{mouse:3},energy:90,satiety:80});c.greet({key:'you',position:{x:-.65,z:1.72}},1e12);s.pets[0].care=c.snapshot();s.care=s.pets[0].care;const saved=snapshotPetState(s,{position:s.position,room:null,outdoor:null,evening:false}),again=restorePetState(saved,world);assert.equal(again.care.habits.greetings.you,1e12);assert.equal(again.care.task.greeting,true);assert.equal(again.care.toys.mouse,3);c.cancel();c.request('play',{source:'companion',actor:'ta',manner:{tempo:.75,offerAfter:3,gentle:true,toy:'mouse',detail:'慢慢玩'}});const copy=createPetCare(c.snapshot());assert.equal(copy.state.task.manner.tempo,.75);assert.equal(copy.state.task.manner.gentle,true);});
test('new care axes migrate even when a role persona hash has not changed since the previous release',()=>{const p=person('性格温柔、细心、耐心。'),old=deriveResidentPreferences(p),r=restoreResident({id:'ta',choices:{preferences:{...old,version:1,scores:{}}}});syncResidentPreferences(r,p);assert.ok(r.choices.preferences.scores.gentle>0);assert.ok(r.choices.preferences.scores.patient>0);});
test('offline recovery preserves learned habits and cannot invent greetings or repeat the same elapsed interval',()=>{const at=new Date(2026,9,5,15).getTime(),from=at-3600000,c=createPetCare({toys:{mouse:4},rests:{sofa:4},habits:{greetings:{you:from-60000}},satiety:90,bowl:100,energy:90}),s=restorePetState({configured:true,clock:restoreClock(null,1,from),care:c.snapshot(),career:{balance:35},town:{place:'home',phase:'idle',position:{x:1,z:1}},resident:{id:'ta',town:{place:'home',phase:'idle',position:{x:-1.15,z:1.35}},life:{at:from,marks:{},notes:[]}}},world);s.pets[0].life.at=from;recoverPetLife(s,world,at);projectActivePet(s);assert.equal(s.care.habits.greetings.you,from-60000);assert.equal(s.care.toys.mouse,4);assert.equal(s.career.balance,35);const saved=structuredClone(s);recoverPetLife(s,world,at);projectActivePet(s);assert.deepEqual(s,saved);assert.equal(careSummary(s.care).habits.toy.formed,true);});

test('a completed night teaches the actual sleeping place once, while an early wake teaches nothing',()=>{const c=createPetCare({energy:40});c.request('rest',{source:'self',restPlaces:['sofa']});c.state.task.night=true;c.arrive();for(let i=0;i<44;i++)c.tick(1,{home:true});assert.equal(c.finishNightRest(),false);c.tick(1,{home:true});const reloaded=createPetCare(c.snapshot());assert.equal(reloaded.finishNightRest(),true);assert.equal(reloaded.state.rests.sofa,1);assert.equal(reloaded.finishNightRest(),false);assert.equal(c.finishNightRest(),true);assert.equal(c.state.rests.sofa,1);assert.equal(c.finishNightRest(),false);c.state.energy=40;c.request('rest',{source:'self',restPlaces:['sofa']});c.state.task.night=true;c.arrive();c.tick(1,{home:true});assert.equal(c.request('wake').accepted,true);assert.equal(c.state.rests.sofa,1);});

 test('offline full-night recovery records one actual sleep per night and a same-time reload cannot repeat it',()=>{const from=new Date(2026,9,5,22).getTime(),at=new Date(2026,9,6,8).getTime(),s=restorePetState({configured:true,clock:restoreClock(null,1,from),care:{satiety:90,bowl:100,energy:50,rests:{sofa:4}},town:{place:'home',phase:'idle',position:{x:1,z:1}}},world);s.pets[0].life.at=from;recoverPetLife(s,world,at);projectActivePet(s);assert.equal(Object.values(s.care.rests).reduce((a,b)=>a+b,0),5);assert.match(s.care.recent.map(x=>x.text).join(' '),/睡了一觉/);const saved=snapshotPetState(s,{position:s.position,room:null,outdoor:null,evening:false}),again=restorePetState(saved,world);recoverPetLife(again,world,at);projectActivePet(again);assert.deepEqual(again.care.rests,s.care.rests);});
