import {createActorNavigation} from './actor-spacing.mjs?v=fg-15a63dee59d32513';
import {restoreHomeCondition} from './home-condition.mjs?v=fg-15a63dee59d32513';
import {createHomeNavigation,PET_STATIONS,petHomePlaces} from './home-navigation.mjs?v=fg-15a63dee59d32513';
import {turnPet,walkRoute} from './movement.mjs?v=fg-15a63dee59d32513';
import {nextRandom} from './autonomy.mjs?v=fg-15a63dee59d32513';
import {residentStepClear,residentGoalClear} from './resident-choice.mjs?v=fg-15a63dee59d32513';

import {furniturePoint} from './furnishings.mjs?v=fg-15a63dee59d32513';
export const HOME_CHORES={toys:{label:'收回玩具',duration:1.4},bowl:{label:'擦饭碗边',duration:5},water:{label:'换一碗清水',duration:6},bedding:{label:'整理睡处',duration:5}};
const bound=(v,a,b,f=0)=>Number.isFinite(v)?Math.max(a,Math.min(b,v)):f;
import {homePoint as point} from './room-layout.mjs?v=fg-15a63dee59d32513';
const body=row=>row.care?.state||row.care,entry=row=>row.entry||row;
import {chorePlaces} from './room-layout.mjs?v=fg-15a63dee59d32513';
export {chorePlaces};
export function restoreHousehold(raw){const t=raw?.task;return {version:1,rng:bound(raw?.rng,1,4294967295,916735),wait:bound(raw?.wait,0,90,45),assignments:Object.fromEntries(Object.keys(HOME_CHORES).map(k=>[k,['you','ta','shared'].includes(raw?.assignments?.[k])?raw.assignments[k]:'shared'])),task:t&&HOME_CHORES[t.kind]&&typeof t.petId==='string'&&point(t.position)&&point(t.goal)&&point(t.focus)&&point(t.target)&&['you','companion'].includes(t.actor)?{kind:t.kind,petId:t.petId,actor:t.actor,actorId:String(t.actorId||'').slice(0,80),name:String(t.name||'你').slice(0,24),petName:String(t.petName||'它').slice(0,24),phase:['walking','pickup','carry','doing'].includes(t.phase)?t.phase:'walking',time:bound(t.time,0,20),blocked:0,heading:bound(t.heading,-1e5,1e5),position:point(t.position),goal:point(t.goal),focus:point(t.focus),target:point(t.target),toy:t.toy==='mouse'?'mouse':'ball',place:['bed','sofa','box'].includes(t.place)?t.place:'bed',picked:t.picked===true}:null,recent:Array.isArray(raw?.recent)?raw.recent.filter(x=>Number.isFinite(x?.at)&&typeof x.text==='string').slice(-12).map(x=>({at:x.at,text:x.text.slice(0,160),completed:x.completed===true})):[]};}
export function choreNeeds(row,index,at=Date.now()){const s=body(row),p=chorePlaces(index),c=s.condition||restoreHomeCondition(),toys=['ball','mouse'].filter(k=>Math.hypot(s.toyPlaces[k].x-p.toys[k].x,s.toyPlaces[k].z-p.toys[k].z)>.16),available=['bed','sofa',...((row.career?.state||entry(row).career)?.furnishings?.sleep?['own']:[]),...((row.career?.state||entry(row).career)?.inventory?.box===1?['box']:[])],rest=available.slice().sort((a,b)=>c.bedding[b]-c.bedding[a])[0];return [{kind:'toys',needed:toys.length>0,toy:toys[0],status:toys.length?toys.length+'件玩具在收纳盘外':'玩具已收好'},{kind:'bowl',needed:c.bowl>=12,status:c.bowl>=12?'碗边留下了一点粮屑':'饭碗边干净着'},{kind:'water',needed:c.water<70||c.waterAt>0&&at-c.waterAt>=8*3600000,status:c.waterAt>0&&at-c.waterAt>=8*3600000?'这碗水放了一阵子':c.water<70?'水剩下 '+Math.round(c.water)+'%':'清水还充足'},{kind:'bedding',needed:c.bedding[rest]>=12,place:rest,status:c.bedding[rest]>=12?({bed:'窝里',sofa:'沙发边',box:'纸箱里',own:'自己的小窝里'}[rest])+'的垫子有些褶皱':'睡处平整着'}];}
function free(row){const s=body(row),t=s.task;return entry(row).town?.place==='home'&&!s.helper&&(!(row.career?.state||entry(row).career)?.job)&&(!t||t.source==='self'&&['watch','wander'].includes(t.kind)&&!t.socialId);}
export function createHousehold(state,{getRows,getActor,getActors=()=>[],onChange=()=>true,now=()=>Date.now()}){
 const nav=createHomeNavigation(1.4);let route=[],key='';
 const rows=()=>getRows(),selected=id=>rows().find(r=>entry(r).id===id),peers=()=>rows().filter(r=>entry(r).town?.place==='home').map(r=>({position:body(r).position||entry(r).town.position,size:entry(r).profile?.size||1}));
 const physical=createActorNavigation(nav,{actor:()=>({id:'companion:'+(state.task?.actorId||getActor('companion')?.id),kind:'person',size:1.6,place:'home'}),actors:getActors});
 const path=(a,b,actor=state.task?.actor)=>actor==='companion'?physical.path(a,b):nav.path(a,b,peers().map(p=>({...p.position,r:.55*(p.size||1)})));
 function transaction(run){const old=structuredClone(state),bodies=rows().map(r=>({r,care:structuredClone(body(r))})),result=run();if(result?.changed&&onChange()===false){Object.assign(state,old);for(const {r,care}of bodies){const s=body(r);for(const k of Object.keys(s))delete s[k];Object.assign(s,care);}route=[];key='';return {accepted:false,text:'这次收拾还没保存成功，请先重试保存。'};}return result;}
 function stand(focus,from,actor=state.task?.actor){for(const r of [.46,.65,.82])for(const a of [Math.atan2(from.x-focus.x,from.z-focus.z),0,.8,-.8,1.6,-1.6,Math.PI]){const q={x:focus.x+Math.sin(a)*r,z:focus.z+Math.cos(a)*r};if(nav.walkable(q.x,q.z)&&(actor==='companion'?physical.clearPoint(q):residentGoalClear(q,peers()))&&path(from,q,actor))return q;}return null;}
 function cancel(text='这次先停一下，收拾留到下次。'){return transaction(()=>{const t=state.task;if(!t)return {accepted:false};const row=selected(t.petId);if(t.picked&&row)body(row).toyPlaces[t.toy]=nav.restore(t.position);state.task=null;state.wait=45;route=[];key='';state.recent.push({at:now(),text,completed:false});state.recent=state.recent.slice(-12);return {accepted:true,changed:true,text};});}
 function request(kind,{petId,actor='you',automatic=false}={}){if(!HOME_CHORES[kind])return {accepted:false,text:'没找到这项家务。'};if(state.task)return {accepted:false,text:'先把正在做的这件收拾好。'};const row=selected(petId),i=rows().indexOf(row);if(!row||!free(row))return {accepted:false,text:'它正在忙自己的事，等空下来再收拾。'};const who=getActor(actor);if(!who?.available||!point(who.position))return {accepted:false,text:actor==='you'?'回到家里再动手吧。':'TA现在正在忙，等回家空下来再做。'};const need=choreNeeds(row,i,now()).find(x=>x.kind===kind);if(!need.needed)return {accepted:false,text:'这里已经收拾好了，暂时不用再做。'};const score=who.preferences?.tidy||0;if(actor==='companion'&&!automatic&&score<0&&nextRandom(state)>.35)return {accepted:false,text:who.name+'这会儿不想收拾，想先歇一会儿。'};const places=chorePlaces(i),s=body(row),focus=kind==='toys'?s.toyPlaces[need.toy]:kind==='bedding'?(need.place==='own'?furniturePoint(row.career?.state||entry(row).career,i):places.bedding[need.place]):places[kind],target=kind==='toys'?places.toys[need.toy]:focus,goal=stand(focus,who.position,actor);if(!goal)return {accepted:false,text:'现在走不过去，先给这里留一点空位。'};
  return transaction(()=>{if(s.task){row.care?.cancel?row.care.cancel():s.task=null;}state.task={kind,petId,petName:entry(row).profile.name,actor,actorId:who.id||'',name:who.name||'你',phase:'walking',time:0,blocked:0,position:{...who.position},heading:who.heading||0,goal,focus:{...focus},target:{...target},toy:need.toy||'ball',place:need.place||'bed',picked:false};route=[];key='';return {accepted:true,changed:true,text:(who.name||'你')+'准备'+HOME_CHORES[kind].label+'，做完才算收拾好。'};});
 }
 function assign(kind,actor){if(!HOME_CHORES[kind]||!['you','ta','shared'].includes(actor))return {accepted:false};return transaction(()=>{state.assignments[kind]=actor;return {accepted:true,changed:true,text:'分工记好了。'};});}
 function auto(){if(state.task||state.wait>0)return false;state.wait=45;const who=getActor('companion');if(!who?.available)return false;const s=who.preferences||{},chance=Math.max(.08,Math.min(.95,.4+(s.tidy||0)*.1+(s.attentive||0)*.06));if(nextRandom(state)>chance)return false;const choices=rows().flatMap((r,i)=>free(r)?choreNeeds(r,i,now()).filter(x=>x.needed&&state.assignments[x.kind]!=='you').map(x=>({...x,petId:entry(r).id,weight:(state.assignments[x.kind]==='ta'?2:1)*(x.kind==='water'?1+Math.max(0,s.attentive||0)*.2:1)})):[]);if(!choices.length)return false;let n=nextRandom(state)*choices.reduce((a,c)=>a+c.weight,0);const chosen=choices.find(x=>(n-=x.weight)<0)||choices.at(-1);return request(chosen.kind,{petId:chosen.petId,actor:'companion',automatic:true}).accepted;}
 function tick(dt){dt=Math.min(.1,Math.max(0,dt));for(const r of rows()){const c=body(r).condition;if(c&&!c.waterAt)c.waterAt=now();}state.wait=Math.max(0,state.wait-dt);const t=state.task;if(!t)return;const row=selected(t.petId),who=getActor(t.actor);if(!row||entry(row).town?.place!=='home'||who&&t.actor==='companion'&&who.id!==t.actorId){cancel('这件家务先停下，东西留在实际放下的位置。');return;}if(!who?.available)return;
  if(body(row).task||body(row).helper||(row.career?.state||entry(row).career)?.job){cancel('它要用这个地方了，这次先让它。');return;}
  if(['walking','carry'].includes(t.phase)){const routeKey=t.phase+':'+t.goal.x+':'+t.goal.z;if(key!==routeKey){route=path(t.position,t.goal)||[];key=routeKey;if(!route.length&&Math.hypot(t.position.x-t.goal.x,t.position.z-t.goal.z)>.12){cancel('走不过去，这次还没有收拾好。');return;}}if(route.length){const p={...t.position},m=t.actor==='companion'?physical.walk(route,p,t.heading,dt,.75):walkRoute(route,p,t.heading,dt,.75,q=>nav.walkable(q.x,q.z));if(m.blocked||t.actor!=='companion'&&!residentStepClear(p,m.position,peers())){t.blocked+=dt;key='';if(t.blocked>2)cancel('这里暂时过不去，收拾留到下次。');return;}t.blocked=0;t.position=m.position;t.heading=m.heading;if(route.length)return;}t.phase=t.kind==='toys'&&!t.picked?'pickup':'doing';t.time=0;key='';onChange();return;}
  t.heading=turnPet(t.heading,Math.atan2(t.focus.x-t.position.x,t.focus.z-t.position.z),dt).heading;t.time+=dt;if(t.phase==='pickup'&&t.time>=.9){const goal=stand(t.target,t.position);if(!goal){cancel('收纳盘旁暂时没有空位，玩具先留在这里。');return;}t.picked=true;t.phase='carry';t.time=0;t.goal=goal;key='';onChange();return;}
  if(t.phase==='doing'&&t.time>=HOME_CHORES[t.kind].duration)transaction(()=>{const s=body(row),c=s.condition;if(t.kind==='toys')s.toyPlaces[t.toy]={...t.target};else if(t.kind==='bowl')c.bowl=0;else if(t.kind==='water'){c.water=100;c.waterAt=now();}else c.bedding[t.place]=0;const text=t.name+'帮'+t.petName+({toys:'把'+(t.toy==='mouse'?'小老鼠':'小球')+'收回了收纳盘。',bowl:'擦干净了饭碗边，原来的粮还留着。',water:'换好了一碗清水。',bedding:'整理好了'+({bed:'窝里的',sofa:'沙发边的',box:'纸箱里的',own:'自己小窝里的'}[t.place])+'垫子。'}[t.kind]);state.recent.push({at:now(),text,completed:true});state.recent=state.recent.slice(-12);state.task=null;state.wait=45;route=[];key='';return {accepted:true,changed:true,text};});
 }
 return {state,tick,auto,request,assign,cancel,snapshot:()=>structuredClone(state),facts:id=>({assignments:{...state.assignments},task:state.task?{...structuredClone(state.task),label:HOME_CHORES[state.task.kind].label}:null,chores:selected(id)?choreNeeds(selected(id),rows().indexOf(selected(id)),now()).map(x=>({...x,label:HOME_CHORES[x.kind].label})):[],recent:structuredClone(state.recent)})};
}
