import {createPetToy} from './toy-prop.mjs?v=fg-3926216862d1a73e';
import {HOME_DETAILS} from './room-layout.mjs?v=fg-3926216862d1a73e';
import {skillTask} from './skills.mjs?v=fg-3926216862d1a73e';
import {chorePlaces} from './home-chores.mjs?v=fg-3926216862d1a73e';
import {WORK_HABITS,habitTask,carriesToy} from './work-habits.mjs?v=fg-3926216862d1a73e';
import {chooseComfortSpot} from './habits.mjs?v=fg-3926216862d1a73e';
import {createParcelProp} from './parcel-prop.mjs?v=fg-3926216862d1a73e';
import {localRoute,idlePose,nextRandom} from './autonomy.mjs?v=fg-3926216862d1a73e';
import {moodFromCare} from '../../art/pet-house/pet-mood.mjs?v=fg-3926216862d1a73e';
import {turnPet} from './movement.mjs?v=fg-3926216862d1a73e';
import {createHomeNavigation,HOME_PLACES,petHomePlaces} from './home-navigation.mjs?v=fg-3926216862d1a73e';
import {TOY_SPOTS,SEEK_KINDS} from './initiative.mjs?v=fg-3926216862d1a73e';
export function createPetHome(T,{scene,pet,care,onNotice,onSave,draw,getPeople=()=>[],getChore=()=>null,index=0,station=null,getOtherPets=()=>[],getBelongings=()=>({}),getPeers=()=>[],getParcels=()=>({queue:[]}),onBag=()=>({accepted:false})}){
 let nav,route=[],pendingTask=null,pendingStage='',homeTime=0,reactionTime=0,poseBase=null,food=[],targetClock=0,visible=false,held=false,blockedTime=0;
 const places={...petHomePlaces(station),water:chorePlaces(index).water};
 const props=new T.Group(),toy=new T.Group();props.visible=false;scene.add(props);props.add(toy);
 const bags=new Map();
 const material=color=>new T.MeshStandardMaterial({color,roughness:.9});
 const makeToy=kind=>createPetToy(T,kind);
 const ball=makeToy('ball'),mouse=makeToy('mouse'),treat=new T.Mesh(new T.SphereGeometry(.05,10,8),material('#a97850'));toy.add(ball,mouse,treat);toy.visible=false;
 const floorToys=Object.fromEntries(Object.keys(TOY_SPOTS).map(k=>{const m=makeToy(k);m.userData.petToy=k;props.add(m);return[k,m];}));
 let ownFood;
 if(station){const bowl=new T.Mesh(new T.CylinderGeometry(.18,.15,.07,24),material(station.color));bowl.position.set(station.bowl.x,.079,station.bowl.z);props.add(bowl);ownFood=new T.Mesh(new T.CylinderGeometry(.13,.13,.018,20),material('#b58c60'));ownFood.position.set(station.bowl.x,.12,station.bowl.z);props.add(ownFood);const cushion=new T.Mesh(new T.CylinderGeometry(.42,.42,.055,32),material(station.color));cushion.scale.z=.85;cushion.position.set(station.rest.x,.063,station.rest.z);props.add(cushion);}
 const box=new T.Group();box.userData.souvenir='box';box.position.set(places.box.x,.05,places.box.z);props.add(box);const cardboard=material('#bd9373'),liner=material('#ead5b6');for(const [w,h,d,x,y,z]of[[.98,.025,.76,0,0,0],[.035,.13,.78,-.49,.065,0],[.035,.13,.78,.49,.065,0],[1,.13,.035,0,.065,-.38],[1,.065,.035,0,.035,.38]]){const m=new T.Mesh(new T.BoxGeometry(w,h,d),cardboard);m.position.set(x,y,z);m.receiveShadow=true;box.add(m);}const mat=new T.Mesh(new T.BoxGeometry(.85,.01,.66),liner);mat.position.y=.02;box.add(mat);
 function makeBag(id){const g=createParcelProp(T,id);props.add(g);return g;}
 function syncBags(){const saved=getParcels(),queue=[...saved.queue,...(saved.opened||[]).filter(b=>care.state.task?.kind==='inspectBag'&&care.state.task.bagId===b.id).map(b=>({...b,empty:true}))];for(const[id,g]of bags)if(!queue.some(b=>b.id===id)){props.remove(g);g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});bags.delete(id);}for(const bag of queue){let g=bags.get(bag.id);if(!g){g=makeBag(bag.id);bags.set(bag.id,g);}g.scale.setScalar(pet.root.scale.x);const t=care.state.task;g.visible=visible&&(bag.phase==='placed'||t?.kind==='carryBag'&&t.bagId===bag.id);if(bag.phase==='placed'){g.position.set(bag.position.x,nav.ground(bag.position.x,bag.position.z),bag.position.z);g.rotation.y=0;}else if(g.visible){const m=mouth();g.position.set(m.x,m.y-.3*pet.root.scale.x,m.z);g.rotation.y=pet.root.rotation.y;}}}
 function pickBag(ray){props.updateMatrixWorld(true);for(const hit of ray.intersectObjects([...bags.values()].filter(g=>g.visible),true)){let g=hit.object;while(g&&!g.userData.parcel)g=g.parent;const bag=getParcels().queue.find(b=>b.id===g?.userData.parcel);if(bag?.phase==='placed')return bag.id;}return null;}
 const others=()=>getOtherPets().filter(p=>p.visible!==false);
 const roomClear=(q,from)=>!others().some(p=>{const distance=Math.hypot(q.x-p.position.x,q.z-p.position.z),before=from?Math.hypot(from.x-p.position.x,from.z-p.position.z):Infinity,radius=.52*Math.max(p.size||1,pet.root.scale.x);return distance<radius&&!(before<radius&&distance>before+1e-7);});
 const local=()=>({x:pet.root.position.x,z:pet.root.position.z});
 const people=()=>getPeople().filter(p=>p.available!==false);
 const person=t=>[...people(),...getPeers()].find(p=>p.key===t.target);
 const mouth=()=>pet.motion.attachment('head',pet.mouthPoint);
 const groundToy=p=>new T.Vector3(p.x,nav.ground(p.x,p.z)+.065,p.z);
 function resetPose(){if(!poseBase)return;poseBase.model.position.copy(poseBase.position);poseBase.model.quaternion.copy(poseBase.quaternion);poseBase.model.scale.copy(poseBase.scale);}
 function begin(model){resetPose();visible=true;props.visible=true;nav=createHomeNavigation(pet.root.scale.x);poseBase={model:pet.model,position:pet.model.position.clone(),quaternion:pet.model.quaternion.clone(),scale:pet.model.scale.clone()};const p=nav.restore(care.state.position);pet.root.position.set(p.x,nav.ground(p.x,p.z),p.z);for(const k of Object.keys(TOY_SPOTS))if(!nav.walkable(care.state.toyPlaces[k].x,care.state.toyPlaces[k].z))care.state.toyPlaces[k]={...TOY_SPOTS[k]};food=ownFood?[ownFood]:[];if(!station)model.traverse(o=>{if(o.isMesh&&o.name.startsWith('feeding-food-'))food.push(o);});pet.bind({ground:nav.ground,matchSpeed:true});pendingTask=null;pendingStage='';route=[];homeTime=0;reactionTime=0;sync();}
 function sync(){syncBags();const belongings=getBelongings();box.visible=belongings.inventory?.box===1;box.scale.setScalar(pet.root.scale.x);const wonky=belongings.inventory?.toy===1&&belongings.shopping?.toyStyle==='wonky';ball.userData.wonkyFace.visible=wonky;floorToys.ball.userData.wonkyFace.visible=wonky;for(const mesh of food)mesh.visible=care.state.bowl>0;for(const[k,m]of Object.entries(floorToys)){m.visible=!(held&&care.state.task?.toy===k)&&!(care.state.task?.kind==='play'&&care.state.task.phase==='doing'&&care.state.task.toy===k);m.position.copy(groundToy(care.state.toyPlaces[k]));}}
 function approach(t){const p=person(t)?.position;if(!p)return null;const from=local(),dx=from.x-p.x,dz=from.z-p.z,a=Math.atan2(dx,dz),m=pet.model.localToWorld(new T.Vector3().fromArray(pet.mouthPoint)),r=Math.hypot(m.x-from.x,m.z-from.z)+(t.target==='you'?.1:.23*pet.root.scale.x);for(const angle of[a,a+.7,a-.7,a+1.5,a-1.5,a+Math.PI]){const q={x:p.x+Math.sin(angle)*r,z:p.z+Math.cos(angle)*r};if(nav.walkable(q.x,q.z)&&roomClear(q))return q;}return null;}
 function destination(t){if(habitTask(t)){if(!carriesToy(t)){if(t.spot)return t.spot;const goals={bakery:places.feeding,store:care.state.toyPlaces.ball,florist:places.window,cafe:places.sofa,courier:HOME_DETAILS.courier};t.focus=t.habit==='courier'?HOME_DETAILS.doorFace:t.habit==='florist'?HOME_DETAILS.flowers:null;return t.spot={x:goals[t.habit].x,z:goals[t.habit].z};}if(t.stage!=='fetch'&&t.habit==='stall')return t.spot||(t.spot={x:places.bed.x,z:places.bed.z});}if((t.socialId||t.bagId)&&t.spot)return t.spot;if(t.kind==='wander'){if(!t.spot)t.spot=chooseComfortSpot(care.state,()=>nextRandom(care.state),q=>nav.walkable(q.x,q.z)&&roomClear(q)&&people().every(p=>Math.hypot(q.x-p.position.x,q.z-p.position.z)>.6)&&!!nav.path(local(),q)?.length);if(t.spot&&nav.walkable(t.spot.x,t.spot.z))return t.spot;const route=localRoute(nav,local(),()=>nextRandom(care.state),{radius:2.6,clear:q=>roomClear(q)&&people().every(p=>Math.hypot(q.x-p.position.x,q.z-p.position.z)>.6)});return t.spot=route?.goal||null;}if(t.kind==='moveAway'){if(t.spot)return t.spot;const from=local(),p=person(t)?.position||from;const options=[places.rug,places.window,{x:1.1,z:.7},{x:-1.15,z:.2}].filter(q=>Math.hypot(q.x-from.x,q.z-from.z)>.6&&Math.hypot(q.x-p.x,q.z-p.z)>.7);return t.spot=options.find(q=>nav.path(from,q))||places.rug;}
  if(carriesToy(t)&&t.stage==='fetch'){const q=care.state.toyPlaces[t.toy],from=local(),a=Math.atan2(q.x-from.x,q.z-from.z),r=.35*pet.root.scale.x;const stand={x:q.x-Math.sin(a)*r,z:q.z-Math.cos(a)*r};return nav.walkable(stand.x,stand.z)?stand:TOY_SPOTS[t.toy];}
  if(t.place==='person'||carriesToy(t))return t.spot||approach(t);
  return places[t.place]||places.rug;
 }
 function dropToy(){if(held){const p=mouth();care.state.toyPlaces[care.state.task?.toy||'ball']=nav.restore({x:p.x,z:p.z});}held=false;toy.visible=false;}
 function schedule(){const t=care.state.task;if(!t){route=[];pendingTask=null;pendingStage='';toy.visible=false;held=false;return;}const stage=(t.stage||'')+'|'+t.phase+'|'+(t.socialId&&t.spot?t.spot.x+','+t.spot.z:'');if(t===pendingTask&&stage===pendingStage)return;pendingTask=t;pendingStage=stage;homeTime=0;targetClock=0;const dest=destination(t);route=t.phase==='walking'&&dest?nav.path(local(),dest)||[]:[];if(t.phase==='walking'&&!route.length&&(!dest||Math.hypot(dest.x-local().x,dest.z-local().z)>.08)){dropToy();care.cancel();onNotice('它暂时走不过去','先换个地方待着。');onSave();}}
 function request(action,options={}){if(getChore())return {accepted:false,text:'正在收拾它的东西，等这件做完再照料。'};if(action==='wake'){resetPose();const p=nav.restore(care.state.position);pet.root.position.set(p.x,nav.ground(p.x,p.z),p.z);pet.bind({ground:nav.ground,matchSpeed:true});}const old=care.state.task,key=options.source==='companion'?'companion:'+options.actor:'you';const nearPerson=options.nearPerson||old?.target===key&&old.phase==='doing'&&SEEK_KINDS.includes(old.kind)&&old.stage!=='fetch';const result=care.request(action,{...options,nearPerson});if(result.accepted){if(held){const p=mouth();care.state.toyPlaces[old.toy]=nav.restore({x:p.x,z:p.z});held=false;}if(nearPerson&&care.state.task?.place==='person')care.state.task.spot=local();schedule();sync();if(!options.deferSave)onSave();}else if(action==='pet'&&care.state.cooldown>0){reactionTime=4;}onNotice(result.accepted?(options.source==='companion'?'它回应'+(options.name||'TA')+'了':'它回应你了'):'它有自己的想法',result.text);draw();return result;}
 function saveSkill(before){if(onSave()!==false)return true;for(const k of Object.keys(care.state))delete care.state[k];Object.assign(care.state,before);route=[];pendingTask=null;pendingStage='';held=carriesToy(care.state.task)&&['carry','lower'].includes(care.state.task.stage);toy.visible=held;if(held){ball.visible=care.state.task.toy==='ball';mouse.visible=!ball.visible;treat.visible=false;toy.position.copy(mouth());toy.quaternion.copy(pet.root.quaternion);}sync();return false;}
 function requestSkill(id,options={}){if(getChore()||getBelongings().job)return {accepted:false,text:'它正忙着，等回家空下来再练。'};const before=care.snapshot();let result;if(id==='stop'){if(!skillTask(care.state.task))return {accepted:false,text:'现在没有正在练的小技能。'};if(care.state.task.skill==='fetch'&&['carry','lower'].includes(care.state.task.stage)&&!held)care.state.toyPlaces[care.state.task.toy]=nav.restore(local());dropToy();care.cancel();result={accepted:true,text:'这次先歇歇，没做完的练习不算完成。'};}else {const target=options.source==='companion'?'companion:'+options.actor:'you';if(!people().some(p=>p.key===target))return {accepted:false,text:'等教它的人回到家里，再一起练。'};result=care.requestSkill(id,options);}if(result.accepted){schedule();sync();if(id!=='stop'&&!skillTask(care.state.task))result={accepted:false,text:'现在走不过去，等换个位置再一起练。'};}if(!saveSkill(before))return {accepted:false,text:'这次练习还没有保存成功，请先重试保存。'};onNotice(result.accepted?'它的小技能':'先歇歇',result.text);draw();return result;}
 function move(dt){let speed=0;if(route.length){const a=route[0],dx=a.x-pet.root.position.x,dz=a.z-pet.root.position.z,d=Math.hypot(dx,dz);speed=.5*pet.root.scale.x;const turn=turnPet(pet.root.rotation.y,Math.atan2(dx,dz),dt);pet.root.rotation.y=turn.heading;let step=turn.canMove?Math.min(d,speed*dt):0;const next={x:a.x+(pet.root.position.x-a.x)*(1-step/Math.max(d,1e-6)),z:a.z+(pet.root.position.z-a.z)*(1-step/Math.max(d,1e-6))};if(step&&!roomClear(next,local())){step=0;speed=0;if(d>.5){for(const offset of[Math.PI/2,-Math.PI/2,2.3,-2.3,Math.PI,.8,-.8]){const angle=Math.atan2(dx,dz)+offset,q={x:pet.root.position.x+Math.sin(angle)*.8,z:pet.root.position.z+Math.cos(angle)*.8};if(nav.walkable(q.x,q.z)&&roomClear(q)){const first=nav.path(local(),q),detour=nav.path(q,a);if(first&&detour){route=[...first,...detour,...route.slice(1)];break;}}}}}if(!step)speed=0;if(d>.0001){pet.root.position.x+=dx/d*step;pet.root.position.z+=dz/d*step;}if(d<=step+.002)route.shift();}pet.root.position.y=nav.ground(pet.root.position.x,pet.root.position.z);return speed;}
 function tick(dt,{idleAllowed=true}={}){const skillBefore=skillTask(care.state.task)?care.snapshot():null;let skillSaveFailed=false;const persist=()=>{if(!skillBefore)return onSave();const ok=saveSkill(skillBefore);skillSaveFailed=skillSaveFailed||!ok;return ok;};if(getChore()){pet.motion?.setActionPose({});pet.motion?.update(dt,0);care.tick(dt,{home:true,idleAllowed:false});sync();return;}resetPose();const inspect=(getParcels().opened||[]).find(b=>!b.served&&!b.reactionDone);if(inspect&&!care.state.task&&!care.state.helper)care.startBag(inspect.id,inspect.position,inspect.reaction);const pending=getParcels().queue.find(p=>p.phase==='carrying');if(pending&&!care.state.task&&!care.state.helper){const base=station?.rug||places.rug;const point=socialBeside(base,pet.root.scale.x)||nav.restore(base);onBag('carry-bag',{bagId:pending.id,position:point});}schedule();homeTime+=dt;targetClock+=dt;reactionTime=Math.max(0,reactionTime-dt);pet.setMood(moodFromCare(care.state,reactionTime>0));let task=care.state.task;const before=task;
  if(task?.target&&['person','toy'].includes(task.place)&&task.kind!=='moveAway'&&!person(task)){dropToy();care.cancel();schedule();persist();task=null;}
  if(task?.phase==='walking'&&task.target&&!task.spot&&!(carriesToy(task)&&task.stage==='fetch')&&targetClock>.6){targetClock=0;const dest=destination(task),last=route.at(-1);if(dest&&last&&Math.hypot(dest.x-last.x,dest.z-last.z)>.25)route=nav.path(local(),dest)||route;}
  let speed=move(dt);blockedTime=route.length&&!speed?blockedTime+dt:0;if(blockedTime>3&&(task?.kind==='wander'||habitTask(task)||skillTask(task))){care.cancel();schedule();task=null;blockedTime=0;persist();}if(task?.phase==='walking'&&!route.length){if(task.place==='person'&&!(carriesToy(task)&&task.stage==='fetch'))task.spot=local();const lastEvent=care.state.recent.at(-1);care.arrive();homeTime=0;task=care.state.task;if(care.state.recent.at(-1)!==lastEvent)onNotice('它来找你们了',care.state.recent.at(-1).text);else if(carriesToy(task)&&task.stage==='fetch')onNotice('它想一起玩','低下头，准备把玩具叼起来。');if(task?.kind==='sleep'){if(task.place!=='person')pet.motion.dispose();pet.root.rotation.y=task.place==='person'?Math.atan2(person(task).position.x-pet.root.position.x,person(task).position.z-pet.root.position.z):places[task.place].yaw;}persist();}
  const doing=task?.phase==='doing',p=task&&person(task)?.position;let desired=null,pose={};
  if(doing&&task.kind==='inspectBag')pose={headPitch:.35+.05*Math.sin(task.time*3),headYaw:.1*Math.sin(task.time),roll:task.bagReaction==='eager'?.025*Math.sin(task.time*3):0};
  if(task?.kind==='carryBag')pose={headPitch:.08};
  if(doing&&['eat','drink','treat'].includes(task.kind))pose={headPitch:.18+.04*Math.sin(task.time*5)};
  if(doing&&task.kind==='waitFood'){const lookBowl=Math.floor(task.time/3)%2===0;desired=lookBowl?places.feeding.yaw:p?Math.atan2(p.x-pet.root.position.x,p.z-pet.root.position.z):0;pose={headPitch:lookBowl?.2:-.06};}
  if(doing&&['pet','invitePet'].includes(task.kind)){const rub=task.kind==='pet'||task.time<4,tempo=task.manner?.tempo||1,gentle=task.manner?.gentle;pose={roll:rub?(gentle?.04:.07)*Math.sin(task.time*2.5*tempo):.025,height:rub?-.012:-.022,chestHeight:rub?0:-.008,pelvisHeight:rub?0:-.01,headRoll:rub?.12*Math.sin(task.time*2.5):.08,headYaw:rub?.08*Math.sin(task.time*2):0};if(p)desired=Math.atan2(p.x-pet.root.position.x,p.z-pet.root.position.z);}
  if(doing&&task.kind==='askSnack'){pose={headPitch:-.12,headYaw:.12*Math.sin(task.time*.9)};if(p)desired=Math.atan2(p.x-pet.root.position.x,p.z-pet.root.position.z);}
  if(doing&&habitTask(task)&&!carriesToy(task)){pose=idlePose(WORK_HABITS[task.habit].pose,task.time);if(task.focus)desired=Math.atan2(task.focus.x-pet.root.position.x,task.focus.z-pet.root.position.z);}
  if(doing&&task.kind==='wander')pose=idlePose(task.idleAction,task.time);
  if(doing&&skillTask(task)&&task.skill!=='fetch'){pose=task.skill==='stay'?{sit:1,headPitch:.2,headYaw:.035*Math.sin(task.time)}:{headPitch:-.04,headYaw:.08*Math.sin(task.time*1.5)};if(p)desired=Math.atan2(p.x-pet.root.position.x,p.z-pet.root.position.z);}
  if(doing&&task.kind==='watch')desired=task.socialId&&task.focus?Math.atan2(task.focus.x-pet.root.position.x,task.focus.z-pet.root.position.z):places.window.yaw+.08*Math.sin(task.time*.6);
  if(carriesToy(task)&&task.stage==='fetch'&&doing){const q=care.state.toyPlaces[task.toy];desired=Math.atan2(q.x-pet.root.position.x,q.z-pet.root.position.z);}
  if(carriesToy(task)&&['fetch','lower'].includes(task.stage)&&doing)pose={height:-.02,chestHeight:-.012,pelvisHeight:-.01,headPitch:1.03};
  if(carriesToy(task)&&task.stage==='carry')pose={headPitch:.06};
  if(carriesToy(task)&&['lower','waiting'].includes(task.stage)&&p)desired=Math.atan2(p.x-pet.root.position.x,p.z-pet.root.position.z);
  let pivot=false;if(desired!==null){const turn=turnPet(pet.root.rotation.y,desired,dt);pivot=Math.abs(turn.heading-pet.root.rotation.y)>.001;pet.root.rotation.y=turn.heading;}
  if(doing&&task.kind==='sleep'&&task.place==='person')pose={height:-.02,chestHeight:-.012,pelvisHeight:-.014,headPitch:.12,headRoll:.10};
  pet.motion.setActionPose(pose);if(doing&&task.kind==='sleep'&&task.place!=='person')pet.motion.updateExpression(dt);else pet.motion.update(dt,speed,0,speed>0||route.length>0||pivot);
  held=false;toy.visible=false;
  if(carriesToy(task)){
   const stage=task.stage;ball.visible=task.toy==='ball';mouse.visible=!ball.visible;treat.visible=false;
   if(stage==='carry'||stage==='lower'||stage==='fetch'&&doing&&task.time>=1.6){held=true;toy.visible=true;const q=mouth();if(stage==='fetch')q.lerp(groundToy(care.state.toyPlaces[task.toy]),Math.max(0,(2-task.time)/.4));if(stage==='lower')q.lerp(groundToy(nav.walkable(q.x,q.z)?{x:q.x,z:q.z}:local()),Math.max(0,Math.min(1,(task.time-.8)/.4)));toy.position.copy(q);toy.quaternion.copy(pet.root.quaternion);}
   if(stage==='fetch'&&care.pickupToy()){schedule();onNotice(habitTask(task)?'它的小习惯':'它想一起玩',habitTask(task)?(task.habit==='stall'?'叼起自己的小球，慢慢带到窝边。':'闻过玩具，正叼来给'+(task.name||'你')+'看。'):'叼起玩具，正送到'+(task.name||'你')+'身边。');persist();}
   else if(stage==='lower'&&care.deliverToy(nav.walkable(toy.position.x,toy.position.z)?{x:toy.position.x,z:toy.position.z}:local())){held=false;toy.visible=false;schedule();onNotice(habitTask(task)?'它的小习惯':skillTask(task)?'它的小技能':'它来找你们了',care.state.recent.at(-1).text);if(!skillTask(task))persist();}
  }else if(doing&&task.kind==='play'){toy.visible=true;treat.visible=false;ball.visible=task.toy==='ball';mouse.visible=!ball.visible;const phase=task.time*.65*(task.manner?.tempo||1),base=task.place==='person'?task.spot:places.rug,target={x:base.x+.55*Math.sin(phase),z:base.z+.4*Math.cos(phase)};toy.position.set(target.x,nav.ground(target.x,target.z)+.12+.06*Math.abs(Math.sin(task.time*2)),target.z);toy.rotation.y=phase;care.state.toyPlaces[task.toy]=nav.restore(target);if(!route.length&&Math.hypot(target.x-pet.root.position.x,target.z-pet.root.position.z)>.18)route=nav.path(local(),target)||[];}
  else if(doing&&task.kind==='treat'){toy.visible=true;treat.visible=true;ball.visible=false;mouse.visible=false;toy.position.copy(mouth());}
  if(doing&&task.kind==='sleep'&&task.place!=='person'){const blend=Math.min(1,homeTime/1.3),p=task.place==='person'?task.spot:places[task.place];if(task.place==='bed'&&!station){pet.root.position.x=T.MathUtils.lerp(p.x,HOME_DETAILS.bed.x,blend);pet.root.position.z=T.MathUtils.lerp(p.z,HOME_DETAILS.bed.z,blend);pet.root.position.y=.11+.25*blend+Math.sin(blend*Math.PI)*.18;}poseBase.model.quaternion.premultiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),blend*1.45));pet.root.updateMatrixWorld(true);const bottom=new T.Box3().setFromObject(poseBase.model,true).min.y,floor=task.place==='bed'&&!station?.32:nav.ground(pet.root.position.x,pet.root.position.z);pet.root.position.y+=floor-bottom+.003*(1+Math.sin(task.time*1.6));}
  if(doing&&task.kind==='sleep'&&task.place==='person'){pet.root.updateMatrixWorld(true);const bottom=new T.Box3().setFromObject(pet.model,true).min.y;pet.root.position.y+=nav.ground(pet.root.position.x,pet.root.position.z)-bottom+.003*(1+Math.sin(task.time*1.6));}
  if(skillSaveFailed){sync();return;}
  care.state.position=doing&&task.kind==='sleep'?{...(task.place==='person'?task.spot:places[task.place])}:local();
  if(task?.kind==='carryBag'&&task.phase==='doing'&&task.time>=1.2){const placed=onBag('place-bag',{bagId:task.bagId});if(placed.accepted)onNotice('小袋子放好了',placed.text);}
  if(task?.kind==='inspectBag'&&task.phase==='doing'&&task.time>=4){onBag('bag-reaction',{bagId:task.bagId});}
  const result=care.tick(dt,{home:true,idleAllowed,people:people(),belongings:getBelongings(),restPlaces:['bed','sofa',...(getBelongings().inventory?.box===1?['box']:[])]});if(result?.accepted){schedule();if(!result.quiet)onNotice('它自己决定了',result.text);persist();}if(before&&before!==care.state.task){if(before.kind==='play'&&before.phase==='doing')care.state.toyPlaces[before.toy]=nav.restore({x:toy.position.x,z:toy.position.z});if(before.kind==='sleep'){resetPose();const p=nav.restore(care.state.position);pet.root.position.set(p.x,nav.ground(p.x,p.z),p.z);pet.bind({ground:nav.ground,matchSpeed:true});}schedule();persist();}sync();
 }
 function leave(){if(nav)dropToy();resetPose();visible=false;props.visible=false;reactionTime=0;pet.motion?.setActionPose({});care.cancel();route=[];pendingTask=null;}
 function dispose(){leave();scene.remove(props);props.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});}
 function socialBeside(point,size=1){const distance=.62*Math.max(size,pet.root.scale.x);for(const angle of[0,Math.PI/2,-Math.PI/2,Math.PI]){const q={x:point.x+Math.sin(angle)*distance,z:point.z+Math.cos(angle)*distance};if(nav?.walkable(q.x,q.z)&&nav.path(local(),q)&&roomClear(q))return q;}return null;}
 function cancelSocial(){const sleeping=care.state.task?.kind==='sleep';dropToy();care.cancel();resetPose();if(sleeping){const p=nav.restore(care.state.position);pet.root.position.set(p.x,nav.ground(p.x,p.z),p.z);pet.bind({ground:nav.ground,matchSpeed:true});}schedule();sync();return true;}
 return {requestSkill,pickBag,bagObjects:()=>[...bags.values()],inspectBag:(point,reaction,id)=>care.startBag(id,point,reaction),cancelSocial,socialSpot:place=>({...((place==='window')?HOME_PLACES.window:places[place])}),socialBeside,begin,request,tick,leave,resetPose,dispose,setVisible:value=>{visible=!!value;props.visible=!!value;},toyObject:kind=>floorToys[kind],boxObject:()=>box,snapshot:()=>({visible,station,route:route.map(p=>({...p})),position:local(),toy:toy.visible,held,box:{visible:box.visible,position:box.position.toArray()},toyPosition:toy.visible?toy.position.toArray():null,people:people(),restPlaces:['bed','sofa',...(getBelongings().inventory?.box===1?['box']:[])],floorToys:Object.fromEntries(Object.entries(floorToys).map(([k,m])=>[k,{visible:m.visible,position:m.position.toArray()}]))})};
}
