import {dailyRoutine} from '../fairy-garden/real-clock.mjs?v=fg-ef50e6818d2983b6';
import {lifeOf,lifeNote} from './routine.mjs?v=fg-ef50e6818d2983b6';
import {createTownLife,newTownLife} from './town-life.mjs?v=fg-ef50e6818d2983b6';
import {localRoute,nextRandom,restoreResident} from './autonomy.mjs?v=fg-ef50e6818d2983b6';
import {createTraveler,loadTravelerSource} from '../fairy-garden/traveler.mjs?v=fg-ef50e6818d2983b6';
import {seatLook} from '../fairy-garden/wardrobe.mjs?v=fg-ef50e6818d2983b6';
import {createHomeNavigation,HOME_PLACES} from './home-navigation.mjs?v=fg-ef50e6818d2983b6';
import {turnPet} from './movement.mjs?v=fg-ef50e6818d2983b6';
// No model calls here: these are visible, local acts in this archive.
export async function createHousemate({scene,host,care,home,notice,save,getPets=()=>[],getActiveId=()=>null,resident={},world=null,getPlace=()=> 'home',getTime=()=>null}){
 const person=host.companion?.();if(!person?.id)return null;
 const archive=host.load(),garden=archive.worlds?.garden||archive.world;
 const look=seatLook('companion',archive.journey?.companionLook||garden?.companion?.look,person.ta);
 const doll=createTraveler(await loadTravelerSource(),true,look);await doll.ready();scene.add(doll.root);doll.root.scale.setScalar(1.6);doll.root.visible=false;
 if(resident.id!==String(person.id)){Object.assign(resident,restoreResident({id:String(person.id)}));delete resident.town;}
 if(world&&!resident.town)resident.town=newTownLife('home',resident.town?.position||resident.position||{x:-1.15,z:1.35},resident.rng);const town=world?createTownLife(resident.town,{world,size:()=>1.4,onChange:save}):null;const nav=createHomeNavigation(1.4);let route=[],clock=0,idle=0,visible=false,job=null,blockedTime=0;
 const members=()=>getPets().length?getPets().filter(x=>!x.entry.town||x.entry.town.place==='home'):[{entry:{id:'pet-1'},care,home}];
 const choose=id=>{const selected=members().find(x=>x.entry.id===id)||members().find(x=>x.entry.id===getActiveId())||members()[0];if(!selected)return '';care=selected.care;home=selected.home;return selected.entry.id;};
 const pos=()=>({x:doll.root.position.x,z:doll.root.position.z});
 function begin(){if(town&&town.state.place!=='home'){visible=false;doll.root.visible=false;return;}visible=true;doll.root.visible=true;const resume=members().find(x=>String(x.care.state.helper?.id)===String(person.id));choose(resume?.entry.id);const old=care.state.helper;job=old&&String(old.id)===String(person.id)?old:null;care.state.helper=job;const p=nav.restore(job?.position||resident.town?.position||resident.position||{x:-1.15,z:1.35});doll.root.position.set(p.x,.08,p.z);doll.root.rotation.y=resident.heading;route=[];if(job){resident.activity=null;if(job.phase==='walking')plan();}else if(resident.activity?.phase==='walking'){const goal=resident.activity.goal;route=goal&&nav.walkable(goal.x,goal.z)?nav.path(pos(),goal)||[]:[];if(!route.length)resident.activity=null;}syncResident();}
 function target(action){const bowl=home.snapshot().station?.bowl;return action==='feed'?(bowl?{x:bowl.x,z:bowl.z+.25}:{x:1.55,z:1.75}):action==='play'?{x:-.85,z:1.35}:{x:-.65,z:.55};}
 function plan(){route=nav.path(pos(),target(job.action))||[];if(!route.length){care.record(person.name+'暂时走不过去，没能照料它。');job=null;care.state.helper=null;save();}}
 function request(action,{responsive=false,automatic=false,petId=getActiveId()}={}){if(!visible&&!town||town&&town.state.place!=='home')return {accepted:false,text:person.name+'正在外面走走，等回家再照料它。'};if(!['feed','play','pet','snack'].includes(action))return {accepted:false,text:'这个动作暂时做不到。'};if(job)return {accepted:false,text:person.name+'正在照料它，等一会儿。'};if(petId&&!members().some(x=>x.entry.id===petId))return {accepted:false,text:'它正在外面走走，等回家再一起照料。'};const selectedId=choose(petId);if(!automatic&&!responsive)town?.hold();resident.activity=null;resident.idle=0;route=[];job={petId:selectedId,id:String(person.id),name:person.name,action,phase:responsive&&action!=='feed'?'doing':'walking',time:0,position:pos(),responsive};care.state.helper=job;if(job.phase==='walking')plan();if(!job)return {accepted:false,text:'暂时走不过去。'};save();return {accepted:true,text:person.name+'准备走过去'+({feed:'添粮',play:'陪玩',pet:'摸摸它',snack:'给一小口零食'})[action]+'，等它回应。'};}
 function syncResident(){resident.position=pos();resident.heading=doll.root.rotation.y;if(town&&town.state.place==='home'&&town.state.phase==='idle'){town.state.position=pos();town.state.heading=doll.root.rotation.y;}}
 const canOfferCare=s=>!s.task||s.task.source==='self'&&['watch','wander','play'].includes(s.task.kind)&&!s.task.socialId;
 const petPosition=x=>x.pet?.root.position||x.home.snapshot().position;
 const petSize=x=>x.pet?.root.scale.x||1;
 function clearGoal(q){return members().every(x=>{const p=petPosition(x);return Math.hypot(q.x-p.x,q.z-p.z)>.55*petSize(x);});}
 function idleLife(dt,settled){
  const time=getTime(),life=lifeOf(resident),period=time?dailyRoutine(time,resident.rng):null;
  if(period&&resident.activity?.kind==='sleep'&&(period.id!=='sleep'||life.wakeUntil>time.at)){resident.activity=null;route=[];}
  if(!settled&&period&&(!town||town.state.place==='home')&&!resident.activity){
   const sleeping=period.id==='sleep'&&!(life.wakeUntil>time.at),meal=['breakfast','lunch','dinner'].includes(period.id);
   if(sleeping||meal&&!(life.marks.date===time.date&&life.marks[period.id])){const goal=nav.restore({x:-.65,z:.55});resident.activity={kind:sleeping?'sleep':'meal',phase:'walking',goal,time:0,duration:sleeping?86400:8};route=nav.path(pos(),goal)||[];}
  }

  if(settled){route=[];resident.activity=null;resident.idle=0;return false;}
  const a=resident.activity;
  if(!a){resident.idle+=dt;if(resident.idle<7)return false;resident.idle=0;const next=localRoute(nav,pos(),()=>nextRandom(resident),{radius:2.5,clear:clearGoal});if(!next)return false;const roll=nextRandom(resident);resident.activity={kind:roll<.35?'read':roll<.65?'look':roll<.85?'rest':'stroll',phase:'walking',goal:next.goal,time:0,duration:8+nextRandom(resident)*8};route=next.route;save();return false;}
  if(a.phase==='walking'){
   const q=route[0];if(q){const p=pos(),dx=q.x-p.x,dz=q.z-p.z,d=Math.hypot(dx,dz),turn=turnPet(doll.root.rotation.y,Math.atan2(dx,dz),dt);doll.root.rotation.y=turn.heading;const step=turn.canMove?Math.min(d,dt*.65):0,next={x:p.x+(d?dx/d*step:0),z:p.z+(d?dz/d*step:0)};const safe=members().every(x=>{const pet=petPosition(x),r=.45*petSize(x);return Math.hypot(next.x-pet.x,next.z-pet.z)>=r||Math.hypot(next.x-pet.x,next.z-pet.z)>Math.hypot(p.x-pet.x,p.z-pet.z);});blockedTime=step&&!safe?blockedTime+dt:0;if(blockedTime>2){route=[];resident.activity=null;resident.idle=3;save();return false;}if(step&&safe){doll.root.position.x=next.x;doll.root.position.z=next.z;}if(d<=step+.002&&safe)route.shift();if(route.length)return step>0&&safe;}
   a.phase='doing';a.time=0;save();
  }else{a.time+=dt;if(a.kind==='look')doll.root.rotation.y+=Math.cos(a.time*.7)*dt*.1;if(a.kind==='sleep'&&time)lifeNote(resident,time,person.name+'在家里睡下了。','sleep');if(a.time>=a.duration){if(a.kind==='meal'&&time)lifeNote(resident,time,person.name+'在家里吃过'+({breakfast:'早餐',lunch:'午饭',dinner:'晚饭'})[period.id]+'。',period.id);resident.activity=null;resident.idle=0;save();}}
  return false;
 }
 function tick(dt){if(job&&town&&!members().some(x=>x.entry.id===job.petId)){care.record(person.name+'看见它出门了，等回家再照料。');if(care.state.task?.source==='companion'&&String(care.state.task.actor)===String(person.id))care.cancel();care.state.helper=null;job=null;route=[];save();}if(town){const settled=members().some(x=>{const t=x.care.state.task;return t?.target==='companion:'+person.id&&['sleep','invitePet','askSnack','invitePlay','waitFood'].includes(t.kind);});const time=getTime(),period=time?dailyRoutine(time,resident.rng):null,stayHome=period?.home&&!(period.id==='sleep'&&lifeOf(resident).wakeUntil>time.at);if(stayHome&&!job&&!settled&&town.state.place!=='home'&&(town.state.target!=='home'||!town.state.goal))town.go('home');const result=town.tick(dt,{stayHome:!!stayHome,blocked:!!job||settled||getPets().some(x=>x.career?.state.job),position:pos(),heading:doll.root.rotation.y,needsHome:!!stayHome||members().some(x=>x.care.state.satiety<40)});if(result.owned||town.state.place!=='home'){if(resident.activity){resident.activity=null;route=[];}const q=town.state.position;doll.root.position.set(q.x,town.nav().ground(q.x,q.z)+.03,q.z);doll.root.rotation.y=town.state.heading;clock+=dt;visible=town.state.place===(getPlace()||'outside');doll.root.visible=visible;doll.animate(clock,{moving:result.speed>0,gesture:'rest',height:doll.root.position.y});syncResident();return;}visible=town.state.place==='home'&&getPlace()==='home';doll.root.visible=visible;}if(!visible&&!town)return;clock+=dt;idle+=dt;let moving=false;
  const pending=members().filter(x=>{const v=x.care.state.task;return v?.source==='self'&&v.target==='companion:'+person.id&&v.phase==='doing'&&v.time>=2&&['waiting','cuddle'].includes(v.stage);}).sort((a,b)=>b.care.state.task.time-a.care.state.task.time)[0];if(!job&&pending)choose(pending.entry.id);const visit=care.state.task;if(!job&&visit?.source==='self'&&visit.target==='companion:'+person.id&&visit.phase==='doing'&&visit.time>=2&&['waiting','cuddle'].includes(visit.stage)){const action=({waitFood:'feed',invitePlay:'play',invitePet:'pet',askSnack:'snack'})[visit.kind];if(action)request(action,{responsive:true,petId:pending?.entry.id});}
  if(job){if(job.phase==='walking'){
   const dest=route[0];if(dest){const p=pos(),dx=dest.x-p.x,dz=dest.z-p.z,d=Math.hypot(dx,dz),turn=turnPet(doll.root.rotation.y,Math.atan2(dx,dz),dt);doll.root.rotation.y=turn.heading;const step=turn.canMove?Math.min(d,dt*.8):0;moving=step>0;if(d>1e-5){doll.root.position.x+=dx/d*step;doll.root.position.z+=dz/d*step;}if(d<=step+.002)route.shift();}
   if(!route.length){job.phase='doing';job.time=0;save();}
  }else{job.time+=dt;const t=care.state.task;const to=job.action==='feed'?(home.snapshot().station?.bowl||HOME_PLACES.feeding):{x:care.state.position?.x||0,z:care.state.position?.z||.55};doll.root.rotation.y=turnPet(doll.root.rotation.y,Math.atan2(to.x-doll.root.position.x,to.z-doll.root.position.z),dt).heading;
   if(job.time>=1&&!job.started){const result=home.request(job.action,{source:'companion',actor:String(person.id),name:person.name,nearPerson:job.responsive});job.started=true;notice(person.name+'与它',result.text);if(!result.accepted){care.record(person.name+'这次没能'+({feed:'添粮',play:'陪玩',pet:'摸摸它',snack:'给一小口零食'})[job.action]+'：'+result.text);job=null;care.state.helper=null;save();}else if(!care.state.task){job=null;care.state.helper=null;save();}}
   else if(job.started&&(!t||t.source!=='companion'||String(t.actor)!==String(person.id))){job=null;care.state.helper=null;idle=0;save();}
  }
  if(job)job.position=pos();
  }else if(members().length&&idle>=50&&!members().some(x=>{const t=x.care.state.task;return t?.kind==='sleep'&&t.phase==='doing'&&t.target==='companion:'+person.id;})){idle=0;const candidate=members().filter(x=>canOfferCare(x.care.state)).sort((a,b)=>a.care.state.satiety-b.care.state.satiety)[0];if(candidate)choose(candidate.entry.id);const s=care.state;if(canOfferCare(s)){if(s.satiety<50&&s.bowl<25)request('feed',{petId:candidate?.entry.id,automatic:true});else if(Math.hypot((s.position?.x||0)-doll.root.position.x,(s.position?.z||0)-doll.root.position.z)<1.8&&s.cooldown<=0)request(s.energy>55&&s.mood<78?'play':'pet',{petId:candidate?.entry.id,automatic:true});}}
  const settled=members().some(x=>{const t=x.care.state.task;return t?.phase==='doing'&&t.target==='companion:'+person.id&&['sleep','invitePet'].includes(t.kind);});
  const approaching=members().some(x=>{const t=x.care.state.task;return t?.phase==='walking'&&t.target==='companion:'+person.id&&['sleep','invitePet','askSnack','invitePlay'].includes(t.kind)&&t.stage!=='fetch';});
  if(!job)moving=idleLife(dt,settled||approaching);syncResident();
  doll.animate(clock,{moving,gesture:job?.phase==='doing'?(job.action==='play'?'stir':'hold'):resident.activity?.phase==='doing'&&resident.activity.kind==='read'?'read':resident.activity?.phase==='doing'&&resident.activity.kind==='meal'?'hold':'rest',seated:resident.activity?.phase==='doing'&&['rest','read','sleep','meal'].includes(resident.activity.kind)||settled||job?.phase==='doing'&&job.action==='pet'||visit?.kind==='sleep'&&visit.place==='person'&&visit.target==='companion:'+person.id&&visit.phase==='doing',height:.08});
 }
 function leave(){if(town){syncResident();visible=false;doll.root.visible=false;return;}syncResident();resident.activity=null;resident.idle=0;visible=false;doll.root.visible=false;route=[];if(job)care.record(person.name+'跟着出门了，这次照料先停下。');job=null;for(const p of members())p.care.state.helper=null;}
 function wake(){const life=lifeOf(resident);life.wakeUntil=Date.now()+30*60000;if(resident.activity?.kind==='sleep'){resident.activity=null;route=[];}save();return true;}
 return {begin,tick,request,wake,leave,doll,person,town,setVisible:value=>{visible=!!value;doll.root.visible=visible;},snapshot:()=>({visible,place:town?.state.place||'home',town:town?structuredClone(town.state):null,position:pos(),job:job?{...job}:null,activity:resident.activity?structuredClone(resident.activity):null,summary:town?.summary(id=>world.building(id)?.title||'小镇街区')|| (job?'正在照料宠物':resident.activity?.phase==='walking'?'在家里慢慢走动':resident.activity?.kind==='sleep'?'在家里睡觉':resident.activity?.kind==='meal'?'在家里吃饭':resident.activity?.kind==='read'?'坐下来翻书':resident.activity?.kind==='look'?'看看家里':resident.activity?.kind==='rest'?'歇一会儿':'在家里陪着它们'),look})};
}
