import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{createPetWorld}from'../../art/pet-career/world-navigation.mjs';
import{createPetCare}from'./care.mjs';import{createPetCareer}from'./career.mjs';import{restorePetState,snapshotPetState,newPetEntry,projectActivePet,PET_LIMIT}from'./state.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
test('v3 writer migration keeps the original pet identity, completed care and wages across repeated reloads',()=>{const care=createPetCare({satiety:50});care.request('snack');care.arrive();for(let i=0;i<6;i++)care.tick(1,{home:true});const career=createPetCareer({balance:35,inventory:{bread:2}});const legacy={version:3,configured:true,profile:{species:'dog',name:'团子',weight:1.22,size:1.18,look:{base:'#8899aa',patch:'#443322'}},care:care.snapshot(),career:career.snapshot(),room:null};const migrated=restorePetState(legacy,world);assert.equal(migrated.pets.length,1);assert.equal(migrated.pets[0].care.relationships.you.snack,1);assert.equal(migrated.career.balance,35);assert.equal(migrated.profile.name,'团子');const saved=snapshotPetState(migrated,{position:migrated.position,room:null,outdoor:null,evening:false});const again=restorePetState(saved,world);assert.deepEqual(again.pets,migrated.pets);assert.equal(again.activePetId,migrated.activePetId);});
test('four independently created pets have their own care, traits, coins, profile and active projection',()=>{const s=restorePetState(null,world);let rng=7;const random=()=>((rng=Math.imul(rng,1664525)+1013904223>>>0)/4294967296);for(let i=1;i<PET_LIMIT;i++)s.pets.push(newPetEntry({species:i%2?'dog':'cat',name:'小家伙'+i},s.pets,random));assert.equal(new Set(s.pets.map(p=>p.id)).size,4);assert.equal(new Set(s.pets.map(p=>p.care.rng)).size,4);assert.equal(new Set(s.pets.map(p=>p.care.traits.active)).size,4);s.activePetId=s.pets[2].id;projectActivePet(s);s.care.relationships.you={play:9,pet:0,food:0,refused:0,snack:0,rest:0};s.career.balance=72;s.profile.weight=1.25;s.configured=true;const restored=restorePetState(snapshotPetState(s,{position:s.position,room:null,outdoor:null,evening:false}),world);assert.equal(restored.activePetId,s.pets[2].id);assert.equal(restored.career.balance,72);for(const p of restored.pets.filter(p=>p.id!==s.activePetId)){assert.equal(p.career.balance,0);assert.equal(p.profile.weight,1);assert.equal(p.care.relationships.you,undefined);}});
test('canonical pet rows take precedence over stale v3 projections and never discard pets from larger backups',()=>{const s=restorePetState({pets:[{id:'a',configured:true,profile:{name:'自己的猫'},care:{satiety:12}},{id:'a',profile:{species:'dog'}},...Array.from({length:4},(_,i)=>({id:'p'+i}))],activePetId:'missing',profile:{name:'过期资料'},care:{satiety:99}},world);assert.equal(s.profile.name,'自己的猫');assert.equal(s.care.satiety,12);assert.equal(s.pets.length,6);assert.equal(new Set(s.pets.map(p=>p.id)).size,6);assert.equal(s.pets[1].profile.name,'狗狗');});

test('every additional pet station can be reached at the largest supported size',async()=>{const{createHomeNavigation}=await import('./home-navigation.mjs');const source=readFileSync(new URL('../../art/pet-career/preview.mjs',import.meta.url),'utf8'),a=source.indexOf('const STATIONS='),b=source.indexOf(';',a);assert.ok(a>=0&&b>a);const stations=Function('return '+source.slice(a+'const STATIONS='.length,b))();const nav=createHomeNavigation(1.3);for(const station of stations.filter(Boolean))for(const key of['bowl','rest','rug','watch']){const q=station[key];assert.ok(nav.walkable(q.x,q.z),key+JSON.stringify(q));assert.ok(nav.path({x:-.28,z:.55},q),key+JSON.stringify(q));}});
