import test from 'node:test';import assert from 'node:assert/strict';
import {choosePetPerson,initiativeFor,YOU_SPOT} from './initiative.mjs';
import {createPetCare} from './care.mjs';
const people=[{key:'you',name:'你',position:YOU_SPOT},{key:'companion:test',id:'test',name:'同伴',position:{x:-1,z:1}}];
const run=(c,n,opts={home:true,people})=>{for(let i=0;i<n;i++)c.tick(1,opts);};
test('an empty bowl produces a request, walking does not fabricate a visit or meal',()=>{const c=createPetCare({satiety:30,initiativeCooldown:0});run(c,12);assert.equal(c.state.task.kind,'waitFood');assert.equal(c.state.recent.length,0);const before=c.state.satiety;run(c,8);assert.ok(c.state.satiety<=before);assert.equal(c.state.bowl,0);c.arrive();assert.equal(c.state.recent[0].type,'visit');assert.equal(c.state.task.stage,'waiting');const again=createPetCare(c.snapshot());again.arrive();assert.equal(again.state.recent.length,1);assert.equal(again.state.bowl,0);});
test('the toy is fetched, carried and physically delivered before a person receives a visit',()=>{const c=createPetCare({initiativeCooldown:0,rng:1,traits:{active:1}});run(c,12);assert.equal(c.state.task.kind,'invitePlay');c.arrive();assert.equal(c.pickupToy(),false);assert.equal(c.state.recent.length,0);run(c,2);assert.equal(c.pickupToy(),true);assert.equal(c.state.task.phase,'walking');run(c,40);assert.equal(c.state.task.stage,'carry');const resumed=createPetCare(c.snapshot());resumed.arrive();assert.equal(resumed.state.recent.length,0);run(resumed,2);assert.equal(resumed.deliverToy({x:-.7,z:1.2}),true);assert.deepEqual(resumed.state.toyPlaces.ball,{x:-.7,z:1.2});assert.equal(resumed.state.recent.length,1);assert.equal(resumed.deliverToy({x:0,z:0}),false);assert.equal(resumed.state.relationships.you?.play||0,0);});
test('completed care teaches distinct people preferences, not assigned caregiver roles',()=>{const c=createPetCare({rng:1});for(let i=0;i<4;i++){c.request('snack');c.arrive();run(c,6,{home:true});}for(let i=0;i<4;i++){c.request('play',{source:'companion',actor:'test',name:'同伴'});c.arrive();run(c,16,{home:true});}assert.equal(c.state.relationships.you.snack,4);assert.equal(c.state.relationships['companion:test'].play,4);let snacks=0,play=0;for(let i=0;i<1000;i++){snacks+=choosePetPerson(c.state,'snack',people,i/1000).key==='you';play+=choosePetPerson(c.state,'play',people,i/1000).key==='companion:test';}assert.ok(snacks>850);assert.ok(play>850);const reverse={relationships:{you:{play:8},'companion:test':{snack:8}}};assert.equal(choosePetPerson(reverse,'play',people,.7).key,'you');assert.equal(choosePetPerson(reverse,'snack',people,.3).key,'companion:test');});
test('a learned snack request is separate from hunger, sleeps choose real available people',()=>{const s=createPetCare({satiety:70,relationships:{you:{snack:5},'companion:test':{pet:8,rest:3}}}).state;assert.equal(initiativeFor(s,people,()=>.1).kind,'askSnack');s.energy=20;const t=initiativeFor(s,people,()=>.5);assert.equal(t.kind,'sleep');assert.equal(t.person.key,'companion:test');assert.equal(initiativeFor(s,[],()=>0),null);});
test('affection ends in physical departure; refused snacks keep the pending request intact',()=>{const c=createPetCare({satiety:95});c.state.task={kind:'invitePet',source:'self',target:'you',place:'person',phase:'doing',stage:'cuddle',time:1};const old=c.state.task;assert.equal(c.request('snack').accepted,false);assert.equal(c.state.task,old);c.request('pet',{nearPerson:true});c.arrive();run(c,5);assert.equal(c.state.relationships.you.pet,1);assert.equal(c.state.task.kind,'moveAway');assert.equal(c.state.task.phase,'walking');assert.ok(!c.state.recent.some(x=>x.text.includes('自己慢慢走开')));c.arrive();assert.equal(c.state.task,null);assert.ok(c.state.recent.some(x=>x.text.includes('自己慢慢走开')));});
test('foreground pause preserves requests, toy placements, cooldown and relationships exactly',()=>{const c=createPetCare({initiativeCooldown:0,satiety:30});run(c,12);c.arrive();const snapshot=c.snapshot();run(c,100,{home:true,people,paused:true});assert.deepEqual(c.snapshot(),snapshot);});

test('broken personal visits cannot fabricate missing caregivers; legacy sleep keeps a real resting place',()=>{const visit=createPetCare({task:{kind:'invitePlay',place:'toy',stage:'carry',phase:'walking'}});assert.equal(visit.state.task,null);const sleep=createPetCare({task:{kind:'sleep',place:'person',phase:'doing',time:44}});assert.equal(sleep.state.task.place,'bed');sleep.tick(1,{home:true});assert.equal(sleep.state.rests.bed,1);assert.equal(sleep.state.relationships[''],undefined);});
