import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createNeighborhood,NEIGHBORS,weekendGathering,gatheringSpot,neighborSchedule} from './neighborhood.mjs';
import {restorePetState,snapshotPetState,petEntry} from './state.mjs';
import {createPetCare} from './care.mjs';
import {createPetCareer} from './career.mjs';
import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
import {newTownLife,roomDoor,createTownNavigation} from './town-life.mjs';
import {recoverPetLife} from './routine.mjs';
import {restoreClock,realTime} from '../fairy-garden/real-clock.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
function fixture(raw=null){const s=restorePetState(raw||{configured:true,profile:{name:'团子'},room:null},world);s.pets.push(petEntry({configured:true,profile:{name:'栗子',species:'dog'}},'pet-two'));const rows=s.pets.map(entry=>({entry,care:createPetCare(entry.care),career:createPetCareer(entry.career)}));let time={at:Date.parse('2026-10-05T14:30:00'),date:'2026-10-05',weekday:1,minute:870},weather='晴日',fail=false,saved=null;const sync=()=>{rows.forEach(x=>{x.entry.care=x.care.snapshot();x.entry.career=x.career.snapshot();});s.care=rows[0].entry.care;s.career=rows[0].entry.career;};const n=createNeighborhood(s.neighborhood,{world,getRows:()=>rows,getTime:()=>time,getWeather:()=>weather,save:()=>{sync();if(fail)return false;saved=snapshotPetState(s,{position:s.position,room:null,outdoor:null,evening:false});return true;}});const place=(id,pet=0)=>{rows[pet].entry.town=newTownLife(n.state.neighbors[id].town.place,n.state.neighbors[id].town.position,17);};return {s,n,rows,place,run:seconds=>{for(let i=0;i<seconds*10;i++)n.tick(.1);},get saved(){return saved;},set time(x){time=x;},get time(){return time;},set fail(x){fail=x;},set weather(x){weather=x;}};}
test('only actual nearby daily greetings teach current names and completed preferences, separately for each pet',()=>{const f=fixture(),id=f.rows[0].entry.id;assert.equal(f.n.request('greet','baker',id).accepted,false);f.place('baker');f.rows[0].care.state.toys.mouse=3;assert.equal(f.n.request('greet','baker',id).accepted,true);assert.equal(f.n.summary(id).neighbors[0].familiarity,1);assert.match(f.n.summary(id).neighbors[0].memory.habit,/小老鼠/);f.n.request('greet','baker',id);assert.equal(f.n.state.neighbors.baker.met[id].greetings,1);assert.equal(f.n.summary('pet-two').neighbors[0].familiarity,0);f.rows[0].entry.profile.name='新小名';f.time={...f.time,date:'2026-10-06',at:f.time.at+86400000};assert.match(f.n.request('greet','baker',id).text,/新小名/);assert.equal(f.n.state.neighbors.baker.met[id].greetings,2);});
test('physical pickup, nearby three-second handoff and the original world writer complete once without money or inventory changes',()=>{const f=fixture(),id=f.rows[0].entry.id,before=f.rows[0].career.snapshot();f.place('baker');f.n.request('greet','baker',id);assert.ok(f.n.request('accept','baker',id).accepted);assert.equal(f.n.request('deliver','florist',id).accepted,false);f.run(6);assert.ok(f.n.state.quest);f.place('florist');assert.ok(f.n.request('deliver','florist',id).accepted);f.run(3.2);assert.equal(f.n.state.quest,null);assert.equal(f.n.summary(id).neighbors[0].familiarity,3);assert.deepEqual(f.rows[0].career.snapshot(),before);assert.equal(f.n.request('deliver','florist',id).accepted,false);assert.equal(f.n.request('accept','baker',id).accepted,false);const restored=restorePetState(snapshotPetState(f.s,{position:f.s.position,room:null,outdoor:null,evening:false}),world);assert.deepEqual(restored.neighborhood,f.n.snapshot());assert.equal(f.saved.neighborhood.neighbors.baker.met[id].favors,1);});
test('carried requests survive refresh, remain with their actual pet, and can be actually returned without a favor',()=>{const f=fixture(),id=f.rows[0].entry.id;f.place('florist');f.n.request('accept','florist',id);const again=fixture(f.saved);assert.equal(again.n.state.quest.petId,id);assert.equal(again.n.request('deliver','regular','pet-two').accepted,false);assert.ok(again.n.request('return','florist',id).accepted);assert.equal(again.n.request('deliver','florist',id).accepted,true);assert.equal(again.n.state.quest,null);assert.equal(again.n.summary(id).neighbors[1].familiarity,0);});
test('failed real writer rolls back pickups, friendship, invitations and final completion, then supports one retry',()=>{const f=fixture(),id=f.rows[0].entry.id;f.place('baker');f.fail=true;let before=f.n.snapshot();assert.equal(f.n.request('greet','baker',id).accepted,false);assert.deepEqual(f.n.snapshot(),before);assert.equal(f.n.request('accept','baker',id).accepted,false);assert.deepEqual(f.n.snapshot(),before);f.fail=false;f.n.request('greet','baker',id);f.n.request('accept','baker',id);f.place('florist');f.n.request('deliver','florist',id);f.run(2.9);before=f.n.snapshot();f.fail=true;f.run(.3);assert.ok(f.n.state.quest);assert.equal(f.n.state.neighbors.baker.met[id].favors,0);f.fail=false;f.run(.3);assert.equal(f.n.state.neighbors.baker.met[id].favors,1);before=f.n.snapshot();f.fail=true;assert.equal(f.n.request('invite','baker',id).accepted,false);assert.deepEqual(f.n.snapshot(),before);});
test('visitors walk the real street and doorway, persist en route, and leave by the same door',()=>{const f=fixture(),id=f.rows[0].entry.id;f.place('baker');f.n.request('greet','baker',id);f.n.request('accept','baker',id);f.place('florist');f.n.request('deliver','florist',id);f.run(3.2);const petBefore=structuredClone(f.rows[0].entry.town);assert.ok(f.n.request('invite','baker',id).accepted);assert.equal(f.n.state.neighbors.baker.town.place,'outside');assert.equal(f.n.request('invite','florist',id).accepted,false);let reached=false;for(let i=0;i<1200;i++){const before=structuredClone(f.n.state.neighbors.baker.town);f.n.tick(.1);const t=f.n.state.neighbors.baker.town;if(t.place!==before.place){assert.ok(world.canEnter(before.position,'home'));assert.deepEqual(t.position,roomDoor('home'));reached=true;break;}assert.ok(Math.hypot(t.position.x-before.position.x,t.position.z-before.position.z)<=.098001);assert.ok(world.walkable(t.position.x,t.position.z));}assert.ok(reached);assert.deepEqual(f.rows[0].entry.town,petBefore);assert.ok(f.n.request('end-visit','baker',id).accepted);f.run(100);assert.equal(f.n.state.visit,null);assert.equal(f.n.state.neighbors.baker.town.place,'outside');assert.ok(Math.hypot(f.n.state.neighbors.baker.town.position.x+14,f.n.state.neighbors.baker.town.position.z+.5)<2.2);});
test('real weekends and weather choose one actual venue; foreground attendance completes once and refresh preserves date guard',()=>{const f=fixture(),id=f.rows[0].entry.id;assert.equal(weekendGathering(f.time).available,false);f.time={...f.time,date:'2026-10-10',weekday:6,minute:660};assert.ok(f.n.request('join','',id).accepted);f.run(25);assert.equal(f.n.state.event.done,false);f.run(25);f.place('regular');f.run(20.1);assert.equal(f.n.state.event.done,true);f.n.request('leave-event','',id);assert.equal(f.n.request('join','',id).accepted,false);const again=fixture(f.saved);again.time=f.time;assert.equal(again.n.request('join','',id).accepted,false);assert.equal(weekendGathering({...f.time,weekday:0,minute:910},'细雨').place,'cafe');assert.ok(createTownNavigation('cafe',1.4).walkable(-1.75,2.2));});
test('weather changing en route relocates actual gathering, while expired dates never award attendance',()=>{const f=fixture(),id=f.rows[0].entry.id;f.time={...f.time,date:'2026-10-10',weekday:6,minute:660};f.n.request('join','',id);f.weather='细雨';f.run(.1);assert.equal(f.n.state.event.place,'cafe');assert.equal(f.n.state.event.time,0);f.time={...f.time,minute:721};f.run(.1);assert.equal(f.n.state.event,null);assert.equal(f.n.state.neighbors.regular.met[id].events,0);});
test('busy and sleepy pets refuse entrusted goods and attendance; all NPC standing positions use original walkable ground',()=>{const f=fixture(),id=f.rows[0].entry.id;for(const n of NEIGHBORS)assert.ok((n.pet?createTownNavigation(n.place,n.profile.size):world).walkable(n.spot.x,n.spot.z),n.id);f.place('baker');f.rows[0].care.request('rest');assert.equal(f.n.request('accept','baker',id).accepted,false);f.time={...f.time,weekday:0,minute:910};assert.equal(f.n.request('join','',id).accepted,false);});
test('offline recovery preserves unfinished neighborhood facts without simulating friendship, guest visits or event completion',()=>{const f=fixture(),at=Date.parse('2026-10-10T11:00:00'),id=f.rows[0].entry.id;f.time={at,date:'2026-10-10',weekday:6,minute:660};f.n.request('join','',id);f.s.clock=restoreClock(null,1,at);f.rows.forEach(p=>{p.entry.life.at=at;p.entry.town=newTownLife('home',{x:0,z:.55},31);});f.s.resident.life.at=at;const before=f.n.snapshot();recoverPetLife(f.s,world,at+3600000);assert.deepEqual(f.n.snapshot(),before);assert.equal(f.n.state.neighbors.regular.met[id].events,0);assert.equal(realTime(f.s.clock,at+3600000).minute,720);});
test('clock rewind cannot replay greetings or reset a real-date attendance guard',()=>{const f=fixture(),id=f.rows[0].entry.id;f.place('baker');f.n.request('greet','baker',id);f.time={...f.time,date:'2026-10-04'};f.n.request('greet','baker',id);f.time={...f.time,date:'2026-10-05'};f.n.request('greet','baker',id);assert.equal(f.n.state.neighbors.baker.met[id].greetings,1);});
test('moving away interrupts the actual handoff and does not record a completed favor',()=>{const f=fixture(),id=f.rows[0].entry.id;f.place('baker');f.n.request('accept','baker',id);f.place('florist');f.n.request('deliver','florist',id);f.run(1);f.place('baker');f.run(.1);assert.equal(f.n.state.quest.phase,'carrying');assert.equal(f.n.state.quest.time,0);assert.equal(f.n.state.neighbors.baker.met[id]?.favors||0,0);});
test('park and rainy cafe gatherings give the host, pet and TA separate walkable spots using the original navigator',()=>{for(const weekday of[6,0])for(const weather of['晴日','细雨']){const e=weekendGathering({date:'2026-10-10',weekday,minute:weekday===6?660:910},weather),p=gatheringSpot(e,'pet',world),ta=gatheringSpot(e,'companion',world),nav=e.place==='outside'?world:createTownNavigation('cafe',1.4);assert.ok(nav.walkable(p.x,p.z)&&nav.walkable(ta.x,ta.z));assert.ok(Math.hypot(p.x-ta.x,p.z-ta.z)>1.8);assert.ok(Math.hypot(p.x-e.point.x,p.z-e.point.z)>.8);assert.ok(Math.hypot(ta.x-e.point.x,ta.z-e.point.z)>.8);}});

test('each local real-day phase and weather chooses a reachable original room or park, with separate daily rhythms',()=>{
 for(const n of NEIGHBORS)for(const minute of [0,360,480,540,600,720,780,840,1080,1140,1260,1320])for(const weather of ['晴日','细雨','细雪']){
  const plan=neighborSchedule(n.id,{minute},weather),nav=plan.place==='outside'?world:createTownNavigation(plan.place,1.4);
  assert.ok(nav.walkable(plan.point.x,plan.point.z),n.id+':'+minute+':'+weather);
  if(plan.place!=='outside')assert.ok(nav.path(roomDoor(plan.place),plan.point));
  if(/雨|雪/.test(weather))assert.notEqual(plan.place,'outside');
 }
 assert.equal(neighborSchedule('baker',{minute:420}).awake,true);assert.equal(neighborSchedule('florist',{minute:420}).awake,false);
 assert.equal(neighborSchedule('regular',{minute:540}).gesture,'read');assert.equal(neighborSchedule('regular',{minute:900}).place,'outside');
});
test('rain sends street neighbors along the real street and doorway, then sunshine brings them back without moving pets or granting friendship',()=>{
 const f=fixture(),petBefore=structuredClone(f.rows.map(p=>p.entry.town));f.weather='细雨';let arrived=false;
 for(let i=0;i<1000;i++){const before=structuredClone(f.n.state.neighbors.baker.town);f.n.tick(.1);const t=f.n.state.neighbors.baker.town;
  if(t.place!==before.place){assert.ok(world.canEnter(before.position,'bakery'));assert.deepEqual(t.position,roomDoor('bakery'));arrived=true;}
  else assert.ok(Math.hypot(t.position.x-before.position.x,t.position.z-before.position.z)<=.098001);
 }
 assert.ok(arrived);assert.equal(f.n.state.neighbors.baker.town.place,'bakery');assert.match(f.n.summary(f.rows[0].entry.id).neighbors[0].place,/面包.*避雨雪/);
 assert.deepEqual(f.rows.map(p=>p.entry.town),petBefore);assert.deepEqual(f.n.state.neighbors.baker.met,{});
 f.weather='晴日';f.run(100);assert.equal(f.n.state.neighbors.baker.town.place,'outside');assert.ok(Math.hypot(f.n.state.neighbors.baker.town.position.x+14,f.n.state.neighbors.baker.town.position.z+.5)<2.2);
});
test('looking for a walking neighbor pauses their actual route briefly, survives refresh with the same pet, and then resumes without social credit',()=>{
 const f=fixture(),id=f.rows[0].entry.id;f.run(2);const before=structuredClone(f.n.state.neighbors.regular.town);assert.ok(before.goal);
 assert.ok(f.n.request('find','regular',id).accepted);f.run(30);assert.deepEqual(f.n.state.neighbors.regular.town.position,before.position);assert.equal(f.n.state.meeting.petId,id);assert.equal(f.n.reserves(id),true);assert.equal(f.n.reserves('pet-two'),false);
 const restored=restorePetState(snapshotPetState(f.s,{position:f.s.position,room:null,outdoor:null,evening:false}),world);assert.deepEqual(restored.neighborhood.meeting,f.n.state.meeting);
 f.run(91);assert.equal(f.n.state.meeting,null);assert.notDeepEqual(f.n.state.neighbors.regular.town.position,before.position);assert.deepEqual(f.n.state.neighbors.regular.met,{});
});
test('greeting faces the real pet and waves in place; repeats animate but do not add experience, and rejected writers preserve the original posture',()=>{
 const f=fixture(),id=f.rows[0].entry.id;f.place('baker');f.rows[0].entry.town.position.x+=1;assert.ok(f.n.request('greet','baker',id).accepted);
 assert.equal(f.n.appearance('baker').gesture,'wave');assert.equal(f.n.state.neighbors.baker.town.heading,Math.PI/2);const pos=structuredClone(f.n.state.neighbors.baker.town.position);f.run(2);assert.deepEqual(f.n.state.neighbors.baker.town.position,pos);f.run(1.2);assert.equal(f.n.state.meeting,null);
 assert.ok(f.n.request('greet','baker',id).accepted);assert.equal(f.n.state.neighbors.baker.met[id].greetings,1);const before=f.n.snapshot();f.fail=true;assert.equal(f.n.request('find','regular',id).accepted,false);assert.deepEqual(f.n.snapshot(),before);
});
test('closing hours defer new visits and greetings, while goods already entrusted can still be delivered without stranding their pet',()=>{
 const f=fixture(),id=f.rows[0].entry.id;f.place('baker');f.n.request('accept','baker',id);f.time={...f.time,minute:1380};f.place('florist');assert.ok(f.n.request('deliver','florist',id).accepted);f.run(3.1);assert.equal(f.n.state.quest,null);
 for(const action of ['greet','accept','invite','find']){const before=f.n.snapshot();assert.match(f.n.request(action,'baker',id).text,/收工休息/);assert.deepEqual(f.n.snapshot(),before);}
 f.run(100);assert.equal(f.n.state.neighbors.baker.town.place,'bakery');assert.equal(f.n.summary(id).neighbors[0].awake,false);
});
test('failed routine destination saves roll back route changes; offline recovery drops a pending meeting without walking or adding greetings',()=>{
 const f=fixture(),id=f.rows[0].entry.id;f.fail=true;f.weather='细雨';const before=f.n.snapshot();f.n.tick(.1);assert.deepEqual(f.n.snapshot(),before);f.fail=false;f.n.tick(.1);assert.ok(f.n.state.neighbors.baker.town.goal);
 f.n.request('find','baker',id);const at=Date.parse('2026-10-05T14:30:00');f.s.clock=restoreClock(null,1,at);f.rows.forEach(p=>{p.entry.life.at=at;if(!p.entry.town)p.entry.town=newTownLife('home',{x:0,z:.55},31);});f.s.resident.life.at=at;const positions=NEIGHBORS.map(n=>structuredClone(f.n.state.neighbors[n.id].town));recoverPetLife(f.s,world,at+3600000);assert.equal(f.s.neighborhood.meeting,null);assert.deepEqual(NEIGHBORS.map(n=>f.n.state.neighbors[n.id].town),positions);assert.deepEqual(f.n.state.neighbors.baker.met,{});
});

test('a second pet can meet a gathering host while the first retains its undelivered parcel, without pinning the host on the wrong street',()=>{
 const f=fixture(),id=f.rows[0].entry.id;f.time={...f.time,date:'2026-10-10',weekday:6,minute:660};f.place('florist');f.n.request('accept','florist',id);assert.ok(f.n.request('join','','pet-two').accepted);f.run(60);assert.equal(f.n.state.quest.petId,id);assert.equal(f.n.state.event.done,false);assert.ok(Math.hypot(f.n.state.neighbors.regular.town.position.x-7,f.n.state.neighbors.regular.town.position.z-19)<.15);
});

test('awake neighbors stroll around their scheduled place, while finding them freezes the actual position',()=>{const f=fixture(),id=f.rows[0].entry.id;f.run(120);const t=f.n.state.neighbors.baker.town,p={...t.position};f.run(25);assert.ok(Math.hypot(t.position.x-p.x,t.position.z-p.z)>.1);assert.equal(t.place,'outside');assert.ok(Math.hypot(t.position.x+14,t.position.z+.5)<2.2);assert.equal(f.n.request('find','baker',id).accepted,true);const held={...t.position};f.run(10);assert.deepEqual(t.position,held);});
