import {PET_HOME_GOODS} from './furnishings.mjs?v=fg-8e92d657ad09bbcc';
import {PET_WORKPLACES,petWorkplace} from './workplaces.mjs?v=fg-8e92d657ad09bbcc';
import {shoppingItem} from './shopping.mjs?v=fg-8e92d657ad09bbcc';
import {homePoint} from './initiative.mjs?v=fg-8e92d657ad09bbcc';
export const parcelSourceTitle=source=>source==='shopping'?'便利店':petWorkplace(source).title;
export const PARCEL_ITEMS={...Object.fromEntries(PET_HOME_GOODS.map(x=>[x.id,{name:x.name,unit:x.kind==='wear'?'件':'个',kind:x.icon,unique:true}])),bookmark:{name:'小爪书签',unit:'张',kind:'book',collectible:true},scentCard:{name:'香气小卡',unit:'张',kind:'leaf',collectible:true},oddButton:{name:'不配套的大纽扣',unit:'颗',kind:'paw',collectible:true},leafBoat:{name:'歪歪的叶子小船',unit:'只',kind:'leaf',collectible:true},deliveryReceipt:{name:'配送小回执',unit:'张',kind:'book',collectible:true},caseCard:{name:'案件纪念卡',unit:'张',kind:'search',collectible:true},coaster:{name:'小爪印杯垫',unit:'张',kind:'cup',collectible:true},guestCard:{name:'客人留言卡',unit:'张',kind:'book',collectible:true},receipt:{name:'奇怪小票',unit:'张',kind:'book',collectible:true},sticker:{name:'小贴纸',unit:'张',kind:'paw',collectible:true},bread:{name:'小面包',unit:'个',kind:'bread'},flower:{name:'小花',unit:'枝',kind:'leaf'},petals:{name:'花瓣',unit:'片',kind:'leaf'},snack:{name:'小零食',unit:'份',kind:'bread'},toy:{name:'歪眼小怪球',unit:'个',kind:'ball'},box:{name:'小纸箱窝',unit:'个',kind:'home'}};
const text=v=>typeof v==='string'?v.slice(0,100):'';
const number=(v,max=10000)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
export function parcelItems(raw){return Object.fromEntries(Object.keys(PARCEL_ITEMS).filter(k=>number(raw?.[k])>0).map(k=>[k,number(raw[k],(['toy','box'].includes(k)||PARCEL_ITEMS[k].unique)?1:10000)]));}
export function restoreParcel(raw){const items=parcelItems(raw?.items);if(!text(raw?.id)||!Object.keys(items).length||!(raw.source==='shopping'||PET_WORKPLACES.some(p=>p.id===raw.source)))return null;return {id:text(raw.id),source:raw.source,day:Math.max(1,number(raw.day,1e7)),phase:raw.phase==='placed'&&homePoint(raw.position)?'placed':'carrying',position:homePoint(raw.position),items};}
export const keepOpened=bags=>bags.filter((b,i)=>i>=bags.length-8||!b.served&&!b.reactionDone);
export function restoreParcels(raw){const seen=new Set();return {queue:(Array.isArray(raw?.queue)?raw.queue:[]).map(restoreParcel).filter(x=>x&&!seen.has(x.id)&&seen.add(x.id)),opened:keepOpened((Array.isArray(raw?.opened)?raw.opened:[]).map(x=>{const p=restoreParcel(x);return p?{...p,...(Number.isFinite(x.openedAt)?{openedAt:x.openedAt}:{}),reaction:['eager','curious','leave'].includes(x.reaction)?x.reaction:'curious',reactionText:typeof x.reactionText==='string'?x.reactionText.slice(0,200):'',served:!!x.served,reactionDone:!!x.reactionDone}:null;}).filter(Boolean))};}
export function addParcel(state,bag){const p=restoreParcel(bag);if(!p||state.parcels.queue.some(x=>x.id===p.id)||state.parcels.opened.some(x=>x.id===p.id))return false;state.parcels.queue.push(p);return true;}
export function migrateShoppingParcel(state){const t=state.shopping.trip,item=shoppingItem(t?.item);if(t?.phase==='packed'&&item)addParcel(state,{id:t.id,day:t.day,source:'shopping',items:{[item.id]:item.count}});}
export function parcelReaction(items,care){const food=(items.bread||items.snack)&&care.satiety<78,toy=items.toy&&care.traits.active>.55,box=items.box&&care.energy<60;const eager=food||toy||box;const leave=!eager&&care.traits.bold<.35;return {reaction:eager?'eager':leave?'leave':'curious',reactionText:eager?'它对这份东西很有兴趣，准备贴近袋口认真闻闻。':leave?'它今天对这份东西兴趣不大，准备闻一闻就去别处待着。':'它想看看刚拆出的东西，准备凑近闻一闻。'};}
export function parcelFacts(state){return {waiting:state.parcels.queue.map(p=>({id:p.id,source:p.source,sourceTitle:parcelSourceTitle(p.source),day:p.day,phase:p.phase,position:p.position})),opened:state.parcels.opened.map(p=>({...structuredClone(p),contents:parcelContents(p)}))};}

export const parcelContents=bag=>Object.entries(bag.items).map(([id,count])=>({id,count,...PARCEL_ITEMS[id]}));
