import test from 'node:test';
import assert from 'node:assert/strict';
import {createPetCare} from './care.mjs';
import {createPetCareer} from './career.mjs';
import {createTownNavigation,newTownLife} from './town-life.mjs';
import {createPetFriends,neighborBondView} from './pet-friends.mjs';
import {restoreNeighborhood,createNeighborhood} from './neighborhood.mjs';
import {readFileSync} from 'node:fs';
import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
function setup(raw,careerRaw){let time=1791230400000,ok=true;const rows=['a','b'].map((id,i)=>{const care=createPetCare({satiety:90,energy:100,mood:90}),career=createPetCareer(careerRaw),town=newTownLife('florist',{x:-2,z:2.5},7+i);return {entry:{id,profile:{name:id},town},care,career,pet:{root:{scale:{x:i?1:1.3}},motion:{setActionPose(){}}},town:{nav:()=>createTownNavigation('florist',i?1:1.3),hold:()=>{town.hold=60;},sync:(place,p,heading)=>Object.assign(town,{place,position:{...p},heading,phase:'idle',goal:null,hold:60})}};});const shared=restoreNeighborhood(raw?.neighbors?raw:raw?{petMeetingSeq:raw.seq,petMeeting:raw.pending,friendBall:raw.ball}:null,rows.map(x=>x.entry.id),rows),engine=createPetFriends(shared,{rows:()=>rows,now:()=>time,save:()=>ok}),state=engine.state;return {rows,state,shared,engine,setSave:v=>{ok=v;},advanceTime:n=>{time+=n;}};}
function complete(q,limit=2400){let result;for(let i=0;i<limit&&q.state.pending;i++){result=q.engine.tick(.05);const p=q.rows[0].entry.town.position;assert.ok(q.rows[0].town.nav().walkable(p.x,p.z));}assert.equal(q.state.pending,null,JSON.stringify(q.state.pending));return result;}
function returnFriend(q){for(let i=0;i<700;i++)q.engine.tick(.05);}
test('real approach finishes before a greeting is recorded; each pet has its own bond and current need gates',()=>{const q=setup();assert.equal(q.engine.request('play','a').accepted,false);assert.equal(q.engine.request('greet','a').accepted,true);assert.equal(neighborBondView({'florist-cat':q.shared.neighbors['florist-cat'].met.a},'florist-cat').known,false);q.engine.tick(.05,{paused:true});assert.equal(q.state.pending.time,0);complete(q);assert.equal(q.shared.neighbors['florist-cat'].met.a.greetings,1);assert.equal(q.shared.neighbors['florist-cat'].met.b,undefined);assert.equal(q.rows[0].career.state.florist.friend,null);assert.equal(q.engine.request('greet','a').accepted,false);q.advanceTime(21*60000);q.rows[0].care.state.energy=20;assert.equal(q.engine.request('greet','a').accepted,false);q.rows[0].care.state.energy=100;assert.equal(q.engine.request('greet','a').accepted,true);complete(q);assert.equal(q.shared.neighbors['florist-cat'].met.a.greetings,2);assert.equal(q.rows[0].career.state.balance,0);});
test('familiar pets and the real neighbor both reach the rolling ball before play counts',()=>{const q=setup(null,{florist:{friend:{day:3,visits:2}}});assert.equal(q.engine.request('play','a').accepted,true);const initial=structuredClone(q.state.resident.position);let moved=false,second=false;for(let i=0;i<2400&&q.state.pending;i++){q.engine.tick(.05);moved||=Math.hypot(q.state.resident.position.x-initial.x,q.state.resident.position.z-initial.z)>.4;second||=q.state.pending?.round===1;}assert.equal(q.state.pending,null);assert.ok(moved&&second);const r=q.shared.neighbors['florist-cat'].met.a;assert.equal(r.work,2);assert.equal(r.play,1);assert.equal(q.shared.neighbors['florist-cat'].met.b.play,0);returnFriend(q);assert.ok(Math.hypot(q.state.resident.position.x,q.state.resident.position.z-.65)<1.8);});
test('actual snapshot resumes an unfinished approach and cancellation or offline never credits it',()=>{let q=setup();q.engine.request('greet','a');for(let i=0;i<35;i++)q.engine.tick(.05);const saved=q.engine.snapshot(),position=structuredClone(q.rows[0].entry.town);q=setup(saved);Object.assign(q.rows[0].entry.town,position);complete(q);assert.equal(q.shared.neighbors['florist-cat'].met.a.greetings,1);q.advanceTime(21*60000);q.engine.request('greet','a');q.engine.tick(.05,{offline:true});assert.equal(q.state.pending,null);assert.equal(q.shared.neighbors['florist-cat'].met.a.greetings,1);q.engine.request('greet','a');q.engine.cancel('a');assert.equal(q.shared.neighbors['florist-cat'].met.a.greetings,1);});
test('archive write failures roll back starts and completed relationship records, then retry exactly once',()=>{const q=setup();q.setSave(false);assert.equal(q.engine.request('greet','a').accepted,false);assert.equal(q.state.pending,null);q.setSave(true);q.engine.request('greet','a');for(let i=0;i<2400&&(q.state.pending.phase!=='doing'||q.state.pending.time<3.95);i++)q.engine.tick(.05);q.setSave(false);const r=q.engine.tick(.05);assert.equal(r.accepted,false);assert.equal(q.shared.neighbors['florist-cat'].met.a,undefined);assert.ok(q.state.pending);q.setSave(true);complete(q);assert.equal(q.shared.neighbors['florist-cat'].met.a.greetings,1);assert.equal(q.rows[0].care.state.recent.filter(x=>x.type==='neighbor').length,1);});
test('legacy work greeting writer upgrades once without inventing play, while unknown identities stay out',()=>{const first=setup(null,{florist:{friend:{day:9,visits:3}}}),m=first.shared.neighbors['florist-cat'].met.a;assert.equal(m.work,3);assert.equal(m.play,0);assert.deepEqual(restoreNeighborhood(first.engine.snapshot(),['a','b']).neighbors['florist-cat'].met.a,m);const q=setup({pending:{petId:'missing',neighborId:'florist-cat',kind:'greet',goal:{x:0,z:0},phase:'doing',time:99}});assert.equal(q.state.pending,null);assert.equal(q.engine.request('greet','missing').accepted,false);assert.equal(q.engine.facts('b').friends[0].known,false);});

test('corrupt completed phases cannot credit a greeting from across the room or a chase before arrival',()=>{const q=setup({seq:5,pending:{id:5,petId:'a',neighborId:'florist-cat',kind:'greet',phase:'doing',goal:{x:1,z:.7},time:8,startedAt:1791230400000}});q.engine.tick(.05);assert.equal(q.state.pending,null);assert.equal(q.shared.neighbors['florist-cat'].met.a,undefined);const r=setup({seq:6,pending:{id:6,petId:'a',neighborId:'florist-cat',kind:'play',phase:'doing',round:1,goal:{x:1,z:.7},time:8,startedAt:1791230400000}});r.engine.tick(.05);assert.ok(r.state.pending);assert.equal(r.shared.neighbors['florist-cat'].met.a,undefined);assert.equal(restoreNeighborhood({pending:{id:0,petId:'a',neighborId:'florist-cat',kind:'greet',phase:'walking',goal:{x:1,z:.7}}},['a']).petMeeting,null);});

test('a failed pet encounter rebinds the existing human routes, so the next visitor still walks into the home',()=>{const q=setup(),world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url)))),engine=createNeighborhood(q.shared,{world,getRows:()=>q.rows,getTime:()=>({at:1791230400000,date:'2026-10-05',weekday:1,minute:870}),save:(()=>{let first=true;return()=>{if(first){first=false;return false;}return true;};})()});assert.equal(engine.request('pet-greet','florist-cat','a').accepted,false);assert.equal(q.shared.petMeeting,null);const n=engine;q.shared.neighbors.baker.met.a={greetings:3,favors:0,visits:0,events:0};assert.ok(n.request('invite','baker','a').accepted);for(let i=0;i<1800&&q.shared.visit.phase==='going';i++)n.tick(.1);assert.equal(q.shared.neighbors.baker.town.place,'home');assert.equal(q.shared.visit.phase,'staying');});

test('idle pet neighbors stroll on the existing shop floor, then return by foot for an invitation without free friendship',()=>{const f=setup(),start={...f.engine.state.resident.position};for(let i=0;i<600;i++)f.engine.tick(.05);const t=f.engine.state.resident;assert.ok(Math.hypot(t.position.x-start.x,t.position.z-start.z)>.1);assert.ok(createTownNavigation('florist',.9).walkable(t.position.x,t.position.z));assert.equal(t.place,'florist');assert.equal(f.rows[0].care.state.recent.length,0);assert.equal(f.engine.request('greet','a').accepted,true);for(let i=0;i<2000&&f.engine.state.pending;i++)f.engine.tick(.05);assert.equal(f.engine.state.pending,null);assert.ok(Math.hypot(t.position.x-start.x,t.position.z-start.z)<.05);});
