import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {RESIDENT_ACTS,deriveResidentPreferences,syncResidentPreferences,activityWeights,chooseResidentAct,destinationWeights,chooseResidentDestination,rememberResidentAct,planResidentAct} from './resident-choice.mjs';
import {restoreResident,nextRandom,localRoute} from './autonomy.mjs';import {createHomeNavigation} from './home-navigation.mjs';
import {restorePetState,snapshotPetState} from './state.mjs';import {restoreClock} from '../fairy-garden/real-clock.mjs';import {recoverPetLife} from './routine.mjs';import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
const world=createPetWorld(JSON.parse(readFileSync('art/pet-career/outside.json'))),person=persona=>({id:'ta',persona});
const actor=persona=>{const r=restoreResident({id:'ta'});syncResidentPreferences(r,person(persona));return r;};
test('full persona biases independent interests, treats explicit dislikes separately and leaves absent interests neutral',()=>{const a=deriveResidentPreferences(person('内向，热爱阅读。喜欢喝茶，不喜欢咖啡。讨厌喧闹，喜欢植物。'));assert.ok(a.scores.reading>0);assert.ok(a.scores.quiet>0);assert.ok(a.scores.tea>0);assert.ok(a.scores.coffee<0);assert.ok(a.scores.plants>0);assert.equal(a.scores.animals,0);assert.ok(Object.values(deriveResidentPreferences(person('')).scores).every(x=>x===0));const p=deriveResidentPreferences(person('曾去过咖啡店，种族是猫妖。'));assert.equal(p.scores.coffee,0);assert.equal(p.scores.animals,0);});
test('negation survives a list, changes after contrast and handles English word boundaries',()=>{const a=deriveResidentPreferences(person('不喜欢读书、喝茶，但喜欢咖啡。喜欢植物，不喜欢运动。'));assert.ok(a.scores.reading<0);assert.ok(a.scores.tea<0);assert.ok(a.scores.coffee>0);assert.ok(a.scores.active<0);const b=deriveResidentPreferences(person('Enjoys reading and tea. Dislikes coffee. Works in education.'));assert.ok(b.scores.reading>0);assert.ok(b.scores.tea>0);assert.ok(b.scores.coffee<0);assert.equal(b.scores.animals,0);});
test('preferences produce different local choices without freezing either resident into one action',()=>{const reader=actor('非常喜欢阅读，热爱读书。喜欢喝茶，性格安静。'),active=actor('非常喜欢运动，热爱散步。性格活泼好奇。不喜欢阅读。');const count=r=>{const counts={};for(let i=0;i<1000;i++){const id=chooseResidentAct(r,{},()=>nextRandom(r));counts[id]=(counts[id]||0)+1;}return counts;};const a=count(reader),b=count(active);assert.ok(a.read>b.read*3);assert.ok(b.stretch>a.stretch*2);assert.ok(Object.keys(a).length>=5);assert.ok(Object.keys(b).length>=5);});
test('recent completed actions vary choices, while walking does not count as completed experience',()=>{const r=actor('喜欢读书。'),before=activityWeights(r).find(x=>x.id==='read').weight;assert.equal(r.choices.recent.length,0);rememberResidentAct(r,'read',10);assert.ok(activityWeights(r).find(x=>x.id==='read').weight<before);assert.equal(r.choices.recent.length,1);assert.equal(rememberResidentAct(r,'teleport',12),false);assert.equal(activityWeights(r,{pets:false}).some(x=>x.id==='pets'),false);});
test('weather and interests change destinations while pets retain their original default town rules',()=>{const r=actor('很喜欢植物，热爱养花。'),weights=destinationWeights(r),f=weights.find(x=>x.id==='florist').weight;assert.ok(f>weights.find(x=>x.id==='store').weight*3);assert.ok(destinationWeights(r,{kind:'细雨'}).find(x=>x.id==='outside').weight<weights.find(x=>x.id==='outside').weight);for(let i=0;i<50;i++)assert.ok(['home','outside','cafe','store','alley','bakery','florist'].includes(chooseResidentDestination(r,{},()=>nextRandom(r))));});
test('every local activity uses reachable real furniture positions and cannot select an occupied goal',()=>{const nav=createHomeNavigation(1.4),r=actor('喜欢喝茶、阅读、植物和运动。');for(let i=0;i<80;i++){const position={x:-.28,z:.55},p=planResidentAct(r,{nav,position,clear:q=>q.x<.5,randomRoute:random=>localRoute(nav,position,random,{radius:2.5,clear:q=>q.x<.5})},()=>nextRandom(r));assert.ok(p);assert.ok(RESIDENT_ACTS[p.activity.kind]);assert.ok(p.activity.goal.x<.5);for(const q of p.route)assert.ok(nav.walkable(q.x,q.z));}assert.equal(planResidentAct(r,{nav:{walkable:()=>false},position:{x:0,z:0}},()=>.2),null);});
test('actual world writer restores preferences, completed history and unfinished acts without keeping persona text',()=>{const s=restorePetState(null,world);s.resident=actor('喜欢阅读，秘密人设内容。');rememberResidentAct(s.resident,'tea',12);s.resident.activity={kind:'plants',phase:'walking',goal:{x:-1.65,z:-.25},time:0,duration:10};const saved=snapshotPetState(s,{position:s.position,room:null,outdoor:null,evening:false}),copy=restorePetState(saved,world);assert.deepEqual(copy.resident,s.resident);assert.doesNotMatch(JSON.stringify(saved.resident),/秘密人设内容/);const previous=copy.resident.choices.recent;syncResidentPreferences(copy.resident,person('不喜欢阅读，喜欢喝茶。'));assert.ok(copy.resident.choices.preferences.scores.reading<0);assert.deepEqual(copy.resident.choices.recent,previous);});
test('offline free time uses the same planner locally, consumes no purchases and cannot repeat recovery',()=>{const from=new Date(2026,9,5,14).getTime(),at=from+3600000,s=restorePetState({configured:true,clock:restoreClock(null,1,from),profile:{name:'团子'},town:{place:'home',position:{x:-.28,z:.55}},care:{satiety:90,bowl:100,energy:90},career:{balance:35},resident:{...actor('喜欢读书，喜欢喝茶。'),town:{place:'home',phase:'idle',position:{x:-1.15,z:1.35}},life:{at:from,marks:{},notes:[]}}},world);s.pets[0].life.at=from;recoverPetLife(s,world,at);assert.ok(s.resident.choices.recent.length>0);assert.equal(s.pets[0].career.balance,35);assert.equal(s.pets[0].career.shopping.log.length,0);const before=structuredClone(s);recoverPetLife(s,world,at);assert.deepEqual(s,before);});
test('a different role cannot overwrite preferences or completed history for the resident',()=>{const r=actor('喜欢读书。');rememberResidentAct(r,'read',12);const before=structuredClone(r);syncResidentPreferences(r,{id:'other',persona:'讨厌读书。'});assert.deepEqual(r,before);assert.equal(rememberResidentAct(r,'toString',13),false);assert.ok(deriveResidentPreferences(person('Hobbies: reading and tea.')).scores.reading>0);});
test('a resident can choose to stay home, while a pet with no preference callback still leaves normally',async()=>{const {createTownLife,newTownLife}=await import('./town-life.mjs'),s=newTownLife('home',{x:0,z:.55},11),life=createTownLife(s,{world});s.idle=600;const before=structuredClone(s.position);life.tick(.05,{position:s.position,chooseDestination:()=> 'home'});assert.equal(s.phase,'idle');assert.deepEqual(s.position,before);s.idle=600;life.tick(.05,{position:s.position});assert.equal(s.phase,'exit');});
test('offline pastimes cannot interrupt a real care request or night sleep and keep the three-day bound',()=>{const at=new Date(2026,9,6,0).getTime(),from=at-8*86400000,s=restorePetState({configured:true,clock:restoreClock(null,1,from),profile:{name:'团子'},town:{place:'home',position:{x:1,z:1}},care:{satiety:95,bowl:100,energy:95,helper:{id:'ta',name:'TA',action:'pet',phase:'walking',petId:'pet-1'}},resident:{...actor('喜欢读书。'),town:{place:'home',phase:'idle',position:{x:-1.15,z:1.35}},life:{at:from,notes:[],marks:{}}}},world);s.pets[0].life.at=from;recoverPetLife(s,world,at);assert.equal(s.resident.choices.recent.length,0);assert.ok(s.pets[0].care.helper);const q=restorePetState({configured:true,clock:restoreClock(null,1,from),profile:{name:'团子'},town:{place:'home',position:{x:1,z:1}},care:{satiety:95,bowl:100,energy:95},resident:{...actor('喜欢读书。'),town:{place:'home',phase:'idle',position:{x:-1.15,z:1.35}},life:{at:from,notes:[],marks:{}}}},world);q.pets[0].life.at=from;recoverPetLife(q,world,at);assert.equal(q.resident.activity.kind,'sleep');assert.ok(q.resident.choices.recent.every(x=>x.at>=at-3*86400000));});

test('sentence boundaries and explicit negation do not leak a dislike into the next sentence',()=>{const r=deriveResidentPreferences(person('Dislikes coffee. Enjoys reading. Not active. 不太喜欢喝茶。不外向。'));assert.ok(r.scores.coffee<0);assert.ok(r.scores.reading>0);assert.ok(r.scores.active<0);assert.ok(r.scores.tea<0);assert.ok(r.scores.social<0);});
