import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {restoreClock,realTime} from '../fairy-garden/real-clock.mjs';
import {restorePetState,snapshotPetState,petEntry,projectActivePet} from './state.mjs';
import {createPetCareer} from './career.mjs';import {createPetCare} from './care.mjs';import {recoverPetLife} from './routine.mjs';import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));const at=(day,h)=>new Date(2026,9,day,h).getTime();
function writer(from){const s=restorePetState({configured:true,clock:restoreClock(null,1,from),profile:{name:'团子'},town:{place:'home',position:{x:-.28,z:.55}},care:{satiety:55,bowl:100,energy:45},career:{balance:35,inventory:{bread:2}},resident:{id:'ta',town:{place:'home',position:{x:-1.15,z:1.35}},life:{at:from,marks:{},notes:[]}}},world);s.pets[0].life.at=from;return snapshotPetState(s,{position:s.position,room:'home',outdoor:null,evening:false});}
test('ordinary offline meals and sleep replay real home routes, keep owners and cannot replay on reload',()=>{const from=at(5,18),to=at(6,8),s=writer(from);s.pets.push(petEntry({configured:true,profile:{name:'栗子',species:'dog'},town:{place:'home',position:{x:1.15,z:1.2}},life:{at:from},career:{balance:72},care:{satiety:70,bowl:100,energy:55}},'pet-2'));recoverPetLife(s,world,to);projectActivePet(s);assert.equal(s.pets[0].career.balance,35);assert.equal(s.pets[1].career.balance,72);assert.ok(s.pets[0].care.energy>60);assert.ok(s.pets[0].care.bowl<100);assert.ok(s.pets[0].life.notes.some(x=>x.text.includes('吃过')));assert.ok(s.pets[0].life.notes.some(x=>x.text.includes('睡下')));assert.equal(s.pets[0].care.task?.night,undefined);assert.ok(s.resident.life.notes.some(x=>x.text.includes('吃过')));const before=structuredClone(s);recoverPetLife(s,world,to);assert.deepEqual(s,before);});
test('daily invitation resets at actual midnight only; repeated requests and clock rollback cannot reroll',()=>{let t=realTime(restoreClock(null,1,at(5,10)),at(5,10));const care=createPetCare({rng:1,mood:100,energy:100,satiety:70}),career=createPetCareer({rng:1},{calendar:()=>t});assert.ok(career.request('invite',{}, {care:care.state,room:'bakery'}).accepted);const job=career.snapshot().job;care.state.elapsed=100000;career.syncDay(care.state);assert.equal(career.state.day,1);t={...t,date:'2026-10-06',day:2};career.syncDay(care.state);assert.deepEqual(career.state.job,job);assert.equal(career.state.daily.invited,false);career.state.daily.closed=true;t={...t,date:'2026-10-05',day:1};career.syncDay(care.state);assert.equal(career.state.daily.closed,true);});
test('agreed offline work waits at a real pending decision and never invents wages or shopping',()=>{const s=writer(at(5,8));s.pets[0].career.schedule={shift:'morning',weekend:false};s.pets[0].career.rng=1;s.pets[0].care.mood=100;s.pets[0].care.energy=100;s.pets[0].care.satiety=80;recoverPetLife(s,world,at(5,11));const p=s.pets[0];assert.equal(p.town.place,'bakery');assert.equal(p.career.job.phase,'choice');assert.equal(p.career.balance,35);assert.equal(p.career.ledger.length,0);assert.equal(p.career.shopping.log.length,0);const job=structuredClone(p.career.job);recoverPetLife(s,world,at(5,12));assert.deepEqual(p.career.job,job);});
test('legacy snapshots gain a timestamp without fabricating a past meal, move or job',()=>{const s=writer(at(5,8));s.pets[0].life.at=0;s.resident.life.at=0;const p=structuredClone(s.pets[0].town);recoverPetLife(s,world,at(6,18));assert.deepEqual(s.pets[0].town,p);assert.equal(s.pets[0].life.notes.length,0);assert.equal(s.pets[0].career.balance,35);});

test('migration preserves an exhausted legacy shopping quota without blocking later real days',()=>{let time=realTime(restoreClock(null,43,at(5,10)),at(5,10));const c=createPetCareer({day:500,shopping:{lastDay:500},daily:{closed:true},balance:35},{calendar:()=>time});c.syncDay({});assert.equal(c.state.day,43);assert.equal(c.state.shopping.lastDay,43);assert.equal(c.state.daily.closed,true);time={...time,date:'2026-10-06',day:44};c.syncDay({});assert.equal(c.state.shopping.lastDay,43);assert.equal(c.state.daily.closed,false);assert.equal(c.state.balance,35);});
