import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createPetCare} from './care.mjs';import {PET_SKILLS,skillFacts} from './skills.mjs';import {restorePetState,snapshotPetState,petEntry,projectActivePet} from './state.mjs';import {recoverPetLife} from './routine.mjs';import {restoreClock} from '../fairy-garden/real-clock.mjs';import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
const fresh=()=>createPetCare({satiety:90,energy:100,mood:100,rng:1,position:{x:0,z:.55}});
function start(c,id,options={}){for(let i=0;i<30;i++){const r=c.requestSkill(id,options);if(r.accepted)return r;assert.match(r.text,/不想跟着/);}assert.fail('Healthy pet never accepted a skill');}
function finish(c,id,options={}){start(c,id,options);c.arrive();if(id==='fetch'){c.tick(1,{home:true,idleAllowed:false});c.tick(1,{home:true,idleAllowed:false});c.tick(.01,{home:true,idleAllowed:false});assert.equal(c.pickupToy(),true);c.arrive();c.tick(1,{home:true,idleAllowed:false});c.tick(.3,{home:true,idleAllowed:false});assert.equal(c.deliverToy({x:-.7,z:1.5}),true);}else for(let i=0;i<20&&c.state.task;i++)c.tick(1,{home:true,idleAllowed:false});assert.equal(c.state.task,null);}
test('old care keeps actual habits and never infers trained skills from toy experience',()=>{const c=createPetCare({version:6,toys:{ball:40},rests:{bed:20},condition:{water:64},skills:{progress:{come:{practice:NaN},fetch:{practice:-3}}}});assert.equal(c.state.condition.water,64);assert.equal(c.state.toys.ball,40);assert.ok(skillFacts(c.state).every(x=>!x.learned&&x.practice===0));});
test('walking, interruption and paused doing cannot teach a skill; actual completion records one practice',()=>{const c=fresh();start(c,'come');for(let i=0;i<10;i++)c.tick(1,{home:true,idleAllowed:false});assert.equal(c.state.skills.progress.come.practice,0);c.cancel();assert.equal(c.state.skills.progress.come.practice,0);start(c,'stay');c.arrive();for(let i=0;i<10;i++)c.tick(1,{home:true,paused:true});assert.equal(c.state.task.time,0);for(let i=0;i<6;i++)c.tick(1,{home:true,idleAllowed:false});assert.equal(c.state.skills.progress.stay.practice,1);for(let i=0;i<30;i++)c.tick(1,{home:true,idleAllowed:false});assert.equal(c.state.skills.progress.stay.practice,1);});
test('three real practices teach each skill; learned requests and practice stay distinct',()=>{for(const id of Object.keys(PET_SKILLS)){const c=fresh();assert.equal(c.requestSkill(id,{mode:'show'}).accepted,false);for(let i=0;i<3;i++)finish(c,id);const x=skillFacts(c.state).find(x=>x.id===id);assert.equal(x.learned,true);assert.equal(x.practice,3);finish(c,id,{mode:'show'});assert.equal(c.state.skills.progress[id].practice,3);assert.equal(c.state.skills.progress[id].shown,1);assert.equal(c.state.recent.filter(x=>x.type==='skill').length,4);}});
test('teacher identity records completed training with you and the actual TA separately',()=>{const c=fresh();finish(c,'come');finish(c,'come',{source:'companion',actor:'ta-1',name:'小伙伴'});finish(c,'come',{source:'companion',actor:'ta-1',name:'小伙伴'});assert.equal(c.state.skills.progress.come.teachers.you.practice,1);assert.equal(c.state.skills.progress.come.teachers['companion:ta-1'].practice,2);assert.equal(c.state.skills.progress.come.teachers['companion:ta-1'].name,'小伙伴');assert.equal(c.requestSkill('come',{source:'companion',actor:''}).accepted,false);});
test('sleep, hunger, fatigue, another care act and malformed requests preserve progress',()=>{for(const raw of [{energy:20},{satiety:10},{mood:20}]){const c=createPetCare({...fresh().snapshot(),...raw});assert.equal(c.requestSkill('come').accepted,false);assert.equal(c.state.skills.progress.come.practice,0);}const c=fresh();c.request('rest');c.arrive();assert.equal(c.requestSkill('stay').accepted,false);c.cancel();c.request('pet');assert.equal(c.requestSkill('fetch').accepted,false);assert.equal(c.requestSkill('unknown').accepted,false);assert.equal(c.requestSkill('constructor').accepted,false);assert.equal(c.requestSkill('__proto__').accepted,false);assert.equal(c.requestSkill('come',{mode:'invented'}).accepted,false);});
test('fetch must really pick up and put down the saved toy, and a reload resumes the same skill stage',()=>{let c=fresh();start(c,'fetch',{toy:'mouse',source:'companion',actor:'ta',name:'TA'});const old={...c.state.toyPlaces.mouse};c.arrive();c.tick(1,{home:true,idleAllowed:false});assert.equal(c.pickupToy(),false);c.tick(1,{home:true,idleAllowed:false});assert.equal(c.pickupToy(),true);assert.equal(c.state.skills.progress.fetch.practice,0);c=createPetCare(c.snapshot());assert.equal(c.state.task.stage,'carry');assert.equal(c.state.task.target,'companion:ta');assert.equal(c.state.task.toy,'mouse');assert.deepEqual(c.state.toyPlaces.mouse,old);c.arrive();c.tick(1,{home:true,idleAllowed:false});assert.equal(c.deliverToy({x:-.7,z:1.5}),false);c.tick(.2,{home:true,idleAllowed:false});assert.equal(c.deliverToy({x:-.7,z:1.5}),true);assert.equal(c.state.skills.progress.fetch.practice,1);assert.deepEqual(c.state.toyPlaces.mouse,{x:-.7,z:1.5});assert.equal(c.deliverToy({x:-.7,z:1.5}),false);assert.equal(c.state.toys.mouse,0);});
test('canonical four-pet archive writer keeps each training record and a pending skill independently',()=>{const c=fresh();finish(c,'come');const s=restorePetState({configured:true,care:c.snapshot(),career:{balance:35}},world);for(let i=2;i<=4;i++)s.pets.push(petEntry({configured:true,profile:{name:'宠物'+i,species:i%2?'cat':'dog'},career:{balance:i*10}},'pet-'+i));const second=createPetCare(s.pets[1].care);second.state.energy=100;second.state.satiety=90;second.state.mood=100;finish(second,'stay');s.pets[1].care=second.snapshot();const first=createPetCare(s.pets[0].care);start(first,'fetch');s.pets[0].care=first.snapshot();projectActivePet(s);const copy=restorePetState(snapshotPetState(s,{position:s.position,room:'home',outdoor:null,evening:false}),world);assert.equal(copy.pets[0].care.skills.progress.come.practice,1);assert.equal(copy.pets[0].care.task.skill,'fetch');assert.equal(copy.pets[1].care.skills.progress.stay.practice,1);assert.equal(copy.pets[2].care.skills.progress.stay.practice,0);assert.equal(copy.pets[3].career.balance,40);});
test('offline recovery leaves practice unfinished, drops the held original toy and never trains invisibly',()=>{const at=new Date(2026,9,5,14,30).getTime(),from=at-600000,c=fresh();finish(c,'come');start(c,'fetch');c.arrive();c.tick(1,{home:true,idleAllowed:false});c.tick(1,{home:true,idleAllowed:false});c.pickupToy();const s=restorePetState({configured:true,clock:restoreClock(null,1,from),care:c.snapshot(),town:{place:'home',phase:'idle',position:c.state.position},resident:{life:{at:from,marks:{},notes:[]}}},world);s.pets[0].life.at=from;recoverPetLife(s,world,at);projectActivePet(s);assert.equal(s.care.skills.progress.come.practice,1);assert.equal(s.care.skills.progress.fetch.practice,0);assert.deepEqual(s.care.toyPlaces.ball,{x:0,z:.55});const before=structuredClone(s.care.skills);recoverPetLife(s,world,at);projectActivePet(s);assert.deepEqual(s.care.skills,before);});

test('reload rejects a mismatched teacher and cannot show an unlearned skill or award an undelivered toy',()=>{const c=fresh();start(c,'fetch',{source:'companion',actor:'ta',name:'TA'});const pending=c.snapshot();assert.equal(createPetCare({...pending,task:{...pending.task,actor:'other'}}).state.task,null);assert.equal(createPetCare({...pending,task:{...pending.task,mode:'show'}}).state.task,null);assert.equal(createPetCare({...pending,task:{...pending.task,stage:'waiting'}}).state.task,null);assert.equal(c.requestSkill('come',{source:'companion',actor:{id:'ta'}}).accepted,false);});
