import {homePoint} from './initiative.mjs?v=fg-56d22a214af323bc';
// One household ledger: pairs are identified by saved pet IDs, never names or slots.
const n=(v,a,b,d)=>Number.isFinite(v)?Math.max(a,Math.min(b,v)):d;
const id=v=>typeof v==='string'&&/^[\w-]{1,80}$/.test(v)?v:'';
export const SOCIAL_KINDS=['window','ball','box'];
export const pairKey=(a,b)=>[a,b].sort().join('|');
export function restoreSocial(raw,ids=[]){const valid=new Set(ids),r=raw||{},p=r.pending;const pending=p&&SOCIAL_KINDS.includes(p.kind)&&valid.has(p.a)&&valid.has(p.b)&&p.a!==p.b&&id(p.id)?{id:p.id,kind:p.kind,a:p.a,b:p.b,time:n(p.time,0,120,0),following:!!p.following,rendezvous:homePoint(p.rendezvous)}:null;return {version:1,rng:n(r.rng,1,4294967295,472911),wait:n(r.wait,0,180,35),seq:n(r.seq,0,1e9,0),pending,pairs:Object.fromEntries(Object.entries(r.pairs||{}).filter(([k])=>{const a=k.split('|');return a.length===2&&a[0]!==a[1]&&a.every(x=>valid.has(x));}).slice(0,6).map(([k,v])=>[k,{window:n(v.window,0,1e6,0),ball:n(v.ball,0,1e6,0),box:n(v.box,0,1e6,0)}])),recent:(Array.isArray(r.recent)?r.recent:[]).filter(x=>SOCIAL_KINDS.includes(x?.kind)&&valid.has(x.a)&&valid.has(x.b)&&x.a!==x.b&&typeof x.text==='string').slice(-12).map(x=>({id:id(x.id),kind:x.kind,a:x.a,b:x.b,day:n(x.day,1,1e7,1),text:x.text.slice(0,160)}))};}
export function socialSummary(state,petId,pets){return {pending:state.pending&&(state.pending.a===petId||state.pending.b===petId)?structuredClone(state.pending):null,peers:pets.filter(p=>p.id!==petId).map(p=>{const counts=state.pairs[pairKey(petId,p.id)]||{window:0,ball:0,box:0},familiarity=counts.window*2+counts.ball*3+counts.box;return {id:p.id,name:p.profile.name,...counts,familiarity,label:familiarity>=18?'越来越合拍':familiarity>=6?'开始熟悉彼此':familiarity?'有过一起待着的小事':'还在认识对方'};}),recent:state.recent.filter(x=>x.a===petId||x.b===petId).map(x=>({...x}))};}
const free=p=>!p.care.state.helper&&p.care.state.energy>35&&p.care.state.satiety>25&&(!p.care.state.task||p.care.state.task.source==='self'&&['watch','wander'].includes(p.care.state.task.kind)&&!p.care.state.task.socialId);
export function createPetSocial(raw,ids){const keys=()=>typeof ids==='function'?ids():ids;let s=restoreSocial(raw,keys());const random=()=>{s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296;};
 function clear(rows){for(const p of rows)if(p.care.state.task?.socialId===s.pending?.id)p.home.cancelSocial?.()||p.care.cancel();s.pending=null;s.wait=70;}
 function request(kind,aId,bId,rows){const a=rows.find(p=>p.entry.id===aId),b=rows.find(p=>p.entry.id===bId);if(s.pending||!SOCIAL_KINDS.includes(kind)||!a||!b||a===b||!free(a)||!free(b))return {accepted:false,text:'先让它们把手头的事做完，吃饱休息好再认识彼此。'};if(kind==='box'&&a.career.state.inventory.box!==1)return {accepted:false,text:'它还没有自己的小纸箱。'};const event={id:'meeting-'+(++s.seq),kind,a:aId,b:bId,time:0};const backup=rows.map(p=>p.care.snapshot());const spot=(p,place)=>p.home.socialSpot(place);const start=(p,task)=>p.care.startSocial({...task,socialId:event.id,peer:p===a?bId:aId});let ok=false;
  if(kind==='window'){const x=spot(a,'window'),y=b.home.socialBeside(x,a.pet.root.scale.x);event.rendezvous=y;event.following=false;ok=!!y&&start(a,{kind:'watch',place:'window',spot:x})&&start(b,{kind:'watch',place:'window',spot:{...b.care.state.position},focus:x});}
  if(kind==='ball'){ok=start(b,{kind:'watch',place:'rug',spot:{...b.care.state.position},focus:{...a.care.state.position}})&&start(a,{kind:'invitePlay',place:'toy',toy:'ball',stage:'fetch',target:'pet:'+bId,name:b.entry.profile.name});}
  if(kind==='box'){const box=spot(a,'box'),beside=a.home.socialBeside(box,b.pet.root.scale.x);ok=!!beside&&start(a,{kind:'sleep',place:'box',spot:box})&&start(b,{kind:'watch',place:'rug',spot:beside,focus:box});}
  if(!ok){rows.forEach((p,i)=>Object.assign(p.care.state,backup[i]));return {accepted:false,text:'这会儿找不到两只都能走到的位置，晚一点再试。'};}s.pending=event;return {accepted:true,text:kind==='window'?'它们准备去窗边一起看看。':kind==='ball'?a.entry.profile.name+'想把小球叼给'+b.entry.profile.name+'。':b.entry.profile.name+'也看上了'+a.entry.profile.name+'的纸箱，准备过去看看。'};
 }
 function tick(dt,rows,{home=true,paused=false}={}){if(paused||!home||!Number.isFinite(dt)||dt<=0)return null;dt=Math.min(dt,1);if(s.pending){const e=s.pending,a=rows.find(p=>p.entry.id===e.a),b=rows.find(p=>p.entry.id===e.b);if(!a||!b||a.care.state.task?.socialId!==e.id||b.care.state.task?.socialId!==e.id){clear(rows);return {changed:true,cancelled:true};}e.time+=dt;if(e.time>110){clear(rows);return {changed:true,cancelled:true};}const at=a.care.state.task,bt=b.care.state.task;if(e.kind==='window'&&!e.following&&at.phase==='doing'){e.following=true;bt.spot=e.rendezvous;bt.phase='walking';bt.time=0;bt.focus=null;return {changed:true};}if(e.kind==='ball'&&at.stage==='waiting')bt.focus={...a.care.state.toyPlaces.ball};const arrived=at.phase==='doing'&&bt.phase==='doing';const done=arrived&&(e.kind!=='window'||e.following)&&(e.kind==='ball'?at.stage==='waiting'&&at.time>=2:at.time>=7&&bt.time>=7);if(!done)return null;const key=pairKey(e.a,e.b),bond=s.pairs[key]||(s.pairs[key]={window:0,ball:0,box:0});bond[e.kind]++;const an=a.entry.profile.name,bn=b.entry.profile.name,text=e.kind==='window'?an+'和'+bn+'在窗边一起看了一会儿外面。':e.kind==='ball'?an+'把小球叼到'+bn+'身边放下，'+bn+'凑近看了看。':bn+'也想钻进'+an+'的小纸箱，见它已经躺下，就在旁边等了一会儿。';const record={...e,day:a.career.state.day,text};delete record.time;s.recent.push(record);s.recent=s.recent.slice(-12);for(const p of[a,b])p.care.record(text,{type:'social',peer:p===a?e.b:e.a,kind:e.kind});clear(rows);return {changed:true,completed:true,text};}
 s.wait=Math.max(0,s.wait-dt);if(s.wait>0||rows.length<2)return null;s.wait=45;const candidates=rows.filter(free);if(candidates.length<2)return null;const a=candidates[Math.floor(random()*candidates.length)],others=candidates.filter(p=>p!==a),weights=others.map(p=>{const c=s.pairs[pairKey(a.entry.id,p.entry.id)];return 1+Math.min(4,((c?.window||0)*2+(c?.ball||0)*3+(c?.box||0))/8);});let pick=random()*weights.reduce((a,b)=>a+b,0),index=weights.findIndex(w=>(pick-=w)<0);const b=others[Math.max(0,index)];if(random()>(a.care.state.traits.social+b.care.state.traits.social)/2)return {changed:true};const kinds=['window'];if(a.care.state.traits.active>.45)kinds.push('ball');if(a.career.state.inventory.box===1)kinds.push('box');const result=request(kinds[Math.floor(random()*kinds.length)],a.entry.id,b.entry.id,rows);return {changed:true,...result};}
 return {get state(){return s;},snapshot:()=>structuredClone(s),restore:raw=>{s=restoreSocial(raw,keys());},request,tick,cancel:clear,summary:(petId,pets)=>socialSummary(s,petId,pets)};
}
