import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import {createPetSocial,restoreSocial,pairKey}from'./social.mjs';import {createPetCare}from'./care.mjs';import {createPetCareer}from'./career.mjs';import {restorePetState,snapshotPetState,petEntry}from'./state.mjs';import {createPetWorld}from'../../art/pet-career/world-navigation.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
function fixture(){const entries=['a','b','c','d'].map((id,i)=>petEntry({configured:true,profile:{name:['团子','小白','小黑','栗子'][i]},care:{position:{x:i*.65-1,z:.8},satiety:80,energy:75,traits:{social:.8}},career:{balance:30,inventory:{box:i===0?1:0}}},id));const state=restorePetState({pets:entries,activePetId:'a',room:'home'},world);const rows=state.pets.map(entry=>{const care=createPetCare(entry.care);return {entry,care,career:createPetCareer(entry.career),pet:{root:{scale:{x:1}}},home:{socialSpot:p=>p==='window'?{x:-.55,z:-1.9}:{x:-1,z:.05},socialBeside:p=>({x:p.x,z:p.z+.7}),cancelSocial:()=>{care.cancel();return true;}}};});const social=createPetSocial(state.social,()=>rows.map(p=>p.entry.id));const write=()=>{for(const p of rows){p.entry.care=p.care.snapshot();p.entry.career=p.career.snapshot();}state.care=rows[0].care.snapshot();state.social=social.snapshot();return snapshotPetState(state,{position:state.position,room:'home',outdoor:null,evening:false});};return {state,rows,social,write};}
function arrive(rows){for(const p of rows)if(p.care.state.task?.socialId)p.care.arrive();}
function step(f,seconds){for(let i=0;i<seconds*20;i++){for(const p of f.rows)if(p.care.state.task?.socialId)p.care.tick(.05,{home:true});f.social.tick(.05,f.rows);for(const p of f.rows)if(p.care.state.task?.socialId&&p.care.state.task.kind==='watch'&&p.care.state.task.phase==='walking')p.care.arrive();}}
test('empty legacy worlds do not invent friendships and invalid identities are discarded',()=>{assert.deepEqual(restoreSocial(null,['a']).pairs,{});assert.equal(restoreSocial({pending:{id:'x',kind:'window',a:'a',b:'missing'}},['a']).pending,null);assert.equal(pairKey('a','b'),pairKey('b','a'));});
test('window bond requires both actual arrivals and time together; menus and outside freeze',()=>{const f=fixture();assert.equal(f.social.request('window','a','b',f.rows).accepted,true);for(let i=0;i<15;i++)f.social.tick(1,f.rows);assert.equal(f.social.state.recent.length,0);arrive(f.rows);f.social.tick(1,f.rows,{paused:true});assert.equal(f.social.state.pending.time,15);f.social.tick(1,f.rows,{home:false});assert.equal(f.social.state.pending.time,15);step(f,8);assert.equal(f.social.state.recent.length,1);assert.equal(f.social.state.pairs['a|b'].window,1);assert.equal(f.rows[0].care.state.recent.at(-1).peer,'b');assert.equal(f.rows[1].care.state.recent.at(-1).peer,'a');assert.equal(f.rows[2].care.state.recent.length,0);});
test('pending tasks and pair ledger round-trip through the actual household writer without duplicate reward',()=>{const f=fixture();f.social.request('window','a','b',f.rows);arrive(f.rows);step(f,3);const save=f.write(),restore=restorePetState(save,world);assert.equal(restore.pets[0].care.task.socialId,restore.social.pending.id);assert.equal(restore.pets[1].care.task.socialId,restore.social.pending.id);const g=fixture();g.rows.forEach((p,i)=>Object.assign(p.care.state,createPetCare(restore.pets[i].care).state));g.social.restore(restore.social);step(g,5);assert.equal(g.social.state.recent.length,1);const completed=restorePetState({...g.write(),activePetId:'b'},world);assert.equal(completed.social.pairs['a|b'].window,1);assert.equal(completed.social.pending,null);assert.equal(g.social.summary('b',completed.pets).peers.find(p=>p.id==='a').window,1);g.social.tick(1,g.rows);assert.equal(g.social.state.recent.length,1);});
test('toy invitation records nothing until pickup, physical delivery and recipient response',()=>{const f=fixture();const money=f.rows.map(p=>p.career.state.balance);f.social.request('ball','a','b',f.rows);arrive(f.rows);step(f,2);assert.equal(f.social.state.recent.length,0);assert.equal(f.rows[0].care.pickupToy(),true);f.rows[0].care.arrive();step(f,1.3);assert.equal(f.rows[0].care.deliverToy({x:.3,z:.8}),true);step(f,2.1);assert.equal(f.social.state.pairs['a|b'].ball,1);assert.deepEqual(f.rows[0].care.state.toyPlaces.ball,{x:.3,z:.8});assert.deepEqual(f.rows.map(p=>p.career.state.balance),money);assert.equal(f.rows[1].career.state.inventory.toy,0);});
test('box meeting retains ownership and learns only after waiting beside the real owner',()=>{const f=fixture();assert.equal(f.social.request('box','b','a',f.rows).accepted,false);assert.equal(f.social.request('box','a','b',f.rows).accepted,true);arrive(f.rows);step(f,8);assert.equal(f.social.state.pairs['a|b'].box,1);assert.equal(f.rows[0].career.state.inventory.box,1);assert.equal(f.rows[1].career.state.inventory.box,0);assert.equal(f.rows[0].care.state.rests.box,0,'seven seconds is not a completed full sleep');assert.match(f.social.state.recent[0].text,/旁边等/);});
test('interruption timeout and blocked planning leave no fabricated friendship',()=>{const f=fixture();f.social.request('window','a','b',f.rows);f.rows[1].care.cancel();f.social.tick(.1,f.rows);assert.equal(f.social.state.pending,null);assert.deepEqual(f.social.state.pairs,{});f.rows[0].home.socialBeside=()=>null;assert.equal(f.social.request('box','a','b',f.rows).accepted,false);assert.equal(f.rows[0].care.state.task,null);f.social.request('ball','a','b',f.rows);for(let i=0;i<111;i++)f.social.tick(1,f.rows);assert.equal(f.social.state.pending,null);assert.equal(f.social.state.recent.length,0);});
test('hunger sleep busy helper and solitary households cannot start encounters',()=>{const f=fixture();f.rows[1].care.state.energy=20;assert.equal(f.social.request('window','a','b',f.rows).accepted,false);f.rows[1].care.state.energy=80;f.rows[1].care.request('rest',{source:'self'});assert.equal(f.social.request('window','a','b',f.rows).accepted,false);f.social.tick(1,f.rows.slice(0,1));assert.equal(f.social.state.pending,null);});

test('local idle scheduling starts a real encounter and acquaintance comes only from experience',()=>{const f=fixture();for(const p of f.rows)p.care.state.traits.social=1;const automatic=createPetSocial({wait:0,rng:1},f.rows.map(p=>p.entry.id));const event=automatic.tick(.05,f.rows);assert.equal(event.accepted,true);assert.ok(automatic.state.pending);assert.equal(automatic.state.recent.length,0);const pending=automatic.state.pending;assert.ok(f.rows.find(p=>p.entry.id===pending.a).care.state.task.socialId);assert.equal(automatic.summary(pending.a,f.state.pets).peers.find(p=>p.id===pending.b).label,'还在认识对方');});
