import {PARCEL_ITEMS,parcelItems} from './parcels.mjs?v=fg-337e28073d0dffaf';
import {canOwn} from './shopping.mjs?v=fg-337e28073d0dffaf';
export const STALL_POINT={x:-9,z:17};
export const STALL_GOODS=['snack','bread','flower','petals','receipt','sticker','coaster'];
const prices={snack:5,bread:4,flower:3,petals:1,receipt:2,sticker:3,coaster:3};
const guests=[{id:'apricot',name:'杏杏',species:'dog'},{id:'sesame',name:'芝麻',species:'cat'},{id:'bean',name:'豆豆',species:'dog'}];
const num=(v,max=10000)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
export function stallStock(raw){let left=3;return Object.fromEntries(STALL_GOODS.flatMap(id=>{const count=Math.min(left,num(raw?.[id],3));left-=count;return count?[[id,count]]:[];}));}
export const stockSize=stock=>Object.values(stock||{}).reduce((a,b)=>a+b,0);
export const atStall=p=>!!p&&Math.hypot(p.x-STALL_POINT.x,p.z-STALL_POINT.z)<.4;
export function restoreMarket(raw){if(!raw||typeof raw.id!=='string'||!Array.isArray(raw.offers)||raw.offers.length!==3)return null;const offers=raw.offers.map(o=>{const guest=guests.find(g=>g.id===o?.guest);return guest&&STALL_GOODS.includes(o.item)&&['sale','haggle','barter'].includes(o.kind)&&['toy','oddButton','leafBoat'].includes(o.gift)?{guest:guest.id,item:o.item,kind:o.kind,gift:o.gift,reluctant:o.reluctant===true,counterAccepted:o.counterAccepted===true}:null;});if(offers.some(o=>!o))return null;const packed=stallStock(raw.packed),remaining=stallStock(raw.remaining),received=parcelItems(Object.fromEntries(['toy','oddButton','leafBoat'].map(id=>[id,raw.received?.[id]]))),sold=num(raw.sold,3),exchanged=num(raw.exchanged,3);if(!stockSize(packed)||stockSize(remaining)+sold+exchanged!==stockSize(packed)||Object.entries(remaining).some(([id,n])=>n>(packed[id]||0))||stockSize(received)!==exchanged||received.toy>1||offers.some(o=>!packed[o.item]))return null;return {id:raw.id.slice(0,80),packed,remaining,received,offers,cursor:num(raw.cursor,3),revision:num(raw.revision,20),income:num(raw.income),sold:num(raw.sold,3),exchanged:num(raw.exchanged,3)};}
export function restoreStall(raw){return {pack:stallStock(raw?.pack),log:(Array.isArray(raw?.log)?raw.log:[]).filter(x=>typeof x?.id==='string').slice(-30).map(x=>({id:x.id.slice(0,80),day:num(x.day,1e7),income:num(x.income),sold:num(x.sold,3),exchanged:num(x.exchanged,3),returned:parcelItems(x.returned),text:String(x.text||'').slice(0,240)}))};}
export function makeMarket(id,stock,care,random){const keys=Object.keys(stock),offset=Math.floor(random()*3);return {id,packed:{...stock},remaining:{...stock},received:{},cursor:0,revision:0,income:0,sold:0,exchanged:0,offers:[0,1,2].map(i=>({guest:guests[(i+offset)%3].id,item:keys[i%keys.length],kind:['sale','haggle','barter'][(i+offset)%3],gift:['toy','oddButton','leafBoat'][Math.floor(random()*3)],reluctant:(['snack','bread'].includes(keys[i%keys.length])&&care.satiety<65)||(keys[i%keys.length]==='coaster'&&care.traits.active>.65),counterAccepted:random()<.35+care.traits.bold*.4}))};}
const option=(id,label,note,extras={})=>({id,label,note,tip:0,like:.05,...extras});
export function marketEvent(job,state){const m=job?.market;if(!m||job.phase!=='choice')return null;let title,text,options;
 if(job.index===0){title='把自己的小东西装好了';text='这趟装了'+Object.entries(m.remaining).map(([id,c])=>c+' '+PARCEL_ITEMS[id].unit+PARCEL_ITEMS[id].name).join('、')+'。沿街走到公园野餐角，再把摊布铺开。';options=[option('open','带上这些，去公园摆摊','带上实际装好的小东西，准备去公园摆摊。',{trait:'bold'})];}
 else if(job.index===2){title='带着剩下的东西回家';text='这一趟实际收入 ￥'+m.income+'，卖出 '+m.sold+' 件、交换 '+m.exchanged+' 件。剩下的和换回的装在回家小袋子里。';options=[option('close','收好小票和没卖掉的东西','已经实际回到家里，收好这趟摆摊的小票和余货。')];}
 else{const o=m.offers[m.cursor],g=guests.find(g=>g.id===o.guest),name=PARCEL_ITEMS[o.item].name,price=prices[o.item];title=g.name+'来到摊前';text=g.name+'（'+(g.species==='cat'?'猫咪':'狗狗')+'）停在野餐角，想看看'+name+'。';
 if(!m.remaining[o.item]){text+='它想要的这一件已经没有了。';options=[option('empty','告诉它这件已经没货啦','告诉'+g.name+'这件已没有余货，没收钱，也没换东西。')];}
 else{const keep=option('keep',o.reluctant?'它舍不得，给它留下吧':'这件先留着，和客人说声谢谢','把'+name+'留在自己的摊袋里，没有成交。',{like:.08,energy:2});text+=o.reluctant?'它把这件往自己身边拨了拨，好像舍不得卖。':'';
 if(o.kind==='barter'){text+=g.name+'想拿'+PARCEL_ITEMS[o.gift].name+'交换这一件。';const room=o.gift!=='toy'||canOwn(state,{id:'toy',max:1});options=[...(room?[option('trade','用一件'+name+'换'+PARCEL_ITEMS[o.gift].name,'实际用一件'+name+'换回了'+PARCEL_ITEMS[o.gift].name+'。',{trait:'active',like:o.reluctant?.01:.05,mood:o.reluctant?-5:0})]:[]),keep];if(!room)text+='家里已经有自己的小球，这份不再换第二个。';}
 else{const amount=o.kind==='haggle'?Math.max(1,price-1):price;text+=o.kind==='haggle'?'它想少付一点，问 ￥'+amount+' 行不行。':'摊签写着 ￥'+price+'，它想买一件。';options=[option('sell','一件 ￥'+amount+'，这笔成交','实际卖出一件'+name+'，收下 ￥'+amount+'。',{trait:'social',like:o.reluctant?.01:.05,mood:o.reluctant?-5:0}),...(o.kind==='haggle'?[option('counter','按摊签 ￥'+price+' 再问一次',o.counterAccepted?'客人接受摊签价格，实际卖出一件'+name+'，收下 ￥'+price+'。':'客人摇摇头，这次没成交，东西还在。',{trait:'bold'})]:[]),keep];}}
 }
 return {id:job.id+':'+job.index+':'+m.revision,title,text,options};}
export function chooseMarket(job,state,id,day,by){const m=job.market;if(job.index!==1){m.revision++;return true;}const o=m.offers[m.cursor],amount=id==='sell'?(o.kind==='haggle'?Math.max(1,prices[o.item]-1):prices[o.item]):id==='counter'&&o.counterAccepted?prices[o.item]:0;if(amount||id==='trade'){m.remaining[o.item]--;if(!m.remaining[o.item])delete m.remaining[o.item];if(id==='trade'){m.exchanged++;m.received[o.gift]=(m.received[o.gift]||0)+1;}else{m.sold++;m.income+=amount;state.balance+=amount;state.ledger.push({id:'market:'+job.id+':'+m.cursor,day,amount,text:by+'商量的摊位交易 · '+PARCEL_ITEMS[o.item].name});state.ledger=state.ledger.slice(-80);}}
 m.cursor++;m.revision++;return m.cursor>=3;}
export const marketReturns=job=>parcelItems({...job.market.remaining,...Object.fromEntries(Object.keys(PARCEL_ITEMS).map(id=>[id,(job.market.remaining[id]||0)+(job.market.received[id]||0)]))});
export function finishMarket(job,stall,day,{stopped=false}={}){const m=job.market,returned=marketReturns(job),text=(stopped?'提前收摊：':'在公园摆摊：')+'实际收入 ￥'+m.income+'，卖出 '+m.sold+' 件、交换 '+m.exchanged+' 件；余货和换回的小东西'+(stopped?'装在回家袋子里。':'带回家。');stall.log.push({id:job.id,day,income:m.income,sold:m.sold,exchanged:m.exchanged,returned,text});stall.log=stall.log.slice(-30);return text;}
export function marketView(job){const m=job?.market;if(!m)return null;const o=job.index===1?m.offers[m.cursor]:null;return {id:m.id,remaining:parcelItems(m.remaining),received:parcelItems(m.received),cursor:m.cursor,income:m.income,sold:m.sold,exchanged:m.exchanged,guest:o?{...guests.find(g=>g.id===o.guest)}:null,destinationTitle:job.index===1?'公园野餐角':'家里',atPark:job.index===1};}
