import {dailyRoutine} from '../fairy-garden/real-clock.mjs?v=fg-95dfbc20ee832516';
export const TOGETHER_SHOPS=['cafe','bakery','florist','store','alley'];
export function restoreTogether(raw){return raw&&typeof raw.id==='string'&&typeof raw.petId==='string'&&typeof raw.personId==='string'&&TOGETHER_SHOPS.includes(raw.shop)&&['travel','settle','browse','home'].includes(raw.phase)?{id:raw.id.slice(0,100),petId:raw.petId,personId:raw.personId,shop:raw.shop,phase:raw.phase,reported:raw.reported===true}:null;}
export function togetherBlock(p,person,time,{reserved=false,companionBusy=false}={}){if(!person?.id)return '先和这一档的TA一起进入小镇。';if(!p)return '先选好同行的小家伙。';const s=p.care?.state||p.care,job=p.career?.state?.job||p.career?.job,t=s?.task,period=dailyRoutine(time,s?.rng||1);if(reserved||companionBusy||job||s.helper||t&&!(t.source==='self'&&['wander','watch','play','moveAway'].includes(t.kind)))return '先忙完眼前的工作、照料或约定，再结伴出门。';if(period.home||s.energy<35||s.satiety<35)return '这会儿先吃饭或休息，空下来再一起逛。';return '';}
const rank=(s,dest)=>s.place===dest?2:s.place==='outside'?1:0;
// Only the member ahead waits. The one behind keeps walking, including through
// doorways; actor-spacing still owns actual body clearance.
export function togetherWaiting(self,peer,dest){if(!self||!peer)return false;const a=rank(self,dest),b=rank(peer,dest);if(a!==b)return a>b;if(self.place!==peer.place||Math.hypot(self.position.x-peer.position.x,self.position.z-peer.position.z)<3)return false;if(!self.goal)return true;if(!peer.goal)return false;const left=s=>Math.hypot(s.position.x-s.goal.x,s.position.z-s.goal.z);return left(self)+.15<left(peer);}
export function cancelOfflineTogether(state,at=Date.now()){const trip=state.together;if(!trip)return false;const p=state.pets.find(x=>x.id===trip.petId);if(!p||String(state.resident.id)!==trip.personId||at-(p.life?.at||0)>=60000){for(const t of[p?.town,state.resident.town])if(t){t.goal=null;t.stop=null;t.manual=false;t.phase=t.place==='home'?'idle':'visit';t.hold=60;t.time=0;}state.together=null;return true;}return false;}
