import {dailyRoutine} from '../fairy-garden/real-clock.mjs?v=fg-dfbc36ab1020098c';
import {restoreWalkEvent,WALK_KINDS} from './walk-life.mjs?v=fg-dfbc36ab1020098c';
export const TOGETHER_SHOPS=['cafe','bakery','florist','store','alley'];
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&Math.abs(p.x)<100&&Math.abs(p.z)<100?{x:p.x,z:p.z}:null;
export const togetherDestination=t=>['home','wipe'].includes(t?.phase)?'home':t?.mode==='walk'?'outside':t?.shop;
export function togetherActivity(t){return t?.mode==='walk'?(t.phase==='wipe'?'你和TA在家门边陪它擦爪':t.phase==='notice'?'你和TA陪它'+(WALK_KINDS[t.street?.kind]||'看看路边'):t.phase==='home'?'你和TA带它一起回家':t.phase==='play'?(t.play?.kind==='pet'?'你和TA停下来陪它贴贴':'你和TA停下来陪它追球'):t.phase==='pause'?'你和TA陪它在路边歇歇':t.phase==='travel'?'你和TA带它一起出门':'你和TA带它沿街散步'):t?.phase==='browse'?'和它在店里逛逛':t?.phase==='home'?'结伴回家':'和它结伴去逛街';}
const bounded=(v,max)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
export function restoreTogether(raw){const walk=raw?.mode==='walk',play=raw?.play;return raw&&typeof raw.id==='string'&&typeof raw.petId==='string'&&typeof raw.personId==='string'&&(walk?raw.shop==='outside':TOGETHER_SHOPS.includes(raw.shop))&&(walk?['travel','walk','pause','play','notice','wipe','home']:['travel','settle','browse','home']).includes(raw.phase)?{id:raw.id.slice(0,100),petId:raw.petId,personId:raw.personId,shop:raw.shop,phase:raw.phase,reported:raw.reported===true,...(walk?{mode:'walk',street:restoreWalkEvent(raw.street),idle:Math.min(90,Number.isFinite(raw.idle)?Math.max(0,raw.idle):0),weatherSeen:typeof raw.weatherSeen==='string'?raw.weatherSeen.slice(0,80):'',point:point(raw.point),sequence:bounded(raw.sequence,1e6),play:['play','pet'].includes(play?.kind)&&point(play.anchor)&&point(play.ball)&&point(play.goal)?{kind:play.kind,anchor:point(play.anchor),ball:point(play.ball),goal:point(play.goal),round:bounded(play.round,3)}:null}:{})}:null;}

export function togetherBlock(p,person,time,{reserved=false,companionBusy=false}={}){if(!person?.id)return '先和这一档的TA一起进入小镇。';if(!p)return '先选好同行的小家伙。';const s=p.care?.state||p.care,job=p.career?.state?.job||p.career?.job,t=s?.task,period=dailyRoutine(time,s?.rng||1);if(reserved||companionBusy||job||s.helper||t&&!(t.source==='self'&&['wander','watch','play','moveAway'].includes(t.kind)))return '先忙完眼前的工作、照料或约定，再结伴出门。';if(period.home||s.energy<35||s.satiety<35)return '这会儿先吃饭或休息，空下来再一起逛。';return '';}
const rank=(s,dest)=>s.place===dest?2:s.place==='outside'?1:0;
// Only the member ahead waits. The one behind keeps walking, including through
// doorways; actor-spacing still owns actual body clearance.
export function togetherWaiting(self,peer,dest){if(!self||!peer)return false;const a=rank(self,dest),b=rank(peer,dest);if(a!==b)return a>b;if(self.place!==peer.place||Math.hypot(self.position.x-peer.position.x,self.position.z-peer.position.z)<3)return false;if(!self.goal)return true;if(!peer.goal)return false;const left=s=>Math.hypot(s.position.x-s.goal.x,s.position.z-s.goal.z);return left(self)+.15<left(peer);}
export function cancelOfflineTogether(state,at=Date.now()){const trip=state.together;if(!trip)return false;const p=state.pets.find(x=>x.id===trip.petId);if(!p||String(state.resident.id)!==trip.personId||at-(p.life?.at||0)>=60000){for(const t of[p?.town,state.resident.town])if(t){t.goal=null;t.stop=null;t.manual=false;t.phase=t.place==='home'?'idle':'visit';t.hold=60;t.time=0;}if(p?.care?.task?.outingId===trip.id){p.care.task=null;p.care.idle=0;}if(state.neighborhood?.streetVisit?.tripId===trip.id)state.neighborhood.streetVisit.phase='returning';state.together=null;return true;}return false;}
