import {createPetToy} from './toy-prop.mjs?v=fg-c27bf8a6a71ea07b';
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&Math.abs(p.x)<100&&Math.abs(p.z)<100?{x:p.x,z:p.z}:null;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
// Plan two reachable, separate stops through the original body-aware navigator.
export function planWalkPair(pet,person,target,world,{bold=.5}={}){if(!point(target))return null;const from=t=>t.state.place==='outside'?t.state.position:world.building(t.state.place)?.approach;if(!from(pet)||!from(person))return null;const a=pet.nav('outside'),b=person.nav('outside'),p=a.freePoint(target,from(pet),.8,true);if(!p)return null;const angle=Math.atan2(from(person).x-p.x,from(person).z-p.z);for(const radius of[bold<.35?1.3:bold>.7?1.8:1.4,1.8])for(const offset of[0,.8,-.8,1.6,-1.6,Math.PI]){const q=b.freePoint({x:p.x+Math.sin(angle+offset)*radius,z:p.z+Math.cos(angle+offset)*radius},from(person),.4,true);if(q&&distance(p,q)>=1.25)return {pet:p,person:q};}return null;}
export function cancelWalkPlay(trip,care){if(care?.state.task?.outingId===trip?.id)care.cancel();if(trip)trip.play=null;}
export function beginWalkPlay(trip,pet,person,care,world,kind,{source='you',actor='',name='',manner}={}){if(!['play','pet'].includes(kind)||trip.mode!=='walk'||trip.phase==='home'||pet.state.place!=='outside'||person.state.place!=='outside')return {accepted:false,text:'等大家一起走到街上，再停下来玩。'};if(trip.play)return {accepted:false,text:'正在陪它玩，做完这一件再来。'};const stops=planWalkPair(pet,person,pet.state.position,world);if(!stops)return {accepted:false,text:'这里有点挤，先一起走到宽一点的路边。'};const result=care.request(kind,{toy:'ball',source,actor,name,manner});if(!result.accepted)return result;care.state.task.outingId=trip.id;trip.sequence=(trip.sequence||0)+1;trip.phase='play';trip.play={kind,anchor:stops.pet,round:0,ball:{...stops.pet},goal:{...stops.pet}};for(const [life,q]of[[pet,stops.pet],[person,stops.person]]){life.sync(life.state.place,life.state.position,life.state.heading,{manual:true});if(distance(q,life.state.position)>.15)life.go('outside',q,{manual:true});}return {accepted:true,text:kind==='play'?'你们停下来，准备陪它追一会儿小球。':'你们停下来，等它靠近，再轻轻摸摸。'};}
export function advanceWalkPlay(trip,pet,person,care,dt){const play=trip.play,t=care.state.task;if(!play||t?.outingId!==trip.id)return false;let changed=false;if(t.phase==='walking'&&!pet.state.goal&&!person.state.goal&&distance(pet.state.position,person.state.position)<2.5){care.arrive();changed=true;}
 if(t.phase==='doing'&&play.kind==='play'&&play.round<3&&t.time>=play.round*4&&!pet.state.goal&&!person.state.goal){const n=pet.nav(),a=Math.atan2(play.anchor.x-person.state.position.x,play.anchor.z-person.state.position.z);let goal=null;for(const radius of[play.round===1?3.2:2.6,2,1.3]){for(const offset of[play.round%2?.65:-.65,0,1.2,-1.2,Math.PI]){const q=n.freePoint({x:play.anchor.x+Math.sin(a+offset)*radius,z:play.anchor.z+Math.cos(a+offset)*radius},pet.state.position,.4,true);if(q&&distance(q,pet.state.position)>.3&&n.segmentClear(play.ball,q)&&n.stepClear(play.ball,q)){goal=q;break;}}if(goal)break;}if(goal&&pet.go('outside',goal,{manual:true})){play.goal=goal;play.round++;changed=true;}}
 if(play.kind==='play'){const d=distance(play.ball,play.goal),amount=Math.min(1,dt*2.1/(d||1));play.ball.x+=(play.goal.x-play.ball.x)*amount;play.ball.z+=(play.goal.z-play.ball.z)*amount;}
 return changed;
}
export function walkPlayReady(trip,pet,person){const v=trip.play;return trip.phase==='play'&&!!v&&!pet.goal&&!person.goal&&pet.place==='outside'&&person.place==='outside'&&(v.kind==='pet'||v.round>0&&distance(v.ball,v.goal)<.08);}
export function createWalkPlayView(T,{scene,getTrip,getPlace,ground}){const ball=createPetToy(T,'ball');ball.scale.setScalar(2.2);ball.userData.walkToy=true;ball.visible=false;scene.add(ball);return {sync(){const p=getTrip()?.play;ball.visible=!!p&&p.kind==='play'&&getPlace()==='outside';if(ball.visible){ball.position.set(p.ball.x,ground(p.ball.x,p.ball.z)+.15,p.ball.z);ball.rotation.z=p.ball.x*4;ball.rotation.x=p.ball.z*4;}},ball};}
