import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
import {newPetEntry,restorePetState,snapshotPetState} from './state.mjs';
import {createTownLife,newTownLife} from './town-life.mjs';
import {restoreTogether,togetherWaiting,cancelOfflineTogether} from './together.mjs';
import {restoreWalkMemory,walkHabitFacts,chooseWalkInterest,beginWalkEvent,advanceWalkEvent,rememberWalk,weatherWalkKind,walkShelters} from './walk-life.mjs';
import {createNeighborhood,restoreNeighborhood} from './neighborhood.mjs';
import {recordNeighborBond} from './pet-friends.mjs';
import {createPetCare} from './care.mjs';
import {createPetCareer} from './career.mjs';
import {restoreLivingAlbum,addLivingPhoto,editLivingAlbum,livingPhotoFacts} from './living-photos.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
function fixture(species='cat'){const at=1791198000000,entry=newPetEntry({species,name:'小团'},[],()=>.4,at);entry.town=newTownLife('outside',{x:0,z:5},3);entry.care.energy=90;entry.care.satiety=90;const human=newTownLife('outside',{x:-1.5,z:5},4),actors=()=>[{id:'pet:'+entry.id,kind:'pet',species,size:1,place:entry.town.place,position:entry.town.position},{id:'companion:ta',kind:'person',size:1.6,place:human.place,position:human.position}],pet=createTownLife(entry.town,{world,actors,actor:()=>actors()[0]}),person=createTownLife(human,{world,actors,actor:()=>actors()[1],size:()=>1.4}),trip=restoreTogether({id:'walk:real',petId:entry.id,personId:'ta',mode:'walk',shop:'outside',phase:'walk',sequence:0});const step=()=>{pet.tick(.05,{group:true,waiting:togetherWaiting(entry.town,human,'outside')});person.tick(.05,{group:true,waiting:togetherWaiting(human,entry.town,'outside')});};return {entry,human,pet,person,trip,at,step};}
test('sniff, leaf and flower observations start only after both real paths have arrived, for cats and dogs',()=>{for(const species of['cat','dog'])for(const kind of['sniff','leaf','flower']){const f=fixture(species),event=beginWalkEvent(f.trip,f.entry,f.pet,f.person,world,{kind,point:{x:3,z:8},at:f.at});assert.ok(event);assert.equal(advanceWalkEvent(event,f.entry.town,f.human,5),false);assert.equal(event.time,0);let done=false;for(let i=0;i<2000&&!done;i++){f.step();done=advanceWalkEvent(event,f.entry.town,f.human,.05);}assert.ok(done,JSON.stringify(f.trip));assert.ok(Math.hypot(f.entry.town.position.x-3,f.entry.town.position.z-8)<1);const text=rememberWalk(f.entry,event,f.at,'阿榆');assert.ok(text);assert.equal(rememberWalk(f.entry,event,f.at,'阿榆'),null);assert.equal(f.entry.walk.spots[0].visits,1);}});
test('only three actually completed observations form a favorite; cancelled preparations and another pet do not learn it',()=>{const f=fixture();assert.equal(walkHabitFacts(f.entry).spots.length,0);beginWalkEvent(f.trip,f.entry,f.pet,f.person,world,{kind:'sniff',point:{x:3,z:8},at:f.at});assert.equal(walkHabitFacts(f.entry).spots.length,0);for(let i=0;i<3;i++)rememberWalk(f.entry,{id:'observed:'+i,kind:'sniff',pet:{x:3,z:8}},f.at+i,'阿榆');const facts=walkHabitFacts(f.entry);assert.equal(facts.spots[0].visits,3);assert.deepEqual(chooseWalkInterest(f.entry,{random:()=>0}),{kind:'sniff',point:{x:3,z:8},friendId:''});assert.equal(walkHabitFacts(fixture('dog').entry).spots.length,0);assert.equal(f.entry.career.balance,0);});
test('species, social personality and the same actual season select different street interests locally',()=>{const cat=fixture('cat').entry,dog=fixture('dog').entry;assert.equal(chooseWalkInterest(cat,{environment:{season:0},random:()=>.9}).kind,'flower');assert.equal(chooseWalkInterest(dog,{random:()=>.1}).kind,'sniff');cat.care.traits.social=1;assert.equal(chooseWalkInterest(cat,{friends:[{id:'cafe-cat'}],random:()=>.5}).kind,'friend');cat.care.traits.social=0;assert.notEqual(chooseWalkInterest(cat,{friends:[{id:'cafe-cat'}],random:()=>.5}).kind,'friend');});
test('rain and summer shade use the current original environment and real reachable awnings; winter leaves the clocks unchanged',()=>{assert.equal(weatherWalkKind({rain:true,season:0,minute:700}),'shelter');assert.equal(weatherWalkKind({season:1,minute:800}),'shade');assert.equal(weatherWalkKind({season:1,minute:1300}),null);assert.equal(weatherWalkKind({season:3,snow:true,minute:800}),null);for(const x of walkShelters(world))assert.ok(world.walkable(x.point.x,x.point.z));assert.equal(walkShelters(world).length,3);});
test('wet paws clear after an actual home wiping animation, not while going home or on cancelled wiping',()=>{const f=fixture();f.entry.walk.wetPaws=true;const e={id:'wipe:1',kind:'wipe',phase:'approach',pet:f.entry.town.position,person:f.human.position,time:0};assert.equal(advanceWalkEvent(e,f.entry.town,f.human,.1),false);assert.equal(e.time,0);assert.equal(f.entry.walk.wetPaws,true);f.entry.town.place=f.human.place='home';let done=false;for(let i=0;i<82;i++)done=advanceWalkEvent(e,f.entry.town,f.human,.1);assert.ok(done);rememberWalk(f.entry,e,f.at,'阿榆');assert.equal(f.entry.walk.wetPaws,false);assert.equal(f.entry.walk.spots.length,0);});
test('the original archive writer retains live event time and learned places; a long absence clears the meeting without learning or rewards',()=>{const f=fixture();f.entry.life.at=f.at;const event=beginWalkEvent(f.trip,f.entry,f.pet,f.person,world,{kind:'leaf',point:{x:3,z:8},at:f.at});event.time=2;const state=restorePetState({pets:[f.entry],activePetId:f.entry.id,together:f.trip,resident:{id:'ta',town:f.human},neighborhood:{streetVisit:{neighborId:'cafe-cat',tripId:f.trip.id,phase:'coming',point:{x:10,z:16},at:f.at}}},world,{at:f.at});const next=restorePetState(snapshotPetState(state,{position:state.position,room:null,outdoor:null,evening:false}),world,{at:f.at+1000});assert.equal(next.together.street.time,2);assert.equal(cancelOfflineTogether(next,f.at+1000),false);assert.equal(cancelOfflineTogether(next,f.at+61000),true);assert.equal(next.neighborhood.streetVisit.phase,'returning');assert.equal(next.together,null);assert.equal(next.pets[0].walk.recent.length,0);assert.equal(next.pets[0].career.balance,0);});
test('a familiar pet friend uses its original doorway and street navigator, returns through its original shop door, and rejected save leaves no visitor',()=>{const f=fixture(),entry=f.entry,shared=restoreNeighborhood(null,[entry.id],[entry]);const rows=[{entry,care:createPetCare(entry.care,{real:true}),career:createPetCareer(entry.career),town:f.pet,pet:{root:{scale:{x:1}}}}];let accept=true;const engine=createNeighborhood(shared,{world,getRows:()=>rows,getActors:()=>[],getTime:()=>({at:f.at,date:'2026-10-05',day:1,minute:600,weekday:1}),save:()=>accept});accept=false;assert.equal(engine.walkFriend('florist-cat',f.trip.id,{x:-14,z:-10}).accepted,false);assert.equal(engine.state.streetVisit,null);assert.equal(engine.state.neighbors['florist-cat'].town.place,'florist');accept=true;assert.equal(engine.walkFriend('florist-cat',f.trip.id,{x:-14,z:-10}).accepted,true);let i=0;for(;i<8000&&engine.state.streetVisit.phase!=='staying';i++)engine.tick(.05);assert.ok(i<8000,JSON.stringify(engine.state.streetVisit));const t=engine.state.neighbors['florist-cat'].town;assert.equal(t.place,'outside');assert.ok(Math.hypot(t.position.x+14,t.position.z+10)<1);assert.equal(engine.state.neighbors['florist-cat'].met[entry.id],undefined);engine.releaseWalkFriend(f.trip.id);for(i=0;i<8000&&engine.state.streetVisit;i++)engine.tick(.05);assert.ok(i<8000);assert.equal(t.place,'florist');});
test('a street friend cannot complete a greeting until the real third body arrives',()=>{const f=fixture(),e={id:'friend:1',kind:'friend',phase:'approach',time:0};assert.equal(advanceWalkEvent(e,f.entry.town,f.human,.1,{place:'florist',position:{x:0,z:0}}),false);assert.equal(e.time,0);assert.equal(advanceWalkEvent(e,f.entry.town,f.human,.1,{place:'outside',position:{x:0,z:5},goal:{x:1,z:5}}),false);assert.equal(e.time,0);for(let i=0;i<102;i++)advanceWalkEvent(e,f.entry.town,f.human,.05,{place:'outside',position:{x:1.5,z:5},goal:null});assert.ok(e.time>=5);const holder={};recordNeighborBond(holder,'florist-cat','greet',{at:f.at,day:1,name:'小团'});assert.equal(holder['florist-cat'].greetings,1);});
test('living photo writer, wall display and deletion belong to the original archive and only metadata enters chat',()=>{const f=fixture(),album=restoreLivingAlbum(),photo={id:'living:1',image:'data:image/jpeg;base64,YWJj',at:f.at,petId:f.entry.id,personId:'ta',petName:'小团',personName:'阿榆',place:'家里',caption:'一起待着',weather:'细雨',season:'春天',time:'10:00'};assert.ok(addLivingPhoto(album,photo));assert.equal(addLivingPhoto(album,photo),false);assert.ok(editLivingAlbum(album,'display',photo.id));const state=restorePetState({pets:[f.entry],album},world,{at:f.at}),again=restorePetState(snapshotPetState(state,{position:state.position,room:'home',outdoor:null,evening:false}),world,{at:f.at+1});assert.equal(again.album.photos[0].image,photo.image);assert.equal(again.album.wallPhotoId,photo.id);assert.equal(JSON.stringify(livingPhotoFacts(album)).includes('base64'),false);assert.equal(editLivingAlbum(album,'delete','other'),false);assert.ok(editLivingAlbum(album,'delete',photo.id));assert.equal(album.wallPhotoId,'');assert.equal(album.photos.length,0);assert.equal(restoreLivingAlbum().photos.length,0);});

test('different actual activity traits change group walking pace without changing ordinary town movement',()=>{const move=(pace,group)=>{const town=newTownLife('outside',{x:0,z:5},3),life=createTownLife(town,{world});life.go('outside',{x:0,z:12},{manual:true});for(let i=0;i<25;i++)life.tick(.05,{group,pace});return town.position.z-5;};assert.ok(move(1.35,true)>move(.8,true)*1.4);assert.equal(move(1.35,false),move(.8,false));});
