import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';
import {createTownLife,newTownLife} from './town-life.mjs';
import {createPetCare,restoreCare} from './care.mjs';
import {newPetEntry,restorePetState,snapshotPetState} from './state.mjs';
import {actorDistance} from './actor-spacing.mjs';
import {restoreTogether,togetherWaiting,cancelOfflineTogether} from './together.mjs';
import {planWalkPair,beginWalkPlay,advanceWalkPlay,walkPlayReady,cancelWalkPlay} from './walk-play.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
function fixture(species='dog',place='home',size=1.3,weight=1.25){
 const p=newTownLife(place,place==='outside'?{x:0,z:3}:{x:0,z:.55},9),h=newTownLife(place,place==='outside'?{x:-1.5,z:3}:{x:-1.15,z:1.35},19),actors=()=>[{id:'pet',kind:'pet',species,size,weight,place:p.place,position:p.position},{id:'ta',kind:'person',size:1.6,place:h.place,position:h.position}],pet=createTownLife(p,{world,size:()=>size,actor:()=>actors()[0],actors}),person=createTownLife(h,{world,size:()=>1.4,actor:()=>actors()[1],actors}),care=createPetCare({energy:90,satiety:80,mood:90,traits:{active:1,social:1},rng:1},{real:true});
 const trip=restoreTogether({id:'walk:1',petId:'pet',personId:'ta',mode:'walk',shop:'outside',phase:'walk',sequence:0,point:{x:0,z:3}});
 const step=()=>{pet.tick(.05,{group:true,waiting:togetherWaiting(p,h,'outside')});person.tick(.05,{group:true,waiting:togetherWaiting(h,p,'outside')});if(p.place===h.place)assert.ok(Math.hypot(p.position.x-h.position.x,p.position.z-h.position.z)>=actorDistance(...actors())-1e-5);};
 return {p,h,pet,person,care,trip,step};
}
test('both largest cats and dogs walk actual door and street routes to separate free stops and change direction',()=>{for(const species of['cat','dog']){const f=fixture(species);for(const target of[{x:0,z:3},{x:3,z:7},{x:-5,z:5},{x:0,z:3}]){const pair=planWalkPair(f.pet,f.person,target,world);assert.ok(pair);assert.ok(Math.hypot(pair.pet.x-pair.person.x,pair.pet.z-pair.person.z)>=1.25);for(const [life,q]of[[f.pet,pair.pet],[f.person,pair.person]])life.go('outside',q,{manual:true});let i=0;for(;i<14000&&(f.p.goal||f.h.goal||f.p.place!=='outside'||f.h.place!=='outside');i++)f.step();assert.ok(i<14000,species+JSON.stringify({p:f.p,h:f.h}));assert.ok(Math.hypot(f.p.position.x-pair.pet.x,f.p.position.z-pair.pet.z)<.01);}assert.equal(planWalkPair(f.pet,f.person,{x:NaN,z:0},world),null);assert.equal(planWalkPair(f.pet,f.person,{x:1000,z:0},world),null);}});
test('street chase uses actual ball routes; preparation and transit do not count as completed play',()=>{for(const species of['cat','dog']){const f=fixture(species,'outside');assert.equal(beginWalkPlay(f.trip,f.pet,f.person,f.care,world,'play').accepted,true);f.care.tick(10,{home:false,interaction:false});assert.equal(f.care.state.task.time,0);assert.equal(f.care.state.toys.ball,0);const start={...f.p.position};let i=0,lead=0,rounds=new Set();for(;i<5000&&f.care.state.task?.outingId===f.trip.id;i++){const ball={...f.trip.play.ball};advanceWalkPlay(f.trip,f.pet,f.person,f.care,.05);assert.ok(world.segmentClear(ball,f.trip.play.ball));f.step();lead=Math.max(lead,Math.hypot(f.trip.play.ball.x-f.p.position.x,f.trip.play.ball.z-f.p.position.z));const before=f.care.state.task.time;const ready=walkPlayReady(f.trip,f.p,f.h);f.care.tick(.05,{interaction:ready});if(!ready&&f.care.state.task?.outingId===f.trip.id)assert.equal(f.care.state.task.time,before);rounds.add(f.trip.play.round);}assert.ok(i<5000,JSON.stringify(f));assert.deepEqual([...rounds].sort(),[1,2,3]);assert.ok(lead>.75,'The ball visibly rolls ahead of the body before it is caught');assert.ok(Math.hypot(f.p.position.x-start.x,f.p.position.z-start.z)>.3);assert.equal(f.care.state.toys.ball,1);assert.equal(f.care.state.relationships.you.play,1);assert.equal(f.care.state.recent.filter(x=>x.completed&&x.text.includes('追着')).length,1);for(let j=0;j<100;j++)f.care.tick(.05,{interaction:false});assert.equal(f.care.state.toys.ball,1);}});
test('cancelled chase earns no completed record; TA petting changes only its original bond after actual arrival',()=>{const f=fixture('cat','outside');assert.equal(beginWalkPlay(f.trip,f.pet,f.person,f.care,world,'play').accepted,true);for(let i=0;i<12;i++){advanceWalkPlay(f.trip,f.pet,f.person,f.care,.05);f.step();f.care.tick(.05,{interaction:walkPlayReady(f.trip,f.p,f.h)});}cancelWalkPlay(f.trip,f.care);assert.equal(f.care.state.task,null);assert.equal(f.care.state.toys.ball,0);assert.equal(f.care.state.recent.filter(x=>x.completed).length,0);assert.equal(beginWalkPlay(f.trip,f.pet,f.person,f.care,world,'pet',{source:'companion',actor:'ta',name:'阿秋'}).accepted,true);for(let i=0;i<3000&&f.care.state.task?.outingId===f.trip.id;i++){advanceWalkPlay(f.trip,f.pet,f.person,f.care,.05);f.step();f.care.tick(.05,{interaction:walkPlayReady(f.trip,f.p,f.h)});}assert.equal(f.care.state.relationships['companion:ta'].pet,1);assert.equal(f.care.state.relationships.you.pet,0);assert.ok(f.care.state.cooldown>0);f.care.cancel();f.trip.play=null;assert.equal(beginWalkPlay(f.trip,f.pet,f.person,f.care,world,'pet').accepted,false);assert.equal(f.care.state.relationships['companion:ta'].pet,1);});
test('original archive restores an in-progress ball and care task; long absence cancels without offline completion',()=>{const f=fixture('dog','outside');beginWalkPlay(f.trip,f.pet,f.person,f.care,world,'play');for(let i=0;i<50;i++){advanceWalkPlay(f.trip,f.pet,f.person,f.care,.05);f.step();f.care.tick(.05,{interaction:walkPlayReady(f.trip,f.p,f.h)});}const p=newPetEntry({species:'dog'},[],()=>.3,100000);p.care=f.care.snapshot();p.town=f.p;p.life.at=100000;f.trip.petId=p.id;const s=restorePetState({pets:[p],activePetId:p.id,resident:{id:'ta',town:f.h},together:f.trip},world,{at:100000}),again=restorePetState(snapshotPetState(s,{position:s.position,room:null,outdoor:null,evening:false}),world,{at:100500});assert.deepEqual(again.together.play,f.trip.play);assert.equal(again.pets[0].care.task.outingId,f.trip.id);assert.equal(again.pets[0].care.task.time,f.care.state.task.time);assert.equal(cancelOfflineTogether(again,100500),false);assert.equal(cancelOfflineTogether(again,160001),true);assert.equal(again.together,null);assert.equal(again.pets[0].care.task,null);assert.equal(again.pets[0].care.toys.ball,0);assert.equal(again.pets[0].career.balance,0);assert.equal(Object.keys(again.journal.days).length,0);assert.equal(restoreCare(p.care).task.outingId,f.trip.id);});

test('the observed second outing retries a street stop occupied by the companion without crossing its body',()=>{const f=fixture('dog','outside',1.18,1.22);f.pet.sync('outside',{x:-17,z:15.25},0,{manual:true});f.person.sync('outside',{x:-17.630601108893504,z:14.442565424706084},7.53,{manual:true});f.person.go('outside',{x:-17,z:14.65},{manual:true});let i=0;for(;i<1500&&f.h.goal;i++)f.step();assert.ok(i<1500,JSON.stringify(f.h));assert.ok(Math.hypot(f.p.position.x-f.h.position.x,f.p.position.z-f.h.position.z)>=1.024);});
