import {planWalkPair} from './walk-play.mjs?v=fg-4ea3c2dd79f75cae';
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&Math.abs(p.x)<100&&Math.abs(p.z)<100?{x:p.x,z:p.z}:null;
const count=n=>Number.isFinite(n)?Math.max(0,Math.min(1e6,n)):0;
export const WALK_KINDS={sniff:'闻闻路边',leaf:'看看落叶',flower:'看看小花',friend:'遇见朋友',shelter:'屋檐下避雨',shade:'阴凉处歇歇',wipe:'回家擦爪'};
export function restoreWalkMemory(raw){return {version:1,spots:(Array.isArray(raw?.spots)?raw.spots:[]).filter(x=>point(x?.point)&&WALK_KINDS[x.kind]&&x.kind!=='wipe').slice(-12).map(x=>({point:point(x.point),kind:x.kind,visits:count(x.visits),last:count(x.last),friendId:typeof x.friendId==='string'?x.friendId:''})),recent:(Array.isArray(raw?.recent)?raw.recent:[]).filter(x=>typeof x?.id==='string'&&WALK_KINDS[x.kind]&&typeof x.text==='string'&&Number.isFinite(x.at)).slice(-24).map(x=>({id:x.id.slice(0,140),kind:x.kind,text:x.text.slice(0,200),at:count(x.at)})),wetPaws:raw?.wetPaws===true};}
export function restoreWalkEvent(raw){return raw&&WALK_KINDS[raw.kind]&&typeof raw.id==='string'&&point(raw.pet)&&point(raw.person)&&['approach','doing'].includes(raw.phase)?{id:raw.id.slice(0,140),kind:raw.kind,phase:raw.phase,pet:point(raw.pet),person:point(raw.person),time:Math.min(10,count(raw.time)),friendId:typeof raw.friendId==='string'?raw.friendId:'',at:count(raw.at)}:null;}
export function walkHabitFacts(entry){const m=entry.walk||restoreWalkMemory(),spots=m.spots.filter(x=>x.visits>=3).sort((a,b)=>b.visits-a.visits);return {wetPaws:m.wetPaws,pace:(entry.care?.traits?.active||.5)>=.7?'喜欢往前探探，再回头等等你们':(entry.care?.traits?.bold||.5)<.35?'更喜欢靠近TA，慢慢走':'喜欢跟着你们舒服地散步',spots:spots.map(x=>({...x,label:WALK_KINDS[x.kind]})),recent:structuredClone(m.recent.slice(-8)).reverse(),detail:spots.length?'实际陪过几次以后，慢慢记住了喜欢停下来的地方。':'一起走过、停下来陪过以后，会慢慢长出自己的散步习惯。'};}
export function rememberWalk(entry,event,at,personName){const m=entry.walk||(entry.walk=restoreWalkMemory());if(m.recent.some(x=>x.id===event.id))return null;const name=entry.profile.name,words={sniff:'停下来认真闻了闻路边的气味',leaf:'停下来拨弄了一会儿飘落的小叶子',flower:'陪它看了看路边的小花',friend:'实际走到朋友身边，互相闻闻打过了招呼',shelter:'一起走到屋檐下，陪它避了一会儿雨',shade:'一起走到阴凉处，陪它歇了一会儿',wipe:'一起回到家，在门边擦干了它的小爪子'};const text='你和'+personName+'带着'+name+'，'+words[event.kind]+'。';m.recent.push({id:event.id,kind:event.kind,text,at});m.recent=m.recent.slice(-24);if(event.kind==='wipe')m.wetPaws=false;else {const old=m.spots.find(x=>x.kind===event.kind&&Math.hypot(x.point.x-event.pet.x,x.point.z-event.pet.z)<2);if(old){old.visits++;old.last=at;}else m.spots.push({point:{...event.pet},kind:event.kind,visits:1,last:at,friendId:event.friendId||''});m.spots=m.spots.slice(-12);}return text;}
export function walkShelters(world){return ['cafe','bakery','florist'].map(id=>({id,point:{x:world.building(id).approach.x,z:world.building(id).approach.z+1.6}})).filter(x=>world.walkable(x.point.x,x.point.z));}
export function weatherWalkKind(environment){return environment?.rain?'shelter':environment?.season===1&&!environment.rain&&!environment.snow&&environment.minute>=660&&environment.minute<1020?'shade':null;}
export function chooseWalkInterest(entry,{environment,random=Math.random,friends=[],forced,friendId}={}){if(forced&&['sniff','leaf','flower','friend','shelter','shade'].includes(forced))return {kind:forced,friendId:forced==='friend'?friendId||friends[0]?.id||'':''};const learned=(entry.walk?.spots||[]).filter(x=>x.visits>=3&&x.kind!=='shelter'&&x.kind!=='shade');if(learned.length&&random()<.45){const x=learned[Math.floor(random()*learned.length)];return {kind:x.kind,point:x.point,friendId:x.friendId};}const traits=entry.care?.traits||{};if(friends.length&&random()<.25+(traits.social||.5)*.4)return {kind:'friend',friendId:friends[Math.floor(random()*friends.length)].id};return {kind:entry.profile.species==='dog'&&random()<.35+(traits.bold||.5)*.4?'sniff':environment?.season===0?'flower':environment?.season===2||random()<.5?'leaf':'sniff'};}
// Every event starts by assigning two actual reachable stops; its timer begins
// only after both roots have arrived, including the friend's real doorway route.
export function beginWalkEvent(trip,entry,pet,person,world,{kind,point:target,friendId='',at=Date.now()}={}){if(!trip||trip.mode!=='walk'||!['walk','pause'].includes(trip.phase)||trip.play||trip.street||pet.state.place!=='outside'||person.state.place!=='outside')return null;const pair=planWalkPair(pet,person,target||pet.state.position,world,{bold:entry.care?.traits?.bold});if(!pair)return null;trip.sequence++;trip.phase='notice';trip.street={id:trip.id+':notice:'+trip.sequence,kind,phase:'approach',pet:pair.pet,person:pair.person,time:0,friendId,at};for(const[life,q]of[[pet,pair.pet],[person,pair.person]]){life.sync(life.state.place,life.state.position,life.state.heading,{manual:true});if(Math.hypot(q.x-life.state.position.x,q.z-life.state.position.z)>.15)life.go('outside',q,{manual:true});}return trip.street;}
export function advanceWalkEvent(event,pet,person,dt,friend){if(!event||!Number.isFinite(dt)||dt<=0)return false;const place=event.kind==='wipe'?'home':'outside';if(pet.place!==place||person.place!==place||pet.goal||person.goal)return false;if(event.kind==='friend'&&(!friend||friend.place!=='outside'||friend.goal||Math.hypot(friend.position.x-pet.position.x,friend.position.z-pet.position.z)>2.6))return false;if(event.phase==='approach'){event.phase='doing';event.time=0;}event.time+=Math.min(.1,dt);return event.time>=({friend:5,wipe:8,shelter:8,shade:8}[event.kind]||6);}
export function walkEventPose(event,species){const doing=event?.phase==='doing';return doing?{action:event.kind==='sniff'||event.kind==='friend'?'sniff':event.kind==='leaf'?'workSort':event.kind==='wipe'?'wipePaws':event.kind==='shelter'||event.kind==='shade'?'sit':'look',time:event.time,species}:null;}

export function walkFriendPoint(world,place){const a=world.building(place)?.approach;if(!a)return null;const point={x:Math.sign(a.x)*6,z:a.z+2.2};return world.walkable(point.x,point.z)&&world.path(a,point)?point:null;}
