export function createPetWardrobe(T,{pet,getState}){
 const root=new T.Group();root.name='pet-worn-accessory';pet.root.add(root);const items=new Map(),material=c=>new T.MeshStandardMaterial({color:c,roughness:.92,side:T.DoubleSide});
 const add=(g,geometry,color,position)=>{const m=new T.Mesh(geometry,material(color));m.position.fromArray(position);g.add(m);return m;};
 const scarf=new T.Group(),shape=new T.Shape();shape.moveTo(-.125,.04);shape.lineTo(.125,.04);shape.lineTo(0,-.13);shape.closePath();add(scarf,new T.ShapeGeometry(shape),'#a7b6c6',[0,0,0]);add(scarf,new T.SphereGeometry(.025,10,8),'#c7d0da',[0,.045,-.005]);items.set('bandana',scarf);
 const bow=new T.Group();for(const x of[-.06,.06]){const m=add(bow,new T.SphereGeometry(.06,12,8),'#bd8691',[x,0,0]);m.scale.set(1,.68,.36);}add(bow,new T.SphereGeometry(.026,10,8),'#9b6878',[0,0,.012]);items.set('bow',bow);
 const wreath=new T.Group();const ring=add(wreath,new T.TorusGeometry(.16,.009,6,32),'#b0b48e',[0,0,0]);ring.rotation.x=Math.PI/2;for(let i=0;i<7;i++){const a=i*Math.PI*2/7;for(let j=0;j<5;j++){const b=j*Math.PI*2/5,m=add(wreath,new T.SphereGeometry(.014,8,6),i%2?'#edd0c8':'#f8efe0',[Math.sin(a)*.16+Math.sin(b)*.018,.007,Math.cos(a)*.16+Math.cos(b)*.018]);m.scale.y=.5;}}items.set('wreath',wreath);
 for(const[id,g]of items){g.userData.accessory=id;root.add(g);g.visible=false;}
 const worldFrame=new T.Matrix4(),inverse=new T.Matrix4(),x=new T.Vector3(),y=new T.Vector3(),z=new T.Vector3();
 function sync(){const id=getState().furnishings?.wear,g=items.get(id);root.visible=!!g;for(const[k,m]of items)m.visible=k===id;if(!g||!pet.motion)return;const head=id==='wreath',bone=head?'head':'chest',p=head?[0,pet.species==='dog'?.80:.80,.16]:[0,.35,.31],a=pet.motion.attachment(bone,p),b=pet.motion.attachment(bone,[p[0]+.1,p[1],p[2]]),c=pet.motion.attachment(bone,[p[0],p[1]+.1,p[2]]);if(!a||!b||!c){root.visible=false;return;}x.copy(b).sub(a).normalize();y.copy(c).sub(a).normalize();z.crossVectors(x,y).normalize();y.crossVectors(z,x);worldFrame.makeBasis(x,y,z);worldFrame.scale(new T.Vector3().setScalar(pet.root.scale.x));worldFrame.setPosition(a);pet.root.updateMatrixWorld(true);inverse.copy(pet.root.matrixWorld).invert();g.matrix.multiplyMatrices(inverse,worldFrame);g.matrixAutoUpdate=false;}
 return {root,sync,snapshot:()=>({item:getState().furnishings?.wear||'',visible:root.visible}),dispose(){root.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});root.removeFromParent();}};
}
