import test from 'node:test';import assert from 'node:assert/strict';
import {createPetCareer}from './career.mjs';import{createPetCare,careSummary}from './care.mjs';import{chooseWorkHabit,fadeWorkHabits,WORK_HABITS}from './work-habits.mjs';import{snapshotPetState,restorePetState}from'./state.mjs';import{createPetWorld}from'../../art/pet-career/world-navigation.mjs';import{readFileSync}from'node:fs';
const people=[{key:'you',name:'你',position:{x:-.65,z:1.72}}];
function writer(id='bakery',seed=1){const body=createPetCare({energy:100,mood:100,satiety:80}),career=createPetCareer({rng:seed,selected:id});const ctx=()=>({care:body.state,room:id==='alley'?'alley':id});return{body,career,ctx};}
function work(f){assert.ok(f.career.request('invite',{},f.ctx()).accepted);for(let i=0;i<3;i++){while(f.career.state.job.phase==='working')f.career.tick(1,f.ctx());const e=f.career.summary().event;assert.ok(f.career.request('choose',{eventId:e.id,choice:e.options[0].id},f.ctx()).accepted);}if(f.career.summary().event?.kind==='deduction'){const e=f.career.summary().event;assert.ok(f.career.request('choose',{eventId:e.id,choice:'leave'},f.ctx()).accepted);}assert.ok(f.career.request('finish',{},f.ctx()).accepted);return f;}
function start(f){f.body.state.habitCooldown=0;f.body.cancel();f.body.state.energy=90;f.body.state.satiety=90;f.body.state.mood=90;for(let i=0;i<1500;i++){f.body.tick(1,{home:true,people,belongings:f.career.state});if(f.body.state.task?.kind==='habit')return f.body.state.task;if(f.body.state.task)f.body.cancel();}throw Error('actual idle picker did not select learned habit');}
test('only real accepted choices/completed work grow habits; selecting a job and waiting at home do not',()=>{const f=writer();f.career.request('select',{profession:'cafe'},f.ctx());for(let i=0;i<100;i++)f.career.tick(1,{care:f.body.state,room:'home'});assert.equal(f.career.summary().habits.length,0);f.career.request('select',{profession:'bakery'},f.ctx());work(f);assert.ok(f.career.state.habits.scores.bakery>.25);assert.equal(f.career.state.habits.scores.cafe,0);const before=f.career.snapshot();assert.equal(f.career.request('finish',{},f.ctx()).accepted,false);assert.deepEqual(f.career.snapshot(),before);});
test('an actual learned home habit walks first and is remembered only after it finishes',()=>{const f=work(writer()),t=start(f);assert.equal(t.habit,'bakery');assert.equal(t.phase,'walking');for(let i=0;i<15;i++)f.body.tick(1,{home:true});assert.ok(!f.body.state.recent.some(x=>x.type==='habit'));f.body.arrive();for(let i=0;i<12;i++)f.body.tick(1,{home:true});assert.equal(f.body.state.recent.filter(x=>x.type==='habit').length,1);assert.equal(f.body.state.habitCooldown,240);assert.equal(f.body.state.task,null);assert.equal(chooseWorkHabit(f.body.state,f.career.state,people,()=>0),null);});
test('hunger, fatigue, helpers, jobs and pauses take precedence over a habit',()=>{const f=work(writer());for(const patch of[{satiety:40},{energy:30},{mood:20},{helper:{id:'ta'}},{habitCooldown:20}]){const body={...f.body.snapshot(),energy:90,satiety:90,mood:90,habitCooldown:0,...patch};assert.equal(chooseWorkHabit(body,f.career.state,people,()=>0),null);}assert.equal(chooseWorkHabit({...f.body.state,habitCooldown:0},{...f.career.state,job:{id:'actual'}},people,()=>0),null);const t=start(f),before=f.body.snapshot();f.body.tick(20,{home:true,paused:true});assert.deepEqual(f.body.snapshot(),before);assert.equal(t.phase,'walking');});
test('reload keeps the actual unfinished habit and cancelling cannot invent a completed memory',()=>{const f=work(writer());start(f);const restored=createPetCare(f.body.snapshot());assert.equal(restored.state.task.habit,'bakery');assert.equal(restored.state.task.phase,'walking');restored.cancel();for(let i=0;i<12;i++)restored.tick(1,{home:true});assert.ok(!restored.state.recent.some(x=>x.type==='habit'));});
test('real rest days weaken other habits exactly once, active work survives; clock rewind does not grow them',()=>{const f=work(writer()),h=f.career.state.habits,before=h.scores.bakery;assert.ok(fadeWorkHabits(h,3));assert.equal(h.scores.bakery,before-.05);assert.equal(fadeWorkHabits(h,3),false);assert.equal(fadeWorkHabits(h,2),false);const held=h.scores.bakery;fadeWorkHabits(h,8,'bakery');assert.equal(h.scores.bakery,held);fadeWorkHabits(h,108);assert.equal(h.scores.bakery,0);});
test('the work writer migrates old actual resumes once without inventing new completed scenes',()=>{const f=work(writer()),raw=f.career.snapshot();delete raw.habits;const migrated=createPetCareer(raw);assert.ok(migrated.state.habits.scores.bakery>0);assert.equal(migrated.state.habits.scores.store,0);assert.deepEqual(createPetCareer(migrated.snapshot()).snapshot(),migrated.snapshot());assert.equal(migrated.state.recent.some(x=>x.type==='habit'),false);});
test('all seven professions map to existing poses and genuine work can learn the original five shop habits',()=>{for(const id of['bakery','store','florist','cafe','alley']){const f=work(writer(id));const t=start(f);assert.equal(t.habit,id);assert.equal(careSummary(f.body.state).activity,'正在'+WORK_HABITS[id].label);}assert.equal(Object.keys(WORK_HABITS).length,12);assert.ok(Object.values(WORK_HABITS).every(x=>['sniff','look','sit'].includes(x.pose)));});
test('canonical multi-pet/archive save isolates career habits and cooldowns',()=>{const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url)))),f=work(writer()),state=restorePetState(null,world);state.pets[0].career=f.career.snapshot();state.pets[0].care=f.body.snapshot();state.career=state.pets[0].career;state.care=state.pets[0].care;const saved=snapshotPetState(state,{position:state.position,room:'home',outdoor:null,evening:false}),again=restorePetState(saved,world),other=restorePetState(null,world);assert.deepEqual(again.career.habits,f.career.state.habits);assert.equal(other.career.habits.scores.bakery,0);});

test('stall keeping actual goods grows collecting more than selling; completed courier shifts leave their own habit',async()=>{const{writeHabitShift}=await import('./habits-test-helpers.mjs'),world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));const keep=writeHabitShift('stall',world),sell=writeHabitShift('stall',world,{keep:false}),courier=writeHabitShift('courier',world);assert.ok(keep.career.state.habits.scores.stall>sell.career.state.habits.scores.stall);assert.ok(courier.career.state.habits.scores.courier>.25);assert.equal(courier.career.state.habits.scores.stall,0);const t=start(keep);assert.equal(t.habit,'stall');assert.equal(t.stage,'fetch');assert.equal(keep.body.pickupToy(),false);keep.body.arrive();for(let i=0;i<2;i++)keep.body.tick(1,{home:true});assert.ok(keep.body.pickupToy());assert.equal(keep.body.state.task.stage,'carry');keep.body.arrive();for(let i=0;i<2;i++)keep.body.tick(1,{home:true});assert.ok(keep.body.deliverToy({x:-1.1,z:-.8}));assert.equal(keep.body.state.recent.filter(x=>x.type==='habit').length,1);assert.deepEqual(keep.body.state.toyPlaces.ball,{x:-1.1,z:-.8});assert.equal(keep.career.state.inventory.toy,1);});
test('successful snack re-invitation records pressure only once and fades on actual later days',()=>{let f;for(let seed=1;seed<2000;seed++){const x=writer('bakery',seed),first=x.career.request('invite',{},x.ctx());if(!first.accepted&&x.career.state.daily.declined&&x.career.request('bribe',{},x.ctx()).accepted){f=x;break;}}assert.ok(f);assert.equal(f.career.state.habits.pressure.bakery,.12);const h=structuredClone(f.career.state.habits);assert.equal(f.career.request('bribe',{},f.ctx()).accepted,false);assert.deepEqual(f.career.state.habits,h);fadeWorkHabits(f.career.state.habits,5);assert.equal(f.career.state.habits.pressure.bakery,0);});
test('first real-clock anchoring keeps learned work instead of treating clock migration as years of rest',()=>{const f=work(writer()),score=f.career.state.habits.scores.bakery;f.career.syncDay(f.body.state,{day:44,date:'2026-10-05'});assert.equal(f.career.state.habits.scores.bakery,score);assert.equal(f.career.state.habits.day,44);f.career.syncDay(f.body.state,{day:45,date:'2026-10-06'});assert.equal(f.career.state.habits.scores.bakery,score-.025);});
test('unsupported task tags cannot create a habit and genuine repeated home work respects exact saved metadata',()=>{assert.equal(createPetCare({task:{kind:'habit',habit:'fake',source:'self'}}).state.task,null);assert.equal(createPetCare({task:{kind:'habit',habit:'stall',source:'you'}}).state.task,null);const f=work(writer());start(f);f.body.state.task.spot={x:1.55,z:1.4};f.body.arrive();f.body.tick(1,{home:true});const restored=createPetCare(f.body.snapshot());for(const k of['habit','phase','spot','stage','time','target','source'])assert.deepEqual(restored.state.task[k],f.body.state.task[k]);assert.deepEqual(createPetCare(restored.snapshot()).snapshot(),restored.snapshot());});
test('opening a real parcel while carrying a habit toy waits for the physical carry to finish',async()=>{const{writeHabitShift}=await import('./habits-test-helpers.mjs'),world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url)))),f=writeHabitShift('stall',world);start(f);f.body.arrive();f.body.tick(1,{home:true});f.body.tick(1,{home:true});assert.ok(f.body.pickupToy());const before=f.body.snapshot();assert.equal(f.body.startBag('actual-opened',{x:0,z:.7},'curious').accepted,false);assert.deepEqual(f.body.snapshot(),before);});
