import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createPetCareer} from './career.mjs';import {createPetCare} from './care.mjs';import {PET_WORKPLACES,workRoom} from './workplaces.mjs';import {restoreClock,realTime} from '../fairy-garden/real-clock.mjs';import {restorePetState,snapshotPetState,petEntry,projectActivePet} from './state.mjs';import {createPetWorld} from '../../art/pet-career/world-navigation.mjs';import {newTownLife,roomDoor} from './town-life.mjs';import {recoverPetLife} from './routine.mjs';import {chooseWorkOption} from './work-autonomy.mjs';
const world=createPetWorld(JSON.parse(readFileSync(new URL('../../art/pet-career/outside.json',import.meta.url))));
const from=new Date(2026,9,5,10).getTime();
function learned(profession){let time=realTime(restoreClock(null,1,from),from-86400000);const body=createPetCare({mood:100,energy:100,satiety:90,traits:{bold:.7,social:.6,active:.5}}),career=createPetCareer({rng:1,balance:35,selected:profession,inventory:{snack:6}},{calendar:()=>time,getProfile:()=>({species:profession==='scent'?'dog':'cat'})});
 const context=()=>({care:body.state,room:career.destination(),position:career.destinationPoint()||{x:-.28,z:.55},name:'团子'});
 if(profession==='stall')assert.ok(career.request('stall-pack',{item:'snack',delta:1},{...context(),room:'home'}).accepted);
 assert.ok(career.request('invite',{},context()).accepted);
 for(let i=0;i<400&&career.state.job;i++){const j=career.state.job,e=career.summary().event;if(e){const choice=e.kind==='deduction'?'leave':e.options[0].id;assert.ok(career.request('choose',{eventId:e.id,choice,by:'你'},context()).accepted);}else if(j.phase==='ready')assert.ok(career.request('finish',{},context()).accepted);else career.tick(1,context());}
 assert.equal(career.state.job,null);assert.ok(career.summary().trialDone);const memory=structuredClone(career.state.firstTrial);time=realTime(restoreClock(null,1,from),from);career.syncDay(body.state,time);career.state.rng=1;body.state.energy=100;body.state.mood=100;
 if(profession==='stall')assert.ok(career.request('stall-pack',{item:'snack',delta:1},{...context(),room:'home'}).accepted);
 assert.ok(career.request('invite',{},context()).accepted);assert.equal(career.state.job.type,'shift');return {career,body,context,memory,time};
}
for(const {id}of PET_WORKPLACES)test(id+' formal shift handles its real choices, route phases and one settlement through the original writer',()=>{let {career,body,memory}=learned(id);const income=career.state.balance,ledger=career.state.ledger.length,history=career.state.history.length,jobId=career.state.job.id;let reloads=0;
 for(let i=0;i<300&&career.state.job;i++){const j=career.state.job,ctx={care:body.state,room:career.destination(),position:career.destinationPoint()||{x:-.28,z:.55},name:'团子'};if(j.phase==='choice'){career=createPetCareer(career.snapshot());reloads++;}career.tick(1,ctx);}
 assert.equal(career.state.job,null);assert.equal(career.state.history.length,history+1);assert.ok(career.state.balance>=income);if(id!=='stall')assert.equal(career.state.ledger.filter(x=>x.id==='income:'+jobId).length,1);assert.ok(reloads>=3);assert.deepEqual(career.state.firstTrial,memory);assert.equal(career.request('finish',{}, {care:body.state,room:workRoom(id)}).accepted,false);assert.deepEqual(createPetCareer(career.snapshot()).snapshot(),career.snapshot());assert.ok(career.state.ledger.length>=ledger);assert.ok(career.state.recent.some(x=>x.text.includes('团子拿了')));if(id==='alley')assert.equal(career.state.casebook.at(-1).conclusion,'leave');if(id==='courier')assert.equal(career.state.courier.log.at(-1).status,'delivered');});
for(const {id}of PET_WORKPLACES)test(id+' offline formal work actually follows doors and positions, brings its bag home and cannot repay on reload',()=>{const f=learned(id),room=workRoom(id),s=restorePetState({configured:true,clock:restoreClock(null,1,from),profile:{name:'团子',species:id==='books'?'cat':'dog',size:1.3},town:newTownLife(room,room==='home'?{x:-.28,z:.55}:roomDoor(room),17),care:f.body.snapshot(),career:f.career.snapshot()},world);s.pets[0].life.at=from;s.pets.push(petEntry({configured:true,profile:{name:'栗子'},career:{balance:72},life:{at:from+20*60000},town:newTownLife('home',{x:1,z:1})},'other'));const saved=snapshotPetState(s,{position:s.position,room,outdoor:null,evening:false}),birthday=structuredClone(saved.pets[0].birth),oldIncome=saved.pets[0].career.balance,jobId=saved.pets[0].career.job.id;
 recoverPetLife(saved,world,from+20*60000);const p=saved.pets[0];assert.equal(p.career.job,null);assert.equal(p.town.place,'home');assert.ok(p.career.balance>=oldIncome);if(id!=='stall')assert.equal(p.career.ledger.filter(x=>x.id==='income:'+jobId).length,1);assert.equal(saved.pets[1].career.balance,72);assert.deepEqual(p.birth,birthday);const result=structuredClone(saved);recoverPetLife(saved,world,from+20*60000);assert.deepEqual(saved,result);recoverPetLife(saved,world,from);recoverPetLife(saved,world,from+20*60000);assert.deepEqual(saved,result);assert.equal(p.career.shopping.log.length,0);});
test('a short offline absence spends time walking before working and preserves partial progress',()=>{const f=learned('bakery'),s=restorePetState({configured:true,clock:restoreClock(null,1,from),town:newTownLife('bakery',roomDoor('bakery'),17),care:f.body.snapshot(),career:f.career.snapshot()},world);s.pets[0].life.at=from;const p=s.pets[0],before={...p.town.position},balance=p.career.balance;recoverPetLife(s,world,from+2000);assert.ok(Math.hypot(p.town.position.x-before.x,p.town.position.z-before.z)>.1);assert.equal(p.career.job.time,0);assert.equal(p.career.balance,balance);recoverPetLife(s,world,from+60000);assert.ok(!p.career.job||p.career.job.index>0);});
test('pause, wrong room and wrong physical position never choose or pay a formal job',()=>{const f=learned('bakery');for(let i=0;i<18;i++)f.career.tick(1,f.context());assert.equal(f.career.state.job.phase,'choice');const pending=f.career.snapshot();for(const extra of[{paused:true},{room:'home'}]){for(let i=0;i<30;i++)f.career.tick(1,{...f.context(),...extra});assert.deepEqual(f.career.snapshot(),pending);}const c=createPetCareer(pending,{workStation:()=>({point:{x:1,z:1}})});for(let i=0;i<30;i++)c.tick(1,{...f.context(),position:{x:-2,z:-2}});assert.deepEqual(c.snapshot(),pending);});
test('an exhausted formal worker stops by itself without issuing an unfinished wage',()=>{const f=learned('bakery'),balance=f.career.state.balance;f.body.state.energy=17;const event=f.career.tick(1,f.context());assert.ok(event.automatic&&event.stopped);assert.equal(f.career.state.job,null);assert.equal(f.career.state.balance,balance);assert.equal(f.career.state.daily.closed,true);});
test('choices use temperament and energy while reluctant market goods remain with their owner',()=>{const care=createPetCare({energy:30,traits:{social:1}}).state,e={options:[{id:'social',trait:'social'},{id:'rest',energy:5}]};assert.equal(chooseWorkOption({},e,care,()=>.8).id,'rest');assert.equal(chooseWorkOption({profession:'stall',index:1,market:{cursor:0,offers:[{reluctant:true}]}},{options:[{id:'sell'},{id:'keep'}]},care,()=>0).id,'keep');});
test('mobile career shell retains its one scroll body and both safe areas while explaining formal delegation',async()=>{const {readFile}=await import('node:fs/promises'),s=await readFile(new URL('../../js/fairy-garden.js',import.meta.url),'utf8'),i=s.indexOf('function PetPanel('),j=s.indexOf('function PetNote(',i);assert.ok(i>=0&&j>i);const shell=s.slice(i,j);assert.equal((shell.match(/overflow-y-auto/g)||[]).length,1);assert.match(shell,/COMPOSER_PAD_BOTTOM/);assert.match(s,/h\(Head,/);assert.match(s,/正式上班会按性格和精神自己处理小事/);});
test('the next agreed weekday starts a learned profession offline, finishes once and keeps the original willingness and daily gates',()=>{const f=learned('bakery');for(let i=0;i<200&&f.career.state.job;i++)f.career.tick(1,f.context());f.career.state.rng=1;assert.ok(f.career.request('schedule',{shift:'morning',weekend:false},f.context()).accepted);const s=restorePetState({configured:true,clock:restoreClock(null,1,from),town:newTownLife('home',{x:-.28,z:.55},17),care:{...f.body.snapshot(),energy:100,satiety:90,bowl:100},career:f.career.snapshot()},world);s.pets[0].life.at=from;const old=s.pets[0].career.ledger.length,to=from+25*3600000;recoverPetLife(s,world,to);const p=s.pets[0];assert.equal(p.career.job,null);assert.equal(p.career.ledger.length,old+1);assert.equal(p.career.daily.closed,true);assert.equal(p.career.shopping.log.length,0);assert.equal(p.town.place,'home');const saved=structuredClone(s);recoverPetLife(s,world,to);assert.deepEqual(s,saved);});
