import {createHomeSouvenirs,homeSouvenirs} from '../../apps/pets/home-souvenirs.mjs?v=fg-f330d135f2ad1c03';
import {YOU_SPOT} from '../../apps/pets/initiative.mjs?v=fg-f330d135f2ad1c03';
import {createPetCareer} from '../../apps/pets/career.mjs?v=fg-f330d135f2ad1c03';
import {moodFromCare} from '../pet-house/pet-mood.mjs?v=fg-f330d135f2ad1c03';
import {createHousemate} from '../../apps/pets/housemate.mjs?v=fg-f330d135f2ad1c03';
import {turnPet} from '../../apps/pets/movement.mjs?v=fg-f330d135f2ad1c03';
import {createPetCare,careSummary} from '../../apps/pets/care.mjs?v=fg-f330d135f2ad1c03';
import {createPetHome} from '../../apps/pets/home.mjs?v=fg-f330d135f2ad1c03';
import * as T from 'three';
import {CAT_PALETTES} from '../pet-house/cat-dye.mjs?v=fg-f330d135f2ad1c03';
import {restorePetState,snapshotPetState,petProfile,bodyWidth,PET_LIMIT,newPetEntry,projectActivePet} from '../../apps/pets/state.mjs?v=fg-f330d135f2ad1c03';
import {createPetCamera} from '../pet-house/pet-camera.mjs?v=fg-f330d135f2ad1c03';
import {GLTFLoader} from '../../apps/fairy-garden/vendor/GLTFLoader.js?v=fg-f330d135f2ad1c03';
import {DRACOLoader} from '../../apps/fairy-garden/vendor/DRACOLoader.js?v=fg-f330d135f2ad1c03';
import {createMapGesture,orthographicPanDelta} from '../../apps/fairy-garden/view-controls.mjs?v=fg-f330d135f2ad1c03';
import {loadPetCompanion,mountPetControls} from '../pet-house/pet-companion.mjs?v=fg-f330d135f2ad1c03';
import {createPetWorld} from './world-navigation.mjs?v=fg-f330d135f2ad1c03';
const read=async url=>{const r=await fetch(new URL(url,import.meta.url));if(!r.ok)throw Error('场景文件 '+r.status);return r.json();};
const layout=await read('./outside.json?v=fg-f330d135f2ad1c03'),world=createPetWorld(layout);
const view=document.getElementById('view'),loading=document.getElementById('loading'),labels=document.getElementById('door-labels');
const title=document.querySelector('h1'),subtitle=document.getElementById('subtitle'),back=document.getElementById('back'),enterButton=document.getElementById('enter');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;view.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#eee8dc');
const camera=new T.OrthographicCamera(-20,20,20,-20,.1,600);
const hemi=new T.HemisphereLight('#fff1dc','#c2ae8e',2.35);scene.add(hemi);
const key=new T.DirectionalLight('#fff1da',3);key.position.set(-15,28,15);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-38,right:38,top:38,bottom:-38,far:150});key.shadow.normalBias=.035;scene.add(key);
const fill=new T.DirectionalLight('#fff8eb',1.2);fill.position.set(20,30,20);scene.add(fill);
const studio=new T.Mesh(new T.PlaneGeometry(500,500),new T.MeshStandardMaterial({color:'#eee8dc',roughness:1}));studio.rotation.x=-Math.PI/2;studio.position.y=-.29;studio.receiveShadow=true;scene.add(studio);
const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath(new URL('../../apps/fairy-garden/vendor/draco/',import.meta.url).href);loader.setDRACOLoader(draco);
const toWeb=p=>new T.Vector3(p[0],p[2],-p[1]);
const host=location.pathname.includes('/apps/pets/')&&window.parent!==window&&window.parent.FairyGardenHostFor?.(window);
let career,housemate,care,homeCare,souvenirs,carePaused=false,previewProfile,petState,dye,customizing=false,saveFailed=false,previewScene,previewCamera;let shapeMeshes=[];const household=new Map();let adding=false,draftSession=null;
const sessionKey='lisa-pet-street-preview-v1';let raw;try{raw=JSON.parse(sessionStorage.getItem(sessionKey));}catch{}
if(host){petState=restorePetState(host.load().worlds?.pets,world);raw=petState;care=createPetCare(petState.care);career=createPetCareer(petState.career);}
let restored=world.restore(raw),position={...restored.position},pan={...position},zoom=1.6,follow=true,overview=false,heading=0,room=null,outdoor=restored.outdoor,roomLayout,activeModel,outsideModel,cat,petRoot,motion,rig,pet,petControls,busy=false,ready=false,path=[],destination='',activeZone='',lastTime=0,settling=0;
const requested=host?null:new URLSearchParams(location.search).get('scene');
if(world.building(requested)&&restored.room!==requested){position={...world.building(requested).approach};pan={...position};restored.room=null;}
if(requested==='outside'||requested==='park')restored.room=null;
let cameraControls;const cameraHost=document.getElementById('scene-camera');
let evening=restored.evening,indoorOrbit={theta:0,phi:0};
function save(force=false){if(host)syncHousehold();if(career){petState.career=career.snapshot();petState.day=career.state.day;}if(care)petState.care=care.snapshot();if(host&&customizing&&force!==true)return true;if(host){try{const snapshot=snapshotPetState(petState,{position,room,outdoor,evening});if(!host.save(snapshot,'pets'))throw Error('没有保存成功');saveFailed=false;return true;}catch(e){saveFailed=true;note('进度还没有保存成功','请留在这里重试，保存成功后再离开。');return false;}}try{sessionStorage.setItem(sessionKey,JSON.stringify({position,room,outdoor,evening}));}catch{}}
function applyProfile(value){homeCare?.resetPose();const next=petProfile(value);petState.profile=next;pet.select(next.species);cat=pet.model;rig=pet.rig;dye=pet.dye;if(customizing){pet.motion?.dispose();motion=null;}dye?.set(next.look);for(const {mesh,original,height}of shapeMeshes){const attr=mesh.geometry.attributes.position;for(let i=0;i<attr.count;i++)attr.setX(i,bodyWidth(original[i*3],original[i*3+1],original[i*3+2],height,next.weight));attr.needsUpdate=true;mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere();}petRoot.scale.setScalar(next.size);if(!customizing){if(room==='home'){homeCare.begin(activeModel);motion=pet.motion;}else if(room)placeIndoor();else setOutdoorPet();}draw();return next;}
function customize(on){homeCare?.resetPose();if(on&&!customizing&&!adding)previewProfile=structuredClone(petState.profile);customizing=!!on;document.body.classList.toggle('customizing',customizing);path=[];destination='';settling=0;motion?.dispose();motion=null;if(customizing){for(const x of household.values())x.pet.root.visible=false;petRoot.visible=true;if(!previewScene){previewScene=new T.Scene();previewScene.background=new T.Color('#eee8dc');previewScene.add(new T.HemisphereLight('#fff4e6','#b9bdad',2.4));const light=new T.DirectionalLight('#fff4e0',3);light.position.set(-2,4,4);previewScene.add(light);previewCamera=new T.OrthographicCamera(-2,2,2,-2,.1,30);}previewScene.add(petRoot);petRoot.position.set(0,0,0);petRoot.rotation.y=0;}else{scene.add(petRoot);if(room==='home'){for(const x of household.values())x.pet.root.visible=true;homeCare.begin(activeModel);motion=pet.motion;syncSouvenirs();}else if(room)placeIndoor();else setOutdoorPet();}draw();}
function commitProfile(value){if(adding)return commitAddition(value);const previous=structuredClone(petState);previous.profile=previewProfile||previous.profile;const profile=applyProfile(value);petState.configured=true;if(!save(true)){petState.profile=previous.profile;petState.configured=previous.configured;const entry=household.get(petState.activePetId).entry;entry.profile=previous.profile;entry.configured=previous.configured;applyProfile(previous.profile);return false;}return profile;}
const STATIONS=[null,{bowl:{x:.65,z:2.08},rest:{x:1.05,z:.48},rug:{x:1.15,z:1.2},watch:{x:1.5,z:.05},color:'#d4b6af'},{bowl:{x:-1.55,z:2.05},rest:{x:-1.3,z:.05},rug:{x:-1.3,z:.5},watch:{x:-1.4,z:-.25},color:'#bfb4ce'},{bowl:{x:.55,z:-.62},rest:{x:.05,z:-.75},rug:{x:.15,z:-.65},watch:{x:.15,z:-.65},color:'#c7b58d'}];
const getPeople=()=>[{key:'you',name:'你',position:YOU_SPOT},...(housemate?.snapshot().visible?[{key:'companion:'+housemate.person.id,id:String(housemate.person.id),name:housemate.person.name,position:housemate.snapshot().position}]:[])];
function shapeFor(model){const meshes=[];model.root.traverse(mesh=>{if(mesh.isMesh){const original=mesh.geometry.attributes.position.array.slice(),h=new T.Box3().setFromBufferAttribute(mesh.geometry.attributes.position);meshes.push({mesh,original,height:h.max.y-h.min.y});}});return meshes;}
function setSessionLook(session,value){session.home?.resetPose();const next=petProfile(value);session.pet.select(next.species);session.pet.dye.set(next.look);for(const {mesh,original,height}of session.shapes){const attr=mesh.geometry.attributes.position;for(let i=0;i<attr.count;i++)attr.setX(i,bodyWidth(original[i*3],original[i*3+1],original[i*3+2],height,next.weight));attr.needsUpdate=true;mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere();}session.pet.root.scale.setScalar(next.size);return next;}
function makeSession(entry,model){const session={entry,pet:model,care:createPetCare(entry.care),career:createPetCareer(entry.career),shapes:shapeFor(model)};setSessionLook(session,entry.profile);scene.add(model.root);const found=petState.pets.findIndex(p=>p.id===entry.id),slot=found<0?petState.pets.length:found,station=STATIONS[slot];if(station&&!session.care.state.position){session.care.state.position={...station.rug};session.care.state.toyPlaces={ball:{x:station.rug.x+.12,z:station.rug.z+.22},mouse:{x:station.rug.x-.18,z:station.rug.z+.12}};}session.home=createPetHome(T,{scene,pet:model,care:session.care,onNotice:(a,b)=>note(entry.profile.name+' · '+a,b),onSave:save,draw,getPeople,station,getBelongings:()=>session.career.state,getOtherPets:()=>[...household.values()].filter(x=>x!==session).map(x=>({position:{x:x.pet.root.position.x,z:x.pet.root.position.z},size:x.pet.root.scale.x,visible:x.pet.root.visible}))});return session;}
function syncHousehold(){for(const session of household.values()){if(adding&&session===draftSession)continue;session.entry.care=session.care.snapshot();session.entry.career=session.career.snapshot();}const a=household.get(petState.activePetId);if(a&&!adding){a.entry.profile=petProfile(petState.profile);a.entry.configured=petState.configured;a.entry.care=care.snapshot();a.entry.career=career.snapshot();projectActivePet(petState);}}
function activateSession(session){pet=session.pet;petRoot=pet.root;cat=pet.model;rig=pet.rig;dye=pet.dye;care=session.care;career=session.career;homeCare=session.home;shapeMeshes=session.shapes;petState.activePetId=session.entry.id;projectActivePet(petState);motion=pet.motion;}
function syncSouvenirs(){souvenirs?.dispose();souvenirs=room==='home'?createHomeSouvenirs(T,{model:activeModel,career:career.state,care:care.state,ballObject:homeCare.toyObject('ball'),boxObject:homeCare.boxObject()}):null;}
function rosterView(){syncHousehold();return {limit:PET_LIMIT,activePetId:petState.activePetId,pets:petState.pets.map(p=>({id:p.id,profile:structuredClone(p.profile),summary:careSummary(household.get(p.id).care.state),atHome:room==='home'||p.id!==petState.activePetId}))};}
function selectPet(id){if(!host||customizing||busy||saveFailed||!household.has(id))return {accepted:false,text:'先保存当前进度，再换到另一只。'};if(id===petState.activePetId)return {accepted:true};if(room&&room!=='home'||path.length)return {accepted:false,text:'先回家，或在街区停下来，再换同行的小家伙。'};syncHousehold();const old=petState.activePetId;activateSession(household.get(id));if(!save()){activateSession(household.get(old));return {accepted:false,text:'切换没有保存成功，先重试保存。'};}if(room==='home')syncSouvenirs();else{for(const x of household.values())x.pet.root.visible=x.pet===pet;setOutdoorPet();}host.selectionChanged?.();refresh();draw();return {accepted:true,text:'现在陪着'+petState.profile.name+'。'};}
async function beginAdd(){if(!host||customizing||busy||saveFailed||petState.pets.length>=PET_LIMIT)return {accepted:false,text:'这一档先住四只小家伙。'};if(room!=='home')return {accepted:false,text:'先一起回家，再迎接新的小家伙。'};if(!save())return {accepted:false,text:'先保存当前进度，再迎接新的小家伙。'};busy=true;try{const entry=newPetEntry({species:'cat',name:'新来的猫猫'},petState.pets),model=await loadPetCompanion(T,loader,{persist:false,compressedMask:true});draftSession=makeSession(entry,model);draftSession.previousId=petState.activePetId;adding=true;pet=draftSession.pet;petRoot=pet.root;cat=pet.model;rig=pet.rig;dye=pet.dye;shapeMeshes=draftSession.shapes;previewProfile=structuredClone(petState.profile);customize(true);petState.profile=entry.profile;return {accepted:true,profile:structuredClone(entry.profile)};}catch(e){note('暂时没能迎接它','请留在家里重试。');return {accepted:false,text:e.message};}finally{busy=false;}}
function commitAddition(value){const previousId=draftSession.previousId,entry=draftSession.entry;entry.profile=setSessionLook(draftSession,value);entry.configured=true;petState.pets.push(entry);household.set(entry.id,draftSession);adding=false;activateSession(draftSession);if(!save(true)){household.delete(entry.id);petState.pets.pop();adding=true;activateSession(household.get(previousId));pet=draftSession.pet;petRoot=pet.root;cat=pet.model;rig=pet.rig;dye=pet.dye;shapeMeshes=draftSession.shapes;petState.profile=entry.profile;return false;}draftSession=null;previewProfile=entry.profile;host.selectionChanged?.();return entry.profile;}
function cancelProfile(){if(adding){const previousId=draftSession.previousId;customizing=false;document.body.classList.remove('customizing');draftSession.home.dispose();draftSession.pet.dispose();draftSession=null;adding=false;activateSession(household.get(previousId));for(const x of household.values())x.pet.root.visible=true;draw();}else{applyProfile(previewProfile||petState.profile);customize(false);}return true;}
function note(a,b){document.getElementById('zone-title').textContent=a;document.getElementById('zone-text').textContent=b;}
function shade(root){root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});}
function clearModel(root){root.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}});}
function applyLight(){hemi.color.set(evening?'#d4dcf3':'#fff1dc');hemi.intensity=evening?1.1:2.35;key.color.set(evening?'#b8cbff':'#fff1da');key.intensity=evening?.65:3;fill.color.set(evening?'#ffdab6':'#fff8eb');fill.intensity=evening?.65:1.2;const b=document.getElementById('light');b.textContent=evening?'白天':'傍晚';b.setAttribute('aria-pressed',String(evening));b.setAttribute('aria-label',evening?'切换到白天':'切换到傍晚');}
function refresh(){const name=document.getElementById('selected-pet');if(name){name.hidden=!host||customizing;name.textContent=petState?.profile.name||'';}const bar=document.getElementById('home-actions');if(bar){bar.hidden=!host||room!=='home'||customizing;bar.querySelector('[data-care=rest]').textContent=care?.state.task?.kind==='sleep'?'叫醒':'休息';for(const b of bar.querySelectorAll('button'))b.disabled=busy||saveFailed||carePaused;}title.textContent=room?world.building(room).title:layout.title;document.title=title.textContent+' · 宠物小世界';subtitle.textContent=room?'从门口进来的小屋':'点地面散步 · 拖动画面';back.textContent=room?'出门':pet?.species==='dog'?'跟着狗':'跟着猫';back.setAttribute('aria-label',room?'出门回到街区':pet?.species==='dog'?'回到狗狗身边':'回到猫猫身边');labels.hidden=!!room;const near=world.nearest(position);enterButton.hidden=!!room||!near||near.distance>.65;enterButton.disabled=busy;enterButton.textContent=near?'走进'+near.building.title:'走进屋里';back.disabled=busy;view.setAttribute('aria-busy',String(busy));}
function setOutdoorPet(){motion?.dispose();petRoot.position.set(position.x,world.ground(position.x,position.z)+.001,position.z);petRoot.rotation.y=heading;motion=pet.bind({ground:world.ground,matchSpeed:true});motion.update(0,0);}
function placeIndoor(){homeCare?.resetPose();petRoot.position.copy(toWeb(roomLayout.cat.position));petRoot.rotation.y=roomLayout.cat.yaw;cat.updateMatrixWorld(true);if(pet)motion=pet.bind({ground:()=>petRoot.position.y});if(host&&room==='home'){for(const session of household.values()){session.pet.root.visible=true;session.home.begin(activeModel);}housemate?.begin();syncSouvenirs();}else if(host){for(const session of household.values())session.pet.root.visible=session.pet===pet;}}
function souvenirLabels(){const el=document.getElementById('home-souvenirs');if(!el)return;el.hidden=room!=='home'||customizing||!souvenirs;if(el.hidden)return;const facts=souvenirs.sync(),markers=souvenirs.markers(camera,innerWidth,innerHeight);for(const b of el.querySelectorAll('button')){const m=markers.find(x=>x.id===b.dataset.souvenir);b.hidden=!m?.visible;if(!m)continue;b.textContent=b.dataset.souvenir==='bread'?'面包篮 · '+facts.breadBasket.count:b.dataset.souvenir==='ball'?facts.ownBall.name:b.dataset.souvenir==='box'?'自己的小纸箱':b.dataset.souvenir==='flowers'?'小花瓶 · '+facts.flowerVase.flowers:'第一份工作';b.style.left=Math.max(58,Math.min(innerWidth-58,m.x))+'px';b.style.top=Math.max(85,Math.min(innerHeight-230,m.y))+'px';b.disabled=carePaused||busy||saveFailed;}}
function updateCamera(){
 const aspect=innerWidth/innerHeight;
 if(!room){const width=(aspect<1?(overview?40:10):(overview?48:12)*aspect)/zoom,height=width/aspect;camera.left=-width/2;camera.right=width/2;camera.top=height/2;camera.bottom=-height/2;const distance=Math.max(75,height*1.5);camera.position.set(pan.x+distance*.6,distance*.75,pan.z+distance*.85);camera.lookAt(pan.x,0,pan.z);camera.far=Math.max(250,distance*4);}
 else if(cameraControls){cameraControls.update();return;}else {const target=toWeb(roomLayout.camera.target),pos=toWeb(roomLayout.camera.position);const span=roomLayout.camera.scale/Math.min(1,aspect)/zoom;camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;const spherical=new T.Spherical().setFromVector3(pos.sub(target));spherical.theta+=indoorOrbit.theta;spherical.phi+=indoorOrbit.phi;spherical.radius*=Math.max(1,1/zoom);camera.position.copy(target).add(new T.Vector3().setFromSpherical(spherical));camera.lookAt(target);camera.far=250;}
 camera.updateProjectionMatrix();camera.updateMatrixWorld();
 for(const b of layout.buildings){const button=document.getElementById('door-'+b.id),v=new T.Vector3(b.x,5.6,b.z+3).project(camera);button.style.left=((v.x+1)*innerWidth/2)+'px';button.style.top=((1-v.y)*innerHeight/2)+'px';const px=(v.x+1)*innerWidth/2,py=(1-v.y)*innerHeight/2;button.hidden=room!==null||v.z<-1||v.z>1||px<55||px>innerWidth-55||py<120||py>innerHeight-85;button.disabled=busy;}
}
async function enter(id){
 if(customizing||saveFailed||busy||room||!world.canEnter(position,id))return false;
 const b=world.building(id);busy=true;path=[];destination='';settling=0;lastTime=0;refresh();loading.textContent='走进'+b.title+'…';loading.hidden=false;
 try{
  const [file,inside]=await Promise.all([loader.loadAsync(new URL(b.interior,import.meta.url).href),read(b.layout)]);
  if(host&&id==='home'&&!housemate&&host.companion?.()){try{housemate=await createHousemate({scene,host,care,home:homeCare,notice:note,save,getPets:()=>[...household.values()],getActiveId:()=>petState.activePetId});}catch(e){console.error(e);}}
  outdoor={position:{...position},heading,pan:{...pan},zoom,follow,overview};motion?.dispose();motion=null;outsideModel.visible=false;activeModel=file.scene;shade(activeModel);scene.add(activeModel);room=id;roomLayout=inside;if(career&&['bakery','florist'].includes(id))career.request('select',{profession:id},{care:care.state,room});zoom=1;indoorOrbit={theta:0,phi:0};gesture.setZoom(1);placeIndoor();cameraHost.hidden=false;cameraControls=createPetCamera(T,{camera,view,position:toWeb(inside.camera.position),target:toWeb(inside.camera.target),scale:inside.camera.scale,getCat:()=>petRoot,getName:()=>pet.species==='dog'?'狗狗':'猫咪',draw,onTap:e=>tap(e.clientX,e.clientY),controlsHost:cameraHost});activeZone='';note(b.title,'点家具看看 · 点「出门」回街区');history.replaceState(null,'','?scene='+id);save();return true;
 }catch(e){console.error(e);note('暂时没能进屋','还在原来的门口，可以再试一次。');return false;}
 finally{busy=false;loading.hidden=true;refresh();draw();}
}
function leave(){if(busy||saveFailed||!room)return;housemate?.leave();if(host){for(const session of household.values()){session.home.leave();session.pet.root.visible=session.pet===pet;}}else homeCare?.leave();souvenirs?.dispose();souvenirs=null;cameraControls?.dispose();cameraControls=null;cameraHost.hidden=true;bindOutdoorGestures();scene.remove(activeModel);clearModel(activeModel);activeModel=outsideModel;outsideModel.visible=true;position={...outdoor.position};pan={...outdoor.pan};zoom=outdoor.zoom;follow=outdoor.follow;overview=outdoor.overview===true;heading=outdoor.heading;room=null;roomLayout=null;activeZone='';settling=0;setOutdoorPet();gesture.setZoom(zoom);note('回到门口','接着走走，也可以去旁边的店。');history.replaceState(null,'','?scene=outside');save();refresh();draw();}
function goTo(point,id=''){
 if(customizing||saveFailed||busy||room||!ready)return false;const route=world.path(position,point);if(!route){note('这里暂时走不过去','点点道路或草地试试。');return false;}path=route;destination=id;follow=true;overview=false;pan={...position};gesture.setZoom(1.6);settling=1;note(id?'去'+world.building(id).title:'散散步',id?'沿路走到门口，再走进去。':'点门牌可以去店里。');draw();return true;
}
function advance(dt){
 if(customizing||carePaused||saveFailed||!motion||busy)return;dt=Math.max(0,Math.min(.05,dt));if(career){const event=career.tick(dt,{care:care.state,room});if(event?.shopping){const bought=careerAction('checkout');note('它自己的小决定',bought.text);}else if(event){save();host.openCareer?.();}}if(room){if(host&&room==='home'){for(const session of household.values())if(session.career.state.shopping.trip?.phase==='packed'){const unpacked=careerAction('unpack',{},session);note(session.entry.profile.name+'带回家的小袋子',unpacked.text);if(saveFailed)return;}housemate?.tick(dt);for(const session of household.values()){session.home.tick(dt);if(session.career!==career)session.career.tick(dt,{care:session.care.state,room:'home'});}souvenirs?.sync();refresh();}else{care?.tick(dt);if(care)pet.setMood(moodFromCare(care.state));motion.update(dt,0);}return;}care?.tick(dt);if(care)pet.setMood(moodFromCare(care.state));let speed=0;
 if(path.length){const q=path[0],dx=q.x-position.x,dz=q.z-position.z,d=Math.hypot(dx,dz);speed=1.1*petRoot.scale.x;const turn=turnPet(heading,Math.atan2(dx,dz),dt);heading=turn.heading;const step=turn.canMove?Math.min(d,speed*dt):0;if(!step)speed=0;if(d>.001){position.x+=dx/d*step;position.z+=dz/d*step;}if(d<=step+.002)path.shift();if(!path.length){speed=0;settling=.65;save();if(destination){const id=destination;destination='';void enter(id);}}}
 petRoot.position.set(position.x,world.ground(position.x,position.z)+.001,position.z);petRoot.rotation.y=heading;motion.update(dt,speed,0,path.length>0);if(follow&&(path.length||settling>0)){pan.x=T.MathUtils.damp(pan.x,position.x,4,dt);pan.z=T.MathUtils.damp(pan.z,position.z,4,dt);}settling=Math.max(0,settling-dt);refresh();
}
let pending=false;function draw(){if(pending||document.hidden)return;pending=true;requestAnimationFrame(time=>{pending=false;const dt=lastTime?Math.min(.05,(time-lastTime)/1000):0;lastTime=time;advance(dt);if(customizing){const h=Math.max(1,innerHeight*.38),aspect=innerWidth/h,span=1.7;previewCamera.left=-span*aspect/2;previewCamera.right=span*aspect/2;previewCamera.top=span/2;previewCamera.bottom=-span/2;previewCamera.position.set(1,1.25,3.4);previewCamera.lookAt(0,.5,0);previewCamera.updateProjectionMatrix();renderer.setViewport(0,innerHeight-h,innerWidth,h);renderer.render(previewScene,previewCamera);}else{renderer.setViewport(0,0,innerWidth,innerHeight);updateCamera();souvenirLabels();renderer.render(scene,camera);}if(!carePaused&&(path.length||settling>0||(career?.state.job?.phase==='working'&&room===(career.state.job.profession||'bakery'))||(host&&room==='store'&&career?.state.shopping.enabled&&!career.state.job&&career.state.shopping.lastDay<career.state.day&&career.state.shopping.trip?.phase!=='packed')||(host&&room==='home'&&!customizing)||(!customizing&&pet?.animating)))draw();else lastTime=0;});}
function resize(){renderer.setSize(innerWidth,innerHeight);draw();}window.addEventListener('resize',resize);
const ray=new T.Raycaster(),pointer=new T.Vector2();
function screenRay(x,y){pointer.set(x/innerWidth*2-1,1-y/innerHeight*2);ray.setFromCamera(pointer,camera);return ray;}
function activateSouvenir(id){if(!id||room!=='home'||carePaused||busy||customizing||saveFailed)return;if(id==='flowers'){const r=careerAction('arrange');note('带回家的小花',r.text);}else if(id==='box'){const r=careerAction('box-rest');note('它自己的小纸箱',r.text);}else if(id==='memory')host.openCareer?.('history');else if(id==='ball'){const r=careAction('play','ball');note('它自己的小球',r.text);}else if(id==='bread'){const r=careerAction('use',{item:'bread'});note('面包篮',r.text);}draw();}
function tap(x,y){if(customizing||saveFailed||busy||!ready)return;screenRay(x,y);if(room){if(host&&room==='home'){const item=souvenirs?.pick(ray);if(item){activateSouvenir(item);return;}}if(host&&room==='home'&&housemate&&ray.intersectObject(housemate.doll.root,true).length){host.openChat?.();return;}if(host&&room==='home'){const hit=ray.intersectObjects([...household.values()].map(p=>p.pet.model),true)[0];if(hit){const selected=[...household.values()].find(p=>{let o=hit.object;while(o){if(o===p.pet.model)return true;o=o.parent;}return false;});if(selected&&selected.entry.id!==petState.activePetId){selectPet(selected.entry.id);note(selected.entry.profile.name,'已经选中它，下面的照料动作都属于它。');}else careAction('pet');return;}}for(const hit of ray.intersectObject(activeModel,true)){let o=hit.object;while(o&&!o.userData.zone)o=o.parent;const zone=roomLayout.zones[o?.userData.zone];if(zone){activeZone=o.userData.zone;if(host&&room==='home'&&['feeding','toys','bed','sofa'].includes(activeZone)){careAction(({feeding:'feed',toys:'play',bed:'rest',sofa:'rest'})[activeZone]);}else note(zone.title,zone.text);break;}}draw();return;}
 for(const hit of ray.intersectObject(outsideModel,true)){let o=hit.object;while(o&&!o.userData.zone)o=o.parent;const id=o?.userData.zone?.replace(/^building_/,'');if(world.building(id)){goTo(world.building(id).approach,id);return;}}
 const p=ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),-.06),new T.Vector3());if(p)goTo({x:p.x,z:p.z});}
const gesture=createMapGesture({initial:zoom,onTap:tap,onZoom:v=>{zoom=v;draw();},onPan:(dx,dy)=>{if(room){indoorOrbit.theta=T.MathUtils.clamp(indoorOrbit.theta-dx*.004,-.6,.6);indoorOrbit.phi=T.MathUtils.clamp(indoorOrbit.phi-dy*.003,-.25,.25);draw();return;}follow=false;screenRay(innerWidth/2,innerHeight/2);const origin=ray.ray.origin.clone(),direction=ray.ray.direction.clone();screenRay(innerWidth/2+dx,innerHeight/2+dy);const delta=orthographicPanDelta(origin,ray.ray.origin,direction);if(delta){pan.x=T.MathUtils.clamp(pan.x+delta.x,-35,35);pan.z=T.MathUtils.clamp(pan.z+delta.z,-54,35);}draw();}});
function bindOutdoorGestures(){view.onpointerdown=e=>{if(e.button&&e.pointerType==='mouse')return;view.setPointerCapture(e.pointerId);gesture.down(e.pointerId,e.clientX,e.clientY);};view.onpointermove=e=>gesture.move(e.pointerId,e.clientX,e.clientY);view.onpointerup=e=>gesture.up(e.pointerId,e.clientX,e.clientY);view.onpointercancel=e=>gesture.up(e.pointerId,e.clientX,e.clientY,true);view.onlostpointercapture=e=>gesture.up(e.pointerId,e.clientX,e.clientY,true);}
bindOutdoorGestures();view.addEventListener('wheel',e=>{if(room)return;e.preventDefault();gesture.setZoom(zoom*Math.exp(-Math.max(-240,Math.min(240,e.deltaY))*.002));},{passive:false});
for(const b of layout.buildings){const button=document.createElement('button');button.id='door-'+b.id;button.className='door-label';button.textContent=b.title;button.setAttribute('aria-label','走到'+b.title);button.onclick=()=>goTo(b.approach,b.id);labels.append(button);}
back.onclick=()=>{if(room)leave();else{follow=true;overview=false;pan={...position};gesture.setZoom(1.6);draw();}};
document.getElementById('reset').onclick=()=>{if(room){cameraControls.reset();activeZone='';note(title.textContent,'点家具看看 · 点「出门」回街区');}else{follow=false;overview=true;pan={x:0,z:-10};gesture.setZoom(.55);note('整个小街区','公园、六栋房子和北边林间小路。');}draw();};
document.getElementById('light').onclick=()=>{evening=!evening;applyLight();save();draw();};enterButton.onclick=()=>{const near=world.nearest(position);if(near)void enter(near.building.id);};
function careerAction(action,options={},session=household.get(petState.activePetId)){if(saveFailed||busy||customizing)return {accepted:false,text:'进度还没保存成功，请先重试保存。'};const engine=session?.career||career,body=session?.care||care,before=engine.snapshot(),careBefore=body.snapshot();const result=engine.request(action,options,{care:body.state,room,name:session?.entry.profile.name||petState.profile.name,startTreat:item=>body.request('snack',{food:item}),startSelfTreat:()=>body.request('snack',{food:'snack',source:'self'}),startRest:place=>body.request('rest',{place})});if(!save()){engine.restore(before);Object.assign(body.state,careBefore);return {accepted:false,text:'这一笔没有保存成功，重试保存后再操作。'};}window.dispatchEvent(new CustomEvent('pet-career-change',{detail:{action,petId:session?.entry.id,...result}}));souvenirs?.sync();if(result.accepted)draw();return result;}

function careAction(action,toy='ball'){if(!host||room!=='home'||busy||carePaused||customizing||saveFailed)return {accepted:false,text:'先回家，再陪它玩吧。'};if(action==='rest'&&care.state.task?.kind==='sleep')action='wake';return homeCare.request(action,{toy});}
document.getElementById('home-souvenirs')?.addEventListener('click',e=>activateSouvenir(e.target.closest('[data-souvenir]')?.dataset.souvenir));
const workButton=document.getElementById('pet-work');if(workButton){workButton.hidden=!host;workButton.onclick=()=>host.openCareer?.();}const homeBar=document.getElementById('home-actions');homeBar?.addEventListener('click',e=>{const b=e.target.closest('[data-care]');if(b)careAction(b.dataset.care,b.dataset.toy||'ball');});const talkButton=document.getElementById('pet-talk');if(talkButton){talkButton.hidden=!host?.companion?.();talkButton.onclick=()=>host.openChat?.();}const statusButton=document.getElementById('pet-status');if(statusButton){statusButton.hidden=!host;statusButton.onclick=()=>host.openCare?.();}
document.getElementById('selected-pet')?.addEventListener('click',()=>host?.openPets?.());
let persistAt=0;const persist=()=>{if(host&&ready&&!customizing&&performance.now()-persistAt>2500){persistAt=performance.now();save();}};setInterval(persist,3000);
document.addEventListener('visibilitychange',()=>{gesture.cancel();cameraControls?.clearGesture();lastTime=0;save();if(!document.hidden)draw();});window.addEventListener('pagehide',()=>save());
try{
 const [outsideFile,companion]=await Promise.all([loader.loadAsync(new URL('./outside.glb?v=fg-f330d135f2ad1c03',import.meta.url).href),loadPetCompanion(T,loader,{persist:!host,initialSpecies:petState?.profile.species,compressedMask:!!host})]);
 outsideModel=outsideFile.scene;shade(outsideModel);scene.add(outsideModel);activeModel=outsideModel;pet=companion;petRoot=pet.root;cat=pet.model;rig=pet.rig;dye=pet.dye;scene.add(petRoot);if(host){for(const entry of petState.pets){const model=entry.id===petState.activePetId?companion:await loadPetCompanion(T,loader,{persist:false,initialSpecies:entry.profile.species,compressedMask:true});const session=makeSession(entry,model);household.set(entry.id,session);model.root.visible=entry.id===petState.activePetId;}activateSession(household.get(petState.activePetId));applyProfile(petState.profile);}else{petControls=mountPetControls(pet,{draw,onSpecies:()=>{cat=pet.model;rig=pet.rig;dye=pet.dye;if(room)placeIndoor();else setOutdoorPet();refresh();}});}applyLight();loading.hidden=true;ready=true;
 window.petCareerPreview={scene,camera,renderer,get pet(){return pet;},get cat(){return cat;},get petRoot(){return petRoot;},household,world,layout,enter,leave,goTo,step:advance,reset:()=>document.getElementById('reset').click(),snapshot:()=>({ready,species:pet.species,tail:pet.tail,mood:pet.mood,room,position:{...position},outdoor,pan:{...pan},zoom:room?cameraControls?.snapshot().zoom:zoom,camera:cameraControls?.snapshot(),evening,busy,walking:path.length>0,destination,zone:activeZone,motion:pet?.motion?.snapshot()}),get model(){return activeModel;},project:(x,z,h=0)=>{const v=new T.Vector3(x,h,z).project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};}};
 note(layout.title,'点地面散步 · 点房子门牌走进去');refresh();resize();
 if(host){window.PetGame={ready:false,companion:()=>housemate?.snapshot()||null,companionAction:(action,petId=petState.activePetId)=>{if(saveFailed||busy||customizing)return {accepted:false,text:'进度还没保存成功，请稍后再试。'};return housemate?.request(action,{petId})||{accepted:false,text:'这一档还没有在场的同行者。'};},chatContext:()=>({map:'pet-home',place:room==='home'?'家里':room?world.building(room).title:'小镇街区',activePetId:petState.activePetId,pets:[...household.values()].map(x=>({id:x.entry.id,...x.entry.profile,...x.care.snapshot(),summary:careSummary(x.care.state),career:x.career.summary(),home:homeSouvenirs(x.career.state,x.care.state),atHome:room==='home'||x.pet!==pet})),pet:{id:petState.activePetId,...petState.profile,...care.snapshot(),summary:careSummary(care.state)},career:career.summary(),home:homeSouvenirs(career.state,care.state),companion:housemate?.snapshot()||null}),care:()=>({...care.snapshot(),summary:{...careSummary(care.state),...(!room?{activity:'在小镇散步'}:{})},atHome:room==='home',paused:carePaused}),career:()=>({...career.summary(),room,petName:petState.profile.name}),careerAction,goBakery:()=>{if(room==='bakery')return true;if(room)leave();return goTo(world.building('bakery').approach,'bakery');},goWork:id=>{if(!['bakery','florist'].includes(id))return false;if(room===id)return true;if(room)leave();return goTo(world.building(id).approach,id);},goShopping:()=>{if(room==='store')return true;if(room)leave();return goTo(world.building('store').approach,'store');},careAction,goHome:()=>{if(room==='home')return true;if(room)leave();return goTo(world.building('home').approach,'home');},pause:value=>{carePaused=!!value;lastTime=0;refresh();if(!carePaused)draw();},home:()=>({...homeCare.snapshot(),souvenirs:homeSouvenirs(career.state,care.state)}),palettes:CAT_PALETTES,roster:rosterView,selectPet,beginAdd,cancelProfile,limit:PET_LIMIT,get previewCamera(){return previewCamera;},get previewScene(){return previewScene;},snapshot:()=>{syncHousehold();const entry=household.get(petState.activePetId)?.entry;return snapshotPetState(adding&&entry?{...petState,profile:entry.profile,care:entry.care,career:entry.career,configured:entry.configured}:petState,{position,room,outdoor,evening});},flush:()=>!busy&&save(),preview:customize,applyProfile,commitProfile,enter,leave,goTo,step:advance};}
 if(restored.room){position={...outdoor.position};heading=outdoor.heading||0;pan={...outdoor.pan};zoom=outdoor.overview===undefined?1.6:outdoor.zoom||1.6;overview=outdoor.overview===true;follow=outdoor.follow!==false;setOutdoorPet();await enter(restored.room);}
 if(host){window.PetGame.ready=true;host.ready?.();}
}catch(e){loading.textContent='小街区没能打开，请刷新重试。';console.error(e);}
