import {createHomeSouvenirs,homeSouvenirs} from '../../apps/pets/home-souvenirs.mjs?v=fg-ef210840935ca136';
import {createPetCareer} from '../../apps/pets/career.mjs?v=fg-ef210840935ca136';
import {moodFromCare} from '../pet-house/pet-mood.mjs?v=fg-ef210840935ca136';
import {createHousemate} from '../../apps/pets/housemate.mjs?v=fg-ef210840935ca136';
import {turnPet} from '../../apps/pets/movement.mjs?v=fg-ef210840935ca136';
import {createPetCare,careSummary} from '../../apps/pets/care.mjs?v=fg-ef210840935ca136';
import {createPetHome} from '../../apps/pets/home.mjs?v=fg-ef210840935ca136';
import * as T from 'three';
import {CAT_PALETTES} from '../pet-house/cat-dye.mjs?v=fg-ef210840935ca136';
import {restorePetState,snapshotPetState,petProfile,bodyWidth} from '../../apps/pets/state.mjs?v=fg-ef210840935ca136';
import {createPetCamera} from '../pet-house/pet-camera.mjs?v=fg-ef210840935ca136';
import {GLTFLoader} from '../../apps/fairy-garden/vendor/GLTFLoader.js?v=fg-ef210840935ca136';
import {DRACOLoader} from '../../apps/fairy-garden/vendor/DRACOLoader.js?v=fg-ef210840935ca136';
import {createMapGesture,orthographicPanDelta} from '../../apps/fairy-garden/view-controls.mjs?v=fg-ef210840935ca136';
import {loadPetCompanion,mountPetControls} from '../pet-house/pet-companion.mjs?v=fg-ef210840935ca136';
import {createPetWorld} from './world-navigation.mjs?v=fg-ef210840935ca136';
const read=async url=>{const r=await fetch(new URL(url,import.meta.url));if(!r.ok)throw Error('场景文件 '+r.status);return r.json();};
const layout=await read('./outside.json?v=fg-ef210840935ca136'),world=createPetWorld(layout);
const view=document.getElementById('view'),loading=document.getElementById('loading'),labels=document.getElementById('door-labels');
const title=document.querySelector('h1'),subtitle=document.getElementById('subtitle'),back=document.getElementById('back'),enterButton=document.getElementById('enter');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;view.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#eee8dc');
const camera=new T.OrthographicCamera(-20,20,20,-20,.1,600);
const hemi=new T.HemisphereLight('#fff1dc','#c2ae8e',2.35);scene.add(hemi);
const key=new T.DirectionalLight('#fff1da',3);key.position.set(-15,28,15);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-38,right:38,top:38,bottom:-38,far:150});key.shadow.normalBias=.035;scene.add(key);
const fill=new T.DirectionalLight('#fff8eb',1.2);fill.position.set(20,30,20);scene.add(fill);
const studio=new T.Mesh(new T.PlaneGeometry(500,500),new T.MeshStandardMaterial({color:'#eee8dc',roughness:1}));studio.rotation.x=-Math.PI/2;studio.position.y=-.29;studio.receiveShadow=true;scene.add(studio);
const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath(new URL('../../apps/fairy-garden/vendor/draco/',import.meta.url).href);loader.setDRACOLoader(draco);
const toWeb=p=>new T.Vector3(p[0],p[2],-p[1]);
const host=location.pathname.includes('/apps/pets/')&&window.parent!==window&&window.parent.FairyGardenHostFor?.(window);
let career,housemate,care,homeCare,souvenirs,carePaused=false,previewProfile,petState,dye,customizing=false,saveFailed=false,previewScene,previewCamera;const shapeMeshes=[];
const sessionKey='lisa-pet-street-preview-v1';let raw;try{raw=JSON.parse(sessionStorage.getItem(sessionKey));}catch{}
if(host){petState=restorePetState(host.load().worlds?.pets,world);raw=petState;care=createPetCare(petState.care);career=createPetCareer(petState.career);}
let restored=world.restore(raw),position={...restored.position},pan={...position},zoom=1.6,follow=true,overview=false,heading=0,room=null,outdoor=restored.outdoor,roomLayout,activeModel,outsideModel,cat,petRoot,motion,rig,pet,petControls,busy=false,ready=false,path=[],destination='',activeZone='',lastTime=0,settling=0;
const requested=host?null:new URLSearchParams(location.search).get('scene');
if(world.building(requested)&&restored.room!==requested){position={...world.building(requested).approach};pan={...position};restored.room=null;}
if(requested==='outside'||requested==='park')restored.room=null;
let cameraControls;const cameraHost=document.getElementById('scene-camera');
let evening=restored.evening,indoorOrbit={theta:0,phi:0};
function save(force=false){if(career){petState.career=career.snapshot();petState.day=career.state.day;}if(care)petState.care=care.snapshot();if(host&&customizing&&force!==true)return true;if(host){try{petState=snapshotPetState(petState,{position,room,outdoor,evening});if(!host.save(petState,'pets'))throw Error('没有保存成功');saveFailed=false;return true;}catch(e){saveFailed=true;note('进度还没有保存成功','请留在这里重试，保存成功后再离开。');return false;}}try{sessionStorage.setItem(sessionKey,JSON.stringify({position,room,outdoor,evening}));}catch{}}
function applyProfile(value){homeCare?.resetPose();const next=petProfile(value);petState.profile=next;pet.select(next.species);cat=pet.model;rig=pet.rig;dye=pet.dye;if(customizing){pet.motion?.dispose();motion=null;}dye?.set(next.look);for(const {mesh,original,height}of shapeMeshes){const attr=mesh.geometry.attributes.position;for(let i=0;i<attr.count;i++)attr.setX(i,bodyWidth(original[i*3],original[i*3+1],original[i*3+2],height,next.weight));attr.needsUpdate=true;mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere();}petRoot.scale.setScalar(next.size);if(!customizing){if(room)placeIndoor();else setOutdoorPet();}draw();return next;}
function customize(on){homeCare?.resetPose();if(on&&!customizing)previewProfile=structuredClone(petState.profile);customizing=!!on;document.body.classList.toggle('customizing',customizing);path=[];destination='';settling=0;motion?.dispose();motion=null;if(customizing){if(!previewScene){previewScene=new T.Scene();previewScene.background=new T.Color('#eee8dc');previewScene.add(new T.HemisphereLight('#fff4e6','#b9bdad',2.4));const light=new T.DirectionalLight('#fff4e0',3);light.position.set(-2,4,4);previewScene.add(light);previewCamera=new T.OrthographicCamera(-2,2,2,-2,.1,30);}previewScene.add(petRoot);petRoot.position.set(0,0,0);petRoot.rotation.y=0;}else{scene.add(petRoot);if(room)placeIndoor();else setOutdoorPet();}draw();}
function commitProfile(value){const previous=structuredClone(petState);previous.profile=previewProfile||previous.profile;const profile=applyProfile(value);petState.configured=true;if(!save(true)){petState=previous;applyProfile(previous.profile);return false;}return profile;}
function note(a,b){document.getElementById('zone-title').textContent=a;document.getElementById('zone-text').textContent=b;}
function shade(root){root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});}
function clearModel(root){root.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}});}
function applyLight(){hemi.color.set(evening?'#d4dcf3':'#fff1dc');hemi.intensity=evening?1.1:2.35;key.color.set(evening?'#b8cbff':'#fff1da');key.intensity=evening?.65:3;fill.color.set(evening?'#ffdab6':'#fff8eb');fill.intensity=evening?.65:1.2;const b=document.getElementById('light');b.textContent=evening?'白天':'傍晚';b.setAttribute('aria-pressed',String(evening));b.setAttribute('aria-label',evening?'切换到白天':'切换到傍晚');}
function refresh(){const bar=document.getElementById('home-actions');if(bar){bar.hidden=!host||room!=='home'||customizing;bar.querySelector('[data-care=rest]').textContent=care?.state.task?.kind==='sleep'?'叫醒':'休息';for(const b of bar.querySelectorAll('button'))b.disabled=busy||saveFailed||carePaused;}title.textContent=room?world.building(room).title:layout.title;document.title=title.textContent+' · 宠物小世界';subtitle.textContent=room?'从门口进来的小屋':'点地面散步 · 拖动画面';back.textContent=room?'出门':pet?.species==='dog'?'跟着狗':'跟着猫';back.setAttribute('aria-label',room?'出门回到街区':pet?.species==='dog'?'回到狗狗身边':'回到猫猫身边');labels.hidden=!!room;const near=world.nearest(position);enterButton.hidden=!!room||!near||near.distance>.65;enterButton.disabled=busy;enterButton.textContent=near?'走进'+near.building.title:'走进屋里';back.disabled=busy;view.setAttribute('aria-busy',String(busy));}
function setOutdoorPet(){motion?.dispose();petRoot.position.set(position.x,world.ground(position.x,position.z)+.001,position.z);petRoot.rotation.y=heading;motion=pet.bind({ground:world.ground,matchSpeed:true});motion.update(0,0);}
function placeIndoor(){homeCare?.resetPose();petRoot.position.copy(toWeb(roomLayout.cat.position));petRoot.rotation.y=roomLayout.cat.yaw;cat.updateMatrixWorld(true);if(pet)motion=pet.bind({ground:()=>petRoot.position.y});if(host&&room==='home'){homeCare?.begin(activeModel);housemate?.begin();souvenirs?.dispose();souvenirs=createHomeSouvenirs(T,{model:activeModel,career:career.state,care:care.state,name:petState.profile.name});}}
function souvenirLabels(){const el=document.getElementById('home-souvenirs');if(!el)return;el.hidden=room!=='home'||customizing||!souvenirs;if(el.hidden)return;const facts=souvenirs.sync(),markers=souvenirs.markers(camera,innerWidth,innerHeight);for(const b of el.querySelectorAll('button')){const m=markers.find(x=>x.id===b.dataset.souvenir);b.hidden=!m?.visible;if(!m)continue;b.textContent=b.dataset.souvenir==='bread'?'面包篮 · '+facts.breadBasket.count:b.dataset.souvenir==='ball'?'自己的小球':'第一份工作';b.style.left=Math.max(58,Math.min(innerWidth-58,m.x))+'px';b.style.top=Math.max(85,Math.min(innerHeight-230,m.y))+'px';b.disabled=carePaused||busy||saveFailed;}}
function housemateLabel(){const el=document.getElementById('housemate-state');if(!el)return;const c=housemate?.snapshot();el.hidden=!c?.visible||room!=='home'||customizing;if(el.hidden)return;const v=new T.Vector3(c.position.x,1.8,c.position.z).project(camera);el.hidden=v.z< -1||v.z>1||Math.abs(v.x)>1||Math.abs(v.y)>1;el.textContent=housemate.person.name+(c.job?' · '+(c.job.phase==='walking'?'走过去':c.job.started?'正在':'准备')+({feed:'添粮',play:'陪玩',pet:'摸摸'})[c.job.action]:' · 在家陪着它');el.style.left=Math.max(90,Math.min(innerWidth-90,(v.x+1)*innerWidth/2))+'px';el.style.top=Math.max(45,(1-v.y)*innerHeight/2)+'px';}
function updateCamera(){
 const aspect=innerWidth/innerHeight;
 if(!room){const width=(aspect<1?(overview?40:10):(overview?48:12)*aspect)/zoom,height=width/aspect;camera.left=-width/2;camera.right=width/2;camera.top=height/2;camera.bottom=-height/2;const distance=Math.max(75,height*1.5);camera.position.set(pan.x+distance*.6,distance*.75,pan.z+distance*.85);camera.lookAt(pan.x,0,pan.z);camera.far=Math.max(250,distance*4);}
 else if(cameraControls){cameraControls.update();return;}else {const target=toWeb(roomLayout.camera.target),pos=toWeb(roomLayout.camera.position);const span=roomLayout.camera.scale/Math.min(1,aspect)/zoom;camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;const spherical=new T.Spherical().setFromVector3(pos.sub(target));spherical.theta+=indoorOrbit.theta;spherical.phi+=indoorOrbit.phi;spherical.radius*=Math.max(1,1/zoom);camera.position.copy(target).add(new T.Vector3().setFromSpherical(spherical));camera.lookAt(target);camera.far=250;}
 camera.updateProjectionMatrix();camera.updateMatrixWorld();
 for(const b of layout.buildings){const button=document.getElementById('door-'+b.id),v=new T.Vector3(b.x,5.6,b.z+3).project(camera);button.style.left=((v.x+1)*innerWidth/2)+'px';button.style.top=((1-v.y)*innerHeight/2)+'px';const px=(v.x+1)*innerWidth/2,py=(1-v.y)*innerHeight/2;button.hidden=room!==null||v.z<-1||v.z>1||px<55||px>innerWidth-55||py<120||py>innerHeight-85;button.disabled=busy;}
}
async function enter(id){
 if(customizing||saveFailed||busy||room||!world.canEnter(position,id))return false;
 const b=world.building(id);busy=true;path=[];destination='';settling=0;lastTime=0;refresh();loading.textContent='走进'+b.title+'…';loading.hidden=false;
 try{
  const [file,inside]=await Promise.all([loader.loadAsync(new URL(b.interior,import.meta.url).href),read(b.layout)]);
  if(host&&id==='home'&&!housemate&&host.companion?.()){try{housemate=await createHousemate({scene,host,care,home:homeCare,notice:note,save});}catch(e){console.error(e);}}
  outdoor={position:{...position},heading,pan:{...pan},zoom,follow,overview};motion?.dispose();motion=null;outsideModel.visible=false;activeModel=file.scene;shade(activeModel);scene.add(activeModel);room=id;roomLayout=inside;zoom=1;indoorOrbit={theta:0,phi:0};gesture.setZoom(1);placeIndoor();cameraHost.hidden=false;cameraControls=createPetCamera(T,{camera,view,position:toWeb(inside.camera.position),target:toWeb(inside.camera.target),scale:inside.camera.scale,getCat:()=>petRoot,getName:()=>pet.species==='dog'?'狗狗':'猫咪',draw,onTap:e=>tap(e.clientX,e.clientY),controlsHost:cameraHost});activeZone='';note(b.title,'点家具看看 · 点「出门」回街区');history.replaceState(null,'','?scene='+id);save();return true;
 }catch(e){console.error(e);note('暂时没能进屋','还在原来的门口，可以再试一次。');return false;}
 finally{busy=false;loading.hidden=true;refresh();draw();}
}
function leave(){if(busy||saveFailed||!room)return;housemate?.leave();homeCare?.leave();souvenirs?.dispose();souvenirs=null;cameraControls?.dispose();cameraControls=null;cameraHost.hidden=true;bindOutdoorGestures();scene.remove(activeModel);clearModel(activeModel);activeModel=outsideModel;outsideModel.visible=true;position={...outdoor.position};pan={...outdoor.pan};zoom=outdoor.zoom;follow=outdoor.follow;overview=outdoor.overview===true;heading=outdoor.heading;room=null;roomLayout=null;activeZone='';settling=0;setOutdoorPet();gesture.setZoom(zoom);note('回到门口','接着走走，也可以去旁边的店。');history.replaceState(null,'','?scene=outside');save();refresh();draw();}
function goTo(point,id=''){
 if(customizing||saveFailed||busy||room||!ready)return false;const route=world.path(position,point);if(!route){note('这里暂时走不过去','点点道路或草地试试。');return false;}path=route;destination=id;follow=true;overview=false;pan={...position};gesture.setZoom(1.6);settling=1;note(id?'去'+world.building(id).title:'散散步',id?'沿路走到门口，再走进去。':'点门牌可以去店里。');draw();return true;
}
function advance(dt){
 if(customizing||carePaused||saveFailed||!motion||busy)return;dt=Math.max(0,Math.min(.05,dt));if(career){const event=career.tick(dt,{care:care.state,room});if(event){save();host.openCareer?.();}}if(room){if(host&&room==='home'){housemate?.tick(dt);homeCare.tick(dt);souvenirs?.sync();refresh();}else{care?.tick(dt);if(care)pet.setMood(moodFromCare(care.state));motion.update(dt,0);}return;}care?.tick(dt);if(care)pet.setMood(moodFromCare(care.state));let speed=0;
 if(path.length){const q=path[0],dx=q.x-position.x,dz=q.z-position.z,d=Math.hypot(dx,dz);speed=1.1*petRoot.scale.x;const turn=turnPet(heading,Math.atan2(dx,dz),dt);heading=turn.heading;const step=turn.canMove?Math.min(d,speed*dt):0;if(!step)speed=0;if(d>.001){position.x+=dx/d*step;position.z+=dz/d*step;}if(d<=step+.002)path.shift();if(!path.length){speed=0;settling=.65;save();if(destination){const id=destination;destination='';void enter(id);}}}
 petRoot.position.set(position.x,world.ground(position.x,position.z)+.001,position.z);petRoot.rotation.y=heading;motion.update(dt,speed,0,path.length>0);if(follow&&(path.length||settling>0)){pan.x=T.MathUtils.damp(pan.x,position.x,4,dt);pan.z=T.MathUtils.damp(pan.z,position.z,4,dt);}settling=Math.max(0,settling-dt);refresh();
}
let pending=false;function draw(){if(pending||document.hidden)return;pending=true;requestAnimationFrame(time=>{pending=false;const dt=lastTime?Math.min(.05,(time-lastTime)/1000):0;lastTime=time;advance(dt);if(customizing){const h=Math.max(1,innerHeight*.38),aspect=innerWidth/h,span=1.7;previewCamera.left=-span*aspect/2;previewCamera.right=span*aspect/2;previewCamera.top=span/2;previewCamera.bottom=-span/2;previewCamera.position.set(1,1.25,3.4);previewCamera.lookAt(0,.5,0);previewCamera.updateProjectionMatrix();renderer.setViewport(0,innerHeight-h,innerWidth,h);renderer.render(previewScene,previewCamera);}else{renderer.setViewport(0,0,innerWidth,innerHeight);updateCamera();housemateLabel();souvenirLabels();renderer.render(scene,camera);}if(!carePaused&&(path.length||settling>0||(career?.state.job?.phase==='working'&&room==='bakery')||(host&&room==='home'&&!customizing)||(!customizing&&pet?.animating)))draw();else lastTime=0;});}
function resize(){renderer.setSize(innerWidth,innerHeight);draw();}window.addEventListener('resize',resize);
const ray=new T.Raycaster(),pointer=new T.Vector2();
function screenRay(x,y){pointer.set(x/innerWidth*2-1,1-y/innerHeight*2);ray.setFromCamera(pointer,camera);return ray;}
function activateSouvenir(id){if(!id||room!=='home'||carePaused||busy||customizing||saveFailed)return;if(id==='memory')host.openCareer?.('history');else if(id==='ball'){const r=careAction('play','ball');note('它自己的小球',r.text);}else if(id==='bread'){const r=careerAction('use',{item:'bread'});note('面包篮',r.text);}draw();}
function tap(x,y){if(customizing||saveFailed||busy||!ready)return;screenRay(x,y);if(room){if(host&&room==='home'){const item=souvenirs?.pick(ray);if(item){activateSouvenir(item);return;}}if(host&&room==='home'&&housemate&&ray.intersectObject(housemate.doll.root,true).length){host.openChat?.();return;}if(host&&room==='home'&&ray.intersectObject(pet.model,true).length){careAction('pet');return;}for(const hit of ray.intersectObject(activeModel,true)){let o=hit.object;while(o&&!o.userData.zone)o=o.parent;const zone=roomLayout.zones[o?.userData.zone];if(zone){activeZone=o.userData.zone;if(host&&room==='home'&&['feeding','toys','bed','sofa'].includes(activeZone)){careAction(({feeding:'feed',toys:'play',bed:'rest',sofa:'rest'})[activeZone]);}else note(zone.title,zone.text);break;}}draw();return;}
 for(const hit of ray.intersectObject(outsideModel,true)){let o=hit.object;while(o&&!o.userData.zone)o=o.parent;const id=o?.userData.zone?.replace(/^building_/,'');if(world.building(id)){goTo(world.building(id).approach,id);return;}}
 const p=ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),-.06),new T.Vector3());if(p)goTo({x:p.x,z:p.z});}
const gesture=createMapGesture({initial:zoom,onTap:tap,onZoom:v=>{zoom=v;draw();},onPan:(dx,dy)=>{if(room){indoorOrbit.theta=T.MathUtils.clamp(indoorOrbit.theta-dx*.004,-.6,.6);indoorOrbit.phi=T.MathUtils.clamp(indoorOrbit.phi-dy*.003,-.25,.25);draw();return;}follow=false;screenRay(innerWidth/2,innerHeight/2);const origin=ray.ray.origin.clone(),direction=ray.ray.direction.clone();screenRay(innerWidth/2+dx,innerHeight/2+dy);const delta=orthographicPanDelta(origin,ray.ray.origin,direction);if(delta){pan.x=T.MathUtils.clamp(pan.x+delta.x,-35,35);pan.z=T.MathUtils.clamp(pan.z+delta.z,-54,35);}draw();}});
function bindOutdoorGestures(){view.onpointerdown=e=>{if(e.button&&e.pointerType==='mouse')return;view.setPointerCapture(e.pointerId);gesture.down(e.pointerId,e.clientX,e.clientY);};view.onpointermove=e=>gesture.move(e.pointerId,e.clientX,e.clientY);view.onpointerup=e=>gesture.up(e.pointerId,e.clientX,e.clientY);view.onpointercancel=e=>gesture.up(e.pointerId,e.clientX,e.clientY,true);view.onlostpointercapture=e=>gesture.up(e.pointerId,e.clientX,e.clientY,true);}
bindOutdoorGestures();view.addEventListener('wheel',e=>{if(room)return;e.preventDefault();gesture.setZoom(zoom*Math.exp(-Math.max(-240,Math.min(240,e.deltaY))*.002));},{passive:false});
for(const b of layout.buildings){const button=document.createElement('button');button.id='door-'+b.id;button.className='door-label';button.textContent=b.title;button.setAttribute('aria-label','走到'+b.title);button.onclick=()=>goTo(b.approach,b.id);labels.append(button);}
back.onclick=()=>{if(room)leave();else{follow=true;overview=false;pan={...position};gesture.setZoom(1.6);draw();}};
document.getElementById('reset').onclick=()=>{if(room){cameraControls.reset();activeZone='';note(title.textContent,'点家具看看 · 点「出门」回街区');}else{follow=false;overview=true;pan={x:0,z:-10};gesture.setZoom(.55);note('整个小街区','公园、六栋房子和北边林间小路。');}draw();};
document.getElementById('light').onclick=()=>{evening=!evening;applyLight();save();draw();};enterButton.onclick=()=>{const near=world.nearest(position);if(near)void enter(near.building.id);};
function careerAction(action,options={}){if(saveFailed||busy||customizing)return {accepted:false,text:'进度还没保存成功，请先重试保存。'};const before=career.snapshot(),careBefore=care.snapshot();const result=career.request(action,options,{care:care.state,room,name:petState.profile.name,startTreat:item=>care.request('snack',{food:item})});if(!save()){career.restore(before);Object.assign(care.state,careBefore);return {accepted:false,text:'这一笔没有保存成功，重试保存后再操作。'};}window.dispatchEvent(new CustomEvent('pet-career-change',{detail:{action,...result}}));souvenirs?.sync();if(result.accepted)draw();return result;}
function careAction(action,toy='ball'){if(!host||room!=='home'||busy||carePaused||customizing||saveFailed)return {accepted:false,text:'先回家，再陪它玩吧。'};if(action==='rest'&&care.state.task?.kind==='sleep')action='wake';return homeCare.request(action,{toy});}
document.getElementById('home-souvenirs')?.addEventListener('click',e=>activateSouvenir(e.target.closest('[data-souvenir]')?.dataset.souvenir));
const workButton=document.getElementById('pet-work');if(workButton){workButton.hidden=!host;workButton.onclick=()=>host.openCareer?.();}const homeBar=document.getElementById('home-actions');homeBar?.addEventListener('click',e=>{const b=e.target.closest('[data-care]');if(b)careAction(b.dataset.care,b.dataset.toy||'ball');});const talkButton=document.getElementById('pet-talk');if(talkButton){talkButton.hidden=!host?.companion?.();talkButton.onclick=()=>host.openChat?.();}const statusButton=document.getElementById('pet-status');if(statusButton){statusButton.hidden=!host;statusButton.onclick=()=>host.openCare?.();}
let persistAt=0;const persist=()=>{if(host&&ready&&!customizing&&performance.now()-persistAt>2500){persistAt=performance.now();save();}};setInterval(persist,3000);
document.addEventListener('visibilitychange',()=>{gesture.cancel();cameraControls?.clearGesture();lastTime=0;save();if(!document.hidden)draw();});window.addEventListener('pagehide',()=>save());
try{
 const [outsideFile,companion]=await Promise.all([loader.loadAsync(new URL('./outside.glb?v=fg-ef210840935ca136',import.meta.url).href),loadPetCompanion(T,loader,{persist:!host,initialSpecies:petState?.profile.species,compressedMask:!!host})]);
 outsideModel=outsideFile.scene;shade(outsideModel);scene.add(outsideModel);activeModel=outsideModel;pet=companion;petRoot=pet.root;cat=pet.model;rig=pet.rig;dye=pet.dye;scene.add(petRoot);setOutdoorPet();if(host)homeCare=createPetHome(T,{scene,pet,care,onNotice:note,onSave:save,draw});if(host){petRoot.traverse(mesh=>{if(mesh.isMesh){const original=mesh.geometry.attributes.position.array.slice();mesh.geometry=mesh.geometry.clone();const h=new T.Box3().setFromBufferAttribute(mesh.geometry.attributes.position);shapeMeshes.push({mesh,original,height:h.max.y-h.min.y});}});applyProfile(petState.profile);}else{petControls=mountPetControls(pet,{draw,onSpecies:()=>{cat=pet.model;rig=pet.rig;dye=pet.dye;if(room)placeIndoor();else setOutdoorPet();refresh();}});}applyLight();loading.hidden=true;ready=true;
 window.petCareerPreview={scene,camera,renderer,pet,get cat(){return cat;},petRoot,world,layout,enter,leave,goTo,step:advance,reset:()=>document.getElementById('reset').click(),snapshot:()=>({ready,species:pet.species,tail:pet.tail,mood:pet.mood,room,position:{...position},outdoor,pan:{...pan},zoom:room?cameraControls?.snapshot().zoom:zoom,camera:cameraControls?.snapshot(),evening,busy,walking:path.length>0,destination,zone:activeZone,motion:pet?.motion?.snapshot()}),get model(){return activeModel;},project:(x,z,h=0)=>{const v=new T.Vector3(x,h,z).project(camera);return {x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};}};
 note(layout.title,'点地面散步 · 点房子门牌走进去');refresh();resize();
 if(host){window.PetGame={ready:false,companion:()=>housemate?.snapshot()||null,companionAction:action=>{if(saveFailed||busy||customizing)return {accepted:false,text:'进度还没保存成功，请稍后再试。'};return housemate?.request(action)||{accepted:false,text:'这一档还没有在场的同行者。'};},chatContext:()=>({map:'pet-home',place:room==='home'?'家里':room?world.building(room).title:'小镇街区',pet:{...petState.profile,...care.snapshot(),summary:careSummary(care.state)},career:career.summary(),home:homeSouvenirs(career.state,care.state),companion:housemate?.snapshot()||null}),care:()=>({...care.snapshot(),summary:{...careSummary(care.state),...(!room?{activity:'在小镇散步'}:{})},atHome:room==='home',paused:carePaused}),career:()=>({...career.summary(),room,petName:petState.profile.name}),careerAction,goBakery:()=>{if(room==='bakery')return true;if(room)leave();return goTo(world.building('bakery').approach,'bakery');},careAction,goHome:()=>{if(room==='home')return true;if(room)leave();return goTo(world.building('home').approach,'home');},pause:value=>{carePaused=!!value;lastTime=0;refresh();if(!carePaused)draw();},home:()=>({...homeCare.snapshot(),souvenirs:homeSouvenirs(career.state,care.state)}),palettes:CAT_PALETTES,get previewCamera(){return previewCamera;},get previewScene(){return previewScene;},snapshot:()=>snapshotPetState(petState,{position,room,outdoor,evening}),flush:()=>!busy&&save(),preview:customize,applyProfile,commitProfile,enter,leave,goTo,step:advance};}
 if(restored.room){position={...outdoor.position};heading=outdoor.heading||0;pan={...outdoor.pan};zoom=outdoor.overview===undefined?1.6:outdoor.zoom||1.6;overview=outdoor.overview===true;follow=outdoor.follow!==false;setOutdoorPet();await enter(restored.room);}
 if(host){window.PetGame.ready=true;host.ready?.();}
}catch(e){loading.textContent='小街区没能打开，请刷新重试。';console.error(e);}
