// Check the decoded production skin: moving the head must not pull the back fur.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.PET_HOUSE_URL||'http://127.0.0.1:18958',out=process.env.PET_HOUSE_EVIDENCE||'/tmp/pet-back-check';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:800,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(base+'/art/pet-house/preview.html');await page.waitForFunction(()=>window.petHousePreview?.snapshot().ready);await page.locator('#pet-species').selectOption('dog');await page.evaluate(()=>requestAnimationFrame=()=>0);
 const result=await page.evaluate(async()=>{const T=await import('three'),p=petHousePreview;let mesh;p.cat.traverse(o=>{if(o.isSkinnedMesh)mesh=o;});const a=mesh.geometry.attributes,probes=[];let maxHeadWeight=0;
  for(let i=0;i<a.position.count;i++){const x=a.position.getX(i),y=a.position.getY(i),z=a.position.getZ(i);if(Math.abs(x)>.16||y<.36||y>.495||z<-.26||z>-.07)continue;probes.push(i);let head=0;for(let j=0;j<4;j++){const n=mesh.skeleton.bones[a.skinIndex.getComponent(i,j)].name;if(['head','earL','earR'].includes(n))head+=a.skinWeight.getComponent(i,j);}maxHeadWeight=Math.max(maxHeadWeight,head);}
  p.pet.motion.dispose();p.pet.setTail({wag:false});p.pet.setMood('neutral');p.petRoot.position.set(0,.041,0);p.petRoot.rotation.y=0;p.pet.bind({ground:()=>.04});for(let i=0;i<200;i++)p.pet.motion.update(.05,0);const points=()=>{p.petRoot.updateMatrixWorld(true);mesh.skeleton.update();return probes.map(i=>mesh.localToWorld(mesh.applyBoneTransform(i,new T.Vector3().fromBufferAttribute(a.position,i))));};const before=points(),head=p.cat.getObjectByName('head'),q=head.quaternion.clone();let maxBackMove=0;for(const angle of[-.55,.8,1.06]){head.quaternion.copy(q).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),angle));const after=points();for(let i=0;i<before.length;i++)maxBackMove=Math.max(maxBackMove,before[i].distanceTo(after[i]));}head.quaternion.copy(q);p.petRoot.updateMatrixWorld(true);
  window.backSkinMesh=mesh;window.backSkinT=T;
  return {probes:probes.length,maxHeadWeight,maxBackMove,bones:mesh.skeleton.bones.length};
 });assert.ok(result.probes>300,'Probe the actual upper back, including fur clumps');assert.equal(result.maxHeadWeight,0,'Back fur belongs to the torso');assert.ok(result.maxBackMove<1e-7,'Head tilting must not pull the back');assert.equal(result.bones,20);
 for(const mood of ['neutral','sleepy','happy','curious','gloomy']){const png=await page.evaluate(mood=>{const p=petHousePreview,T=backSkinT;p.pet.bind({ground:()=>.04});p.pet.setMood(mood);for(let i=0;i<240;i++)p.pet.motion.update(.05,0);p.room.visible=false;p.scene.children.find(o=>o.isMesh&&o.geometry.type==='PlaneGeometry').position.y=.04;const at=new T.Vector3(0,.45,0);p.camera.left=-.78;p.camera.right=.78;p.camera.top=.78;p.camera.bottom=-.78;p.camera.position.copy(at).add(new T.Vector3(2.5,1.2,-1.5));p.camera.lookAt(at);p.camera.updateProjectionMatrix();p.camera.updateMatrixWorld(true);p.renderer.render(p.scene,p.camera);return p.renderer.domElement.toDataURL('image/png').split(',')[1];},mood);fs.writeFileSync(path.join(out,'dog-'+mood+'.png'),Buffer.from(png,'base64'));}
 assert.deepEqual(errors,[]);result.ok=true;fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
