// Actual WebGL comparison with the published v74.817 eyelid line; same pose, dye and closure.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.PET_FACE_URL||'http://127.0.0.1:18961',out=process.env.PET_FACE_EVIDENCE||'/tmp/pet-face';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),p=await browser.newPage({viewport:{width:900,height:700}}),errors=[],report=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.goto(base+'/art/pet-house/preview.html');await p.waitForFunction(()=>window.petHousePreview?.snapshot().ready);await p.evaluate(()=>requestAnimationFrame=()=>0);
 for(const species of ['dog','cat'])for(const pose of ['stand','sleep'])for(const side of [-1,0,1]){
  const r=await p.evaluate(async({species,pose,side})=>{const T=await import('three'),A=await import('./pet-action.mjs'),q=petHousePreview;q.pet.select(species);q.petRoot.position.set(0,.041,0);q.petRoot.rotation.y=0;q.pet.setMood(pose==='sleep'?'sleepy':'neutral');q.pet.saveLook({base:'#f4eee0',patch:'#a98565'});q.pet.bind({ground:()=>.04,resetAction:true});q.pet.motion.setActionPose(A.samplePetAction(pose,0,{species}));for(let i=0;i<240;i++)q.pet.motion.update(1/60,0);q.room.visible=false;document.querySelectorAll('body > :not(#view):not(script)').forEach(e=>e.style.visibility='hidden');
   const at=new T.Vector3(0,pose==='sleep'?.31:.43,.15);q.camera.left=-.65;q.camera.right=.65;q.camera.top=.5056;q.camera.bottom=-.5056;q.camera.position.copy(at).add(new T.Vector3(side?side*2:0,.12,side?.35:3));q.camera.lookAt(at);q.camera.updateProjectionMatrix();
   window.faceHooks ||= new WeakMap();const oldLine={value:0};q.pet.model.traverse(o=>{if(!o.isMesh)return;let original=faceHooks.get(o.material);if(!original){original={compile:o.material.onBeforeCompile,key:o.material.customProgramCacheKey};faceHooks.set(o.material,original);}o.material.onBeforeCompile=shader=>{original.compile(shader);shader.uniforms.uOldEyeLine=oldLine;shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\n uniform float uOldEyeLine;').replace('float crease=','float oldCrease=exp(-pow((ep.y-(-.17+.24*ep.x*ep.x))/.080,2.))*(1.-smoothstep(.75,.94,abs(ep.x)));\n float crease=');shader.fragmentShader=shader.fragmentShader.replace(/diffuseColor\.rgb=mix\(diffuseColor\.rgb,mix\(lid,(.*?),crease\*([\d.]+)\),cover\);/,(_,color,strength)=>'vec3 nextLid=mix(lid,'+color+',crease*'+strength+'); vec3 oldLid=mix(lid,vec3(.065,.038,.022),oldCrease*.98); diffuseColor.rgb=mix(diffuseColor.rgb,mix(nextLid,oldLid,uOldEyeLine),cover);');};o.material.customProgramCacheKey=()=>original.key()+'-face-proof-'+species+pose+side;o.material.needsUpdate=true;});q.renderer.render(q.scene,q.camera);
   const canvas=document.createElement('canvas');canvas.width=q.renderer.domElement.width;canvas.height=q.renderer.domElement.height;const ctx=canvas.getContext('2d'),capture=value=>{oldLine.value=value;q.renderer.render(q.scene,q.camera);ctx.drawImage(q.renderer.domElement,0,0);return {png:canvas.toDataURL(),pixels:ctx.getImageData(0,0,canvas.width,canvas.height).data};};
   const before=capture(1),after=capture(0);let changed=0,maxChange=0,brighter=0,darker=0;for(let i=0;i<before.pixels.length;i+=4){const ds=[0,1,2].map(j=>after.pixels[i+j]-before.pixels[i+j]),d=Math.max(...ds.map(Math.abs));if(d>3){changed++;if(Math.max(...ds)>3)brighter++;if(Math.min(...ds)<-3)darker++;}maxChange=Math.max(maxChange,d);}
   // Project actual authored rest positions through the current skin to compare protected features.
   let mesh;q.pet.model.traverse(o=>{if(o.isSkinnedMesh)mesh=o});const pos=mesh.geometry.attributes.position,points=species==='dog'?[[0,.555,.489],[0,.485,.46],[0,.445,.46]]:[[0,.425,.455],[0,.40,.445]];
   const protectedChanges=points.map(point=>{let id=0,dist=Infinity;for(let i=0;i<pos.count;i++){const d=new T.Vector3().fromBufferAttribute(pos,i).distanceToSquared(new T.Vector3().fromArray(point));if(d<dist){dist=d;id=i}}const v=mesh.localToWorld(mesh.applyBoneTransform(id,new T.Vector3().fromBufferAttribute(pos,id))).project(q.camera),x=Math.round((v.x+1)*canvas.width/2),y=Math.round((1-v.y)*canvas.height/2);let change=0;for(let a=-2;a<=2;a++)for(let b=-2;b<=2;b++){const i=((y+b)*canvas.width+x+a)*4;for(let j=0;j<3;j++)change=Math.max(change,Math.abs(after.pixels[i+j]-before.pixels[i+j]));}return change;});return {before:before.png,after:after.png,changed,maxChange,brighter,darker,protectedChanges,lie:q.pet.motion.snapshot().action.lie};
  },{species,pose,side});const id=species+'-'+pose+'-'+side;for(const name of ['before','after'])fs.writeFileSync(path.join(out,id+'-'+name+'.png'),Buffer.from(r[name].split(',')[1],'base64'));delete r.before;delete r.after;assert.deepEqual(r.protectedChanges,r.protectedChanges.map(()=>0),id+' must preserve nose/mouth/tongue');if(species==='dog'&&pose==='sleep'){assert.ok(r.changed>50&&r.brighter>50,id+' closed-eye line must visibly soften '+JSON.stringify(r));assert.equal(r.darker,0,id+' line must not gain darker pixels');}else assert.equal(r.changed,0,id+' awake face and cat lids stay unchanged');report.push({species,pose,side,...r});
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'face.json'),JSON.stringify({ok:true,report,errors},null,2));console.log(JSON.stringify({ok:true,views:report.length}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
