// Actual WebGL lids: both load orders, fixed pose, open/closed iris and protected features.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.PET_FACE_URL||'http://127.0.0.1:18961',out=process.env.PET_FACE_EVIDENCE||'/tmp/pet-face';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],report=[];try{
 for(const order of [['cat','dog'],['dog','cat']]){
  const p=await browser.newPage({viewport:{width:900,height:700}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/art/pet-house/preview.html');await p.waitForFunction(()=>window.petHousePreview?.snapshot().ready);await p.evaluate(()=>requestAnimationFrame=()=>0);
  const geometry=await p.evaluate(async()=>{const {GLTFLoader}=await import('../../apps/fairy-garden/vendor/GLTFLoader.js'),{DRACOLoader}=await import('../../apps/fairy-garden/vendor/DRACOLoader.js'),{catLooseFragmentIndices}=await import('./pet-skin.mjs');const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath(new URL('../../apps/fairy-garden/vendor/draco/',location.href).href);loader.setDRACOLoader(draco);const result=[];for(const species of ['cat','dog']){const source=await loader.loadAsync('./'+species+'.glb');let raw,live;source.scene.traverse(o=>{if(o.isSkinnedMesh)raw=o.geometry});petHousePreview.pet.select(species);petHousePreview.pet.model.traverse(o=>{if(o.isSkinnedMesh)live=o.geometry});const expected=species==='cat'?catLooseFragmentIndices(raw.attributes.position.array,raw.index.array):{index:Array.from(raw.index.array),removedTriangles:0};result.push({species,removed:expected.removedTriangles,indexMatches:expected.index.every((v,i)=>v===live.index.array[i])&&expected.index.length===live.index.count,attributes:['position','normal','uv'].every(k=>raw.attributes[k].array.every((v,i)=>v===live.attributes[k].array[i])),idempotent:species!=='cat'||catLooseFragmentIndices(live.attributes.position.array,live.index.array).removedTriangles===0});}draco.dispose();return result;});
  for(const g of geometry){assert.equal(g.removed,g.species==='cat'?505:0);assert.equal(g.indexMatches,true);assert.equal(g.attributes,true);assert.equal(g.idempotent,true);}
  for(const species of order)for(const pose of ['stand','greet','sleep'])for(const side of [-1,0,1]){
   const r=await p.evaluate(async({species,pose,side})=>{const T=await import('three'),A=await import('./pet-action.mjs'),q=petHousePreview;q.pet.select(species);q.petRoot.position.set(0,.041,0);q.petRoot.rotation.y=0;q.pet.setMood('neutral');q.pet.saveLook({base:'#f4eee0',patch:'#d5a064'});q.pet.bind({ground:()=>.04,resetAction:true});q.pet.motion.setActionPose(A.samplePetAction(pose,pose==='greet'?.5:0,{species}));for(let i=0;i<240;i++)q.pet.motion.update(1/60,0);q.room.visible=false;document.querySelectorAll('body > :not(#view):not(script)').forEach(e=>e.style.visibility='hidden');
    const at=new T.Vector3(0,pose==='sleep'?.31:.43,.15);q.camera.left=-.65;q.camera.right=.65;q.camera.top=.5056;q.camera.bottom=-.5056;q.camera.position.copy(at).add(new T.Vector3(side?side*2:0,.12,side?.35:3));q.camera.lookAt(at);q.camera.updateProjectionMatrix();
    window.eyeHooks ||= new WeakMap();let closure,key,mesh;q.pet.model.traverse(o=>{if(!o.isMesh)return;mesh=o;let hook=eyeHooks.get(o.material);if(!hook){hook={compile:o.material.onBeforeCompile,key:o.material.customProgramCacheKey()};eyeHooks.set(o.material,hook);o.material.customProgramCacheKey=()=>hook.key+'-face-proof';}o.material.onBeforeCompile=shader=>{hook.compile(shader);hook.uniform=shader.uniforms.uEyeClosed;};key=hook.key;o.material.needsUpdate=true;});q.renderer.render(q.scene,q.camera);closure=eyeHooks.get(mesh.material).uniform;if(!closure)throw Error('eyelid uniform missing');
    const canvas=document.createElement('canvas');canvas.width=q.renderer.domElement.width;canvas.height=q.renderer.domElement.height;const ctx=canvas.getContext('2d'),capture=value=>{closure.value=value;q.renderer.render(q.scene,q.camera);ctx.drawImage(q.renderer.domElement,0,0);return {png:canvas.toDataURL(),pixels:ctx.getImageData(0,0,canvas.width,canvas.height).data};};
    const open=capture(0),closed=capture(1),pos=mesh.geometry.attributes.position;
    function project(point){let id=0,dist=Infinity;for(let i=0;i<pos.count;i++){const d=new T.Vector3().fromBufferAttribute(pos,i).distanceToSquared(new T.Vector3().fromArray(point));if(d<dist){dist=d;id=i;}}const v=mesh.localToWorld(mesh.applyBoneTransform(id,new T.Vector3().fromBufferAttribute(pos,id))).project(q.camera);return [Math.round((v.x+1)*canvas.width/2),Math.round((1-v.y)*canvas.height/2)];}
    const points=species==='dog'?[[0,.555,.489],[0,.485,.46],[0,.445,.46],[.096,.529,.46],[-.096,.529,.46]]:[[0,.425,.455],[0,.40,.445]],protectedChanges=points.map(point=>{const[x,y]=project(point);let change=0;for(let a=-2;a<=2;a++)for(let b=-2;b<=2;b++){const i=((y+b)*canvas.width+x+a)*4;for(let j=0;j<3;j++)change=Math.max(change,Math.abs(closed.pixels[i+j]-open.pixels[i+j]));}return change;});
    const eyes=side===0?[-1,1].map(sign=>{const[x,y]=project(species==='dog'?[sign*.083,.617,.382]:[sign*.11,.518,.44]);let openDark=0,closedDark=0,changed=0;for(let b=-35;b<=35;b++)for(let a=-43;a<=43;a++){const i=((y+b)*canvas.width+x+a)*4,bright=data=>(data[i]+data[i+1]+data[i+2])/3;if(bright(open.pixels)<100)openDark++;if(bright(closed.pixels)<100)closedDark++;if(Math.abs(bright(open.pixels)-bright(closed.pixels))>10)changed++;}return {openDark,closedDark,changed};}):[];
    return {open:open.png,closed:closed.png,key,protectedChanges,eyes};
   },{species,pose,side});const id=order.join('-')+'-'+species+'-'+pose+'-'+side;for(const name of ['open','closed'])fs.writeFileSync(path.join(out,id+'-'+name+'.png'),Buffer.from(r[name].split(',')[1],'base64'));delete r.open;delete r.closed;
   assert.deepEqual(r.protectedChanges.slice(0,3),r.protectedChanges.slice(0,3).map(()=>0),id+' must preserve nose/mouth/tongue');const visibleMuzzle=side===0?r.protectedChanges.slice(3):r.protectedChanges.slice(side>0?3:4,side>0?4:5);assert.ok(visibleMuzzle.every(v=>v<=3),id+' must not draw a dark lid on the visible side muzzle '+JSON.stringify(r.protectedChanges));for(const eye of r.eyes){assert.ok(eye.changed>100,id+' must cover the actual iris '+JSON.stringify(eye));assert.ok(eye.closedDark>15,id+' must retain a visible eyelid line');assert.ok(eye.closedDark<eye.openDark*.6,id+' must replace the round pupil with a thin lid '+JSON.stringify(eye));}report.push({order,species,pose,side,...r});
  }
  await p.close();
 }
 const keys=new Map(report.map(r=>[r.species,r.key]));assert.notEqual(keys.get('cat'),keys.get('dog'));assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'face.json'),JSON.stringify({ok:true,report,errors},null,2));console.log(JSON.stringify({ok:true,views:report.length}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
