// Actual WebGL before/after comparison: keep pose, light, dye and eye closure fixed.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.PET_FACE_URL||'http://127.0.0.1:18961',out=process.env.PET_FACE_EVIDENCE||'/tmp/pet-face';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),p=await browser.newPage({viewport:{width:900,height:700}}),errors=[],report=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.goto(base+'/art/pet-house/preview.html');await p.waitForFunction(()=>window.petHousePreview?.snapshot().ready);await p.evaluate(()=>requestAnimationFrame=()=>0);
 for(const species of ['dog','cat'])for(const pose of ['stand','sleep'])for(const side of [-1,0,1]){
  const r=await p.evaluate(async({species,pose,side})=>{const T=await import('three'),A=await import('./pet-action.mjs'),q=petHousePreview;q.pet.select(species);q.petRoot.position.set(0,.041,0);q.petRoot.rotation.y=0;q.pet.setMood(pose==='sleep'?'sleepy':'neutral');q.pet.saveLook({base:'#f4eee0',patch:'#a98565'});q.pet.bind({ground:()=>.04,resetAction:true});q.pet.motion.setActionPose(A.samplePetAction(pose,0,{species}));for(let i=0;i<240;i++)q.pet.motion.update(1/60,0);q.room.visible=false;document.querySelectorAll('body > :not(#view):not(script)').forEach(e=>e.style.visibility='hidden');
   const at=new T.Vector3(0,pose==='sleep'?.31:.43,.15);q.camera.left=-.65;q.camera.right=.65;q.camera.top=.5056;q.camera.bottom=-.5056;q.camera.position.copy(at).add(new T.Vector3(side?side*2:0,.12,side?.35:3));q.camera.lookAt(at);q.camera.updateProjectionMatrix();
   const uniforms=[];q.pet.model.traverse(o=>{if(!o.isMesh)return;const before=o.material.onBeforeCompile,key=o.material.customProgramCacheKey;o.material.onBeforeCompile=s=>{before(s);uniforms.push(s.uniforms.uMouthSoft);};o.material.customProgramCacheKey=()=>key()+'-face-proof-'+species+pose+side;o.material.needsUpdate=true;});q.renderer.render(q.scene,q.camera);if(!uniforms.length)throw Error('Face shader was not rendered');
   const canvas=document.createElement('canvas');canvas.width=q.renderer.domElement.width;canvas.height=q.renderer.domElement.height;const ctx=canvas.getContext('2d'),capture=value=>{uniforms.forEach(u=>u.value=value);q.renderer.render(q.scene,q.camera);ctx.drawImage(q.renderer.domElement,0,0);return {png:canvas.toDataURL(),pixels:ctx.getImageData(0,0,canvas.width,canvas.height).data};};
   const before=capture(0),after=capture(species==='dog'?1:0);let changed=0,maxChange=0;for(let i=0;i<before.pixels.length;i+=4){const d=Math.max(...[0,1,2].map(j=>Math.abs(after.pixels[i+j]-before.pixels[i+j])));if(d>3)changed++;maxChange=Math.max(maxChange,d);}
   // Project actual authored rest positions through the current skin to compare protected features.
   let mesh;q.pet.model.traverse(o=>{if(o.isSkinnedMesh)mesh=o});const pos=mesh.geometry.attributes.position,points=species==='dog'?[[0,.555,.489],[-.075,.617,.382],[.075,.617,.382],[0,.445,.46]]:[[0,.425,.455],[-.115,.51,.445],[.115,.51,.445]];
   const protectedChanges=points.map(point=>{let id=0,dist=Infinity;for(let i=0;i<pos.count;i++){const d=new T.Vector3().fromBufferAttribute(pos,i).distanceToSquared(new T.Vector3().fromArray(point));if(d<dist){dist=d;id=i}}const v=mesh.localToWorld(mesh.applyBoneTransform(id,new T.Vector3().fromBufferAttribute(pos,id))).project(q.camera),x=Math.round((v.x+1)*canvas.width/2),y=Math.round((1-v.y)*canvas.height/2);let change=0;for(let a=-2;a<=2;a++)for(let b=-2;b<=2;b++){const i=((y+b)*canvas.width+x+a)*4;for(let j=0;j<3;j++)change=Math.max(change,Math.abs(after.pixels[i+j]-before.pixels[i+j]));}return change;});return {before:before.png,after:after.png,changed,maxChange,protectedChanges,lie:q.pet.motion.snapshot().action.lie};
  },{species,pose,side});const id=species+'-'+pose+'-'+side;for(const name of ['before','after'])fs.writeFileSync(path.join(out,id+'-'+name+'.png'),Buffer.from(r[name].split(',')[1],'base64'));delete r.before;delete r.after;assert.deepEqual(r.protectedChanges,r.protectedChanges.map(()=>0),id+' must preserve nose/eyes/tongue');if(species==='dog'&&side===1){assert.ok(r.changed>100&&r.maxChange>15,id+' visible cheek seam must shorten '+JSON.stringify(r));}else if(species==='cat')assert.equal(r.changed,0,id+' cat face must stay unchanged');report.push({species,pose,side,...r});
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'face.json'),JSON.stringify({ok:true,report,errors},null,2));console.log(JSON.stringify({ok:true,views:report.length}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
