server {
  listen 8080;
  client_max_body_size 52m;

  location = /healthz {
    add_header Content-Type application/json;
    return 200 '{"ok":true,"service":"lisa-cloud"}';
  }

  location /auth/v1/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Prefix /auth/v1;
    proxy_pass http://auth:9999/;
  }

  location /rest/v1/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header apikey $http_apikey;
    proxy_pass http://rest:3000/;
  }

  location /storage/v1/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Prefix /storage/v1;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header apikey $http_apikey;
    proxy_pass http://storage:5000/;
  }

  location = /migrate/v1/session {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://session-migrator:8081/session;
  }
}
